; $ID:	PRODS_2PNG_DEMO.PRO,	2020-07-01-12,	USER-KJWH	$
; #########################################################################; 
PRO PRODS_2PNG_DEMO
;+
; PURPOSE:  DEMO FOR PRODS_2PNG
;
; CATEGORY:   DEMO
;
;
; INPUTS: [MAKE SURE INPUT 'ANNUAL_1996_1998-OSTAM-2010_12-SMI-CHLOR_A-STATS.SAVE' FILE IS IN !S.FILES]
;
;
; KEYWORDS:  NONE

; OUTPUTS:   DEPENDS ON THE SWITCHES 
;

;
; MODIFICATION HISTORY:
;     AUG 22, 2017  WRITTEN BY: J.E. O'REILLY
;     AUG 24,2017 JEOR: NOW USING NEW CBAR INSTEAD OF PRODS_COLORBAR
;     AUG 28,2017 JEOR: NOW OUTFILE [NOT FILE] IS PASSED TO PRODS_2PNG
;-
; #########################################################################

;**************************
ROUTINE = 'PRODS_2PNG_DEMO'
;**************************
;===> SWITCHES
DO_MAPS  = 'VO'

;END OF SWITCHES||||||||||||||||||||

SL = PATH_SEP()
DIR_DEMO = !S.DEMO + 'PRODS_2PNG_DEMO' + PATH_SEP()
DIR_PNGS = !S.DEMO + 'PRODS_2PNG_DEMO' + PATH_SEP() + 'PNGS'+ PATH_SEP()
DIR_TEST,[DIR_DEMO,DIR_PNGS]

;*************************
IF KEY(DO_MAPS) THEN BEGIN
  ;***********************
  SWITCHES,DO_MAPS,STOPP=STOPP,OVERWRITE=OVERWRITE,VERBOSE=VERBOSE,INIT=INIT,R_FILES=R_FILES,R_DATASETS=R_DATASETS
  IF STOPP THEN STOP
  FILE = !S.FILES + 'ANNUAL_1996_1998-OSTAM-2010_12-SMI-CHLOR_A-STATS.SAVE'
  FN = FILE_PARSE(FILE)
  DAT = STRUCT_READ(FILE,TAG = 'MEAN',STRUCT = STRUCT)
  ADD_LAND  = 1
  ADD_CB    = 1
  ADD_DB    = 1
  ADD_NAME  = 1
  ADD_TXT   = 1
  ADD_AUTH  = 1 & AUTH_TXT = 'K.J.W.Hyde-NOAA'
  OVERWRITE = 1
  ADD_LONLAT = 1 ; ONLY FOR 'ROBINSON','MOLLWEIDE'


  DATA_TAG = 'MEAN'
  MAPS_OUT = ['SMI','EC','NEC','GEQ','ROBINSON','MOLLWEIDE','NWA']
   MAPS_OUT = 'SMI'
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR NTH = 0,NOF(MAPS_OUT)-1 DO BEGIN
    MAP_OUT = MAPS_OUT[NTH]
    PFILE,MAP_OUT,/M
    
    OUTFILE = DIR_DEMO+REPLACE(FN.NAME_EXT,'SMI',MAP_OUT)
    IF FILE_MAKE(FILE,OUTFILE,OVERWRITE=OVERWRITE) EQ 0 THEN BEGIN
      
     NEW = STRUCT_REMAP(STRUCT, MAP_OUT=MAP_OUT,/INIT)
    ;===> WRITE THE NEW REPAPPED STRUCTURE TO DIR_DEMO
    SAVE,FILENAME = OUTFILE,NEW,/COMPRESS
    ENDIF; IF EXISTS(OUTFILE) EQ 0 THEN BEGIN

    ;===> MAKE A PNG OF THE OUTFILE   MAP_OUT
  
  PRODS_2PNG,FILE,MAPP=MAPP,PROD=PROD,DATA_TAG=DATA_TAG,LOG=LOG,DIR_OUT=DIR_OUT,VERBOSE=VERBOSE,$;===> MAIN INPUTS
   
                 ;===> IMAGE,COLORBAR,DATE_BAR,AND TEXT ANNOTATION POSITIONS [USUALLY READ FROM MAPS_MASTER]
                 IMG_POS=IMG_POS,CB_POS=CB_POS,CB_TYPE=CB_TYPE,DB_POS=DB_POS,TXT_POS=TXT_POS,TEST=TEST,$

                ;===> OUTPUT PNG CHARACTERISTICS
                PNGFILE=PNGFILE,PAL=PAL,BIT_DEPTH=BIT_DEPTH, OVERWRITE=OVERWRITE,MAP_OUT=MAP_OUT,EDIT=EDIT,BUFFER=BUFFER,$
                                      
                 ;===> ADD FILE NAME TO BOTTOM OF IMAGE
                 ADD_NAME=ADD_NAME,NAME_POS= NAME_POS,$ 
                   
                 ;===> COLORBAR
                 ADD_CB=ADD_CB,CB_X=CB_X,CB_Y=CB_Y,CB_LONG=CB_LONG,CB_SHORT=CB_SHORT,CB_FONT_SIZE=CB_FONT_SIZE,COMMA=COMMA,VSTAG=VSTAG,$
                   
                ;===> ADD ADD_LONLAT TO EDGES OF MAP [ONLY IF ROBINSON]
                ADD_LONLAT=ADD_LONLAT,$  
                 
                ;===> ADD LME BOUNDARIES 
                ADD_LMES=ADD_LMES,$
                 
                ;===> ADD LANDMASK              
                ADD_LAND = ADD_LAND,$ 
                    
                 ;===> DATE_BAR [USED PRIMARILY IN MOVIES]
                 ADD_DB=ADD_DB,DB_SIZE=DB_SIZE,DB_COLOR=DB_COLOR,DB_THICK=DB_THICK,DB_BKG=DB_BKG,NO_YEAR=NO_YEAR,NO_DAY=NO_DAY,$
                 DB_X=DB_X,DB_Y=DB_Y,DB_LONG=DB_LONG,DB_SHORT=DB_SHORT,$
                   
                 ;===> CONTOURS
                 C_LEVELS=C_LEVELS,C_COLORS=C_COLORS,$
                 C_ANNOTATION=C_ANNOTATION,C_CHARSIZE=C_CHARSIZE,$
                 C_CHARTHICK=C_CHARTHICK,C_THICK=C_THICK,$
                 OUTFILE=OUTFILE,OBJ=OBJ,$
                 
                 ;===> TEXT ANNOTATION DEFAULT TXT_TAGS=['SENSOR', 'METHOD','MAP','PROD','ALG']
                 ADD_TXT=ADD_TXT,TXT_SIZE=TXT_SIZE,TXT_SPACES=TXT_SPACES,$
                   
                 ;===> AUTHOR
                 ADD_AUTH=ADD_AUTH,AUTH_TXT=AUTH_TXT,AUTH_POS=AUTH_POS,AUTH_SIZE=AUTH_SIZE
  IF STOPP THEN STOP
ENDFOR; FOR NTH = 0,NOF(MAPS_OUT)-1 DO BEGIN

ENDIF;IF KEY(DO_MAPS) THEN BEGIN
;||||||||||||||||||||||||||||||||




END; #####################  END OF ROUTINE ################################
