; $ID:	JUNK_COMPARE_MODIS.PRO,	2020-06-26-15,	USER-KJWH	$
PRO JUNK_COMPARE_MODIS

  L1A_DIR = '/modis/DATASETS/OC-MODIS-1KM/L1A/'
  MODIS_FILES = FILE_SEARCH(L1A_DIR+'*L1A_LAC*')
  HELP, MODIS_FILES
  
  MFP = FILE_PARSE(MODIS_FILES)
  OK = WHERE(STRUPCASE(MFP.EXT) EQ 'BZ2', COUNT, COMPLEMENT=COMPLEMENT)
  MFILES = MFP.NAME_EXT
  IF COUNT GE 1 THEN MFILES[OK] = MFP[OK].NAME
  
  BACKUP_FILES = FILE_SEARCH('/localnet/satbackup2/nightly/modis/DATASETS/OC-MODIS-1KM/L1A/A*L1A_LAC*')
  BACKUP_DIRS = FILE_SEARCH('/localnet/satbackup2/nightly/CHANGES/*sep-2015/modis/DATASETS/OC-MODIS-1KM/L1A/',/TEST_DIRECTORY,/MARK_DIRECTORY)
  FOR B=0, N_ELEMENTS(BACKUP_DIRS)-1 DO BACKUP_FILES = [BACKUP_FILES,FILE_SEARCH(BACKUP_DIRS(B),'A*L1A_LAC*')]
  HELP, BACKUP_FILES
  BFP = FILE_PARSE(BACKUP_FILES)
  OK = WHERE(STRUPCASE(BFP.EXT) EQ 'BZ2', COUNT, COMPLEMENT=COMPLEMENT)
  BFILES = BFP.NAME_EXT 
  IF COUNT GE 1 THEN BFILES[OK] = BFP[OK].NAME
  BFILES = BFILES[SORT(BFILES)]
  BFILES = BFILES[UNIQ(BFILES)]
  OK_B = WHERE_MATCH(BFILES,MFILES,COUNT,COMPLEMENT=COMPLEMENT,NCOMPLEMENT=NCOMPLEMENT,VALID=VALID,INVALID=INVALID)
  IF NCOMPLEMENT GT 0 THEN BEGIN
    PRINT, NUM2STR(NCOMPLEMENT) + 'Missing L1A files based on BACKUP L1A files'
    STOP
  ENDIF 
    
; Compare with existing L2 files
  L2_FILES = FILE_SEARCH('/modis/DATASETS/OC-MODIS-1KM/L2_R2015/A*.*')
  LFP = FILE_PARSE(L2_FILES)
  LFILES = LFP.NAME + '.L1A_LAC'
  LFILES = LFILES[SORT(LFILES)]
  LFILES = LFILES[UNIQ(LFILES)]
  OK_L2 = WHERE_MATCH(LFILES,MFILES,COUNT,COMPLEMENT=COMPLEMENT,NCOMPLEMENT=NCOMPLEMENT,VALID=VALID)
  IF NCOMPLEMENT GT 0 THEN BEGIN
    PRINT, NUM2STR(NCOMPLEMENT) + ' Missing L1A files based on L2 files'
    STOP
  ENDIF


END
