; $ID:	JUNK_PRODS_2PNG.PRO,	2020-07-01-12,	USER-KJWH	$
PRO JUNK_PRODS_2PNG
FILE = FLS("C:\DATASETS\OC_OCTS\SMI\STATS\CHLOR_A\ANNUAL_1996_1997-OCTS-ADEOS-R2015-SMI-CHLOR_A-STATS.SAV")
PRODS_2PNG,FILE, DIR_OUT = !S.IDL_TEMP,/OVERWRITE,/BUFFER,/ADD_NAME,/ADD_DATE_BAR,MAP_OUT = 'ROBINSON',/LONLAT,/LMES







;|||||||||||||||||||||||||||||||||||||||||||||
END; #####################  END OF ROUTINE ################################
