; $ID:	IMG_FROM_TRUE.PRO,	2020-06-03-17,	USER-KJWH	$
;+
;;#############################################################################################################
	PRO IMG_FROM_TRUE,FILE,DIR_OUT=DIR_OUT

; PURPOSE: THIS FUNCTION CONVERTS A TRUE-COLOR [3-COLOR PLANES] INTO AN 8-BIT 'NORMAL' PNG
; 
; 
; CATEGORY:	IMG FAMILY;		 
;
; CALLING SEQUENCE: RESULT = IMG_FROM_TRUE(FILE)
;
; INPUTS: FILE NAME  

; OPTIONAL INPUTS:
;		
; KEYWORD PARAMETERS:
;         DIR_OUT - OUTPUT FILE DIRECTORY

; OUTPUTS: AN 8-BIT 'NORMAL' PNG WITH THE SAME NAME AS THE INPUT FILE
;		
;; EXAMPLES:
;      IMG_FROM_TRUE,!S.IMAGES + 'MASK_NEC_ESTUARY_SHELF.BMP'
;	NOTES:
;      WHEN USING PAINT - SAVE YOUR MODIFIED IMAGE AS A '.BMP' TRUE-COLOR FILE

;
; MODIFICATION HISTORY:
;			WRITTEN JUL 2, 2014 J.O'REILLY
;			JUL 4,2014,JOR: NEW = CONGRID(NEW,PX,PY)
;     JUL 6,2014,JOR, ADDED EXAMPLE & ENSURE 3 COLOR PLANES:
;     IF SZ.N_DIMENSIONS NE 3 THEN MESSAGE,'ERROR: INPUT FILE NOT A TRUE-TYPE IMAGE [3-COLOR PLANES]'

 
;#################################################################################
;-
;********************************
ROUTINE_NAME  = 'IMG_FROM_TRUE'
;********************************
; FILE = "C:\IDL\IMAGES\MASK_NEC_ESTUARY_SHELF.bmp"
PRINT,'WHEN USING PAINT - SAVE YOUR MODIFIED SUBAREAS IMAGE AS A .BMP TRUE-COLOR FILE'
IF NONE(DIR_OUT) THEN DIR_OUT = !S.IDL_TEMP
IF NONE(FILE) THEN MESSAGE,'ERROR: MUST PROVIDE FILE'

IM = READ_IMAGE(FILE)
SZ = SIZEXYZ(IM)
PX = SZ.PX
PY = SZ.PY

IF SZ.N_DIMENSIONS NE 3 THEN MESSAGE,'ERROR: INPUT FILE NOT A TRUE-TYPE IMAGE [3-COLOR PLANES]'
RGB_TABLE = CPAL_READ('PAL_SW3')
I = IMAGE(IM,DIMENSIONS = [PX,PY],RGB_TABLE = RGB_TABLE)
I.SAVE,!S.IDL_TEMP +'JUNK.PNG',BIT_DEPTH = 1,RESOLUTION = 600,BORDER = 0
I.CLOSE
NEW = READ_PNG(!S.IDL_TEMP +'JUNK.PNG',R,G,B)

;===> RESIZE TO SAME DIMENSIONS AS INPUT IMG
NEW = CONGRID(NEW,PX,PY)
FN = FILE_PARSE(FILE)
OUTFILE = DIR_OUT + FN.NAME + '-8B.PNG'
WRITE_PNG,OUTFILE,NEW,R,G,B & PFILE,OUTFILE


DONE:          
	END; #####################  END OF ROUTINE ################################
