; $ID:	ADG_443_DATA_DEMO.PRO,	2014-04-29	$
PRO ADG_443_DATA_DEMO
FILE ="ADG_443_DATA.SAVE"
S = IDL_RESTORE(FILE)

 D = S.D
 ST,D
 DATA = D.L3M_DATA & HELP,DATA
 OK=WHERE(DATA NE -32767 ,COUNT) & P,COUNT
 OK=WHERE(DATA NE -32767 AND DATA GT S.D.DATA_MINIMUM AND DATA LT S.D.DATA_MAXIMUM ,COUNT) & P,COUNT
 
STOP
END; #####################  END OF ROUTINE ################################
