; $ID:	BRICAUD_1998_TABLE_AP_APHI.PRO,	2020-06-30-17,	USER-KJWH	$
;######################################################################################
PRO BRICAUD_1998_TABLE_AP_APHI
;+
;	THIS PROGRAM GENERATES A POSTSCRIPT PLOT OF THE BRICAUD_1998_TABLE [WAVELENGTH VS APHI*]

; MODIFICATION HISTORY:
;	JAN 1,2001	WRITTEN BY:	J.E. O'REILLY, NOAA, 28 TARZWELL DRIVE, NARRAGANSETT, RI 02882
;	JUL 03,2016,JOR UPDATED, FORMATTING, NEW FUNCTIONS,NEW DIR_IN,DIR_OUT = PLOTS
;-
; ****************************************
ROUTINE_NAME='BRICAUD_1998_TABLE_AP_APHI'
; ****************************************
  
  
  DIR_IN=!S.DATA
  FILE = DIR_IN + 'BRICAUD_1998_TABLE_AP_APHI.CSV'
  DB=CSV_READ(FILE)
  D =STRUCT_2DBL(DB)
  DIR_OUT = !S.IDL + 'PLOTS\'
;


  PSFILE=DIR_OUT+ROUTINE_NAME+'.PS'
  PSPRINT,/HALF,/COLOR,FILENAME=PSFILE
  FONT_TIMES
  !P.CHARSIZE=1.6
  PAL_36,R,G,B
  CHL = [ 0.01,0.03,0.1,0.3,1,3,10,30]
  CHL = [ '0.01','0.03','0.1','0.3','1','3','10']
 ; !P.MULTI=[0,1,N_ELEMENTS(CHL)]
 !P.MULTI=0
 !P.THICK=7
 !X.THICK=3
 !Y.THICK=3
 YTITLE =  UNITS('APHI*')
 XTITLE =  UNITS('LAMBDA')
 TITLE_PAGE = 'BRICAUD, MOREL, BABIN, ALLALI & CLAUSTRE, 1998'
  FOR _CHL = 0,N_ELEMENTS(CHL)-1 DO BEGIN
    ACHL = CHL(_CHL)
    A_P =  DB.AP*ACHL^(DB.EP-1)
    A_PHI =  DB.APHI*ACHL^(DB.EPHI-1)


    COLORS = [4,9,10,12,17,19,21,27]
    IF _CHL EQ 0 THEN BEGIN

      PLOT, DB.LAMBDA,A_PHI,YRANGE=[0,0.25],XTICKS=6,XRANGE=[400,700],/XSTYLE,/YSTYLE, XTITLE=XTITLE,YTITLE=YTITLE,/NODATA
    ENDIF
      OPLOT, DB.LAMBDA,A_PHI,COLOR=COLORS(_CHL)
      OPLOT, DB.LAMBDA,A_PHI,COLOR=0,THICK=2
      OK_L = WHERE(DB.LAMBDA LT 460)
      MAX_CHL =  MAX(A_PHI(OK_L))
      OK = WHERE(A_PHI(OK_L) EQ MAX_CHL)
      TXT = ACHL
      IF _CHL EQ 0 THEN TXT = TXT + UNITS('CHLOR_A',/NAME)
       IF _CHL EQ 0 THEN ALIGN= 0.1 ELSE ALIGN = 0.5
      XYOUTS,D(OK_L(OK[0])).LAMBDA,MAX_CHL,TXT,ALIGN=ALIGN,COLOR=COLORS(_CHL)

  ENDFOR
        XYOUTS,0.5, 0.95,/NORMAL,TITLE_PAGE,ALIGN=0.47
  PSPRINT
  PFILE,PSFILE



END; #####################  END OF ROUTINE ################################
