; $ID:	CHL_TEST.PRO,	2021-04-15-17,	USER-KJWH	$

  PRO CHL_TEST, DO_OLD_SEAWIFS=DO_OLD_SEAWIFS

;+
; NAME:
;   PP_TEST
;
; PURPOSE:
;   This procedure tests the calculation of the CHL data
;
; CATEGORY:
;   CATEGORY
;
; CALLING SEQUENCE:
;
; INPUTS:
;   
;
; OPTIONAL INPUTS:
;   
;
; KEYWORD PARAMETERS:
;  
;
; OUTPUTS:
;  
;
; OPTIONAL OUTPUTS:
;     SWITCHES governs which processing steps to do and what to do in the step
;     '' (NULL STRING) = do not do the step
;        ANY ONE OR COMBINATION OF LETTERS WILL RUN THE STEP:
;     Y  = YES do the step
;     O  = OVERWRITE any output
;     V  = VERBOSE (allow PRINT statements)
;     RF = REVERSE the processing order of files in the step
;     S  = STOP at the beginning of the step and step through each command in the step
;     DATERANGE = Daterange for selecting files
;
; MODIFICATION HISTORY:
;			Written:  March 09, 2017 by K.J.W. Hyde, 28 Tarzwell Drive, NMFS, NOAA 02882 (kimberly.hyde@noaa.gov)
;			Modified: 
;-
;	****************************************************************************************************
	ROUTINE_NAME = 'CHL_TEST'
	
	;===> #####   SWITCHES
	DO_PAN = ''
	DO_PAN_OLD_NEW = 'Y'
	DO_WERDELL = 'Y'


	;|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

  SL = PATH_SEP()
  DIR_DEMO = !S.DEMO + ROUTINE_NAME + SL & DIR_TEST, DIR_DEMO

; *****************************
	IF KEY(DO_PAN) THEN BEGIN
; *****************************
	  SNAME = 'DO_PAN'
    SWITCHES,DO_PAN,STOPP=STOPP,OVERWRITE=OVERWRITE,VERBOSE=VERBOSE,INIT=INIT,R_FILES=R_FILES,R_DATASETS=R_DATASETS,R_MAPS=R_MAPS,DATERANGE=DATERANGE
    IF VERBOSE THEN PRINT, 'Running: ' + SNAME
	  IF KEY(STOPP) THEN STOP
	  
	  BUFFER = 1
	  PAL = 'PAL_BR'
	  DATERANGE = ['20030601','20030630']
	  MPIN = 'L3B2'
	  MPS = 'NEC'
	  LAND = READ_LANDMASK(MP,/STRUCT)
	  
	  IF NONE(DATASETS) THEN DATASETS = ['OC-MODISA-1KM','OC-SEAWIFS-1KM']

	  FOR MTH=0, N_ELEMENTS(MPS)-1 DO BEGIN
	    AMAP = MPS(MTH)

	    FOR NTH = 0L, N_ELEMENTS(DATASETS)-1 DO BEGIN
	      DATASET = DATASETS[NTH]
	      CASE DATASET OF
	        'OC-MODISA-1KM':  BEGIN & PRODS=['CHLOR_A-PAN'] & SERVER=!S.MODIS  & PREFIX='A' & RPRODS = ['RRS_488','RRS_547','RRS_667']  & END
	        'OC-SEAWIFS-1KM': BEGIN & PRODS=['CHLOR_A-PAN'] & SERVER=!S.SEADAS & PREFIX='S' & RPRODS = ['RRS_490','RRS_555','RRS_670'] & END
	      ENDCASE
	      SENSOR = VALIDS('SENSORS',DATASET)

	      IF ANY(DPRODS) THEN PRODS = DPRODS[NTH]
	  
	      SPROD = 'RRS'
    	  RFILES = FLS(SERVER + DATASET+SL+MPIN+SL+'NC'+SL+PREFIX+'2003*'+'RRS'+'*.nc',DATERANGE=DATERANGE,COUNT=COUNT)
    	  CFILES = REPLACE(RFILES,'RRS','CHL')
    	  
    	  
	      
	      IF KEY(R_FILES) THEN FILES = REVERSE(FILES)
    	  FOR F=0, N_ELEMENTS(RFILES)-1 DO BEGIN
    	    FP = FILE_PARSE(RFILES(F))
    	    SI = SENSOR_INFO(RFILES(F))
    	    DATE = PERIOD_2DATE(SI.PERIOD)
    	    MS = MAPS_SIZE(SI.MAP,PX=PX,PY=PY)
    	    PNGFILE = DIR_DEMO + SI.PERIOD + '-' + REPLACE(SI.FILELABEL, SI.MAP, AMAP) + '-PAN_OCI_COMPARE' + '.PNG'
    	    

    	    IF FILE_MAKE([RFILES(F),CFILES(F)],PNGFILE,OVERWRITE=OVERWRITE) EQ 0 THEN CONTINUE

    	    C = READ_NC(CFILES(F),PRODS='CHLOR_A',BINS=BINS,/DATA) & CHLO = MAPS_REMAP(C,MAP_IN='L3B2',MAP_OUT=AMAP,BINS=BINS) & CHLOB = PRODS_2BYTE(CHLO,PROD='CHLOR_A',MP=AMAP,/ADD_COAST)
    	    D = READ_NC(RFILES(F),PRODS=RPRODS,GLOBAL=GLOBAL)
    	    
    	    FOR S=0, N_ELEMENTS(RPRODS)-1 DO BEGIN
    	      CASE RPRODS(S) OF
    	        'RRS_412': BEGIN & RRS_412=D.SD.RRS_412.DATA & BIN_412=D.SD.RRS_412.BINS & BIN_NUM=NOF(BIN_412) & END
    	        'RRS_443': BEGIN & RRS_443=D.SD.RRS_443.DATA & BIN_443=D.SD.RRS_443.BINS & BIN_NUM=NOF(BIN_443) & END
    	        'RRS_488': BEGIN & RRS_488=D.SD.RRS_488.DATA & BIN_490=D.SD.RRS_488.BINS & BIN_NUM=NOF(BIN_490) & END
    	        'RRS_490': BEGIN & RRS_490=D.SD.RRS_490.DATA & BIN_490=D.SD.RRS_490.BINS & BIN_NUM=NOF(BIN_490) & END
    	        'RRS_547': BEGIN & RRS_547=D.SD.RRS_547.DATA & BIN_555=D.SD.RRS_547.BINS & BIN_NUM=NOF(BIN_555) & END
    	        'RRS_555': BEGIN & RRS_555=D.SD.RRS_555.DATA & BIN_555=D.SD.RRS_555.BINS & BIN_NUM=NOF(BIN_555) & END
    	        'RRS_667': BEGIN & RRS_667=D.SD.RRS_667.DATA & BIN_670=D.SD.RRS_667.BINS & BIN_NUM=NOF(BIN_670) & END
    	        'RRS_670': BEGIN & RRS_670=D.SD.RRS_670.DATA & BIN_670=D.SD.RRS_670.BINS & BIN_NUM=NOF(BIN_670) & END
    	      ENDCASE ; SPROD
    	    ENDFOR ; SD_PRODS
    	    
    	    CHLPAN = CHLOR_A_PAN(RRS490=RRS_490,RRS488=RRS_488,RRS547=RRS_547,RRS555=RRS_555,RRS667=RRS_667,RRS670=RRS_670,SENSOR=SI.SENSOR,ERROR=ERRORS,ERR_MSG=ERR_MSGS)
    	    CHLP = MAPS_REMAP(CHLPAN,MAP_IN='L3B2',MAP_OUT=AMAP,BINS=BIN_490) & CHLPB = PRODS_2BYTE(CHLP,PROD='CHLOR_A',MP=AMAP,/ADD_COAST)
    	    
	        ADAT = MAPS_BLANK(AMAP) 
	        OK = WHERE(CHLO NE MISSINGS(0.0) AND CHLP NE MISSINGS(0.0))
	        ADAT[OK] = CHLO[OK]-CHLP[OK] & ABYT = PRODS_2BYTE(ADAT,PROD='DIF_-0.5_0.5',MP=AMAP,/ADD_COAST)
	    
    	    W = WINDOW(DIMENSIONS=[1024,1025],BUFFER=BUFFER)
    	    OIM = IMAGE(CHLOB,RGB_TABLE=CPAL_READ(PAL),LAYOUT=[2,2,1],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
    	    NIM = IMAGE(CHLPB,RGB_TABLE=CPAL_READ(PAL),LAYOUT=[2,2,2],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
    	    AIM = IMAGE(ABYT, RGB_TABLE=CPAL_READ('PAL_ANOMG'),LAYOUT=[2,2,3],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
    	    PRODS_COLORBAR, 'CHLOR_A', IMG=OIM, LOG=1, ORIENTATION=0, TITLE=CTITLE, FONT_SIZE=14, POSITION=[0.25,0.51,0.75,0.54],  TEXTPOS=0, PAL=PAL
    	    PRODS_COLORBAR, 'DIF_-0.5_0.5',IMG=AIM, LOG=1, ORIENTATION=0, TITLE=CTITLE, FONT_SIZE=14, POSITION=[0.05,0.03,0.45,0.06], TEXTPOS=0, PAL='PAL_ANOMG'
	    
    	    OKXY = WHERE(CHLO NE MISSINGS(CHLO) AND CHLP NE MISSINGS(CHLP))
    	    RANGE = NICE_RANGE(MINMAX([CHLO(OKXY),CHLP(OKXY)]))
    	    P = PLOTXY_NG(CHLO(OKXY),CHLP(OKXY),DECIMALS=3,/LOGLOG,/QUIET,/CURRENT,MODEL='RMA',PARAMS=[1,5,6,7,11],CHARSIZE=FONTSIZE,PSYM='CIRCLE',$
    	      XTITLE='CHLOR_A-OCI',YTITLE='CHLRO_A-PAN',SYM_COLOR=22,SYMSIZE=SYMSIZE,THICK=THICK,XRANGE=NICE_RANGE(RANGE),YRANGE=NICE_RANGE(RANGE),/GRID_NONE,LAYOUT=[2,2,4],MARGIN=MARGIN,STATS_CHARSIZE=STATS_CHARSIZE,$
    	      STATS_POS=[0.61,0.33],/ONE2ONE,ONE_COLOR=253,ONE_THICK=ONE_THICK,ONE_LINESTYLE=ONE_LINESTYLE,BUFFER=BUFFER) 
    	    
    	    TXT = TEXT(0.05,0.95,'CHLOR_A-OCI')
    	    TXT = TEXT(0.55,0.95,'CHLOR_A-PAN')
    	    TXT = TEXT(0.05,0.45,'OCI-PAN CHL')
    	    
    	    W.SAVE,PNGFILE
    	    W.CLOSE  
    	  ENDFOR
    	ENDFOR
    ENDFOR  
	  
	  STOP
	 
	  IF VERBOSE THEN , SNAME
	ENDIF ; DO_PAN 
	
	
	; *****************************
	IF KEY(DO_PAN_OLD_NEW) THEN BEGIN
	  ; *****************************
	  SNAME = 'DO_PAN_OLD_NEW'
	  SWITCHES,DO_PAN_OLD_NEW,STOPP=STOPP,OVERWRITE=OVERWRITE,VERBOSE=VERBOSE,INIT=INIT,R_FILES=R_FILES,R_DATASETS=R_DATASETS,R_MAPS=R_MAPS,DATERANGE=DATERANGE
	  IF VERBOSE THEN PRINT, 'Running: ' + SNAME
	  IF KEY(STOPP) THEN STOP

	  BUFFER = 1
	  PAL = 'PAL_BR'
	  DATERANGE = ['20030601','20030630']
	  MPIN = 'L3B2'
	  MPS = 'NEC'
	  LAND = READ_LANDMASK(MP,/STRUCT)

	  IF NONE(DATASETS) THEN DATASETS = ['OC-SEAWIFS-1KM','OC-MODISA-1KM']

	  FOR MTH=0, N_ELEMENTS(MPS)-1 DO BEGIN
	    AMAP = MPS(MTH)

	    FOR NTH = 0L, N_ELEMENTS(DATASETS)-1 DO BEGIN
	      DATASET = DATASETS[NTH]
	      CASE DATASET OF
	        'OC-MODISA-1KM':  BEGIN & PRODS=['CHLOR_A-PAN'] & SERVER=!S.MODIS  & PREFIX='A' & RPRODS=['RRS_488','RRS_547','RRS_667'] & ODIR='OC-MODIS-LAC' & END
	        'OC-SEAWIFS-1KM': BEGIN & PRODS=['CHLOR_A-PAN'] & SERVER=!S.SEADAS & PREFIX='S' & RPRODS=['RRS_490','RRS_555','RRS_670'] & ODIR='OC-SEAWIFS-MLAC' & END
	      ENDCASE
	      SENSOR = VALIDS('SENSORS',DATASET)

	      IF ANY(DPRODS) THEN PRODS = DPRODS[NTH]

	      SPROD = 'RRS'
	      RFILES = FLS(SERVER + DATASET+SL+MPIN+SL+'NC'+SL+PREFIX+'2003*'+'RRS'+'*.nc',DATERANGE=DATERANGE,COUNT=COUNT)
	      OFILES = FLS(!S.ARCHIVE + ODIR + SL + AMAP + SL + 'STATS' + SL + 'CHLOR_A-PAN' + SL + 'D_200306*MEAN.SAVE',DATERANGE=DATERANGE,COUNT=COUNT)
	      FO = PARSE_IT(OFILES)

	      IF KEY(R_FILES) THEN FILES = REVERSE(FILES)
	      FOR F=0, N_ELEMENTS(RFILES)-1 DO BEGIN
	        FP = FILE_PARSE(RFILES(F))
	        SI = SENSOR_INFO(RFILES(F))
	        DATE = PERIOD_2DATE(SI.PERIOD)
	        MS = MAPS_SIZE(SI.MAP,PX=PX,PY=PY)
	        PNGFILE = DIR_DEMO + SI.PERIOD + '-' + REPLACE(SI.FILELABEL, SI.MAP, AMAP) + '-PAN_OLD_NEW_COMPARE' + '.PNG'

          OFILE = OFILES[WHERE(FO.PERIOD EQ SI.PERIOD,/NULL)]
          IF OFILE EQ [] THEN CONTINUE
	        IF FILE_MAKE([RFILES(F),OFILE],PNGFILE,OVERWRITE=OVERWRITE) EQ 0 THEN CONTINUE

	        CHLO = STRUCT_READ(OFILE) & CHLOB = PRODS_2BYTE(CHLO,PROD='CHLOR_A',MP=AMAP,/ADD_COAST)
	        D = READ_NC(RFILES(F),PRODS=RPRODS,GLOBAL=GLOBAL)

	        FOR S=0, N_ELEMENTS(RPRODS)-1 DO BEGIN
	          CASE RPRODS(S) OF
	            'RRS_412': BEGIN & RRS_412=D.SD.RRS_412.DATA & BIN_412=D.SD.RRS_412.BINS & BIN_NUM=NOF(BIN_412) & END
	            'RRS_443': BEGIN & RRS_443=D.SD.RRS_443.DATA & BIN_443=D.SD.RRS_443.BINS & BIN_NUM=NOF(BIN_443) & END
	            'RRS_488': BEGIN & RRS_488=D.SD.RRS_488.DATA & BIN_490=D.SD.RRS_488.BINS & BIN_NUM=NOF(BIN_490) & END
	            'RRS_490': BEGIN & RRS_490=D.SD.RRS_490.DATA & BIN_490=D.SD.RRS_490.BINS & BIN_NUM=NOF(BIN_490) & END
	            'RRS_547': BEGIN & RRS_547=D.SD.RRS_547.DATA & BIN_555=D.SD.RRS_547.BINS & BIN_NUM=NOF(BIN_555) & END
	            'RRS_555': BEGIN & RRS_555=D.SD.RRS_555.DATA & BIN_555=D.SD.RRS_555.BINS & BIN_NUM=NOF(BIN_555) & END
	            'RRS_667': BEGIN & RRS_667=D.SD.RRS_667.DATA & BIN_670=D.SD.RRS_667.BINS & BIN_NUM=NOF(BIN_670) & END
	            'RRS_670': BEGIN & RRS_670=D.SD.RRS_670.DATA & BIN_670=D.SD.RRS_670.BINS & BIN_NUM=NOF(BIN_670) & END
	          ENDCASE ; SPROD
	        ENDFOR ; SD_PRODS

	        CHLPAN = CHLOR_A_PAN(RRS490=RRS_490,RRS488=RRS_488,RRS547=RRS_547,RRS555=RRS_555,RRS667=RRS_667,RRS670=RRS_670,SENSOR=SI.SENSOR,ERROR=ERRORS,ERR_MSG=ERR_MSGS)
	        CHLP = MAPS_REMAP(CHLPAN,MAP_IN='L3B2',MAP_OUT=AMAP,BINS=BIN_490) & CHLPB = PRODS_2BYTE(CHLP,PROD='CHLOR_A',MP=AMAP,/ADD_COAST)

	        ADAT = MAPS_BLANK(AMAP)
	        OK = WHERE(CHLO NE MISSINGS(0.0) AND CHLP NE MISSINGS(0.0))
	        ADAT[OK] = CHLO[OK]-CHLP[OK] & ABYT = PRODS_2BYTE(ADAT,PROD='DIF_-0.1_0.1',MP=AMAP,/ADD_COAST)

	        W = WINDOW(DIMENSIONS=[1024,1025],BUFFER=BUFFER)
	        OIM = IMAGE(CHLOB,RGB_TABLE=CPAL_READ(PAL),LAYOUT=[2,2,1],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
	        NIM = IMAGE(CHLPB,RGB_TABLE=CPAL_READ(PAL),LAYOUT=[2,2,2],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
	        AIM = IMAGE(ABYT, RGB_TABLE=CPAL_READ('PAL_ANOMG'),LAYOUT=[2,2,3],MARGIN=0,/DEVICE,/CURRENT,BUFFER=BUFFER)
	        PRODS_COLORBAR, 'CHLOR_A', IMG=OIM, LOG=1, ORIENTATION=0, TITLE=CTITLE, FONT_SIZE=14, POSITION=[0.25,0.51,0.75,0.54],  TEXTPOS=0, PAL=PAL
	        PRODS_COLORBAR, 'DIF_-0.1_0.1',IMG=AIM, LOG=1, ORIENTATION=0, TITLE=CTITLE, FONT_SIZE=14, POSITION=[0.05,0.03,0.45,0.06], TEXTPOS=0, PAL='PAL_ANOMG'

	        OKXY = WHERE(CHLO NE MISSINGS(CHLO) AND CHLP NE MISSINGS(CHLP))
	        RANGE = NICE_RANGE(MINMAX([CHLO(OKXY),CHLP(OKXY)]))
	        P = PLOTXY_NG(CHLO(OKXY),CHLP(OKXY),DECIMALS=3,/LOGLOG,/QUIET,/CURRENT,MODEL='RMA',PARAMS=[1,5,6,7,11],CHARSIZE=FONTSIZE,PSYM='CIRCLE',$
	          XTITLE='CHLOR_A-PAN OLD',YTITLE='CHLRO_A-PAN NEW',SYM_COLOR=22,SYMSIZE=SYMSIZE,THICK=THICK,XRANGE=NICE_RANGE(RANGE),YRANGE=NICE_RANGE(RANGE),/GRID_NONE,LAYOUT=[2,2,4],MARGIN=MARGIN,STATS_CHARSIZE=STATS_CHARSIZE,$
	          STATS_POS=[0.61,0.33],/ONE2ONE,ONE_COLOR=253,ONE_THICK=ONE_THICK,ONE_LINESTYLE=ONE_LINESTYLE,BUFFER=BUFFER)

	        TXT = TEXT(0.05,0.95,'CHLOR_A-PAN OLD')
	        TXT = TEXT(0.55,0.95,'CHLOR_A-PAN NEW')
	        TXT = TEXT(0.05,0.45,'OLD-NEW CHL')

	        W.SAVE,PNGFILE
	        W.CLOSE
	      ENDFOR
	    ENDFOR
	  ENDFOR

	  STOP

	  IF VERBOSE THEN , SNAME
	ENDIF ; DO_OLD_SEAWIFS

	


END; #####################  End of Routine ################################
