; $ID:	CROP_IMAGE_MAIN.PRO,	2020-06-30-17,	USER-KJWH	$
PRO CROP_IMAGE_MAIN
FILES = FILE_SEARCH('D:\MISC\','*.JPG')
PLIST,FILES
 IM = READ_IMAGE(FILES[0] , Red, Green, Blue)
 SZ = SIZEXYZ(IM)
STOP
CROP_IMAGE, FILES,BACKGROUND = BACKGROUND
END; OF PROGRAM
