; $ID:	DEMO.PRO,	2020-06-26-15,	USER-KJWH	$

PRO DEMO_OC

ROUTINE_NAME='CONTOUR_DEMO'

PSFILE = ROUTINE_NAME+'.PS'
PSPRINT,FILENAME=PSFILE,/COLOR,/FULL,/TIMES,/LANDSCAPE
!P.MULTI = [0,1,5]

PAL_SW3,R,G,B
 	XMARGIN = [0.1,0.1]
 	YMARGIN = [0.1,0.1]

	D = IDL_RESTORE('D:/IDL/PROGRAMS/N01_DEMO.SAVE')

	MAXDEPTH = 50
	YRANGE = [-MAXDEPTH,0]
	MINDATE = 19980101
	MAXDATE = 20040101
	MINJD = DATE_2JD(MINDATE)
	MAXJD = DATE_2JD(MAXDATE)

	AX = DATE_AXIS([MINJD,MAXJD],/MONTH)
	AY = DATE_AXIS([MINJD,MAXJD],/YEAR)
	XX = AY.TICKV - MINJD
	XRANGE = MINMAX(AX.JD - MINJD)

	OK = WHERE(D.TEMP NE MISSINGS(0.0))
	TIME_DEPTH_GRID,D[OK].DATE,D[OK].DEPTH,D[OK].TEMP,DEPTH_INTERVAL=1,NEAR=0.5,[MINDATE,MAXDATE],[MAXDEPTH,0],[-1,25],DIMENSIONS=[4000,200],AX_INTERVAL='MONTH',AY_GRID='YEAR',YTITLE='Depth (m)'
	LABEL = 'Temperature'
	COOR = COORD_2PLOT(0.05,0.05)
	XYOUTS, COOR.X,COOR.Y, LABEL, ALIGN=-0.1, CHARSIZE=1.5, COLOR=215, CHARTHICK=5

	OK = WHERE(D.SAL NE MISSINGS(0.0) AND D.SAL GT 0)
	TIME_DEPTH_GRID,D[OK].DATE,D[OK].DEPTH,D[OK].SAL,DEPTH_INTERVAL=1,NEAR=0.5,[MINDATE,MAXDATE],[MAXDEPTH,0],[20,35],DIMENSIONS=[4000,200],AX_INTERVAL='MONTH',AY_GRID='YEAR',YTITLE='Depth (m)'
	LABEL = 'Salinity'
	COOR = COORD_2PLOT(0.05,0.05)
	XYOUTS, COOR.X,COOR.Y, LABEL, ALIGN=-0.1, CHARSIZE=1.5, COLOR=215, CHARTHICK=5

	OK = WHERE(D.CHLA NE MISSINGS(0.0) AND D.CHLA GT 0)
	TIME_DEPTH_GRID,D[OK].DATE,D[OK].DEPTH,D[OK].CHLA,DEPTH_INTERVAL=1,NEAR=0.5,[MINDATE,MAXDATE],[MAXDEPTH,0],[0,60],DIMENSIONS=[4000,200],AX_INTERVAL='MONTH',AY_GRID='YEAR',YTITLE='Depth (m)'
	LABEL = 'Chlorophyll'
	COOR = COORD_2PLOT(0.05,0.05)
	XYOUTS, COOR.X,COOR.Y, LABEL, ALIGN=-0.1, CHARSIZE=1.5, COLOR=215, CHARTHICK=5
	TIME_DEPTH_GRID,D[OK].DATE,D[OK].DEPTH,D[OK].CHLA,/INTERPOLATE,DEPTH_INTERVAL=1,NEAR=0.5,[MINDATE,MAXDATE],[MAXDEPTH,0],[0,60],DIMENSIONS=[4000,200],AX_INTERVAL='MONTH',AY_GRID='YEAR',YTITLE='Depth (m)'
	LABEL = 'Chlorophyll (Interpolated)'
	COOR = COORD_2PLOT(0.05,0.05)
	XYOUTS, COOR.X,COOR.Y, LABEL, ALIGN=-0.1, CHARSIZE=1.5, COLOR=215, CHARTHICK=5
	TIME_DEPTH_GRID,D[OK].DATE,D[OK].DEPTH,D[OK].CHLA,/INTERPOLATE,/LOG,DEPTH_INTERVAL=1,NEAR=0.5,[MINDATE,MAXDATE],[MAXDEPTH,0],[0.01,60],DIMENSIONS=[4000,200],AX_INTERVAL='MONTH',AY_GRID='YEAR',YTITLE='Depth (m)'
	LABEL = 'Log Chlorophyll (Interpolated)'
	COOR = COORD_2PLOT(0.05,0.05)
	XYOUTS, COOR.X,COOR.Y, LABEL, ALIGN=-0.1, CHARSIZE=1.5, COLOR=215, CHARTHICK=5
psprint
STOP
END
