; $ID:	DETREND_DEMO.PRO,	2014-12-18	$

 PRO DETREND_DEMO
;+
; NAME:
;       DETREND_DEMO
;
; PURPOSE:
;		DEMO TO ILLUSTRATE EFFECT OF DETRENDING ON DATA
;

; MODIFICATION HISTORY:
;       Written by:  J.E.O'Reilly, MARCH 4,1999
;       June 2, 2003 td replace strtrim(string with strtrim if format not specific
;-

ROUTINE_NAME='DETREND_DEMO'

	!P.CHARSIZE=1.5
	PAL_36
	COLOR_DATA = 6
	COLOR_IDL = 16
	COLOR_SCARGLE = 21
	COLOR_SCARGLE_CROSS = 26

  ps= 0

	SERIES = ['0.5','1','2','3','8_7','DAMPED','SARGASSO','MAB_SLOPE','GB_CENTRAL']

; LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
  FOR SERIES_=0,N_ELEMENTS(SERIES)-1L DO BEGIN
		ASERIES=SERIES(SERIES_)

		TS=TIME_SERIES(ASERIES)
		TIMES = DOUBLE(TS.TIME)
		DATA=DOUBLE(TS.DATA)
;		===> NUMBER OF TARGET FREQUENCIES (NUMF)
		NUMF=2*N_ELEMENTS(data)

; 		===> CONVERT Julian TIMES TO DECIMAL YEARS
		IF TS.TIME_UNITS EQ 'JULIAN' THEN TIMES = DOUBLE(DT_JULIAN2DYEAR(TIMES))

 		IF TS.PROD EQ 'CHLOR_A' THEN BEGIN
			DATA=ALOG(DATA)
			numf=4*1024
		ENDIF

;		****************************************************************************************************
	  IF PS THEN PSPRINT,FILENAME=ROUTINE_NAME+'_NumF_'+NUM2STR(NUMF)+'_'+NUM2STR(ASERIES)+'.PS',/FULL,/COLOR
;		****************************************************************************************************
		!P.MULTI=[0,3,4]

;		===> ORIGINAL DATA
		PLOT, TIMES,DATA,TITLE='Data',/NODATA,/XSTYLE
		OPLOT, TIMES,DATA,PSYM=3,COLOR=6
		PLOT_EVENT,MEAN(DATA),/YAXIS,LINESTYLE=1

		PLOTXY, TIMES,DATA,TYPES='0',STATS_CHARSIZE=1,REG_COLOR=26,DECIMALS=3,PSYM=3,PARAMS=[1,2,3,4],TITLE='DATA)',SYM_COLOR=21

		PLOTXY, TIMES,DEMEAN(DATA),TYPES='0',STATS_CHARSIZE=1,REG_COLOR=26,DECIMALS=3,PSYM=3,PARAMS=[1,2,3,4],TITLE='DEMEAN(DATA))',SYM_COLOR=21


;		===> DEMEANED DATA
		PLOT, TIMES,DEMEAN(DATA),title='DEMEAN(DATA)',/NODATA,/YSTYLE
		OPLOT, TIMES,DEMEAN(DATA),PSYM=3,COLOR=11
		PLOT_EVENT,MEAN(DEMEAN(DATA)),/YAXIS,LINESTYLE=1

;		===> DETREND
	  DETRENDED = DETREND(TIMES,DATA,STRUCT=STRUCT,REG_TYPE='0')
		PLOT,TIMES, DETRENDED,PSYM=3,/XSTYLE,TITLE='DETRENDED(DATA)',/YSTYLE
		OPLOT,TIMES, DETRENDED,PSYM=3,COLOR=18
		PLOT_EVENT,MEAN(DETRENDED),/YAXIS,LINESTYLE=1

;		===> DETREND
	  DETRENDED = DETREND(TIMES,DEMEAN(DATA),STRUCT=STRUCT,REG_TYPE='0')
		PLOT,TIMES, DETRENDED,PSYM=3,/XSTYLE,TITLE='DETREND(DEMEAN(DATA))',/YSTYLE
		OPLOT,TIMES, DETRENDED,PSYM=3,COLOR=21
		PLOT_EVENT,MEAN(DETRENDED),/YAXIS,LINESTYLE=1

		PLOTXY, TIMES,DETREND(TIMES,DEMEAN(DATA)),TYPES='0',STATS_CHARSIZE=1,REG_COLOR=26,DECIMALS=3,PSYM=3,PARAMS=[1,2,3,4],TITLE='DETREND(DEMEAN(DATA))',SYM_COLOR=21

;		===> POLYFIT
    DEMEANED=DEMEAN(DATA)
		Result = POLY_FIT(TIMES,DEMEANED, 1, /DOUBLE, STATUS=STATUS,YFIT=YFIT)
		PLOT, TIMES,DEMEANED,TITLE='POLY_FIT DEMEAN(DATA)'	,/NODATA
		OPLOT, TIMES,DEMEANED-YFIT,COLOR=26,PSYM=3
		PLOT_EVENT,MEAN(DEMEANED),/YAXIS,LINESTYLE=1

		PLOTXY, TIMES,DEMEANED-YFIT,TYPES='0',STATS_CHARSIZE=1,REG_COLOR=26,DECIMALS=3,PSYM=3,PARAMS=[1,2,3,4],TITLE='POLY_FIT DETREND(DEMEAN(DATA))',SYM_COLOR=21,/XSTYLE


		N=N_ELEMENTS(DATA) & HALF=N/2
		X=[MEDIAN(TIMES(0:HALF)), MEDIAN(TIMES(HALF:*)) ] & X=[X,X]
		Y=[MEDIAN(DATA(0:HALF)), MEDIAN(DATA(HALF:*))]    & Y=[Y,Y]
		PLOTXY, X, Y,TYPES='0',STATS_CHARSIZE=1,REG_COLOR=26,DECIMALS=3,PSYM=3,PARAMS=[1,2,3,4],TITLE='MEDIAN',SYM_COLOR=21,/XSTYLE

   ;	IF PS THEN PSPRINT ELSE STOP

stop

	ENDFOR ; SERIES

END; #####################  End of Routine ################################



