; $ID:	FILE_RENAME_MONTHS.PRO,	2020-07-08-15,	USER-KJWH	$
;+
;#############################################################################################################
	PRO FILE_RENAME_MONTHS,FILES,OVERWRITE=OVERWRITE,$
	                       NOYEARS=NOYEARS,NEW_NAMES=NEW_NAMES

;
; PURPOSE: RENAMES STATS PERIOD FILES TO NEW PERIOD NAMES FOR MONTH
;
; CATEGORY:	FILE FAMILY
;
; CALLING SEQUENCE: FILE_RENAME_MONTHS,STRUCT
;
; INPUTS: FILES
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;	NOYEARS - WILL RENAME AS MONTH_01, MONTH_02, ETC.
; NEW_NAMES - NEW_NAMES OF FILES

; OUTPUTS: 
;  RENAMES THE FILE WITH THE NEW MONTH PERIOD SCHEME
;		
; EXAMPLES: 
; DIR_IN = "C:\PROJECTS\UNEP\OREILLY CHL PPD\LME_MONTHLY_CHL_HDF - Copy\"
; FILES = FILE_SEARCH(DIR_IN, '*MONTH*.hdf') & PLIST,FILES & PN,FILES,'FILES'
; FILES = FILE_SEARCH('C:\SMI\STATS_PERIODS\', '*MONTH*.SAVE') & PLIST,FILES & PN,FILES,'FILES'
;
; MODIFICATION HISTORY:
;			JUN 27,2014,  WRITTEN BY J.O'REILLY 
;			JUL 3,2014,JOR ADDED KEY NOYEARS
;			
;			
;			
;#################################################################################
;-
;***********************************
ROUTINE_NAME  = 'FILE_RENAME_MONTHS'
;***********************************
UL = '_'

IF NONE(FILES) THEN MESSAGE,'ERROR: FILES ARE REQUIRED'
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR NTH = 0, N_ELEMENTS(FILES)-1 DO BEGIN
FILE = FILES[NTH]
FN = FILE_PARSE(FILE)
NAME =FN.NAME
W = WORDS(NAME)
OK = WHERE_STRING(W,'MONTH_',COUNT)
IF COUNT EQ 1 THEN BEGIN
  PERIOD_OLD = W[OK]
  IF STRLEN(PERIOD_OLD) EQ 19 THEN BEGIN
    T = WORDS(PERIOD_OLD,DELIM = '_')
    START_YRMON = T[1]
    END_YRMON = T(2)
    START_YEAR = STRMID(START_YRMON,0,4)
    END_YEAR = STRMID(END_YRMON,0,4)
    START_MONTH = STRMID(START_YRMON,4,2)
    END_MONTH = STRMID(END_YRMON,4,2)
    IF START_MONTH NE END_MONTH THEN MESSAGE,'ERROR: MONTH VALUES DO NOT AGREE'
    PERIOD_NEW = 'MONTH_' + START_MONTH + UL +START_YEAR + UL + END_YEAR
    ;===> CHECK PERIOD_NEW
    PER = STRUCT_PERIOD(PERIOD_NEW)
    IF PER.PERIOD_CODE NE 'MONTH' THEN MESSAGE,'ERROR: INVALID PERIOD'
    IF KEY(NOYEARS) THEN   PERIOD_NEW = 'MONTH_' + START_MONTH 
     
  
      ;NEW_NAMES = [NEW_NAMES,PERIOD_NEW]      
      FILE_NEW = REPLACE(FILE,PERIOD_OLD,PERIOD_NEW)
      FILE_MOVE,FILE,FILE_NEW,/VERBOSE
    
  ENDIF ELSE BEGIN
   PFILE,FILE,/K    
  ENDELSE;IF STRLEN(PERIOD) EQ 19 THEN BEGIN
    
ENDIF;IF COUNT EQ 1 THEN BEGIN

ENDFOR;FOR NTH = 0, N_ELEMENTS(FILES)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF




END; #####################  END OF ROUTINE ################################
