; $ID:	FILE_CHECK.PRO,	2020-06-30-17,	USER-KJWH	$
;#############################################################################################################
	FUNCTION FILE_CHECK,FILES,DIR_IN=DIR_IN,DIR_OUT=DIR_OUT,PAT=PAT
	;##############################################
;+
; NAME:
;		FILE_CHECK
;
; PURPOSE: THIS FUNCTION RETURNS 1 IF FILES IN DIR_OUT ARE PRESENT AND UP-TO-DATE,
;           0 IF FILES IN DIR_OUT ARE NOT PRESENT OR ARE EARLIER THAN FILES IN DIR_IN
;
; CATEGORY:
;		FILES
;		 
;
; CALLING SEQUENCE:RESULT = FILE_CHECK(DIR_IN)
;
; INPUTS:
;		DIR_IN:	INPUT DIRIECTORY TO PASS TO FILE_SEARCH
;		PAT: STRING PATTERN TO PASS TO FILE_SEARCH 
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
; DIR_OUT  THE OUTPUT DIR TO CHECK

; OUTPUTS:
;   1 IF ALL FILES IN DIR_OUT ARE PRESENT AND UP-TO-DATE
;		0 IF ANY FILES IN DIR_OUT ARE NOT PRESENT OR ARE EARLIER THAN FILES IN DIR_IN
;; EXAMPLES:
;  PRINT, FILE_CHECK('D:\IDL\PROGRAMS\' ,'DOUBTFUL.PRO',DIR_OUT = 'D:\JUNK\') 
;
; MODIFICATION HISTORY:
;			WRITTEN JAN 11,2013 J.O'REILLY
;			NOV 8,2013,JOR ADDED FILE_INFO [MTIME] CHECKS
;#################################################################################
;-
;	**************************
ROUTINE_NAME  = 'FILE_CHECK'
; **************************
IF N_ELEMENTS(DIR_IN) NE 1 OR N_ELEMENTS(DIR_OUT) NE 1 OR N_ELEMENTS(PAT) NE 1 THEN $
  MESSAGE,'ERROR: DIR_IN,PAT AND DIR_OUT ARE REQUIRED'
  
;###> ASSUME TRUE UNLESS FOLLOWING CONDITIONS OCCUR
TF =  1
IF N_ELEMENTS(FILES) EQ 0 AND N_ELEMENTS(DIR_IN) EQ 1 AND N_ELEMENTS(PAT) EQ 1 THEN BEGIN
  FILES_IN=FILE_SEARCH(DIR_IN,'*'+PAT)
ENDIF ELSE BEGIN
  FILES_IN = FILES
ENDELSE;IF N_ELEMENTS(FILES) EQ 0 AND N_ELEMENTS(DIR_IN) EQ 1 THEN BEGIN
IF FILES_IN[0] EQ '' THEN TF = 0
IF N_ELEMENTS(FILES_IN) EQ 0 THEN TF = 0
IF N_ELEMENTS(FILE_TEST(FILES_IN)) EQ 0 THEN TF = 0
FI = FILE_INFO(FILES_IN) 
IF N_ELEMENTS(FILES) EQ 0 AND N_ELEMENTS(DIR_IN) EQ 1 AND N_ELEMENTS(PAT) EQ 1 THEN BEGIN
  FILES_OUT = FILE_SEARCH(DIR_OUT,PAT)
ENDIF ELSE BEGIN
  FILES_OUT
ENDELSE
FI = FILE_INFO(FILES_IN) 
FO = FILE_INFO(FILES_OUT)
IF MAX(FI.MTIME) GT MAX(FO.MTIME) OR $
   MIN(FO.SIZE) EQ 0 OR $
   (N_ELEMENTS(FI) GT N_ELEMENTS(FO) ) THEN TF = 0
RETURN,TF

END; #####################  END OF ROUTINE ################################
