; $ID:	FILTER_DEMO.PRO,	2020-06-30-17,	USER-KJWH	$

	PRO FILTER_DEMO

;+
; NAME:
;		FILTER_DEMO
;
; PURPOSE:
;		This procedure Demonstrates the shapes of various image filters
;
; CATEGORY:
;		IMAGE
;
; CALLING SEQUENCE:
;
;		FILTER_DEMO;

; INPUTS:
;		NONE
;
; OUTPUTS:
;		This Program Writes PNG images illustrating the magnitude of the filter
;
;	NOTES:
;
;
; MODIFICATION HISTORY:
;			Written Nov 21, 2006 by J.O'Reilly, 28 Tarzwell Drive, NMFS, NOAA 02882 (Jay.O'Reilly@NOAA.GOV)
;-
;	****************************************************************************************************
	ROUTINE_NAME = 'FILTER_DEMO'


;	===> PROGRAM SWITCHES
	DO_FILTER_IMAGES = 0
	DO_FILTER_PLOTS  = 0
	DO_FILTER_PLOTS  = 2


;	***********************************
	IF DO_FILTER_IMAGES GE 1 THEN BEGIN
;	***********************************

		PAL_SW3,R,G,B
		WIDTHS = [3,5,7,9,11,13,15,17,19,21]
		FILTERS = ['GAUSSIAN','TRICUBE']
	  FILTERS = ['TRAPEZOID']
		SIGMA = 1
		DATA = FINDGEN(100,100)

;		LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
		FOR NTH=0,N_ELEMENTS(FILTERS)-1 DO BEGIN
			AFILTER = FILTERS[NTH]
			FOR _WIDTH = 0,N_ELEMENTS(WIDTHS)-1 DO BEGIN
				AWIDTH = WIDTHS(_WIDTH)
				IF AFILTER EQ 'GAUSSIAN' THEN F = FILTER_GAUSSIAN(DATA,WIDTH=AWIDTH,/FILTER,SIGMA=SIGMA)
				IF AFILTER EQ 'TRICUBE'  THEN F = FILTER_TRICUBE(DATA,WIDTH=AWIDTH,/FILTER)
				IF AFILTER EQ 'TRAPEZOID' THEN F = FILTER_TRAPEZOID(DATA,WIDTH=AWIDTH,/FILTER)

				DATA = DATA/MAX(DATA)

				BIMAGE = SCALE(CONGRID(F,512,512), [1,250], MIN=0)

				NAME_EXTRA = AFILTER+ '-Width_'+ STR_PAD(STRTRIM(AWIDTH,2),2)

				IF AFILTER EQ 'GAUSSIAN' THEN BEGIN
					NAME_EXTRA = NAME_EXTRA+ '-SIGMA_'+ REPLACE(ROUNDS(STRTRIM(SIGMA,2),1),'.','_')
				ENDIF ELSE BEGIN
					NAME_EXTRA = NAME_EXTRA + ''
				ENDELSE
				TITLE = 'Relative Weight ' +   NAME_EXTRA
				LEG = COLOR_BAR_SCALE(PROD='PROB', XTITLE = TITLE, px=450,py=60,charsize=1.0,/cut,FONT='TIMES',BACKGROUND=252)
				BIMAGE(35,0) = LEG
				WRITE_PNG,ROUTINE_NAME+'-'+ NAME_EXTRA+ '.PNG', BIMAGE,R,G,B
			ENDFOR
		ENDFOR
	ENDIF


;	***********************************
	IF DO_FILTER_PLOTS GE 1 THEN BEGIN
;	***********************************
 		FILTERS = ['GAUSSIAN','TRICUBE']
 	;	FILTERS = 'TRAPEZOID'
	 	WIDTHS = FIX( SUBSAMPLE(INTERVAL([3,41]),2))
	  SIGMA = [0.5, 1.0, 2.0, 3.0, 4.0,5.0,6.0,7.0]
 		XAX =  SUBSAMPLE(FIX(INTERVAL([0,MAX(WIDTHS)/2])),2)

;		LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
		FOR _FILTER = 0,N_ELEMENTS(FILTERS)-1 DO BEGIN

			AFILTER = FILTERS(_FILTER)
			PS_FILE= ROUTINE_NAME+'-'+AFILTER+'.PS'
	 		PSPRINT,FILENAME=PS_FILE,/HALF,/COLOR
		 	FONTS,'TIMES'
			PAL_SW3,R,G,B

			YLOG=0
	 		PLOT,[XAX],[0,1],/NODATA,CHARSIZE=1.25,YLOG=YLOG,XTICKV = XAX,XTICKNAME=STRTRIM(XAX,2),XTICKS=N_ELEMENTS(XAX)-1,$
						TITLE = STR_CAP(AFILTER +' Filter'),xtitle='Distance from center (pixels)',ytitle='Relative Weight',/XSTYLE
			BACKGROUND,/PLOT,COLOR=TC(254)
			GRIDS,X= XAX,COLOR=TC(252),THICK=3
			FRAME,/PLOT,COLOR=TC[0],THICK=4

;			LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
			FOR NTH=0,N_ELEMENTS(SIGMA)-1 DO BEGIN
				ASIGMA = SIGMA[NTH]

				ODD = 1
;				LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
				FOR _WIDTH = N_ELEMENTS(WIDTHS)-1, 0 ,-1 DO BEGIN
					AWIDTH = WIDTHS(_WIDTH)
					DATA = FINDGEN(AWIDTH*4,AWIDTH*4)
					IF AFILTER EQ 'GAUSSIAN' 	THEN F = FILTER_GAUSSIAN(DATA,WIDTH=AWIDTH,/FILTER,SIGMA=ASIGMA)
					IF AFILTER EQ 'TRICUBE' 	THEN F = FILTER_TRICUBE(DATA,WIDTH=AWIDTH,/FILTER )
					IF AFILTER EQ 'TRAPEZOID' THEN F = FILTER_TRAPEZOID(DATA,WIDTH=AWIDTH,/FILTER)
					F = F/MAX(F)
					HORIZ = F(AWIDTH/2,AWIDTH/2:*)
					COLOR = 250- _WIDTH*11
					OK=WHERE(HORIZ EQ 1.0,COUNT)

					OPLOT, FINDGEN(N_ELEMENTS(HORIZ)),HORIZ	,COLOR= TC(COLOR)	,THICK=7
					IF  ODD EQ 1 THEN OPLOT, FINDGEN(N_ELEMENTS(HORIZ)),HORIZ	,COLOR= TC[0]	,THICK=1
					IF  ODD EQ 0 THEN OPLOT, FINDGEN(N_ELEMENTS(HORIZ)),HORIZ	,COLOR= TC(255)	,THICK=1
					ODD = ABS(ODD-1)
				ENDFOR
			ENDFOR
			IF AFILTER EQ 'GAUSSIAN' THEN BEGIN
				X= [1,2,4,6,8,10,12,14]
				I=LINDGEN(N_ELEMENTS(X))
				Y=REPLICATE(0.162,N_ELEMENTS(X))
				LABELS =STRING(SIGMA,FORMAT='(G-0)')
				LABELS(LAST(I))= LABELS(LAST(I))+' Sigma'
				XYOUTS2,X,Y,LABELS,ALIGN=[0.5,0.5],/DATA,CHARSIZE=1.5;,/background
			ENDIF
			CAPTION,"J.O'Reilly (NOAA) & I.Belkin (URI)",CHARSIZE=.75
			PSPRINT
			IMAGE_TRIM,PS_FILE
		ENDFOR ; FILTER
	ENDIF




	END; #####################  End of Routine ################################
