; $ID:	FLS.PRO,	2020-04-14-15,	USER-KJWH	$
;+
;#############################################################################################################
	FUNCTION FLS, DIR, TXT, DATERANGE=DATERANGE, COUNT=COUNT
;
; PURPOSE:  SHORTCUT FOR FILE_SEARCH [RETURNS !NULL WHEN NO FILES ARE FOUND]
;
; CATEGORY:	FILES
;
;
; INPUTS: DIR......... DIRECTORY
;         TXT......... TEXT STRING TO PASS TO FILE_SEARCH
;         		
; OPTIONAL INPUTS: 
;			    DATERANGE... DATE RANGE TO PASS TO DATE_SELECT 
;		
; KEYWORD PARAMETERS: 
;
; OUTPUTS: 
;         ARRAY OF FILES FOUND USING FILE_SEARCH [OR !NULL WHEN NONE FOUND]
;        
; OPTIONAL OUTPUTS:
;         COUNT... NUMBER OF FILES FOUND WITHIN THE INPUT DATERANGE        
;		
; EXAMPLES: [TWO METHODS ACCEPTED BY FILE_SEARCH]           
;           
;           FILES = FLS(!S.PROGRAMS+'*.PRO', COUNT=COUNT) & P,COUNT
;           FILES = FLS(!S.PROGRAMS,'*.PRO', COUNT=COUNT) & P,COUNT
;           FILES = FLS(!S.PROGRAMS +'*.ZZZ', COUNT=COUNT) & P,COUNT & HELP, FILES
; 
; NOTES:
;           NOTE THAT WHEN PROVIDING BOTH DIR AND TXT
;           FILE_SEARCH SEARCHES ALL SUBDIRECTORS IN DIR
;           
; MODIFICATION HISTORY:
;			NOV 20, 2014 WRITTEN BY J.O'REILLY
;     DEC 13, 2014 - JEOR: Overhauled
;     FEB 07, 2017 - KJWH: Added DATERANGE keyword and step to subset the files based on a daterange
;     NOV 05, 2018 - KJWH: Added IF N_ELEMENTS(DATERANGE) EQ 1 THEN FILES = DATE_SELECT(FILES,YEAR=DATERANGE,COUNT=COUNT)
;     APR 14, 2020 - KJWH: Changed name from FS to FLS because of a conflict with FS
;			
;#################################################################################
;-
; ********************
  ROUTINE_NAME  = 'FS'
; ********************
  IF N_PARAMS() EQ 0 THEN MESSAGE,'ERROR: MUST PROVIDE EITHER DIR,TXT OR A TXT STRING [INCLUDING DIR] FOR FILE_SEARCH'
  IF KEY(DIR) AND NONE(TXT) THEN FILES = FILE_SEARCH(DIR,COUNT=COUNT)
  IF KEY(DIR) AND KEY(TXT)  THEN FILES = FILE_SEARCH(DIR,TXT,COUNT=COUNT)
  
  IF N_ELEMENTS(DATERANGE) EQ 2 THEN FILES = DATE_SELECT(FILES,DATERANGE,COUNT=COUNT)
  IF N_ELEMENTS(DATERANGE) EQ 1 THEN FILES = DATE_SELECT(FILES,YEAR=DATERANGE,COUNT=COUNT)

  IF COUNT GE 1 THEN RETURN, FILES ELSE RETURN,[]

END; #####################  END OF ROUTINE ################################
