; $ID:	GET_IP.PRO,	2020-06-30-17,	USER-KJWH	$

function GET_IP
;+
; NAME:
;       GET_IP
;
; PURPOSE:
;       Get the IP address of the current system
;
; CATEGORY:
;       SYSTEM
;
; CALLING SEQUENCE:
;        IP=GET_IP()
;
; INPUTS:
;       NONE
;
; KEYWORD PARAMETERS:
;       NONE
; OUTPUTS:
;       IP ADDRESS OF CURRENT SYSTEM
;
; MODIFICATION HISTORY:
;       Written by:  J.E.O'Reilly, Nov 14,2000
;-

  OS=STRUPCASE(!VERSION.OS)
  IF OS EQ 'WIN32'  THEN CMD = 'IPCONFIG'

  IF OS EQ 'LINUX' THEN CMD = 'IPCONFIG'
  IF OS EQ 'IRIX'  THEN CMD = 'IPCONFIG'
  IF OS EQ 'OSF'   THEN CMD = 'IPCONFIG'

  SPAWN,CMD,IP

  OK = WHERE(STRPOS(STRUPCASE(IP),'ADDRESS') GE 0,COUNT)
  IF COUNT GE 1 THEN BEGIN
  	txt = STR_SEP(IP(OK[0]),':')
    RETURN, LAST(STRTRIM(TXT,2))
  ENDIF ELSE BEGIN
    RETURN, -1L
  ENDELSE
  END; OF PROGRAM
