; $ID:	GET_LME_MEAN.PRO,	2020-06-30-17,	USER-KJWH	$
;+
;;#############################################################################################################
	FUNCTION GET_LME_MEAN,LME,PROD = PROD,INIT=INIT,PER=PER,YR_RANGE=YR_RANGE,ALL=ALL,PPY=PPY,OTHER=OTHER,_EXTRA=_EXTRA

; PURPOSE: THIS FUNCTION COMPUTES THE MEAN FROM A YEARLY LME TIME SERIES 
; 
; 
; CATEGORY:	LMES;		 
;
; CDING SEQUENCE: RESULT = GET_LME_MEAN(LME)
;
; INPUTS: LME  [NAME OR NUMERIC CODE]

; OPTIONAL INPUTS:
;		
; KEYWORD PARAMETERS:
;         PROD : STANDARD PROD NAME
;         INIT : REREAD THE SAVFILE INTO MEMORY
;         ALL  : RETURNS MEANS FOR ALL LMES
;         OTHER : ADDITIONAL TAGS TO ADD TO THE OUTPUT STRUCTURE
; NOTES:
;       THE FIRST RUNS OF STATS_TRENDS WERE DONE USING AMEAN OF CHLOR_A


; OUTPUTS: 
;		
;; EXAMPLES:
;  T = GET_LME_MEAN('BALTIC_SEA',PROD = 'CHLOR_A') &H,T
;  T = GET_LME_MEAN('KARA_SEA',  PROD = 'CHLOR_A') &H,T
;  T = GET_LME_MEAN(7,  PROD = 'CHLOR_A') &H,T
;  T = GET_LME_MEAN('BALTIC_SEA',PROD = 'CHLOR_A',PER = 'M') &H,T
;  T = GET_LME_MEAN('BALTIC_SEA',PROD = 'CHLOR_A',PER = 'MONTH') &H,T
;  T = GET_LME_MEAN('yellow_SEA',PROD = 'CHLOR_A') &H,T
;  T = GET_LME_MEAN('BALTIC_SEA',PROD = 'PPD') & P,T.MEAN*365.25
;  T = GET_LME_MEAN('YELLOW_SEA',PROD = 'PPD') & P,T.MEAN*365.25
;  T = GET_LME_MEAN(7,PROD = 'PPD') & P,T.MEAN*365.25
;  T = GET_LME_MEAN(/ALL,  PROD = 'CHLOR_A') &H,T
;	NOTES:

;
; MODIFICATION HISTORY:
;			WRITTEN OCT 9, 2014 J.O'REILLY
;			OCT 14,2014,JOR ADDED PER TO OUTPUT STRUCT
;			OCT 19,2014,JOR ADDED FOR LOOP [TO GET MEANS FOR MANY LMES]
;			                ADDED KEY ALL
;			                IF PROD EQ 'PPD' AND KEY(PPY) THEN S.MEAN = S.MEAN* 365.25
;     OCT 22,2014,JOR ADDED ,PPY=PPY TO GET_LME_TS & REMOVED *365.25 LOGIC

;			
;#################################################################################
;-
;******************************
ROUTINE_NAME  = 'GET_LME_MEAN'
;******************************
;######      DEFAULTS     ##########
IF NONE(PER) THEN PER= 'Y'
IF NONE(YR_RANGE) THEN YR_RANGE = FIX(['1998','2013'])
IF KEY(ALL) THEN LME = (READ_LME_DB()).MAP


;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR NTH = 0,N_ELEMENTS(LME)-1 DO BEGIN 
 TS =GET_LME_TS(LME[NTH],PROD = PROD,PER = PER,YR_RANGE=YR_RANGE,PPY=PPY,_EXTRA=_EXTRA)
 JD = PERIOD_2JD(TS.PERIOD)
 S = FIRST(TS)
 S = CREATE_STRUCT(S,'N',N_ELEMENTS(TS))
 S.MEAN_TYPE ='AMEAN'
 S.MEAN =  MEAN(TS.MEAN,/NAN)
 S.PERIOD = STRTRIM(MIN(TS.PERIOD),2) +  STRTRIM(MAX(TS.PERIOD),2) 

IF NONE(D) THEN D = S ELSE D = [D,S] 
ENDFOR;FOR NTH = 0,N_ELEMENTS(LME)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
RETURN,D

DONE:          
	END; #####################  END OF ROUTINE ################################
