; $ID:	I_SUN_KIRK_DAY_LENGTH_MAP_DEMO.PRO,	2020-06-03-17,	USER-KJWH	$

  PRO I_SUN_KIRK_DAY_LENGTH_MAP_DEMO, DOY,MAP=MAP, PS=PS

;+
; NAME:
;       I_SUN_KIRK_DAY_LENGTH_MAP_DEMO
;
; PURPOSE:
;       CALCULATE SUN CHARACTERISTICS ACCORDING TO EQUATIONS IN:
;       KIRK, J.T.O, 1994, LIGHT AND PHOTOSYNTHESIS IN AQUATIC ECOSYSTEMS,
;                          CAMBRIDGE UNIVERSITY PRESS, 509PP.
;
; CATEGORY:
;       LIGHT, MAP
;
; CALLING SEQUENCE:
;
;       I_SUN_KIRK_DAY_LENGTH_MAP
;
;
; INPUTS:
;       DOY: DAY OF YEAR (1,366)
;
; KEYWORD PARAMETERS:
;       MAP:
;       AN IDL MAP NAME (I.E.  NEC, GLOBAL_EQUIDISTANT, SEC)
;
; OUTPUTS:
;       A MAP IMAGE WITH FLOATING POINT VALUES EQUAL TO THE CALCULATED DAY LENGTH
;
; SIDE EFFECTS:
;       NONE.
;
; RESTRICTIONS:
;       NONE.
;
; PROCEDURE:
;       STRAIGHTFORWARD.
;
; MODIFICATION HISTORY:
;       WRITTEN BY:  J.E.O'REILLY, AUGUST 27, 1999
;-


; ====================>
ROUTINE_NAME='I_SUN_KIRK_DAY_LENGTH_MAP_DEMO'
  PROD = 'DAY_LENGTH'
  MAPS = ['L3B','NEC']
  MAPS = 'SMI'

	FOR _MAP = 0,N_ELEMENTS(MAPS)-1 DO BEGIN
	  MAP = MAPS(_MAP)

;*****************************
  	IF MAP EQ 'NEC' THEN BEGIN
;*****************************
  	PAL_SW3,R,G,B

  		CMD = 'MAP_'+MAP
  		PX = 1024
  		PY = 1024

; 		================>
; 		OPEN ZWIN TO DIMENSION PROPERLY THE MAP
  		ZWIN,[PX,PY]

  		A = EXECUTE(CMD)
; 		====================>
; 		DEVICE COORDINATES FOR ALL PIXELS IN THE MAP
  		XX =  FINDGEN(PX) # REPLICATE(1.,PY)
  		YY = REPLICATE(1.,PX) # FINDGEN(PY)

; 		===================>
; 		ADD 1/2 PIXEL SO COORDINATES ARE IN THE CENTER OF EACH PIXEL
  		XX = XX+0.5
  		YY = YY+0.5

; 		===================>
; 		CONVERT DEVICE COORDINATES TO DATA COORDINATES
  		XYZ = CONVERT_COORD(XX,YY,/DEVICE, /TO_DATA)

  		ZWIN ; CLOSE ZWIN

; 		===================>
; 		EXTRACT LON AND LAT
  		LON = REFORM(XYZ(0,*))
  		LAT = REFORM(XYZ(1,*))

    		DAY = 21
    	FOR MONTH = 1,12 DO BEGIN
      	JD  = JULDAY(MONTH,DAY,2000,0,0)
      	DT = JD_2DATE(JD)
      	DOY = DATE_2DOY(DT)
      	DAY_LENGTH=I_SUN_KIRK_DAY_LENGTH(LAT, DOY)
      	DAY_LENGTH=REFORM(DAY_LENGTH,PX,PY)

      	SLIDEW,BYTSCL(DAY_LENGTH,MIN=7,MAX=16),TITLE=NUM2STR(MONTH)
    ;  	SLIDEW,BYTSCL(DAY_LENGTH),TITLE=NUM2STR(MONTH)
     		_MIN=MIN(DAY_LENGTH,MAX=_MAX)
     		_MEAN = MEAN(DAY_LENGTH)
     		RANGE = _MAX -  _MIN
     		PRINT, 'MONTH: ',MONTH, ' MIN: ',_MIN,' MAX: ',_MAX,' MEAN: ', _MEAN, 'RANGE: ',RANGE
     		STOP
   		ENDFOR
   	ENDIF;IF MAP EQ NEC THEN BEGIN
   	;|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
 
 
 
   	;*****************************
   	IF MAP EQ 'SMI' THEN BEGIN
   	;*****************************
   	  PAL_SW3,R,G,B   	  
      MAPS_SET,MAP
   	   PX = !D.X_SIZE
   	   PY = !D.Y_SIZE
   	  
   	  
   	  ;     ====================>
   	  ;     DEVICE COORDINATES FOR ALL PIXELS IN THE MAP
   	  XX =  FINDGEN(PX) # REPLICATE(1.,PY)
   	  YY = REPLICATE(1.,PX) # FINDGEN(PY)
   	  
   	  ;     ===================>
   	  ;     ADD 1/2 PIXEL SO COORDINATES ARE IN THE CENTER OF EACH PIXEL
   	  XX = XX+0.5
   	  YY = YY+0.5
   	  
   	  ;     ===================>
   	  ;     CONVERT DEVICE COORDINATES TO DATA COORDINATES
   	  XYZ = CONVERT_COORD(XX,YY,/DEVICE, /TO_DATA)
   	  
   	  ZWIN ; CLOSE ZWIN
   	  
   	  ;     ===================>
   	  ;     EXTRACT LON AND LAT
   	  LON = REFORM(XYZ(0,*))
   	  LAT = REFORM(XYZ(1,*))
   	  
   	  DAY = 21
   	  FOR MONTH = 1,12 DO BEGIN
   	    JD  = JULDAY(MONTH,DAY,2000,0,0)
   	    DT = JD_2DATE(JD)
   	    DOY = DATE_2DOY(DT)
   	    DAY_LENGTH=I_SUN_KIRK_DAY_LENGTH(LAT, DOY)
   	    DAY_LENGTH=REFORM(DAY_LENGTH,PX,PY)
   	    FILE = !S.IDL_TEMP + MAP + '-' + MONTH_NAMES(MONTH) + '.PNG'
   	  
        PRODS_2PNG,FILE,PROD=PROD,STAT=STAT,DIR_OUT=DIR_OUT,NOBAR=NOBAR,$
                 CB_POS=CB_POS,EDIT=EDIT,BUFFER=BUFFER,VERBOSE=VERBOSE,$
                 OVERWRITE=OVERWRITE,MAP_OUT=MAP_OUT,ADD_NAME=ADD_NAME,$
                 ASPECT=ASPECT,BIT_DEPTH =BIT_DEPTH,LOG=LOG,$
                 CB_FONT_SIZE=CB_FONT_SIZE,COMMA=COMMA,LONLAT=LONLAT,LMES=LMES,OUTFILE=OUTFILE,$
                 EXTEND=EXTEND,_EXTRA = _EXTRA   	    ;;SLIDEW,BYTSCL(DAY_LENGTH,MIN=7,MAX=16),TITLE=NUM2STR(MONTH)
   	    ;   SLIDEW,BYTSCL(DAY_LENGTH),TITLE=NUM2STR(MONTH)
   	    _MIN=MIN(DAY_LENGTH,MAX=_MAX)
   	    _MEAN = MEAN(DAY_LENGTH)
   	    RANGE = _MAX -  _MIN
   	    ;PRINT, 'MONTH: ',MONTH_NAMES(MONTH), ' MIN: ',ROUNDS(_MIN,2),' MAX: ',ROUNDS(_MAX,2),' MEAN: ', ROUNDS(_MEAN,2), '  RANGE: ',ROUNDS(RANGE,2)
   	    STOP
   	  ENDFOR
   	ENDIF;IF MAP EQ NEC THEN BEGIN
   	;|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
   	IF MAP EQ 'L3B' THEN BEGIN
   	  IF KEYWORD_SET(PS) THEN PSPRINT,FILENAME='D:\IDL\PROGRAMS\'+ROUTINE_NAME+'-'+MAP+'.PS',/COLOR,/PORTRAIT,/HALF
   	  PAL_36,R,G,B
   	  LAT = DINDGEN(181)-90

   	  JULIAN = TIMEGEN(12, START=DT_DATE2JULIAN('2003122012') ,MONTHS=INDGEN(12)+1)
   	  DATE = DT_JULIAN2DATE(JULIAN)
   	  DOY = DT_DATE2DOY(DATE)
   	  COLORS = [2,7,9,10,11,13,17,18,20,22,24,26]
   	  XTICKV=INDGEN(25)
   	  FOR _DOY = 0,N_ELEMENTS(DOY)-1 DO BEGIN
  	  	DL= I_SUN_KIRK_DAY_LENGTH(LAT,DOY(_DOY))
   	    IF _DOY EQ 0 THEN BEGIN
   	    	PLOT, DL,LAT,/NODATA ,YRANGE=[-90,90],/YSTYLE,YTITLE='LATITUDE',XRANGE=[-0.5,24.5],XTITLE='DAYLENGTH (H)',$
   	    	XTHICK=3,YTHICK=3,YTICKS=18,XTICKS=24,/XSTYLE,XTICKV=XTICKV,XTICK_GET=XTICK_GET,YTICK_GET=YTICK_GET
   	    	GRIDS,XTICK_GET,YTICK_GET,COLOR=34,/ALL,/AUTO
   	    ENDIF
   	    OPLOT, DL,LAT,COLOR=COLORS(_DOY),THICK=3
       IF NOT KEYWORD_SET(PS) THEN STOP
			ENDFOR
			IF KEYWORD_SET(PS) THEN PSPRINT ELSE STOP
   	ENDIF

	ENDFOR ; MAPS

; ===================>
  END; END OF PROGRAM
