; $ID:	IMAGE_INTERVALS.PRO,	2020-06-30-17,	USER-KJWH	$
;#############################################################################################################
	PRO IMAGE_INTERVALS,FILES,DIR_OUT=DIR_OUT,PS=PS,OVERWRITE=OVERWRITE
	
;  PRO IMAGE_INTERVALS
;+
; NAME:
;		IMAGE_INTERVALS
;
; PURPOSE: THIS PROGRAM MAKES A PNG IMAGE STRIP OF RANGES OF DATA (FROM A SD SAVEFILE) 
;
; CATEGORY:
;		PROGRAMS
;		 
;
; CALLING SEQUENCE:IMAGE_INTERVALS
;
; INPUTS: 
;     FILES: COMPLETE FILES NAME
;		
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		NONE: 

; OUTPUTS: A PNG FILE FOR EACH INPUT FILES
;		
;; EXAMPLES:
;  IMAGE_INTERVALS,'F:\SMI\LNP\!STUDY-SEAWIFS_AQUA-ORBV2_EOSAT-SMI-2010-CHLOR_A-LNP_1CPY.SAVE'
;  IMAGE_INTERVALS,'F:\SMI\LNP\!STUDY-SEAWIFS_AQUA-ORBV2_EOSAT-SMI-2010-CHLOR_A-LNP_2CPY.SAVE'
;  IMAGE_INTERVALS,'F:\SMI\LNP\!STUDY-SEAWIFS_AQUA-ORBV2_EOSAT-SMI-2010-CHLOR_A-LNP_3CPY.SAVE'
;  IMAGE_INTERVALS,'F:\SMI\LNP\!STUDY-SEAWIFS_AQUA-ORBV2_EOSAT-SMI-2010-CHLOR_A-LNP_4CPY.SAVE'
;  IMAGE_INTERVALS,'F:\SMI\LNP\!STUDY-SEAWIFS_AQUA-ORBV2_EOSAT-SMI-2010-CHLOR_A-VAR.SAVE'
;	NOTES:

;
; MODIFICATION HISTORY:
;			WRITTEN DEC 5,2012  J.O'REILLY
;			FEB 7,2013,JOR ADDED FILES LOOP
;			FEB 15,2013,JOR:IF N_ELEMENTS(OVERWRITE) NE 1 THEN _OVERWRITE = 0 ELSE _OVERWRITE = OVERWRITE

;#################################################################################
;
;
;-
;*******************************************
ROUTINE_NAME='IMAGE_INTERVALS'
;*******************************************

IF N_ELEMENTS(OVERWRITE) NE 1 THEN _OVERWRITE = 0 ELSE _OVERWRITE = OVERWRITE

IF N_ELEMENTS(DIR_OUT) NE 1 THEN BEGIN
CD,CURRENT = DIR
DIR_OUT = DIR + PATH_SEP()
ENDIF;IF N_ELEMENTS(DIR_OUT) NE 1 THEN BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR _FILE = 0,N_ELEMENTS(FILES)-1 DO BEGIN
  FILE = FILES(_FILE)
  PFILE,FILE,/R
  IF _FILE NE 0 THEN _OVERWRITE = 0
  DATA=STRUCT_SD_READ(FILE,STRUCT=STRUCT)
  SZ=SIZEXYZ(DATA) & PX = SZ.PX & PY = SZ.PY & _CHARSIZE = 0.005*PX 
  FN=FILE_PARSE(FILE)
  NAME = FN.NAME
  REPORT,NAME,OVERWRITE=_OVERWRITE 
  
  ;===> MAKE A PS FILE
  PSFILE = DIR_OUT +NAME +'.PS'
  PAL_36,R,G,B
  _MM = MINMAX(DATA,/FIN)
  ;===> GET THE SPAN OF THE DATA
  _SPAN=SPAN(_MM)
  
  ;===> DIVIDE THE _SPAN INTO 10 INTERVALS
  _INTERVALS = ROUNDS(INTERVAL([_MM],_SPAN/10.),1)
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR NTH = 0,N_ELEMENTS(_INTERVALS)-1 DO BEGIN
    LOWER = _INTERVALS[NTH]
    UPPER = _INTERVALS(0 > (NTH+1) < (N_ELEMENTS(_INTERVALS)-1))
    OK = WHERE(DATA GE LOWER AND DATA LE UPPER AND DATA NE MISSINGS(DATA),COUNT)
    IF COUNT GE 1 THEN BEGIN
      TXT = '  RANGE:   '+STRTRIM(LOWER,2) + ' TO  '+STRTRIM(UPPER,2) + '  COUNT   ' + STRTRIM(COUNT,2)
      
      REPORT,TXT
      IF KEYWORD_SET(PS) THEN BEGIN  
        TXT = '!C    RANGE:   '+STRTRIM(LOWER,2) + ' TO  '+STRTRIM(UPPER,2) + '!C COUNT   ' + STRTRIM(COUNT,2)
        
        IM = BYTE(DATA) & IM(*) = 255 & IM[OK] = 30;DARK GRAY
        FONT_TIMES
        PSPRINT,PSFILE,/COLOR & TV,IM        
        XYOUTS,0.5,0.95,TXT,/NORMAL,CHARSIZE = _CHARSIZE,COLOR = 21,CHARTHICK = 3,ALIGN = 0.5
        FRAME,COLOR = 0,/REGION,THICK = 3
        IM=TVRD()
        ZWIN
        IF N_ELEMENTS(PAGE) EQ 0 THEN PAGE = IM ELSE PAGE = IMAGE_WELD(PAGE,IM) 
        WRITE_PNG,PSFILE,PAGE,R,G,B
        PFILE,PSFILE,/W    
      ENDIF;IF KEYWORD_SET(PS) THEN BEGIN
    ENDIF;IF COUNT GE 1 THEN BEGIN 
    
  ENDFOR;FOR NTH = 0,N_ELEMENTS(_INTERVALS)-1 DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  REPORT,''
ENDFOR;FOR _FILE = 0,N_ELEMENTS(FILES)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

DONE:          
	END; #####################  END OF ROUTINE ################################
