; $ID:	IMAGE_CAPTION.PRO,	2020-07-01-12,	USER-KJWH	$
;#############################################################################################################
	PRO IMAGE_CAPTION,FILES,TXT,CHARSIZE=CHARSIZE,CHARTHICK=CHARTHICK,COLOR = COLOR,DIR_OUT=DIR_OUT,_EXTRA=_EXTRA
	
;  PRO IMAGE_CAPTION
;+
; NAME:
;		IMAGE_CAPTION
;
; PURPOSE: THIS PROGRAM ADDS A CAPTION TO THE LOWER RIGHT OF AN IMAGE FILE.
;
; CATEGORY:
;		IMAGES
;		 
;
; CALLING SEQUENCE: IMAGE_CAPTION
;
; INPUTS: 
;   FILES: COMPLETE NAMES OF A BINARY IMAGE FILE
;         IF FILE IS NOT PROVIDED THEN IT MAY BE SELECTED USING DIALOG_PICKFILE
;		
;		
; OPTIONAL INPUTS:
;		TXT: TEXT STRING TO ADD TO IMAGE [ DEFAULT IS J.O'Reilly ]	
;		
; KEYWORD PARAMETERS:
;		NONE:

; OUTPUTS: WRITES OVER THE INPUT FILE
;		
;; EXAMPLES:
;  IMAGE_CAPTION,"C:\UP\TUFTED TITMOUSE 71 PLEASANT ST J.O'REILLY WSBC0071.JPG"
;  IMAGE_CAPTION,"C:\UP\BLUE JAY 71 PLEASANT ST J.O'REILLY WSBC0062.JPG",CHARTHICK=5,COLOR = 255,CHARSIZE = 8
;  FILES = FILE_SEARCH('C:\UP\*.JPG') &  OK = WHERE_STRING(FILES,'eilly',COUNT,/cases) & F = REMOVE(FILES,OK) & IMAGE_CAPTION,F
;	NOTES:

;
; MODIFICATION HISTORY:
;			WRITTEN NOV 9 1,2012 J.O'REILLY
;			NOV 12.2012,JOR, NOW USES TWO COLOR ,WHITE UNDER BLACK
;			                  ADDS SUFFIX [TXT] TO OUTPUT FILE NAME
;			JAN 2,2013,JOR ADDED FOR LOOP
;			JAN 15,2013,JOR FIXED LOOP PROBLEM [NTH] 
;			JUL 22,2013,JOR CHANGED TXT TO _TXT FOR OUTFILE
;#################################################################################
;
;
;-
;	*******************************************
ROUTINE_NAME='IMAGE_CAPTION'
; *******************************************
;CHARTHICK
;===> CONSTANTS
PLOT=1
FONT_HELVETICA
COLOR = 255
FILTER = ['*.JPG;*.JPEG', '*.TIF;*.TIFF', '*.PNG']
IF N_ELEMENTS(CHARSIZE) NE 1 THEN CHARSIZE = 8
IF N_ELEMENTS(CHARTHICK) NE 1 THEN CHARTHICK = 5

IF N_ELEMENTS(FILES) EQ 0 THEN FILES = DIALOG_PICKFILE(FILTER = FILTER,/MUST_EXIST,/READ)
IF N_ELEMENTS(TXT) NE 1 THEN TXT = "J.E.O'Reilly"
IF N_ELEMENTS(COLOR) NE 1 THEN COLOR = 255

;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR NTH = 0,N_ELEMENTS(FILES)-1 DO BEGIN
FILE = FILES[NTH]
PFILE,FILE,/R
POF,NTH,FILES

;;IM = READALL(FILE,RED=RED,GREEN=GREEN,BLUE=BLUE, TYPE=type)
IM = READ_IMAGE(FILE , RED, GREEN, BLUE)
IF IDLTYPE(IM,/CODE) NE 1 AND IDLTYPE(IM,/CODE) NE 12 THEN MESSAGE,'ERROR:   FILE MUST BE A BYTE IMAGE'
FN = FILE_PARSE(FILE)
FMT = FN.EXT
IF STRUPCASE(FMT) EQ 'JPG' THEN FMT = 'JPEG'

_TXT = REPLACE(TXT,'.','')
IF N_ELEMENTS(DIR_OUT) EQ 0 THEN DIR_OUT = FN.DIR
OUTFILE = DIR_OUT +FN.NAME +'-'+ _TXT + '.'+ FN.EXT
SZ=SIZEXYZ(IM)
DIMS = SZ.N_DIMENSIONS

;CAPTION, TXT, X=X, Y=Y,DATE=DATE,ROUTINE=ROUTINE, PLOT=PLOT, REGION=REGION,_EXTRA=_EXTRA
IF DIMS EQ 2 THEN BEGIN
   ZWIN,IM
;   XYOUTS2,1.0,1.5,TXT,COLOR=TC(COLOR),CHARSIZE=CHARSIZE,CHARTHICK=CHARTHICK,ALIGN=[0.5, 0.5] ,/BACKGROUND,GRACE = [.2,.2];, LINESPACE=.6
  CAPTION, TXT, X=X, Y=Y,DATE=DATE,ROUTINE=ROUTINE, PLOT=PLOT, REGION=REGION,COLOR = 0,THICK=THICK,_EXTRA=_EXTRA
  IM=TVRD()
ENDIF;IF DIMS EQ 2 THEN BEGIN
  
IF DIMS EQ 3 THEN BEGIN  
  ;FFFFFFFFFFFFFFFFFFFFFFFF
  FOR P = 0,DIMS-1 DO BEGIN
    PLANE = REFORM(IM(P,*,*))
    ZWIN,PLANE & TV,PLANE
 ;    XYOUTS2,1.0,1.5,TXT,COLOR=TC(COLOR),CHARSIZE=CHARSIZE,CHARTHICK=CHARTHICK,ALIGN=[0.5, 0.5]; ,/BACKGROUND,GRACE = [.2,.2];, LINESPACE=.6
;     XYOUTS2,0.02,1.0,/NORMAL,TXT,COLOR=TC(COLOR),CHARSIZE=CHARSIZE,CHARTHICK=CHARTHICK,ALIGN=[0.5, 0.5]; ,/BACKGROUND,GRACE = [.2,.2];, LINESPACE=.6
    CAPTION, TXT, X=X, Y=Y,DATE=DATE,ROUTINE=ROUTINE, PLOT=PLOT, REGION=REGION,COLOR = COLOR,CHARSIZE = CHARSIZE,_EXTRA=_EXTRA
    PLANE = TVRD()
    IM(P,*,*) = PLANE  
  ENDFOR;FOR P = 0,DIMS-1 DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
ENDIF;IF DIMS EQ 3 THEN BEGIN


;*********************************
IF N_ELEMENTS(RED) EQ 0 THEN BEGIN
  WRITE_IMAGE, OUTFILE, FMT, IM 
ENDIF ELSE BEGIN
  WRITE_IMAGE, OUTFILE, FMT, IM , Red, Green, Blue
ENDELSE;IF N_ELEMENTS(RED) EQ 0 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||

 PFILE,OUTFILE,/W

ENDFOR;FOR NTH = 0,N_ELEMENTS(FILES)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

DONE:

END; #####################  END OF ROUTINE ################################
