; $ID:	ISCCP_LOCATION_PLOT.PRO,	2014-12-18	$
;+
;	This Program Plots ISCCP data from a single grid BOOTH_BAY_HARBOR
; NOTES:
; GO TO: http://ingrid.ldgo.columbia.edu/SOURCES/.ISCCP/
;	PICK OUT TWO NEAREST GRID BOOTH_BAY_HARBORS
;	PICK OPTION DAYS SINCE 1960
; SAVE FILE IN C:\AAA\gridtable.tsv
;
;		April  6,2003	Written by:	J.E. O'Reilly, NOAA, 28 Tarzwell Drive, Narragansett, RI 02882
;-
; *************************************************************************

PRO ISCCP_BOOTH_BAY_HARBOR_PLOT,FILE
  ROUTINE_NAME='ISCCP_BOOTH_BAY_HARBOR_PLOT'

  IF N_ELEMENTS(FILE) EQ 0 THEN FILE = 'C:\AAA\gridtable.tsv'
   FILE='D:\IDL\DATA\ISCCP_43_75N_68_75W_DAYS_SINCE_19600101.CSV'

;  BY TWO LONGITUDES FOR INTERPOLATION TO BOOTH BAY
   FILE ='D:\IDL\DATA\ISCCP_43_75N_71_25W_68_75W_DAYS_SINCE_19600101.CSV'
   TITLE = 'Surface Radiation at 43.75N,68.75W'
   PAL_36
   SETCOLOR,255
  D=READ_CSV(FILE)



  JULIAN_19600101= JULDAY(1,1,1960)

  JULIAN = DOUBLE(D.DAYS_SINCE_19600101) + JULIAN_19600101 - 1 ;
	DATE=DT_JULIAN2DATE(JULIAN)

  YEAR = LONG(STRMID(DATE,0,4))
  MONTH= LONG(STRMID(DATE,4,2))
  DPM=dt_DAYS_MONTH(month, year=year)
  JULIAN = JULIAN - DPM/2.0


  ISCCP_W_M2_71_25W =FLOAT(D.ISCCP_W_M2_71_25W)
  ISCCP_W_M2_68_75W =FLOAT(D.ISCCP_W_M2_68_75W)
  LON1 = -71.25
  LON2 = -68.75

  L=LOCATE('BOOTH BAY HARBOR')
  LAT = L.LAT
  LON = L.LON

  ISCCP_W_M2 = REPLICATE(0.0,N_ELEMENTS(D))
  FOR N=0L,N_ELEMENTS(D)-1 DO BEGIN
  V1 = ISCCP_W_M2_71_25W(N)
  V2 = ISCCP_W_M2_68_75W(N)
  ISCCP_W_M2(N) = INTERPOL([V1,V2],[LON1,LON2],LON)
  ENDFOR


  DX=DT_AXIS(JULIAN,/MONTHS,name=1)
  PLOT, JULIAN,ISCCP_W_M2,XTICKS=DX.TICKS,XTICKNAME=DX.TICKNAME,XTICKV=DX.TICKV,$
  	    title=title,/nodata,XTICK_GET=XTICK_GET,YTICK_GET=YTICK_GET
  grids, COLOR=35,XTICK_GET,YTICK_GET
  OPLOT, JULIAN,ISCCP_W_M2
  STOP
	julian=DT_SAT2JULIAN(CSV.INAME)
	dt = DT_JULIAN2DATE(julian)
	SUN=DT_SUNPOS(DT=dt,LAT=lat,LON=lon)

	TYPE= NECW_CWF_NAME2TYPE(CSV.FIRST_NAME)
	OK = WHERE(SUN.EL LT 20.4 AND TYPE NE 'sm',COUNT)

STOP

END; #####################  End of Routine ################################
