; $ID:	LIST_2ZIP.PRO,	2020-07-01-12,	USER-KJWH	$
;+
;#############################################################################################################
	PRO LIST_2ZIP,FILE,DIR_IN = DIR_IN,DIR_OUT=DIR_OUT,ZIP=ZIP

;
; PURPOSE: MAKE A ZIP FILE FROM A LIST OF PROGRAM FILE NAMES
;
; CATEGORY:	
;
; CALLING SEQUENCE: LIST_2ZIP
;
; INPUTS: 
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		

; OUTPUTS: 
;		
; EXAMPLES: 
; 
;
; MODIFICATION HISTORY:
;			JUL 3,2014,  WRITTEN BY J.O'REILLY 
;			
;			
;			
;#################################################################################
;-
;**************************
ROUTINE_NAME  = 'LIST_2ZIP'
;**************************
;===> DEFAULTS
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
IF NONE(DIR_OUT) THEN DIR_OUT = !S.IDL_TEMP
IF NONE(ZIP) THEN ZIP = ROUTINE_NAME
IF NONE(FILE) THEN TXT = READ_TXT() ELSE TXT =READ_TXT(FILE)
NAMES = FILE_SEARCH(TXT+ '.PRO')
NAMES = STRUPCASE(NAMES)
;===> IF ANY ARE DEMOS THEN GET THE PRO THAT DEMO CALLS
OK = WHERE_STRING(NAMES,'_DEMO',COUNT)
IF COUNT GE 1 THEN BEGIN
  ORIG = REPLACE(NAMES[OK],'_DEMO','')
  NAMES = [NAMES,ORIG]
ENDIF;IF COUNT GE 1 THEN BEGIN
;===> ZIP NAMES
ZIP_FILE = DIR_OUT +ZIP+'-' + DATE_FORMAT(DATE_NOW(),/YMD) + '.ZIP'
;!!! IDL'S LIST NOT WORKING SO COPY FILES TO A NEW DIR
ZDIR = !S.IDL + 'DEMOS\'
DIR_TEST,ZDIR
FILE_COPY,NAMES,ZDIR,/VERBOSE,/OVERWRITE

FILE_ZIP,ZIP_FILE,FILES = NAMES
STOP



END; #####################  END OF ROUTINE ################################
