; $ID:	MAKE_LME_SUBAREAS_SMI.PRO,	2020-07-01-12,	USER-KJWH	$
PRO MAKE_LME_SUBAREAS_SMI



; ===> CODES IN THE LANDMASK
  OCEAN_CODE      = 0
  COAST_CODE      = 1
  LAND_CODE       = 2
  LAKSIDE_CODE    = 3
  LAKE_CODE       = 4
  COUNTRY_CODE    = 5
  SUBAREA_CODE   = 11
  OUTLINE_CODE   = 21
  PX = 4320
  PY = 2160

DIR_OUT = 'D:\IDL\IMAGES\'
COUNTRY_FILE = 'D:\IDL\LME\LME64_wgs.shp'
PAL_36,R,G,B
LME_FILE = 'D:\IDL\SHAPEFILES\LME\LMES_64_OFFSHORE.SHP'
LME_FILE = 'D:\IDL\SHAPEFILES\LME\LMES_64.SHP'
PFILE,LME_FILE,/R
FN = FILE_PARSE(LME_FILE)
NAME = FN.NAME
MAP='SMI'
; ===> SOLID SUBAREA WITH SOLID LAND AND COASTLINE,FILLED LME SUBAREA, THEN DRAW THE SUBAREA LINE 
ZWIN,[PX,PY]
CALL_PROCEDURE,'MAP_' + MAP
ERASE,OCEAN_CODE
;PLOT_SHAPE,LME_FILE, COLOR=SUBAREA_CODE,FILL=1
PLOT_SHAPE,LME_FILE, COLOR=OUTLINE_CODE,FILL=1
; NOT YET WORKING   
;PLOT_SHAPE,COUNTRY_FILE, COLOR=COUNTRY_CODE,FILL=0

MAP_CONTINENTS,/HIRES,/COASTS,COLOR =LAND_CODE ,/FILL
MAP_CONTINENTS,/HIRES,/COASTS,COLOR = COAST_CODE
MAP_CONTINENTS,/HIRES,/COUNTRIES,COLOR = COUNTRY_CODE
NAME = NAME + "   J.O'REILLY"
CAPTION,NAME,COLOR = 1,CHARSIZE = 9,CHARTHICK = 5
IM = TVRD()
ZWIN
PAL_LANDMASK,R,G,B
PNGFILE = DIR_OUT + 'MASK_LAND_LME_SUBAREA' +'-'+ MAP + '-PXY_'+ ROUNDS(PX) + '_' +ROUNDS(PY) + '.PNG'
WRITE_PNG,PNGFILE,IM,R,G,B
PFILE,PNGFILE,/W
CDPRO


END


