; $ID:	MANUSCRIPT_ECOS_ANN_REVIEW.PRO,	2020-07-08-15,	USER-KJWH	$

PRO MANUSCRIPT_ECOS_ANN_REVIEW

;	This Program is the main program to generate figures for the USECoS's manuscript to be submitted to Annual Reviews
;
;


; HISTORY:
; April 2, 2010  Created by: K.J.W. Hyde, NOAA, Narragnsett, RI 02882 kimberly.hyde@noaa.gov
;-
; **************************************************************************************
  ROUTINE_NAME='MANUSCRIPT_ECOS_ANN_REVIEW'

	DO_COLORBARS            = 0
	DO_GLOBAL_PP            = 0
	DO_BATHY_IMAGE          = 0
	DO_SUBAREA_IMAGE        = 0
  DO_MAKE_CHL_PAN         = 0
  DO_CHL_COMPARISON_PLOT  = 0
	DO_SUBAREA_EXTRACTS     = 0
	DO_NENA_CHL             = 2

	COMPUTER = GET_COMPUTER()
  IF COMPUTER EQ 'HALIBUT'  THEN DIR_PROJECTS = 'D:\' ELSE DIR_PROJECTS = 'D:\'
  IF COMPUTER NE 'BLUEFIN' AND COMPUTER NE 'HALIBUT'  THEN PATH_GS_PS = 'C:\GSTOOLS\gs5.50\'

	DIR_SST    			= 'T:\SST-4-NENA\ts_images\stats\'
	DIR_CHL         = 'S:\OC-SEA_AQU-9-NENA\stats\'
	DIR_SAVE        = 'S:\OC-SEAWIFS-EC\SAVE\
	DIR_PLOTS       = DIR_PROJECTS+'PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\'
	DIR_DATA        = DIR_PROJECTS+'PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\DATA\'


; ********************************************
  IF DO_COLORBARS GE 1 THEN BEGIN
; ********************************************
    CHARSIZE = 2.5
    POSITION = [0.05, 0.57,0.95, 0.92]
    PAL_SW3,R,G,B
    RATIO_TITLE = 'Chlorophyll Global:Regional Ratio'
    LEG=COLOR_BAR_SCALE(PROD='RATIO',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=PPY_TITLE,FONT='HELVETICA',SPECIAL_SCALE='4',PAL='PAL_ANOMG')
    WRITE_PNG,DIR_PLOTS+'Figure8c-EC-CHLOR_A-RATIO-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure8c-EC-CHLOR_A-RATIO-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20
       
    
    PPY_TITLE = 'Primary Production' + UNITS('PPY',/NO_NAME)
;    LEG=COLOR_BAR_SCALE(PROD='PPY',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=PPY_TITLE,FONT='HELVETICA',SPECIAL_SCALE='LOW',PAL='PAL_SW3')
;    WRITE_PNG,DIR_PLOTS+'Figure1-GLOBAL-PP_ANNUAL-COLORBAR.PNG',LEG,R,G,B
    LEG=COLOR_BAR_SCALE(PROD='PPY',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=PPY_TITLE,FONT='HELVETICA',SPECIAL_SCALE='MID',PAL='PAL_SW3')
    WRITE_PNG,DIR_PLOTS+'Figure1-GLOBAL-PP_ANNUAL-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure1-GLOBAL-PP_ANNUAL-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/TOP,/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20

    PPD_TITLE = 'Primary Production' + UNITS('PPD',/NO_NAME)
    LEG=COLOR_BAR_SCALE(PROD='PPD',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=PPD_TITLE,FONT='HELVETICA',SPECIAL_SCALE='LOW',PAL='PAL_SW3')
    WRITE_PNG,DIR_PLOTS+'Figure1-GLOBAL-PP_DAILY-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure1-GLOBAL-PP_DAILY-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/TOP,/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20
    
    CHL_TITLE = 'Chlorophyll !8a!7' + UNITS('CHLOR_A',/NO_NAME)
    LEG=COLOR_BAR_SCALE(PROD='CHLOR_A',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=CHL_TITLE,FONT='HELVETICA',PAL='PAL_SW3')
    WRITE_PNG,DIR_PLOTS+'Figure3-EC-CHLOROPHYLL-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure3-NEC-CHLOROPHYLL-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/TOP,/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20
    
    CHL_TITLE = 'Temperature' + UNITS('SST',/NO_NAME)
    LEG=COLOR_BAR_SCALE(PROD='SST',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=CHL_TITLE,FONT='HELVETICA',PAL='PAL_SW3')
    WRITE_PNG,DIR_PLOTS+'Figure4-NENA-SST-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure4-NENA-SST-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/TOP,/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20
    
    LEG=COLOR_BAR_SCALE(PROD='BATHY',POSITION=POSITION,CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE,PAL='PAL_BATHY')
    PAL_BATHY,R,G,B
    WRITE_PNG,DIR_PLOTS+'Figure2a-NENA-BATHYMETRY-COLORBAR.PNG',LEG,R,G,B
    PS_IMAGE, FILES=DIR_PLOTS+'Figure2a-NENA-BATHYMETRY-COLORBAR.PNG',DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/TOP,/EPS,/COLOR,FULL=full,SCALE=2.25,XOFFSET=0,YOFFSET=20
    
    
    
STOP
  ENDIF ; DO_COLORBARS

; ********************************************
  IF DO_GLOBAL_PP GE 1 THEN BEGIN
; ********************************************

    PPD = DIR_DATA + '!ANNUAL-SA_N4AT-9_4-L3B-PPD-OPAL-MEAN.SAVE'
    PPY = DIR_DATA + '!ANNUAL-SA_N4AT-9_4-L3B-PPY-OPAL-MEAN.SAVE'
    PNG = DIR_DATA + '!ANNUAL-SA_N4AT-9_4-ROBINSON-PXY_4096_2048-PPY-OPAL-MEAN.PNG'
    PS  = DIR_DATA + '!ANNUAL-SA_N4AT-9_4-ROBINSON-PXY_4096_2048-PPY-OPAL-MEAN.ps'
    STRUCT_SD_2PNG,PPD,/ADD_LAND,/ADD_COAST,/ADD_BATHY,BATHS=200,BATHY_COLOR=255,MISS_COLOR=254,/OVERWRITE,SPECIAL_SCALE='LOW',USE_PROD='PPD',MAP_OUT='ROBINSON',/ADD_COLORBAR

;    DATA = STRUCT_SD_READ(PPD,STRUCT=STRUCT,SUBS=SUBS)
;    STRUCT.IMAGE(SUBS) = DATA(SUBS) * 365
;    STRUCT.PROD  = 'PPY'
;    SAVE,FILENAME=PPY,STRUCT

    STRUCT_SD_2PNG,PPY,/ADD_LAND,/ADD_COAST,/ADD_BATHY,BATHS=200,BATHY_COLOR=0,/BATHY_THICK,MISS_COLOR=254,/OVERWRITE,SPECIAL_SCALE='MID',USE_PROD='PPY',MAP_OUT='ROBINSON'

    OLDDEVICE= !D.NAME
    MAP_ROBINSON
    PS_IMAGE, FILES=PNG,DIR_OUT=DIR_DATA,/COLOR,FULL=full,/NO_CLOSE,/LANDSCAPE,SCALE=0.65,XOFFSET=3,YOFFSET= 0
    !P.FONT = 0
    LATS = [-90,-60,-30,0,30,60,90]     & LATNAMES = STRTRIM(LATS, 2)
    LONS = [-180,-120,-60,0,60,120,180] & LONNAMES = STRTRIM(LONS, 2)
    MAP_GRID, LABEL=1, LATS=LATS, LATNAMES=LATNAMES, LONS=LONS, LONNAMES=LONNAMES, GLINESTYLE=0,/BOX_AXES, CHARSIZE=0.7, COLOR=254
    COLORBAR_TITLE='Primary Production ' + UNITS('PPY',/NO_NAME)
  ;  LEG = COLOR_BAR_SCALE(PROD='PPY',PX=1400,PY=195,SPECIAL_SCALE='MID',/CUT,GRACE=7,CHARSIZE=1.5,BACKGROUND=252,POS=[.44,.0,.78,.025],PAL='PAL_SW3',TITLE=COLORBAR_TITLE)
  ;  PAGE=IMAGE_PASTE(PAGE,BAR,X=1900,Y=0,BACKGROUND=252,/TRANSPARENT)

    DEVICE,/CLOSE
    SET_PLOT,OLDDEVICE

    IMAGE_TRIM, PS, DIR_OUT=DIR_PLOTS, DPI=600, BACKGROUND=BACKGROUND,GRACE=[20,20,20,20], /OVERWRITE


  ENDIF ; DO_GLOBAL_PP GE 1


; ********************************************
  IF DO_BATHY_IMAGE GE 1 THEN BEGIN
; ********************************************
;   Bathy figure 1

    SAVEFILE = 'D:\IDL\DATA\SRTM30-EC-PXY_1024_1024-BATHY-SMOOTH_5.SAVE'
    PNGFILE  = DIR_PLOTS  + 'SRTM30-EC-PXY_1024_1024-BATHY-SMOOTH_5.PNG'
    PSFILE   = DIR_PLOTS  + 'Figure2a-NENA-BATHYMETRY.PS'

    PAL = 'PAL_BATHY'
    TITLE = 'Depth (m)'
    STRUCT_SD_2PNG,SAVEFILE,DIR_OUT=DIR_PLOTS,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,/ADD_BATHY,BATHS=200,BATHY_COLOR=250,SPECIAL_SCALE=SPECIAL_SCALE,PAL='PAL_BATHY'

    IM = READ_PNG(PNGFILE,R,G,B)
    OLDDEVICE= !D.NAME
    ZWIN,IM
    MAP_EC
    PS_IMAGE, FILES=PNGFILE,DIR_OUT=DIR_PLOTS, /COLOR,/NO_CLOSE,SCALE=2,XOFFSET=2,YOFFSET=2
    TV,IM
    
    !P.FONT = 0
    LATS = [20,25,30,35,40,45,50]     & LATNAMES = STRTRIM(LATS, 2)
    LONS = [-85,-80,-75,-70,-65,-60,-55] & LONNAMES = STRTRIM(LONS, 2)
    MAP_GRID, LABEL=1, LATS=LATS, LATNAMES=LATNAMES, LONS=LONS, LONNAMES=LONNAMES, GLINESTYLE=0,/BOX_AXES, CHARSIZE=0.7, COLOR=0
   ; MAP_GRID, LABEL=1,LATS=LATS,LONS=LONS, GLINESTYLE=0,/BOX_AXES, CHARSIZE=0.7, COLOR=0
    ;PLOTDEGL,COLOR=0, DEG=5, X_OFFSET=4, Y_OFFSET=4

    TITLE = 'Depth (m)'
    CHARSIZE = 0.75
  ;  LEG=COLOR_BAR_SCALE(PROD='BATHY',POSITION=[0.01, 0.96,0.49, 0.98],CHARSIZE=0.65,/BOTTOM,TITLE=TITLE,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE,PAL='PAL_BATHY')
    CHARSIZE=0.7
;    XYOUTS,0.08, 0.35,'SAB', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
;    XYOUTS,0.31, 0.66,'MAB', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
;    XYOUTS,0.48, 0.85,'GOM', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
;    XYOUTS,0.54, 0.77,'GB', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
   ; XYOUTS,0.02, 0.66,'Chesapeake!C        Bay ', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
   ; XYOUTS,0.12, 0.74,'Delaware!C     Bay', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
   ; XYOUTS,0.22, 0.81,'Hudson!CEstuary', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'

    DEVICE,/CLOSE
    SET_PLOT,OLDDEVICE
    ZWIN


    PSFILES = FILE_SEARCH(DIR_PLOTS+'SRTM30-EC-PXY_1024_1024-BATHY-SMOOTH_5.ps')
    IMAGE_TRIM, PSFILES, DIR_OUT=DIR_PLOTS, DPI=600, BACKGROUND=BACKGROUND,GRACE=[20,20,20,20], /OVERWRITE

    
 STOP

  ENDIF ; DO_BATHY_IMAGE


; ********************************************
  IF DO_SUBAREA_IMAGE GE 1 THEN BEGIN
; ********************************************
    OVERWRITE = DO_SUBAREA_IMAGE GT 1
  
    PAL_36,R,G,B
    SUBAREA_PNG = DIR_PLOTS+'Figure2b-NENA-SUBAREAS_LARGE.PNG'
    OLDDEVICE= !D.NAME
    PS_IMAGE, FILES=SUBAREA_PNG,DIR_OUT=DIR_PLOTS, /COLOR,FULL=full,/NO_CLOSE,SCALE=2,XOFFSET=2,YOFFSET=3
  
    CHARSIZE=0.7
    XYOUTS,0.74, 0.91,'SS', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.50, 0.84,'GOM', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.60, 0.72,'NES', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.31, 0.66,'MAB', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.43, 0.58,'GS', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.015, 0.29,'SAB', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    XYOUTS,0.3, 0.35,'SAR', ALIGN=-0.1, CHARSIZE=CHARSIZE, COLOR=0, CHARTHICK=1,/NORMAL,FONT='HELVETICA'
    

    DEVICE,/CLOSE
    SET_PLOT,OLDDEVICE
    
    STOP

  ENDIF ; DO_SUBAREA_IMAGE

; ********************************************
  IF DO_MAKE_CHL_PAN GE 1 THEN BEGIN
; ********************************************
  OVERWRITE = DO_MAKE_CHL_PAN GT 1

  DIR_IN  = 'S:\OC-SEAWIFS-MLAC-NEC\SAVE\'
  DIR_OUT = DIR_DATA + 'CHLOR_A_PAN\'

  WAVES = ['490','555','670']
  FOR NTH = 0L, N_ELEMENTS(WAVES)-1 DO BEGIN
    WAVE = WAVES[NTH]
    IF WAVE EQ '490' THEN F0 = 196.473        ; CONVERSION FROM NLW TO RRS - http://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?pid=1634;hlm=adv;hl=reflectance#pid1634
    IF WAVE EQ '555' THEN F0 = 188.158        ; SeaWiFS F0 TABLE - http://oceancolor.gsfc.nasa.gov/DOCS/RSR_tables.html
    IF WAVE EQ '670' THEN F0 = 151.143
    FA= FILE_ALL(DIR_IN+'!S_2006*-NLW_'+WAVE+'.save')
    FOR FTH = 0L, N_ELEMENTS(FA)-1 DO BEGIN
      FILENAME = DIR_OUT + REPLACE(FA(FTH).NAME_EXT,'NLW','RRS')
      IF FILE_TEST(FILENAME) EQ 1 AND OVERWRITE EQ 0 THEN CONTINUE
      NLW = STRUCT_SD_READ(FA(FTH).FULLNAME,STRUCT=STRUCT,SUBS=SUBS)
      OK = WHERE(NLW GT 0.0 AND NLW NE MISSINGS(NLW),COUNT)
      IF COUNT EQ 0 THEN CONTINUE
      RRS = NLW & RRS(*) = MISSINGS(0.0)
      RRS[OK] = NLW[OK]/F0
      STRUCT_SD_WRITE,  FILENAME, PROD='RRS_'+WAVE, IMAGE=RRS, MISSING_CODE=MISSINGS(0.0),$
                  MASK=STRUCT.MASK, CODE_MASK=STRUCT.CODE_MASK, CODE_NAME_MASK=STRUCT.CODE_NAME_MASK, $
                  SCALING='LINEAR', INTERCEPT=0.0, SLOPE=1.0, DATA_UNITS='sr^-1',$
                  TRANSFORMATION='', PERIOD=STRUCT.PERIOD, SENSOR=STRUCT.SENSOR, SATELLITE=STRUCT.SATELLITE, SAT_EXTRA=STRUCT.SAT_EXTRA,$
                  METHOD=STRUCT.METHOD, SUITE=STRUCT.SUITE, MAP=STRUCT.MAP, INFILE=FA(FTH).FULLNAME,$
                  NOTES=STRUCT.NOTES,ERROR=ERROR,OVERWRITE=OVERWRITE
    ENDFOR
  ENDFOR

  DATE_RANGE = ['20060101','20061231']
  CHL_ALGS = 'PAN'
  PERIOD_CODE = '!S'
  MAP = 'NEC'
  CHLOR_A_SAVE_MAKE,DIR_IN=DIR_OUT,DIR_OUT=DIR_OUT,DATE_RANGE=DATE_RANGE,CHL_ALGS=CHL_ALGS,PERIOD_CODE=PERIOD_CODE,MAP=MAP,OVERWRITE=OVERWRITE

  CHL_FILES = FILE_SEARCH(DIR_OUT +'!S_2006*CHLOR_A-PAN.SAVE')
  SD_STATS_ALL, CHL_FILES,PROD='CHLOR_A',PERIOD_CODE_IN='!S',PERIOD_CODE_OUT='!D',ALG='PAN',OUTSENSOR='SEAWIFS',STAT_TYPE='MEAN',DIR_STATS=DIR_OUT
  SD_STATS_ALL, CHL_FILES,PROD='CHLOR_A',PERIOD_CODE_IN='!S',PERIOD_CODE_OUT='!M',ALG='PAN',OUTSENSOR='SEAWIFS',STAT_TYPE='MEAN',DIR_STATS=DIR_OUT
  CHL_FILES = FILE_SEARCH(DIR_OUT +'!M_2006*CHLOR_A-PAN-MEAN.SAVE')
  SD_STATS_ALL, CHL_FILES,PROD='CHLOR_A',PERIOD_CODE_IN='!M',PERIOD_CODE_OUT='!Y',ALG='PAN',OUTSENSOR='SEAWIFS',STAT_TYPE='MEAN',DIR_STATS=DIR_DATA
 STOP

  ENDIF

; ********************************************
  IF DO_CHL_COMPARISON_PLOT GE 1 THEN BEGIN
; ********************************************
    OVERWRITE = DO_CHL_COMPARISON_PLOT GT 1

    CHL_OC4 = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-OC4-MEAN.SAVE'
    CHL_PAN = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-PAN-MEAN.SAVE'

;    STRUCT_SD_2PNG, CHL_OC4,DIR_OUT=DIR_DATA,/ADD_LAND,/ADD_COAST,OVERWRITE=OVERWRITE,/ADD_COLORBAR,COLORBAR_TITLE='Chlorophyll !8a!7 (mg m!U-3!N) - Global'
;    STRUCT_SD_2PNG, CHL_PAN,DIR_OUT=DIR_DATA,/ADD_LAND,/ADD_COAST,OVERWRITE=OVERWRITE;,COLORBAR_TITLE='Chlorophyll !8a!7 (mg m!U-3!N) - Regional'

    RATIO_SAVEFILE = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-OC4_PAN-RATIO.SAVE'
;    MAKE_ANOM_SAVES,SAVEFILE=RATIO_SAVEFILE,FILEA=CHL_OC4,FILEB=CHL_PAN,ANOM=ANOM,OVERWRITE=OVERWRITE

    COLORBAR_TITLE = 'Chlorophyll Global:Regional Ratio'
    STRUCT_SD_2PNG, RATIO_SAVEFILE,DIR_OUT=DIR_DATA,USE_PROD='RATIO',SPECIAL_SCALE='.5-3',/ADD_LAND,/ADD_COAST,OVERWRITE=overwrite,PAL='PAL_ANOMG',COLORBAR_TITLE=COLORBAR_TITLE,/ADD_COLORBAR

    PNG_OC4 = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-OC4-MEAN.PNG'
    PNG_PAN = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-PAN-MEAN.PNG'
    PNG_RATIO = DIR_DATA + '!Y_2004-SEAWIFS-REPRO5-MLAC-NEC-CHLOR_A-OC4_PAN-RATIO.PNG'

    BACKGROUND = 255
    PNGFILE = DIR_PLOTS + 'Figure7-2004-SEAWIFS-NEC-CHLOR_A-OC4_PAN_ANOMALY-COMPOSITE.PNG'

    IMAGE1 = IMAGE_2TRUE(READ_PNG(PNG_OC4,R,G,B),PAL='PAL_SW3')
    IMAGE2 = IMAGE_2TRUE(READ_PNG(PNG_PAN,R,G,B),PAL='PAL_SW3')
    IMAGE3 = IMAGE_2TRUE(READ_PNG(PNG_RATIO,R,G,B),PAL='PAL_ANOMG')

    NEW = IMAGE_WELD(IMAGE1,IMAGE2, /LANDSCAPE,BACKGROUND=BACKGROUND,SPACE=SPACE)
    NEW2 = IMAGE_WELD(NEW,IMAGE3, /LANDSCAPE,BACKGROUND=BACKGROUND,SPACE=SPACE)
    WRITE_PNG,PNGFILE,NEW2
    PS_IMAGE, FILES=PNGFILE,DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/COLOR,/LANDSCAPE,FULL=full,SCALE=1.1,XOFFSET=5,YOFFSET=29
    

  ENDIF ; DO_CHL_COMPARISON_PLOT


; *******************************************************
  IF DO_NENA_CHL GE 1 THEN BEGIN
; *******************************************************
    OVERWRITE = DO_NENA_CHL GE 2

    PRODS = ['CHLOR_A','SST']
    FOR PTH = 0L, N_ELEMENTS(PRODS)-1 DO BEGIN
      PROD = PRODS(PTH)
      IF PROD EQ 'CHLOR_A' THEN BEGIN
        NENA_A = '1_1'  &  LAB_A = 'NO!D3!N v1'    
        NENA_B = '1_2'  &  LAB_B = 'NO!D3!N v2'
        DATE = '200410'
        PLAB  = 'CHL'
        FIGURE = '7'
        SATFILE = '!M_'+DATE+'-SEAWIFS-REPRO6-9-NENA-CHLOR_A-OC4-MEAN.SAVE' 
        SATPNG  = '!M_'+DATE+'-SEAWIFS-REPRO6-9-NENA_NS-PXY_700_700-CHLOR_A-OC4-MEAN.PNG'
        ANOM = 'RATIO' & ANOM_SCALE = '33' & ANOM_LAB = ':Satellite Ratio'
        LAB_UNITS = ' (mg m!U-3!N)'
        PROD_LAB = 'Chlorophyll !8a!7'
        HIST_TITLE = 'Chlorophyll !8a!7!COctober 2004'    
        XSCALE = SD_SCALES([1,250],PROD=PROD,/BIN2DATA) & YSCALE = XSCALE
        XRANGE = NICE_RANGE(ALOG10(XSCALE)) & YRANGE = XRANGE
        ALOGX = 1
      ENDIF  
      
      IF PROD EQ 'SST' THEN BEGIN
        NENA_A = '0'    &  LAB_A = '0'    
        NENA_B = '1_4'  &  LAB_B = '1.4'
        DATE = '200406'
        PLAB  = 'SST'
        FIGURE = '5'
        SATFILE = '!M_'+DATE+'-N4AT-4-NENA-SST-MEAN.SAVE'
        SATPNG  = '!M_'+DATE+'-N4AT-4-NENA_NS-PXY_700_700-SST-MEAN.PNG
        ANOM = 'DIF' & ANOM_SCALE = '15' & ANOM_LAB = '-Satellite Difference'
        LAB_UNITS=' (!Uo!NC)'
        PROD_LAB = 'SST'
        HIST_TITLE = 'Sea Surface Temperature!CJune 2004'
        XSCALE = SD_SCALES([1,250],PROD='SST',/BIN2DATA) & YSCALE = XSCALE
        XRANGE = NICE_RANGE(XSCALE) & YRANGE = XRANGE
        ALOGX = 0
      ENDIF  
         
      DIR_ROMS = DIR_DATA + 'ROMS\'
      ROMSA = FILE_SEARCH(DIR_ROMS + '!3D_'+DATE+'*ROMS_'+NENA_A+'-NENA-'+PROD+'.SAVE')
      ROMSB = FILE_SEARCH(DIR_ROMS + '!3D_'+DATE+'*ROMS_'+NENA_B+'-NENA-'+PROD+'.SAVE')
  
      SD_STATS_ALL, ROMSA,PROD=PROD,PERIOD_CODE_IN='!3D',PERIOD_CODE_OUT='!M',OUTSENSOR='ROMS_'+NENA_A,STAT_TYPE='MEAN',DIR_STATS=DIR_OUT,OVERWRITE=OVERWRITE
      SD_STATS_ALL, ROMSB,PROD=PROD,PERIOD_CODE_IN='!3D',PERIOD_CODE_OUT='!M',OUTSENSOR='ROMS_'+NENA_B,STAT_TYPE='MEAN',DIR_STATS=DIR_OUT,OVERWRITE=OVERWRITE
  
      STRUCT_SD_2PNG, DIR_DATA + SATFILE,                                              DIR_OUT=DIR_DATA,/ADD_LAND,/ADD_COAST,MAP_OUT='NENA_NS',OVERWRITE=OVERWRITE,PAL='PAL_SW3';,/ADD_COLORBAR,COLORBAR_TITLE='Satellite ' + LAB_UNITS
      STRUCT_SD_2PNG, DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_A+'-NENA-'+PROD+'-MEAN.SAVE',DIR_OUT=DIR_DATA,/ADD_LAND,/ADD_COAST,MAP_OUT='NENA_NS',OVERWRITE=OVERWRITE,PAL='PAL_SW3';,/ADD_COLORBAR,COLORBAR_TITLE='NENA '+LAB_A+LAB_UNITS
      STRUCT_SD_2PNG, DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_B+'-NENA-'+PROD+'-MEAN.SAVE',DIR_OUT=DIR_DATA,/ADD_LAND,/ADD_COAST,MAP_OUT='NENA_NS',OVERWRITE=OVERWRITE,PAL='PAL_SW3';,/ADD_COLORBAR,COLORBAR_TITLE='NENA '+LAB_B+LAB_UNITS    
  
      RATIO_A = DIR_DATA + '!M_'+DATE+'-SATELLITE-ROMS_'+NENA_A+'-NENA-'+PROD+'-RATIO.SAVE'
      MAKE_ANOM_SAVES,SAVEFILE=RATIO_A,FILEA=DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_A+'-NENA-'+PROD+'-MEAN.SAVE',FILEB=DIR_DATA + SATFILE,ANOM=ANOM,OVERWRITE=OVERWRITE
  
      RATIO_B = DIR_DATA + '!M_'+DATE+'-SATELLITE-ROMS_'+NENA_B+'-NENA-'+PROD+'-RATIO.SAVE'
      MAKE_ANOM_SAVES,SAVEFILE=RATIO_B,FILEA=DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_B+'-NENA-'+PROD+'-MEAN.SAVE',FILEB=DIR_DATA + SATFILE,ANOM=ANOM,OVERWRITE=OVERWRITE
  
      STRUCT_SD_2PNG, RATIO_A,DIR_OUT=DIR_DATA,USE_PROD=ANOM,SPECIAL_SCALE=ANOM_SCALE,/ADD_LAND,/ADD_COAST,MAP_OUT='NENA_NS',OVERWRITE=OVERWRITE,PAL='PAL_ANOMG';,/ADD_COLORBAR,COLORBAR_TITLE=PLAB + ' NENA '+LAB_A+ANOM_LAB+LAB_UNITS
      STRUCT_SD_2PNG, RATIO_B,DIR_OUT=DIR_DATA,USE_PROD=ANOM,SPECIAL_SCALE=ANOM_SCALE,/ADD_LAND,/ADD_COAST,MAP_OUT='NENA_NS',OVERWRITE=OVERWRITE,PAL='PAL_ANOMG';,/ADD_COLORBAR,COLORBAR_TITLE=PLAB + ' NENA '+LAB_B+ANOM_LAB+LAB_UNITS
        
      SAT     = STRUCT_SD_READ(DIR_DATA + SATFILE,STRUCT=S_SAT)
      ROMSA   = STRUCT_SD_READ(DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_A+'-NENA-'+PROD+'-MEAN.SAVE',     STRUCT=S_ROMSA)
      ROMSB   = STRUCT_SD_READ(DIR_ROMS + '!M_'+DATE+'-ROMS_'+NENA_B+'-NENA-'+PROD+'-MEAN.SAVE',     STRUCT=S_ROMSB)
    
      !P.MULTI=[0,0,1]
      PAL_SW3,R,G,B
      !Y.OMARGIN=[2,2]
      !X.OMARGIN=[8,6]
  
      DIR_FINAL = 'D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\'
      PSFILEA = DIR_FINAL+'Figure'+FIGURE+'d-M_'+DATE+'-ROMS_'+NENA_A+'_SATELLITE-'+PROD+'-HIST2D.PS'
      PSPRINT,FILENAME=PSFILEA,/COLOR,/TIMES,/PORTRAIT
      OK = WHERE(S_SAT.IMAGE NE MISSINGS(S_SAT.IMAGE) AND S_ROMSA.IMAGE NE MISSINGS(S_ROMSA.IMAGE),COUNT)
      IF PROD EQ 'CHLOR_A' THEN X = ALOG10(S_SAT.IMAGE[OK])   ELSE X = S_SAT.IMAGE[OK]
      IF PROD EQ 'CHLOR_A' THEN Y = ALOG10(S_ROMSA.IMAGE[OK]) ELSE Y = S_ROMSA.IMAGE[OK] 
  
      PLOT_HIST2D, X,Y, IMAGE=HIST_IMAGE, PAL='PAL_SW3', MODEL='RMA', FAST=1, CHARSIZE=1.5, TITLE=HIST_TITLE, $
            BIN_X=(XRANGE[1]-XRANGE[0])/100., MIN_X=XRANGE[0], MAX_X=XRANGE[1], $
            BIN_Y=(XRANGE[1]-XRANGE[0])/100., MIN_Y=YRANGE[0], MAX_Y=YRANGE[1], $
            PX=PX, XTITLE=PLAB + UNITS(PROD,/NO_NAME) + '  -  Satellite',  XLABEL=XLABEL, XTHICK=3, XMARGIN=XMARGIN, $
            PY=PY, YTITLE=PLAB + UNITS(PROD,/NO_NAME) + '  -  NENA '+LAB_A,YLABEL=YLABEL, YTHICK=3, YMARGIN=YMARGIN, $
            LAB_TXT=LAB_TXT, LAB_CHARSIZE=5, STATS_CHARSIZE=1.25, ISOTROPIC=ISOTROPIC,/NO_TIMESTAMP,$
            BKG_COLOR=255, ZERO_COLOR=254, MAX_COLOR=250,$
            REG_COLOR=0,  REG_THICK=5, ONE_COLOR=255,ONE_THICK=8, $
            ALOGX=ALOGX,ALOGY=ALOGX,LOG_FREQ=1,STATS_PARAMS=[2,3,4,8,10], _EXTRA=_EXTRA
      PSPRINT
  
      PSFILEB = DIR_FINAL+'Figure'+FIGURE+'g-M_'+DATE+'-ROMS_'+NENA_B+'_SATELLITE-'+PROD+'-HIST2D.PS'
      PSPRINT,FILENAME=PSFILEB,/COLOR,/TIMES,/PORTRAIT
      OK = WHERE(S_SAT.IMAGE NE MISSINGS(S_SAT.IMAGE) AND S_ROMSB.IMAGE NE MISSINGS(S_ROMSB.IMAGE),COUNT)
      IF PROD EQ 'CHLOR_A' THEN X = ALOG10(S_SAT.IMAGE[OK])   ELSE X = S_SAT.IMAGE[OK]
      IF PROD EQ 'CHLOR_A' THEN Y = ALOG10(S_ROMSB.IMAGE[OK]) ELSE Y = S_ROMSB.IMAGE[OK] 
  
      PLOT_HIST2D, X, Y, IMAGE=HIST_IMAGE, PAL='PAL_SW3', MODEL='RMA', FAST=1, CHARSIZE=1.5, TITLE=HIST_TITLE, $
            BIN_X=(XRANGE[1]-XRANGE[0])/100., MIN_X=XRANGE[0], MAX_X=XRANGE[1], $
            BIN_Y=(XRANGE[1]-XRANGE[0])/100., MIN_Y=YRANGE[0], MAX_Y=YRANGE[1], $
            PX=PX, XTITLE=PLAB + UNITS(PROD,/NO_NAME) + '  -  Satellite', XLABEL=XLABEL, XTHICK=3, XMARGIN=XMARGIN, $
            PY=PY, YTITLE=PLAB + UNITS(PROD,/NO_NAME) + '  -  NENA '+LAB_B,  YLABEL=YLABEL, YTHICK=3, YMARGIN=YMARGIN, $
            LAB_TXT=LAB_TXT, LAB_CHARSIZE=5, STATS_CHARSIZE=1.25, ISOTROPIC=ISOTROPIC,/NO_TIMESTAMP,$
            BKG_COLOR=255, ZERO_COLOR=254, MAX_COLOR=250,$
            REG_COLOR=0,  REG_THICK=5, ONE_COLOR=255,ONE_THICK=8, $
            ALOGX=ALOGX,ALOGY=ALOGX,LOG_FREQ=1,STATS_PARAMS=[2,3,4,8,10], _EXTRA=_EXTRA
      PSPRINT
  
      PSAT   = READ_PNG(DIR_DATA + SATPNG,R,G,B)
      PROMSA = READ_PNG(DIR_DATA + '!M_'+DATE+'-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',R,G,B)
      PROMSB = READ_PNG(DIR_DATA + '!M_'+DATE+'-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',R,G,B)
      PRATA  = READ_PNG(DIR_DATA + '!M_'+DATE+'-SATELLITE-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',R,G,B)
      PRATB  = READ_PNG(DIR_DATA + '!M_'+DATE+'-SATELLITE-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',R,G,B)
      

      PS_IMAGE,FILES=DIR_DATA+SATPNG,DIR_OUT=DIR_FINAL,/EPS,/COLOR,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
      PS_IMAGE,FILES=DIR_DATA+'!M_'+DATE+'-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',DIR_OUT=DIR_FINAL,/EPS,/COLOR,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
      PS_IMAGE,FILES=DIR_DATA+'!M_'+DATE+'-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',DIR_OUT=DIR_FINAL,/EPS,/COLOR,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
      PAL_ANOMG,R,G,B
      PS_IMAGE,FILES=DIR_DATA+'!M_'+DATE+'-SATELLITE-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',DIR_OUT=DIR_FINAL,/EPS,/COLOR,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
      PS_IMAGE,FILES=DIR_DATA+'!M_'+DATE+'-SATELLITE-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',DIR_OUT=DIR_FINAL,/EPS,/COLOR,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
      PAL_SW3,R,G,B
      CHARSIZE = 2.5
      POSITION = [0.05, 0.07,0.95, 0.42]
      COLORBAR_TITLES = ['Satellite ' + PROD_LAB + ' ' + LAB_UNITS,$
                         'NENA ' + PROD_LAB + ' ' +LAB_UNITS +' '+LAB_A,$      
                         'NENA ' + PROD_LAB + ' ' +LAB_UNITS +' '+LAB_B,$
                         PROD_LAB + ' NENA ' + ' ' +LAB_A+ANOM_LAB,$
                         PROD_LAB + ' NENA ' + ' ' +LAB_B+ANOM_LAB]
      COLORBAR_NAMES  = [DIR_PLOTS+ REPLACE(SATPNG,['!M','MEAN.PNG'],['Figure'+FIGURE+'a-M','MEAN-COLORBAR.PNG']),$
                         DIR_PLOTS+ REPLACE('!M_'+DATE+'-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',['!M','.PNG'],['Figure'+FIGURE+'b-M','-COLORBAR.PNG']),$
                         DIR_PLOTS+ REPLACE('!M_'+DATE+'-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG',['!M','.PNG'],['Figure'+FIGURE+'e-M','-COLORBAR.PNG']),$
                         DIR_PLOTS+ REPLACE('!M_'+DATE+'-SATELLITE-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',['!M','.PNG'],['Figure'+FIGURE+'c-M','-COLORBAR.PNG']),$
                         DIR_PLOTS+ REPLACE('!M_'+DATE+'-SATELLITE-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG',['!M','.PNG'],['Figure'+FIGURE+'f-M','-COLORBAR.PNG'])]
      PALS            = ['PAL_SW3','PAL_SW3','PAL_SW3','PAL_ANOMG','PAL_ANOMG']
      CPRODS          = [PROD,PROD,PROD,ANOM,ANOM]
      SPECIAL_SCALES  = ['','','',ANOM_SCALE,ANOM_SCALE]
                       
      FOR CTH = 0L, N_ELEMENTS(COLORBAR_TITLES)-1 DO BEGIN   
        CALL_PROCEDURE, PALS(CTH),R,G,B
        LEG=COLOR_BAR_SCALE(PROD=CPRODS(CTH),POSITION=POSITION,CHARSIZE=CHARSIZE,SPECIAL_SCALE=SPECIAL_SCALES(CTH),/TOP,TITLE=COLORBAR_TITLES(CTH),FONT='HELVETICA',PAL=PALS(CTH))        
        WRITE_PNG,COLORBAR_NAMES(CTH),LEG,R,G,B
        PS_IMAGE, FILES=COLORBAR_NAMES(CTH),DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/EPS,/COLOR,FULL=full,SCALE=3.5,XOFFSET=0,YOFFSET=30,/LANDSCAPE
      ENDFOR        
  
      FILE_RENAME,REPLACE(DIR_FINAL+SATPNG,'.PNG','.EPS'),NAME_CHANGE=['!M','Figure'+FIGURE+'a-M']
      FILE_RENAME,REPLACE(DIR_FINAL+'!M_'+DATE+'-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG','.PNG','.EPS'),NAME_CHANGE=['!M','Figure'+FIGURE+'b-M']
      FILE_RENAME,REPLACE(DIR_FINAL+'!M_'+DATE+'-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-MEAN.PNG','.PNG','.EPS'),NAME_CHANGE=['!M','Figure'+FIGURE+'e-M']
      FILE_RENAME,REPLACE(DIR_FINAL+'!M_'+DATE+'-SATELLITE-ROMS_'+NENA_A+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG','.PNG','.EPS'),NAME_CHANGE=['!M','Figure'+FIGURE+'c-M']
      FILE_RENAME,REPLACE(DIR_FINAL+'!M_'+DATE+'-SATELLITE-ROMS_'+NENA_B+'-NENA_NS-PXY_700_700-'+PROD+'-RATIO.PNG','.PNG','.EPS'),NAME_CHANGE=['!M','Figure'+FIGURE+'f-M']
  
      IMAGE_TRIM, [PSFILEA,PSFILEB], DIR_OUT=DIR_DATA, DPI=600,PATH_GS_PS=PATH_GS_PS,BACKGROUND=215,GRACE=[100,100,100,100], OVERWRITE=OVERWRITE
      PHISA  = CONGRID(READ_PNG(DIR_DATA + 'TRIM\!M_'+DATE+'-ROMS_'+NENA_A+'_SATELLITE-'+PROD+'-HIST2D-PS_1-trim.PNG',R,G,B),700,700)
      PHISB  = CONGRID(READ_PNG(DIR_DATA + 'TRIM\!M_'+DATE+'-ROMS_'+NENA_B+'_SATELLITE-'+PROD+'-HIST2D-PS_1-trim.PNG',R,G,B),700,700)
      THISTOA = IMAGE_2TRUE(PHISA,R,G,B);,PAL='PAL_SW3')
      THISTOB = IMAGE_2TRUE(PHISB,R,G,B);,PAL='PAL_SW3')
  
  
      TSAT    = IMAGE_2TRUE(PSAT,  R,G,B,PAL='PAL_SW3')
      TROMSA  = IMAGE_2TRUE(PROMSA,R,G,B,PAL='PAL_SW3')
      TROMSB  = IMAGE_2TRUE(PROMSB,R,G,B,PAL='PAL_SW3')
      TRATIOA = IMAGE_2TRUE(PRATA, R,G,B,PAL='PAL_ANOMG')
      TRATIOB = IMAGE_2TRUE(PRATB, R,G,B,PAL='PAL_ANOMG')
      
      IMAGE1 = IMAGE_WELD(TROMSA,IMAGE_WELD(TRATIOA,THISTOA,/LANDSCAPE,BACKGROUND=215,SPACE=SPACE),/LANDSCAPE,BACKGROUND=BACKGROUND,SPACE=SPACE)
      IMAGE2 = IMAGE_WELD(TROMSB,IMAGE_WELD(TRATIOB,THISTOB,/LANDSCAPE,BACKGROUND=215,SPACE=SPACE),/LANDSCAPE,BACKGROUND=BACKGROUND,SPACE=SPACE)
      IMAGE3 = IMAGE_WELD(IMAGE2,IMAGE1,/PORTRAIT,BACKGROUND=BACKGROUND,SPACE=SPACE)
      IMAGE4 = IMAGE_WELD(TSAT,IMAGE3,/LANDSCAPE,BACKGROUND=BACKGROUND,SPACE=SPACE)
  
      PNGFILE = DIR_PLOTS + 'Figure'+FIGURE+'-SATELLITE_NENA'+NENA_A+'_NENA'+NENA_B+'-'+PROD+'-COMPOSITE.PNG'
      WRITE_PNG,PNGFILE,IMAGE4
      PS_IMAGE, FILES=PNGFILE,DIR_OUT='D:\PROJECTS\ECOS\DOC\ANNUAL_REVIEW_MANU\PLOTS\EPS_AND_COLORBARS\',/COLOR,/LANDSCAPE,FULL=full,SCALE=1.75,XOFFSET=5,YOFFSET=28
    ENDFOR
  ENDIF ; DO_NENA_CHL
STOP
END
