; $ID:	MANUSCRIPT_OPAL.PRO,	2020-07-08-15,	USER-KJWH	$

 PRO MANUSCRIPT_OPAL
;+
; NAME:
;       MANUSCRIPT_FRONTS_1
;
; PURPOSE:
;				To create the final figures for the first FRONTS manuscript
;
;	NOTES:
;				Most procedures are copied from other programs
;
; MODIFICATION HISTORY:

;

ROUTINE_NAME='MANUSCRIPT_FRONTS_1'

TIMER

;	===> Load simple color palette
 	PAL_36,r,g,b

; **************************************************
; ***** SWITCHES CONTROLLING PROCESSING STEPS  *****
; **************************************************
;		Switch	Operation
;		0  			Do not do Step
;		1				Do Step (unless output from this step already exists, then skip this step)
; 	2     	Do Step (make output file from step and overwrite output if it already exists)


		DO_HIST2D_PLOTS		            = 0
		DO_COLORBAR_PNGS							= 0
		DO_PS_2PNG                    = 0
		DO_PPD_SAT_COMPARISONS        = 0
		DO_IMAGE_COMPOSITES						= 2

;	*** Define names of input and output files so that they are available to various steps

	COMPUTER = GET_COMPUTER()
	IF COMPUTER EQ 'KHYDE-XP' THEN DIR_IDL = 'C:\IDL\' ELSE DIR_IDL = 'D:\IDL\'


	DIR_SAVE  = 'D:\PROJECTS\OPAL\DATA\SAVE\'
	DIR_STATS = 'D:\PP-N4AT-NEC\stats\'
	IF COMPUTER EQ 'KHYDE-XP' THEN DIR_PROJECTS = 'C:\WORK\PROJECTS\' ELSE DIR_PROJECTS = 'D:\PROJECTS\'
	DIR_PLOTS = DIR_PROJECTS + 'OPAL\PLOTS\'
	DIR_BROWSE = DIR_PROJECTS + 'OPAL\BROWSE\'
	DIR_POSTER = DIR_PROJECTS + 'OPAL\PLOTS\'
	DIR_PPD   = DIR_PROJECTS + 'OPAL\'
	DIR_RATIO = DIR_PROJECTS + 'OPAL\RATIO\'



; *******************************************************
	IF DO_HIST2D_PLOTS GE 1 THEN BEGIN
; *******************************************************
		OVERWRITE = DO_HIST2D_PLOTS GE 2



		GRACE = [250,250,250,250]
	;	IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=1200, BACKGROUND=BACKGROUND,GRACE=GRACE, OVERWRITE=_overwrite
STOP

	ENDIF


; *******************************************************
	IF DO_COLORBAR_PNGS GE 1 THEN BEGIN
; *******************************************************
		OVERWRITE = DO_COLORBAR_PNGS GE 2


		GRACE = [25,25,20,20]
		PRODS =          ['PPD','RATIO','RATIO']
		SPECIAL_SCALES = ['',   '2','3']
		PALS=['PAL_SW3','PAL_ANOM','PAL_ANOM']
		TITLES = [UNITS('PPD'),'Ratio OPAL:VGPM2a','Ratio OPAL:VGPM2a']
		FOR NTH = 0L, N_ELEMENTS(PRODS)-1 DO BEGIN
			PROD = PRODS[NTH]
			PAL = PALS[NTH]
			SPECIAL_SCALE = SPECIAL_SCALES[NTH]
			TITLE = TITLES[NTH]
			PSFILE = DIR_PLOTS + 'COLORBAR_HORIZONTAL-'+PROD+'-'+SPECIAL_SCALE+'.PS'
			CHARSIZE = 1.5
			PSPRINT,FILENAME=PSFILE,/ARIAL,/COLOR,/HALF
			!P.MULTI = [0,1,1]
			LEG = COLOR_BAR_SCALE(PROD=PROD,POSITION=[0.1, 0.9,0.9, 0.95],CHARSIZE=CHARSIZE,/TOP,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL)
			PSPRINT
			IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=BACKGROUND,GRACE=GRACE, OVERWRITE=overwrite
			PSFILE = DIR_PLOTS + 'COLORBAR_VERTICAL-'+PROD+'-'+SPECIAL_SCALE+'.PS'
			TITLE = ' '
			CHARSIZE = 1.5
			PSPRINT,FILENAME=PSFILE,/ARIAL,/COLOR,/HALF
			!P.MULTI = [0,1,1]
			LEG = COLOR_BAR_SCALE(PROD=PROD,POSITION=[0.5, 0.05,0.55, 0.95],CHARSIZE=CHARSIZE,/RIGHT,/VERTICAL,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL)
			PSPRINT
			IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=BACKGROUND,GRACE=GRACE, OVERWRITE=overwrite
		ENDFOR
STOP
	ENDIF ;DO_COLORBAR_PNGS


; *******************************************************
	IF DO_PS_2PNG GE 1 THEN BEGIN
; *******************************************************
		OVERWRITE = DO_PS_2PNG GE 2

		PSFILES = FILE_SEARCH(DIR_PLOTS + 'COLOR*.PS')
		GRACE = [20,20,20,20]
		BACKGROUND=215
		FOR _P = 0L, N_ELEMENTS(PSFILES)-1 DO BEGIN
			PSFILE = PSFILES(_P)
			IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=BACKGROUND,GRACE=GRACE, OVERWRITE=overwrite
		ENDFOR
STOP
	ENDIF ;DO_PS_2PNG


; ********************************************
  IF DO_PPD_SAT_COMPARISONS GE 1 THEN BEGIN
; ********************************************
		_OVERWRITE = DO_PPD_SAT_COMPARISONS GT 1

		DO_OPAL_VGPM 		= 1
		DO_OPAL_VGPM2A  = 1
		DO_VGPM_VGPM2A	= 1
		DO_MONTHS       = 1
		DO_YEARS        = 1
		DO_ANNUALS      = 1
		PPDS = [DO_OPAL_VGPM,DO_OPAL_VGPM2A,DO_VGPM_VGPM2A]
		PERIODS = [DO_MONTHS,DO_YEARS,DO_ANNUALS]
		PERS = ['!MONTH_','!Y_','!ANNUAL']
		PPD_ALGS1 = ['OPAL','OPAL','VGPM']
		PPD_ALGS2 = ['VGPM','VGPM2A','VGPM2A']

		PAL_SW3,R,G,B
		PAL = 'PAL_SW3'
		BACKGROUND = 255
		SPACE = 20
		PX = 772
		PY = 330
		!P.FONT = 0
		FIGSIZE = 1.5
		PAL_SW3

		FOR _PPD = 0L, N_ELEMENTS(PPDS)-1 DO BEGIN
			IF PPDS(_PPD) EQ 0 THEN CONTINUE
			PPD_ALG1 			= PPD_ALGS1(_PPD)
			PPD_ALG2 			= PPD_ALGS2(_PPD)
			DIR_DATA   		= DIR_PPD + 'DATA\STATS\'									& IF FILE_TEST(DIR_DATA,/DIR) 						EQ 0 THEN FILE_MKDIR, DIR_DATA
			DIR_SAVE   		= DIR_PPD + 'SAVE\' 											& IF FILE_TEST(DIR_SAVE,/DIR) 						EQ 0 THEN FILE_MKDIR, DIR_SAVE
			DIR_BROWSE 		= DIR_PPD + 'BROWSE\' 										& IF FILE_TEST(DIR_BROWSE,/DIR)				 		EQ 0 THEN FILE_MKDIR, DIR_BROWSE
			DIR_RATIO  		= DIR_PPD + 'RATIO\' 											& IF FILE_TEST(DIR_RATIO,/DIR) 						EQ 0 THEN FILE_MKDIR, DIR_RATIO
			DIR_PLOTS 	 	= DIR_PPD + 'PLOTS\' 											& IF FILE_TEST(DIR_PLOTS,/DIR) 						EQ 0 THEN FILE_MKDIR, DIR_PLOTS
			DIR_TRUE 			= DIR_PPD + 'TRUE\'
			DIR_TRIM      = DIR_PLOTS +'TRIM\'
			DIR_COMPOSITE = DIR_PPD + 'COMPOSITE\' 									& IF FILE_TEST(DIR_COMPOSITE,/DIR) 				EQ 0 THEN FILE_MKDIR, DIR_COMPOSITE
			DIR_COMPOSITE_HIST2D = DIR_PPD + 'HIST_2D_COMPOSITE\' 	& IF FILE_TEST(DIR_COMPOSITE_HIST2D,/DIR) EQ 0 THEN FILE_MKDIR, DIR_COMPOSITE_HIST2D

			FOR PTH = 0L, N_ELEMENTS(PERIODS)-1 DO BEGIN
				IF PERIODS(PTH) EQ 0 THEN CONTINUE
				PERIOD = PERS(PTH)
				FILES1 = FILE_SEARCH(DIR_DATA + PERIOD + '*NEC*PPD-' + PPD_ALG1 + '-MEAN.SAVE')
				FILES2 = FILE_SEARCH(DIR_DATA + PERIOD + '*NEC*PPD-' + PPD_ALG2 + '-MEAN.SAVE')

				IF N_ELEMENTS(FILES1) NE N_ELEMENTS(FILES2) THEN STOP

				FOR NTH = 0L, N_ELEMENTS(FILES1)-1 DO BEGIN
					FP1 = PARSE_IT(FILES1[NTH],/ALL)
					FP2 = PARSE_IT(FILES2[NTH],/ALL)
					IF FP1.PERIOD NE FP2.PERIOD THEN STOP
					APERIOD = FP1.PERIOD

					STRUCT_SD_2PNG, [FP1.FULLNAME,FP2.FULLNAME],DIR_OUT=DIR_BROWSE,USE_PROD=APROD,$
					    								/ADD_COLORBAR, /ADDDATE,/ADD_PROD,SPECIAL_SCALE=SPECIAL_SCALE,$
		                   				/ADD_LAND, /ADD_COAST, BACKGROUND=ABACKGROUND,/ADD_ALG,$
		                  				LAND_COLOR=252,FLAG_COLOR=AFLAG_COLOR,OUTSCAN_COLOR=aoutscan_color,$
		                  				ALGFAIL_COLOR=AALGFAIL_COLOR,HI_LO_COLOR=AHI_LO_COLOR,PAL=PAL,FLAGS=_FLAGS,SOLO=SOLO,$
		                  				OVERWRITE=_overwrite,/QUIET

					RATIO_SAVEFILE = DIR_RATIO + APERIOD + '-' + FP1.SENSOR +'-' + FP1.COVERAGE + '-' + FP1.MAP + '-' + FP1.PROD + '-' + FP1.ALG + '_' + FP2.ALG + '-RATIO.SAVE'
					ANOM ='RATIO'
		      MAKE_ANOM_SAVES,DIR_OUT=DIR_RATIO,SAVEFILE=RATIO_SAVEFILE,FILEA=FP1.FULLNAME,FILEB=FP2.FULLNAME,ANOM=ANOM,OVERWRITE=_OVERWRITE

					USE_PROD = ANOM
					SPECIAL_SCALE = '3'
					IF FP1.PERIOD_CODE EQ '!MONTH'  THEN ADD_EXTRA = MONTH_NAMES(FP1.MONTH_START) + ' ' + FP1.ALG + ':' + FP2.ALG
					IF FP1.PERIOD_CODE EQ '!Y'      THEN ADD_EXTRA = FP1.YEAR_START + ' ' + FP1.ALG + ':' + FP2.ALG
					IF FP1.PERIOD_CODE EQ '!ANNUAL' THEN ADD_EXTRA = 'Annual' + ' ' + FP1.ALG + ':' + FP2.ALG
					STRUCT_SD_2PNG, RATIO_SAVEFILE,DIR_OUT=DIR_BROWSE,USE_PROD=USE_PROD,$
					    								/ADD_COLORBAR,/ADD_PROD,SPECIAL_SCALE=SPECIAL_SCALE,$
		                   				/ADD_LAND, /ADD_COAST, BACKGROUND=ABACKGROUND,$
		                  				LAND_COLOR=252,FLAG_COLOR=AFLAG_COLOR,OUTSCAN_COLOR=aoutscan_color,$
		                  				ALGFAIL_COLOR=AALGFAIL_COLOR,HI_LO_COLOR=AHI_LO_COLOR,PAL='PAL_ANOM',FLAGS=_FLAGS,SOLO=SOLO,$
		                  				OVERWRITE=_overwrite,/QUIET, ADD_EXTRA=ADD_EXTRA

					DATA1 = STRUCT_SD_READ(FP1.FULLNAME,STRUCT=STRUCT1)
					DATA2 = STRUCT_SD_READ(FP2.FULLNAME,STRUCT=STRUCT2)

					OK = WHERE(STRUCT1.IMAGE NE MISSINGS(STRUCT1.IMAGE) AND STRUCT2.IMAGE NE MISSINGS(STRUCT2.IMAGE),COUNT)

					!P.MULTI=[0,0,1]
					APROD = FP1.PROD
					PSFILE = DIR_PLOTS + APERIOD + '-' + FP1.SENSOR +'-' + FP1.COVERAGE + '-' + FP1.MAP + '-' + FP1.PROD + '-' + FP1.ALG + '_' + FP2.ALG + '-HIST2D.PS'
					PSPRINT,FILENAME=PSFILE,/COLOR,/TIMES
					XSCALE = SD_SCALES([1,250],PROD='PPD',/BIN2DATA)
					YSCALE = SD_SCALES([1,250],PROD='PPD',/BIN2DATA)
					XX = STRUCT1.IMAGE[OK]
					YY = STRUCT2.IMAGE[OK]

					ALG_A = PPD_ALG1
					ALG_B = PPD_ALG2
					PERIOD_A = APERIOD
					PERIOD_B = APERIOD
					IF FP1.PERIOD_CODE EQ '!MONTH'  THEN TITLE = 'Primary Production' + '!C' + MONTH_NAMES(FP1.MONTH_START)
					IF FP1.PERIOD_CODE EQ '!Y'      THEN TITLE = 'Primary Production' + '!C' + FP1.YEAR_START
					IF FP1.PERIOD_CODE EQ '!ANNUAL' THEN TITLE = 'Primary Production' + '!C' + 'Annual'
					ALOGX = 1
					ALOGY = 1
					IF KEYWORD_SET(ALOGX) THEN BEGIN
						XRANGE = NICE_RANGE(ALOG10(XSCALE))
						XTITLE = UNITS(APROD) + '  -  ' + ALG_A
						XX = ALOG10(XX)
					ENDIF	ELSE BEGIN
						XRANGE = NICE_RANGE(XSCALE)
						XTITLE = UNITS(APROD) + '  -  ' + ALG_A
					ENDELSE
					IF KEYWORD_SET(ALOGY) THEN BEGIN
						YRANGE = NICE_RANGE(ALOG10(YSCALE))
						YTITLE = UNITS(APROD) + '  -  ' + ALG_B
						YY = ALOG10(YY)
					ENDIF ELSE BEGIN
						YRANGE = NICE_RANGE(YSCALE)
						YTITLE = UNITS(APROD) + '  -  ' + ALG_B
					ENDELSE
					XRANGE = ALOG10([0.1,10])
					YRANGE = ALOG10([0.1,10])
					BINX=(XRANGE[1]-XRANGE[0])/100.
					BINY=(YRANGE[1]-YRANGE[0])/100.
					!Y.OMARGIN=[2,2]
					!X.OMARGIN=[8,6]
					STATS_PARAMS = [2,3,4,8,10]

					PLOT_HIST2D, XX, YY, IMAGE=HIST_IMAGE, PAL=_PAL, MODEL='RMA', FAST=1, CHARSIZE=1.5,$
			          BIN_X=BINX, MIN_X=XRANGE[0], MAX_X=XRANGE[1], $
			          BIN_Y=BINY, MIN_Y=YRANGE[0], MAX_Y=YRANGE[1], $
			          PX=PX, XTITLE=XTITLE, XLABEL=XLABEL, XTHICK=3, XMARGIN=XMARGIN, TITLE=TITLE, $
			          PY=PY, YTITLE=YTITLE, YLABEL=YLABEL, YTHICK=3, YMARGIN=YMARGIN, $
			          LAB_TXT=LABEL, LAB_CHARSIZE=5, STATS_CHARSIZE=1.25, ISOTROPIC=ISOTROPIC,$
			          BKG_COLOR=255, ZERO_COLOR=254, MAX_COLOR=250,$
			          REG_COLOR=0,  REG_THICK=5, ONE_COLOR=255,ONE_THICK=8, $
			          ALOGX=ALOGX,ALOGY=ALOGY,$
			          LOG_FREQ=1, POSITION=POSITION,STATS_PARAMS=STATS_PARAMS, _EXTRA=_EXTRA

					PSPRINT

					FP = FILE_PARSE(PSFILE)
					GRACE = [100,100,100,100]
					DPI = 600
					BACKGROUND = 215

					IMAGE_TRIM, PSFILE,DIR_OUT=DIR_PLOTS,DPI=DPI,BACKGROUND=BACKGROUND,GRACE=GRACE,OVERWRITE=_overwrite

					DIRS = [DIR_TRIM,DIR_BROWSE,DIR_BROWSE,DIR_BROWSE]
					NAMES = ['HIST2D','RATIO','PROD1','PROD2']

					FOR DTH=0L, N_ELEMENTS(DIRS)-1 DO BEGIN
						NAME = NAMES(DTH)
						IF NAME EQ 'HIST2D' THEN FILES = FILE_SEARCH(DIRS(DTH)+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-HIST2D-PS_1-trim.PNG')
						IF NAME EQ 'RATIO'  THEN FILES = FILE_SEARCH(DIRS(DTH)+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-'+ANOM+'.PNG')
						IF NAME EQ 'PROD1' 	THEN FILES = FILE_SEARCH(DIRS(DTH)+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'-MEAN.PNG')
						IF NAME EQ 'PROD2'  THEN FILES = FILE_SEARCH(DIRS(DTH)+APERIOD+'-'+FP2.SENSOR+'-'+FP2.COVERAGE+'-'+FP2.MAP+'-'+FP2.PROD+'-'+FP2.ALG+'-MEAN.PNG')
						FN = PARSE_IT(FILES,/ALL)
						FOR FTH = 0L, N_ELEMENTS(FILES)-1 DO BEGIN
							PNGFILE = DIR_TRUE+FN(FTH).NAME+'-TRUE.PNG'
							EXIST = FILE_TEST(PNGFILE)
							IF EXIST EQ 0 OR _OVERWRITE EQ 1 THEN BEGIN
								IMAGE = READ_PNG(FILES(FTH),R,G,B)
								TRUE = IMAGE_2TRUE(IMAGE,R,G,B)
								WRITE_PNG,PNGFILE ,TRUE,R,G,B
							ENDIF
						ENDFOR
					ENDFOR

					FILES_0 = FILE_SEARCH(DIR_TRUE+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'-MEAN-TRUE.PNG') & FN_0 = PARSE_IT(FILES_0,/ALL)
					FILES_1 = FILE_SEARCH(DIR_TRUE+APERIOD+'-'+FP2.SENSOR+'-'+FP2.COVERAGE+'-'+FP2.MAP+'-'+FP2.PROD+'-'+FP2.ALG+'-MEAN-TRUE.PNG') & FN_1 = PARSE_IT(FILES_1,/ALL)
					FILES_3 = FILE_SEARCH(DIR_TRUE+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-'+ANOM+'-TRUE.PNG') & FN_3 = PARSE_IT(FILES_3,/ALL)
					FILES_4 = FILE_SEARCH(DIR_TRUE+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-HIST2D-PS_1-trim-TRUE.PNG') & FN_4 = PARSE_IT(FILES_4,/ALL)
					FILES = [FILES_0,FILES_1,FILES_3,FILES_4]

					SETS = WHERE_SETS(FN_0.PERIOD,FN_1.PERIOD,FN_3.PERIOD,FN_4.PERIOD)
					FOR STH = 0L, N_ELEMENTS(SETS)-1 DO BEGIN
						SUBS = WHERE_SETS_SUBS(SETS(STH),GROUPS=GROUPS)
						OK = WHERE(GROUPS EQ 0,COUNT) & IF COUNT EQ 1 THEN FILE_0 = FILES(SUBS[OK]) ELSE FILE_0 = BLANK
						OK = WHERE(GROUPS EQ 1,COUNT) & IF COUNT EQ 1 THEN FILE_1 = FILES(SUBS[OK]) ELSE FILE_1 = BLANK
						OK = WHERE(GROUPS EQ 2,COUNT) & IF COUNT EQ 1 THEN FILE_3 = FILES(SUBS[OK]) ELSE FILE_3 = BLANK
						OK = WHERE(GROUPS EQ 3,COUNT) & IF COUNT EQ 1 THEN FILE_4 = FILES(SUBS[OK]) ELSE FILE_4 = BLANK

						AFILES = [FILE_0,FILE_1,FILE_3,FILE_4]
						INAME = SETS(STH).VALUE
						PNGFILE = DIR_COMPOSITE+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-COMPOSITE.PNG'
						ROWS = 3
						COLS = 1
						IF FILE_TEST(PNGFILE) EQ 0  OR _OVERWRITE EQ 1 THEN $
						IMAGE_WELD_PAGE,FILES=AFILES(0:2),ROWS=ROWS,COLS=COLS,PNGFILE=pngfile,SPACE=SPACE,PX=PX,py=PY,BACKGROUND=BACKGROUND,/NOTRIM
						PNGFILE2 = DIR_COMPOSITE_HIST2D+APERIOD+'-'+FP1.SENSOR+'-'+FP1.COVERAGE+'-'+FP1.MAP+'-'+FP1.PROD+'-'+FP1.ALG+'_'+FP2.ALG+'-COMPOSITE_HIST2D.PNG'
						ROWS = 1
						COLS = 2
						IF FILE_TEST(PNGFILE2) EQ 0  OR _OVERWRITE EQ 1 THEN $
						IMAGE_WELD_PAGE,FILES=[PNGFILE,AFILES(3)],ROWS=ROWS,COLS=COLS,PNGFILE=pngfile2,SPACE=SPACE,PX=PX,py=PY,BACKGROUND=BACKGROUND,/NOTRIM
					ENDFOR
				ENDFOR
			ENDFOR
		ENDFOR
		!Y.OMARGIN = [0,0]
		!X.OMARGIN = [0,0]
	ENDIF



; *******************************************************
	IF DO_IMAGE_COMPOSITES GE 1 THEN BEGIN
; *******************************************************
		OVERWRITE = DO_IMAGE_COMPOSITES GE 2

		BACKGROUND = 255
		SPACE = 20
		PX = 1024
		PY = 1024
		!P.FONT = 0
		FIGSIZE = 1.5

		DIR_STATS = DIR_PPD + 'DATA\STATS\'
		DIR_RATIO = DIR_PPD + 'RATIO\'
		DIR_BROWSE = DIR_PPD + 'PRESENTATION_COMPOSITES\BROWSE\'
		DIR_PLOTS = DIR_PPD + 'PRESENTATION_COMPOSITES\PLOTS\'
		DIR_POSTER = DIR_PPD + 'PRESENTATION_COMPOSITES\COMPOSITES\'

;		Make Monthly Images
			PRODS = ['PPD-OPAL','PPD-VGPM','PPD-VGPM2A','PPD-OPAL_VGPM','PPD-OPAL_VGPM2A','PPD-VGPM_VGPM2A']
			MAPS  = ['NEC','NEC','NEC','NEC','NEC','NEC']
			DIRS  = [DIR_STATS, DIR_STATS,DIR_STATS,DIR_RATIO,DIR_RATIO,DIR_RATIO]
			STAT  = ['MEAN','MEAN','MEAN','RATIO','RATIO','RATIO']
			PALS  = ['PAL_SW3','PAL_SW3','PAL_SW3','PAL_ANOM','PAL_ANOM','PAL_ANOM']
			SPECIAL_SCALES = ['','','','3','3','3']
			MAKE_PNGS = [0,0,0,1,1,1]

			PNGFILES = [DIR_PLOTS + 'Figure_ppd_opal-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_1_12.PNG',$
									DIR_PLOTS + 'Figure_ppd_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_1_12.PNG',$
									DIR_PLOTS + 'Figure_ppd_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_1_12.PNG',$
									DIR_PLOTS + 'Figure_ratio_opal_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM-RATIO-COMPOSITE_1_12.PNG',$
									DIR_PLOTS + 'Figure_ratio_opal_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM2A-RATIO-COMPOSITE_1_12.PNG',$
									DIR_PLOTS + 'Figure_ratio_vgpm_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM_VGPM2A-RATIO-COMPOSITE_1_12.PNG']

			PNGFILE2 = [DIR_PLOTS + 'Figure_ppd_opal-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_4_3.PNG',$
         					DIR_PLOTS + 'Figure_ppd_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_4_3.PNG',$
         					DIR_PLOTS + 'Figure_ppd_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_4_3.PNG',$
         					DIR_PLOTS + 'Figure_ratio_opal_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM-RATIO-COMPOSITE_4_3.PNG',$
									DIR_PLOTS + 'Figure_ratio_opal_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM2A-RATIO-COMPOSITE_4_3.PNG',$
									DIR_PLOTS + 'Figure_ratio_vgpm_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM_VGPM2A-RATIO-COMPOSITE_4_3.PNG']

			ROWS = 1
			COLS = 12
			ROW2 = 3
			COL2 = 4
			BACKGROUND=255
			SPACE=20

			FOR PTH =0L, N_ELEMENTS(PRODS)-1 DO BEGIN
				IF MAKE_PNGS(PTH) EQ 0 THEN CONTINUE
				APROD = PRODS(PTH)
				FILES =FILE_SEARCH(DIRS(PTH)+'!MONTH_*S*_N4AT-*'+MAPS(PTH) + '-*' + APROD+'-*'+STAT(PTH)+'.SAVE')
				USE_PROD = VALIDS('PRODS',APROD)
				IF STAT(PTH) EQ 'RATIO' THEN USE_PROD='RATIO'
				IF FILES[0] EQ '' THEN CONTINUE
				STRUCT_SD_2PNG,FILES,DIR_OUT=DIR_BROWSE,USE_PROD=USE_PROD,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALES(PTH),/BATHY_THICK, BATHY_COLOR=0, PAL=PALS(PTH),/ADD_COLORBAR
				PNGS  = FILE_SEARCH(DIR_BROWSE+'!MONTH_*-'+MAPS(PTH) + '-*'+APROD+'-'+STAT(PTH)+'.PNG')
				IMAGE_WELD_PAGE,FILES=PNGS,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=PNGFILES(PTH),SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
				IMAGE_WELD_PAGE,FILES=PNGS,ROWS=ROW2,COLS=COL2,PAL=PAL,PNGFILE=PNGFILE2(PTH),SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
			ENDFOR

			PSFILES  = [DIR_POSTER + 'Figure_ppd_opal-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_1_12.PS',$
									DIR_POSTER + 'Figure_ppd_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_1_12.PS',$
									DIR_POSTER + 'Figure_ppd_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_1_12.PS',$
									DIR_POSTER + 'Figure_ratio_opal_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM-RATIO-COMPOSITE_1_12.PS',$
									DIR_POSTER + 'Figure_ratio_opal_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM2A-RATIO-COMPOSITE_1_12.PS',$
									DIR_POSTER + 'Figure_ratio_vgpm_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM_VGPM2A-RATIO-COMPOSITE_1_12.PS']


			PSFILE2  = [DIR_POSTER + 'Figure_ppd_opal-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_4_3.PS',$
									DIR_POSTER + 'Figure_ppd_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_4_3.PS',$
									DIR_POSTER + 'Figure_ppd_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_4_3.PS',$
									DIR_POSTER + 'Figure_ratio_opal_vgpm-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM-RATIO-COMPOSITE_4_3.PS',$
									DIR_POSTER + 'Figure_ratio_opal_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-OPAL_VGPM2A-RATIO-COMPOSITE_4_3.PS',$
									DIR_POSTER + 'Figure_ratio_vgpm_vgpm2a-!MONTH-SA_N4AT-MLAC-4-NEC-PPD-VGPM_VGPM2A-RATIO-COMPOSITE_4_3.PS']


			OK = WHERE(FILE_TEST(PNGFILES) EQ 1, COUNT)
			IF COUNT GE 1 THEN BEGIN & PNGFILES = PNGFILES[OK] & PSFILES = PSFILES[OK] & PRODS1 = PRODS[OK] & SPECIAL_SCALES1=SPECIAL_SCALES[OK] & ENDIF ELSE GOTO, SKIP_PNGFILE1

			FOR NTH = 0L, N_ELEMENTS(PNGFILES)-1 DO BEGIN
				PNGFILE = PNGFILES[NTH]
				PSFILE  = PSFILES[NTH]
				SPECIAL_SCALE = SPECIAL_SCALES1[NTH]
				APROD = PRODS1[NTH]
				MAP = 'NEC'

				IMAGE = READ_PNG(PNGFILE,R,G,B)
		   	OLDDEVICE= !D.NAME
				_XOFFSET = 10.
		  	_YOFFSET = 27.5
		    _SCALE   = 0.25

				PS_IMAGE, FILES=PNGFILE,DIR_OUT=DIR_POSTER, /COLOR,FULL=full,/NO_CLOSE,SCALE=_SCALE,XOFFSET=_XOFFSET,YOFFSET=_YOFFSET,/LANDSCAPE,PAL=PAL
				!P.FONT = 0
				ALIGN     = 0.5
			 	X = 0.010
			 	Y = 0.85
			 	IX = 0.0838
				POSITION = [0.925, 0.05,0.93, 0.95]
				CHARSIZE  = 2.75
				COLOR     = 0
				CHARTHICK = 1
				ALIGN     = 0.5
				XYOUTS,X+0*IX,Y, 'Jan', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+1*IX,Y, 'Feb', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+2*IX,Y, 'Mar', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+3*IX,Y, 'Apr', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+4*IX,Y, 'May', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+5*IX,Y, 'Jun', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+6*IX,Y, 'Jul', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+7*IX,Y, 'Aug', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+8*IX,Y, 'Sep', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+9*IX,Y, 'Oct', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+10*IX,Y,'Nov', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+11*IX,Y,'Dec', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL

				TITLE = UNITS('PPD')

				CHARSIZE = 0.75
		;		LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
				DEVICE,/CLOSE
				SET_PLOT,OLDDEVICE
;				IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=215,GRACE=[0,0,0,0],/OVERWRITE
		  ENDFOR
		  SKIP_PNGFILE1:
		  OK = WHERE(FILE_TEST(PNGFILE2) EQ 1, COUNT)
			IF COUNT GE 1 THEN BEGIN & PNGFILE2 = PNGFILE2[OK] & PSFILE2 = PSFILE2[OK] & PRODS2 = PRODS[OK] & SPECIAL_SCALES2=SPECIAL_SCALES[OK] & ENDIF ELSE GOTO, SKIP_PNGFILE2
		  FOR NTH = 0L, N_ELEMENTS(PNGFILE2)-1 DO BEGIN
				PNGFILE = PNGFILE2[NTH]
				PSFILE  = PSFILE2[NTH]
				SPECIAL_SCALE = SPECIAL_SCALES2[NTH]
				APROD = PRODS2[NTH]

				IMAGE = READ_PNG(PNGFILE,R,G,B)
		   	OLDDEVICE= !D.NAME
				_XOFFSET = 2
	  	  _YOFFSET = 26.5
	      _SCALE = 0.67
				PS_IMAGE, FILES=PNGFILE,DIR_OUT=DIR_POSTER, /COLOR,FULL=full,/NO_CLOSE,SCALE=_SCALE,XOFFSET=_XOFFSET,YOFFSET=_YOFFSET,/LANDSCAPE,PAL=PAL
				!P.FONT = 0
				ALIGN     = 0.5

				X = 0.035
				Y = 0.96
				IX = 0.25
				IY = -0.335

				CHARSIZE  = 2.75
				COLOR     = 0
				CHARTHICK = 1
				ALIGN     = 0.5
				XYOUTS,X,Y,'Jan', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+IX,Y,'Feb', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+2*IX,Y,'Mar', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+3*IX,Y,'Apr', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X,Y+IY,'May', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+IX,Y+IY,'Jun', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+2*IX,Y+IY,'Jul', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+3*IX,Y+IY,'Aug', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X,Y+2*IY,'Sep', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+IX,Y+2*IY,'Oct', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+2*IX,Y+2*IY,'Nov', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
				XYOUTS,X+3*IX,Y+2*IY,'Dec', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL

				TITLE = UNITS('PPD')

				CHARSIZE = 0.5
				POSITION = [0.05, 0.01,0.95, 0.02]
;				LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
				DEVICE,/CLOSE
				SET_PLOT,OLDDEVICE
				IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=215,GRACE=[50,50,50,50],/OVERWRITE
		  ENDFOR
		  SKIP_PNGFILE2:
STOP
;			YEARLY COMPOSITES
			BLANK = DIR_IDL + 'IMAGES\BLANK_1024.PNG'
			TRUE  = DIR_IDL+'IMAGES\BLANK_1024_BY_1024_TRUE.PNG'
			IMAGE = READ_PNG(BLANK)
			WRITE_PNG,TRUE, IMAGE_2TRUE(IMAGE,R,G,B)

			PNGFILES = [DIR_PLOTS + 'Figure_opal-!Y-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_1_11.PNG',$
 									DIR_PLOTS + 'Figure_vgpm-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_1_11.PNG',$
 									DIR_PLOTS + 'Figure_vgpm2a-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_1_11.PNG']

			PNGFILE2 = [DIR_PLOTS + 'Figure_opal-!Y-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_2_6.PNG',$
 									DIR_PLOTS + 'Figure_vgpm-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_2_6.PNG',$
 									DIR_PLOTS + 'Figure_vgpm2a-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_2_6.PNG']

			PRODS = ['PPD-OPAL','PPD-VGPM','PPD-VGPM2A']
			DIRS  = [DIR_STATS, DIR_STATS,DIR_STATS]
			SPECIAL_SCALES = ['','','']
			STAT  = ['MEAN','MEAN','MEAN']
			MAPS  = ['NEC','NEC','NEC','NEC']
			MAKE_PNGS = [1,1,1]

			ROWS = [1,2]
			COLS = [11,6]
			BACKGROUND=255
			SPACE=20

			FOR PTH =0L, N_ELEMENTS(PRODS)-1 DO BEGIN
				IF MAKE_PNGS(PTH) EQ 0 THEN CONTINUE
				APROD = PRODS(PTH)
				FILES =FILE_SEARCH(DIRS(PTH)+'!Y_*S_N4AT-*'+MAPS(PTH) + '-*' + APROD+'-*'+STAT(PTH)+'.SAVE')
				USE_PROD = VALIDS('PRODS',APROD)
				IF FILES[0] EQ '' THEN CONTINUE
				STRUCT_SD_2PNG,FILES,DIR_OUT=DIR_BROWSE,USE_PROD=USE_PROD,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALES(PTH),/BATHY_THICK, BATHY_COLOR=0
				PNGS  = FILE_SEARCH(DIR_BROWSE+'!Y_*-' +MAPS(PTH)+ '-*' +APROD+'-'+STAT(PTH)+'.PNG')
				IMAGE_WELD_PAGE,FILES=PNGS,ROWS=ROWS[0],COLS=COLS[0],PAL=PAL,PNGFILE=PNGFILES(PTH),SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
				PNGS = [PNGS,BLANK]
				IMAGE_WELD_PAGE,FILES=PNGS,ROWS=ROWS[1],COLS=COLS[1],PAL=PAL,PNGFILE=PNGFILE2(PTH),SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
			ENDFOR


			PSFILES  = [DIR_POSTER + 'Figure_opal-!Y-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_1_11.PS',$
									DIR_POSTER + 'Figure_vgpm-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_1_11.PS',$
									DIR_POSTER + 'Figure_vgpm2a-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_1_11.PS']

			PSFILE2  = [DIR_POSTER + 'Figure_opal-!Y-SA_N4AT-MLAC-4-NEC-PPD-OPAL-MEAN-COMPOSITE_2_6.PS',$
									DIR_POSTER + 'Figure_vgpm-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM-MEAN-COMPOSITE_2_6.PS',$
									DIR_POSTER + 'Figure_vgpm2a-!Y-SA_N4AT-MLAC-4-NEC-PPD-VGPM2A-MEAN-COMPOSITE_2_6.PS']

			OK = WHERE(FILE_TEST(PNGFILES) EQ 1)
			PNGFILES = PNGFILES[OK] & PSFILES = PSFILES[OK]

			OK = WHERE(FILE_TEST(PNGFILE2) EQ 1)
			PNGFILE2 = PNGFILE2[OK] & PSFILE2 = PSFILE2[OK]

			FOR NTH = 0L, N_ELEMENTS(PNGFILES)-1 DO BEGIN
				PNGFILE = PNGFILES[NTH]
				PSFILE  = PSFILES[NTH]
				SPECIAL_SCALE = SPECIAL_SCALES[NTH]
				APROD = PRODS[NTH]
				SST_YEARS = 0
				MAP = 'NEC'

		   	OLDDEVICE= !D.NAME
		   	_XOFFSET = 12.
		  	_YOFFSET = 27.5
		    _SCALE   = 0.295
				PS_IMAGE, FILES=PNGFILE,DIR_OUT=DIR_POSTER, /COLOR,FULL=full,/NO_CLOSE,SCALE=_SCALE,XOFFSET=_XOFFSET,YOFFSET=_YOFFSET,/LANDSCAPE,PAL=PAL
				!P.FONT = 0
				X = 0.019
				Y = 0.84
				IX = 0.101
				IY = -0.25
				CHARSIZE 	= 2.95
				COLOR     = 0
				CHARTHICK = 1
				ALIGN     = 0.5
				X = 0.019
				Y = 0.84
				IX = 0.1005

				XYOUTS,X+0*IX,Y,'1998', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+1*IX,Y,'1999', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+2*IX,Y,'2000', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+3*IX,Y,'2001', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+4*IX,Y,'2002', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+5*IX,Y,'2003', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+6*IX,Y,'2004', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+7*IX,Y,'2005', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+8*IX,Y,'2006', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+9*IX,Y,'2007', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+9*IX,Y,'2008', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'

				IF APROD EQ 'GRAD_MAG' THEN TITLE = '!Eo!NC  km!E-1!N'
				IF APROD EQ 'GRAD_DIR' THEN TITLE = 'Gradient Direction'
				IF APROD EQ 'GRAD_MAG_RATIO' THEN TITLE = 'Chlorophyll Gradient Magnitude (ratio)'
				IF APROD EQ 'CHLOR_A'  THEN TITLE = UNITS('CHLOROPHYLL')
				IF APROD EQ 'SST'      THEN TITLE = UNITS('SST')
				CHARSIZE = 0.75
		;		LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
				DEVICE,/CLOSE
				SET_PLOT,OLDDEVICE
		;		IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=215,GRACE=[0,0,0,0],/OVERWRITE
		  ENDFOR

		  FOR NTH = 0L, N_ELEMENTS(PNGFILE2)-1 DO BEGIN
				PNGFILE = PNGFILE2[NTH]
				PSFILE  = PSFILE2[NTH]
				SPECIAL_SCALE = SPECIAL_SCALES[NTH]
				APROD = PRODS[NTH]
				IF APROD EQ 'SST-4UM' OR APROD EQ 'GRAD_MAG' THEN SST_YEARS = 1 ELSE SST_YEARS = 0

				_XOFFSET = 0
		  	_YOFFSET = 15.5
		    _SCALE   = 0.38
		    PS_IMAGE, FILES=PNGFILE,DIR_OUT=DIR_POSTER, /COLOR,FULL=full,/NO_CLOSE,SCALE=_SCALE,XOFFSET=_XOFFSET,YOFFSET=_YOFFSET,PAL=PAL

				CHARSIZE 	= 2.75
				COLOR     = 0
				CHARTHICK = 1
				ALIGN     = 0.5
				X = 0.0325
				Y = 0.915
				IX = 0.167
				IY = -0.49

				XYOUTS,X,     Y,'1998', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+IX,  Y,'1999', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+2*IX,Y,'2000', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+3*IX,Y,'2001', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+4*IX,Y,'2002', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+5*IX,Y,'2003', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X,     Y+IY,'2004', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+IX,  Y+IY,'2005', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+2*IX,Y+IY,'2006', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+3*IX,Y+IY,'2007', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
				XYOUTS,X+4*IX,Y+IY,'2008', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'


				TITLE = UNITS('PPD')
				CHARSIZE = 0.75
		;		LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
				DEVICE,/CLOSE
				SET_PLOT,OLDDEVICE
				IMAGE_TRIM, PSFILE, DIR_OUT=DIR_POSTER, DPI=600, BACKGROUND=215,GRACE=[0,0,0,0],/OVERWRITE
			ENDFOR


		STOP






;		Bathy figure 1
		SAVEFILE = 'D:\IDL\DATA\SRTM30-NEC-PXY_1024_1024-BATHY-SMOOTH_5.SAVE'
		PNGFILE  = DIR_BROWSE  + 'SRTM30-NEC-PXY_1024_1024-BATHY-SMOOTH_5.PNG'
		PSFILE 	 = DIR_PLOTS	 + 'Figure-SRTM30-NEC-PXY_1024_1024-BATHY-SMOOTH_5.PS'

		PAL = 'PAL_BATHY'
		STRUCT_SD_2PNG,SAVEFILE,DIR_OUT=DIR_BROWSE,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALE,PAL='PAL_BATHY'
		IMAGE = READ_PNG(PNGFILE,r,g,b)
		SZ=SIZE(IMAGE,/STRUCT)
		TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
   	xsize = DOUBLE(2.54*(PX_IMAGE/300.))
   	ysize = DOUBLE(2.54*(PY_IMAGE/300.))
   	width = 20.5
   	height = 26.9
		xoffset = 2
    yoffset  = 10
    SCALE = 2
    olddevice= !d.name  ; Get present graphics device
  	!P.FONT = 0
    SET_PLOT,'ps'
    DEVICE,FILENAME=psfile
		DEVICE, /PORTRAIT
		DEVICE,/COLOR
 		CALL_PROCEDURE,PAL,R,G,B
 		TVLCT,R,G,B
 		COLOR=1
		DEVICE,BITS_PER_PIXEL=8
		DEVICE,/HELVETICA
    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, $
    XSIZE=xsize, YSIZE=ysize, $
    SCALE_FACTOR=scale
    TV,IMAGE, TRUE=TRUE_COLOR
		CHARSIZE = 1.15
		TITLE = 'Depth (m)'
		CHARSIZE = 0.75
		LEG=COLOR_BAR_SCALE(PROD='BATHY',POSITION=[0.02, 0.94,0.5, 0.96],CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE,PAL='PAL_BATHY')
    DEVICE,/CLOSE
    SET_PLOT,olddevice

		PAL_SW3,R,G,B

;		Mean Annuals
		SAVEFILE = DIR_SAVE 		+ '!ANNUAL-PP-PSAT-NEC-PPD-OPAL-MEAN.SAVE'
		PNGFILE  = DIR_BROWSE 	+ '!ANNUAL-PP-PSAT-NEC-PPD-OPAL-MEAN.PNG'
		SPECIAL_SCALE = ''
		PAL = 'PAL_SW3'
		STRUCT_SD_2PNG,SAVEFILE,DIR_OUT=DIR_BROWSE,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,$
			/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL,/ADD_COLORBAR

		SAVEFILE = DIR_SAVE 		+ '!ANNUAL-PP-PSAT-NEC-PPD-VGPM2A-MEAN.SAVE'
		PNGFILE  = DIR_BROWSE 	+ '!ANNUAL-PP-PSAT-NEC-PPD-VGPM2A-MEAN.PNG'
		SPECIAL_SCALE = ''
		PAL = 'PAL_SW3'
		STRUCT_SD_2PNG,SAVEFILE,DIR_OUT=DIR_BROWSE,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,$
			/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL,/ADD_COLORBAR

		SAVEFILE = DIR_SAVE 		+ '!ANNUAL-PP-PSAT--NEC-PPD-MEANS-RATIO-OPAL_VGPM2A.SAVE'
		PNGFILE  = DIR_BROWSE  	+ '!ANNUAL-PP-PSAT--NEC-PPD-MEANS-RATIO-OPAL_VGPM2A.PNG'
		SPECIAL_SCALE = '2'
		PAL = 'PAL_RATIO'
		COLORBAR_TITLE = 'Ratio OPAL:VGPM2a'
		STRUCT_SD_2PNG,SAVEFILE,DIR_OUT=DIR_BROWSE,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE, $
			/ADD_BATHY,SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL,/ADD_COLORBAR,COLORBAR_TITLE=COLORBAR_TITLE

;		IMAGE = READ_PNG(PNGFILE,r,g,b)
;		SZ=SIZE(IMAGE,/STRUCT)
;		TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
;  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
;  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
;   	xsize = DOUBLE(2.54*(PX_IMAGE/300.))
;   	ysize = DOUBLE(2.54*(PY_IMAGE/300.))
;   	width = 20.5
;   	height = 26.9
;		xoffset = 2
;    yoffset  = 10
;    SCALE = 2
;    olddevice= !d.name  ; Get present graphics device
;  	!P.FONT = 0
;    SET_PLOT,'ps'
;    DEVICE,FILENAME=psfile
;		DEVICE, /PORTRAIT
;		DEVICE,/COLOR
; 		CALL_PROCEDURE,PAL,R,G,B
; 		TVLCT,R,G,B
; 		COLOR=1
;		DEVICE,BITS_PER_PIXEL=8
;		DEVICE,/HELVETICA
;    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, $
;    XSIZE=xsize, YSIZE=ysize, $
;    SCALE_FACTOR=scale
;    TV,IMAGE, TRUE=TRUE_COLOR
;		CHARSIZE = 1.15
;		TITLE = 'Chlorophyll Gradient !C(ratio)'
;		CHARSIZE = 0.75
;		LEG=COLOR_BAR_SCALE(PROD='GRAD_MAG_RATIO',POSITION=[0.02, 0.94,0.5, 0.96],PAL='PAL_SW3',CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA',SPECIAL_SCALE=SPECIAL_SCALE)
;    DEVICE,/CLOSE
;    SET_PLOT,olddevice

;		OPAL Monthly composite figure
		_FILES = ['-PP-PSAT-NEC-PPD-OPAL-MEAN', $
		 					'-PP-PSAT-NEC-PPD-VGPM2a-MEAN', $
		 					'-PP-PSAT--NEC-PPD-MEANS-RATIO-OPAL_VGPM2A']
		_SPECIAL_SCALE = ['','','2']
		_PALS = ['PAL_SW3','PAL_SW3','PAL_RATIO']
		PRODS = ['PPD','PPD','RATIO']
		MAPS  = ['NEC','NEC','NEC']


		FOR NTH = 0L, N_ELEMENTS(_FILES)-1 DO BEGIN
			FILES = FILE_SEARCH(DIR_SAVE + '!MONTH_*' + _FILES[NTH] + '.SAVE')
			IF N_ELEMENTS(FILES) GE 1 THEN BEGIN
				SPECIAL_SCALE = _SPECIAL_SCALE[NTH]
				PAL = _PALS[NTH]
				APROD = PRODS[NTH]
				MAP = MAPS[NTH]
				STRUCT_SD_2PNG,FILES,DIR_OUT=DIR_BROWSE,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,SPECIAL_SCALE=SPECIAL_SCALE,PAL=PAL
				PFILES = FILE_SEARCH(DIR_BROWSE + '!MONTH_*' + _FILES[NTH] + '.PNG')
				ROWS = 4
				COLS = 4
				PNGFILE1 = DIR_BROWSE + '!MONTH' + _FILES[NTH] + '-COMPOSITE.PNG'
				IMAGE_WELD_PAGE,FILES=PFILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=pngfile1,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
				ROWS = 1
				COLS = 12
				PNGFILE2 = DIR_BROWSE + '!MONTH' + _FILES[NTH] + '-COMPOSITE-1_12.PNG'
				IMAGE_WELD_PAGE,FILES=PFILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=pngfile2,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
				PSFILE1 = DIR_PLOTS + '!MONTH' + _FILES[NTH] + '-COMPOSITE.PS'
				PSFILE2 = DIR_PLOTS + '!MONTH' + _FILES[NTH] + '-COMPOSITE-1_12.PS'
			ENDIF

			IF APROD EQ 'PPD' THEN TITLE = UNITS('PPD')
			IF APROD EQ 'RATIO' THEN TITLE = 'Ratio OPAL:VGPM2a'

			IF FILE_TEST(PNGFILE1) EQ 0 THEN GOTO, IMAGE2
			IMAGE = READ_PNG(PNGFILE1,R,G,B)
			SZ=SIZE(IMAGE,/STRUCT)
			TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
	  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
	  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
	;  	===> Postscript (idl) has 1000/cm resolution
	;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
	   	XSIZE = DOUBLE(2.54*(PX_IMAGE/300.))
	   	YSIZE = DOUBLE(2.54*(PY_IMAGE/300.))
	;		===> Dimensions of postscript page
	 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
			IF MAP EQ 'NEC' THEN XOFFSET = -3
	  	IF MAP EQ 'NEC' THEN YOFFSET = 26.5
	    IF MAP EQ 'NEC' THEN SCALE = 0.67

	;		===> Set up the postscript device
	    OLDDEVICE= !D.NAME  ; Get present graphics device
	    olddevice= !d.name  ; Get present graphics device
	  	!P.FONT = 0
	    SET_PLOT,'ps'
	    DEVICE,FILENAME=psfile1
			DEVICE,/COLOR
	 		CALL_PROCEDURE,PAL,R,G,B
	 		TVLCT,R,G,B
	 		COLOR=1
			DEVICE,BITS_PER_PIXEL=8
			DEVICE,/HELVETICA
			DEVICE,/LANDSCAPE
	    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
	    TV,IMAGE, TRUE=TRUE_COLOR

			X = 0.035
			Y = 0.96
			IF MAP EQ 'NEC' THEN IX = 0.25
			IF MAP EQ 'NEC' THEN IY = -0.25
			IF MAP EQ 'NEC' THEN POSITION = [0.05, 0.23,0.95, 0.245]
			CHARSIZE  = 2.75
			COLOR     = 0
			CHARTHICK = 1
			ALIGN     = 0.5
			XYOUTS,X,Y,'Jan', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+IX,Y,'Feb', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+2*IX,Y,'Mar', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+3*IX,Y,'Apr', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X,Y+IY,'May', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+IX,Y+IY,'Jun', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+2*IX,Y+IY,'Jul', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+3*IX,Y+IY,'Aug', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X,Y+2*IY,'Sep', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+IX,Y+2*IY,'Oct', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+2*IX,Y+2*IY,'Nov', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+3*IX,Y+2*IY,'Dec', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL

			LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL=PAL,CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
	    DEVICE,/CLOSE
	    SET_PLOT,olddevice

			IMAGE2:
			IF FILE_TEST(PNGFILE2) EQ 0 THEN CONTINUE
			IMAGE = READ_PNG(PNGFILE2,R,G,B)
			SZ=SIZE(IMAGE,/STRUCT)
			TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
	  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
	  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
	;  	===> Postscript (idl) has 1000/cm resolution
	;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
	   	XSIZE = DOUBLE(2.54*(PX_IMAGE/300.))
	   	YSIZE = DOUBLE(2.54*(PY_IMAGE/300.))
	;		===> Dimensions of postscript page
	 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
			IF MAP EQ 'NEC' THEN XOFFSET = 10
	  	IF MAP EQ 'NEC' THEN YOFFSET = 27.5
	    IF MAP EQ 'NEC' THEN SCALE = 0.245

	;		===> Set up the postscript device
	    OLDDEVICE= !D.NAME  ; Get present graphics device
	    olddevice= !d.name  ; Get present graphics device
	  	!P.FONT = 0
	    SET_PLOT,'ps'
	    DEVICE,FILENAME=psfile2
			DEVICE,/COLOR
	 		CALL_PROCEDURE,PAL,R,G,B
	 		TVLCT,R,G,B
	 		COLOR=1
			DEVICE,BITS_PER_PIXEL=8
			DEVICE,/HELVETICA
			DEVICE,/LANDSCAPE
	    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
	    TV,IMAGE, TRUE=TRUE_COLOR

			X = 0.010 & Y = 0.85 & IX = 0.0838
			POSITION = [0.925, 0.05,0.93, 0.95]
			CHARSIZE  = 2.75
			COLOR     = 0
			CHARTHICK = 1
			ALIGN     = 0.5
			XYOUTS,X+0*IX,Y, 'Jan', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+1*IX,Y, 'Feb', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+2*IX,Y, 'Mar', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+3*IX,Y, 'Apr', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+4*IX,Y, 'May', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+5*IX,Y, 'Jun', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+6*IX,Y, 'Jul', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+7*IX,Y, 'Aug', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+8*IX,Y, 'Sep', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+9*IX,Y, 'Oct', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+10*IX,Y,'Nov', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL
			XYOUTS,X+11*IX,Y,'Dec', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL

	;		LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/RIGHT,/VERTICAL,TITLE=' ',/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
	    DEVICE,/CLOSE
	    SET_PLOT,olddevice
    ENDFOR

stop


;		Figure 21 GRAD_MAG CHL Annual composite figure
		FILES = FILE_SEARCH(DIR_SAVE + '!Y_*-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.SAVE')
;		STRUCT_SD_2PNG,FILES,DIR_OUT=DIR_OUT,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE,SPECIAL_SCALE='LOW_1'
		FILES = FILE_SEARCH(DIR_OUT+'!Y_*-SEAWIFS-REPRO5-NEC-*CHLOR_A-GRAD_MAG_RATIO-MEAN.PNG')
		ROWS = 4
		COLS = 3
		PNGFILE = DIR_OUT  + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE.PNG'
;		IMAGE_WELD_PAGE,FILES=FILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=pngfile,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
		ROWS = 1
		COLS = N_ELEMENTS(FILES)
		PNGFILE = DIR_OUT  + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE-1_9.PNG'
;		IMAGE_WELD_PAGE,FILES=FILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=pngfile,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM




;;;;;;;		YEARLY COMPOSITES
;;;;;;		PNGFILES = [DIR_OUT + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE.PNG',$
;;;;;;								DIR_OUT + 'Figure_22-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR-MEAN-COMPOSITE.PNG',$
;;;;;;								DIR_OUT + 'Figure_chl-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-OC4-MEAN-COMPOSITE.PNG']
;;;;;;		PSFILES  = [DIR_MANU + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE.PS',$
;;;;;;								DIR_MANU + 'Figure_22-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR_RATIO-MEAN-COMPOSITE.PS',$
;;;;;;								DIR_MANU + 'Figure_chl-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-OC4-MEAN-COMPOSITE.PS']
;;;;;;		SPECIAL_SCALES = ['LOW_1','','']
;;;;;;		PRODS = ['GRAD_MAG_RATIO','GRAD_DIR','CHLOR_A']
;;;;;;		MAPS = ['NEC','NEC','NEC']
;;;;;;		FOR NTH = 0L, N_ELEMENTS(PNGFILES)-1 DO BEGIN
;;;;;;			PNGFILE = PNGFILES[NTH]
;;;;;;			PSFILE  = PSFILES[NTH]
;;;;;;			SPECIAL_SCALE = SPECIAL_SCALES[NTH]
;;;;;;			APROD = PRODS[NTH]
;;;;;;			MAP = MAPS[NTH]
;;;;;;			IF APROD EQ 'GRAD_MAG' THEN TITLE = '!Eo!NC  km!E-1!N'
;;;;;;			IF APROD EQ 'GRAD_DIR' THEN TITLE = 'Gradient Direction'
;;;;;;			IF APROD EQ 'GRAD_MAG_RATIO' THEN TITLE = 'Chlorophyll Gradient Magnitude (ratio)'
;;;;;;			IF APROD EQ 'CHLOR_A'  THEN TITLE = UNITS('CHLOROPHYLL')
;;;;;;			IF APROD EQ 'SST'      THEN TITLE = UNITS('SST')
;;;;;;
;;;;;;			IMAGE = READ_PNG(PNGFILE,R,G,B)
;;;;;;			SZ=SIZE(IMAGE,/STRUCT)
;;;;;;			TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
;;;;;;	  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
;;;;;;	  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
;;;;;;	;  	===> Postscript (idl) has 1000/cm resolution
;;;;;;	;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
;;;;;;	   	XSIZE = DOUBLE(2.54*(PX_IMAGE/300.))
;;;;;;	   	YSIZE = DOUBLE(2.54*(PY_IMAGE/300.))
;;;;;;	;		===> Dimensions of postscript page (LANDSCAPE)
;;;;;;	 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
;;;;;;			XOFFSET = -1
;;;;;;	  	YOFFSET = 26.5
;;;;;;	    SCALE = 0.67
;;;;;;	;		===> Dimensions of postscript page (PORTRAIT)
;;;;;;	 		HEIGHT = 26.9  &   WIDTH = 20.5  ; MAX SIZE
;;;;;;			XOFFSET = 1
;;;;;;	  	YOFFSET = -1
;;;;;;	    SCALE = 0.67
;;;;;;
;;;;;;	;		===> Set up the postscript device
;;;;;;	    OLDDEVICE= !D.NAME  ; Get present graphics device
;;;;;;	  	!P.FONT = 0
;;;;;;	    SET_PLOT,'ps'
;;;;;;	    DEVICE,FILENAME=psfile
;;;;;;			DEVICE, /PORTRAIT
;;;;;;			DEVICE,/COLOR
;;;;;;	 		CALL_PROCEDURE,PAL,R,G,B
;;;;;;	 		TVLCT,R,G,B
;;;;;;	 		COLOR=1
;;;;;;			DEVICE,BITS_PER_PIXEL=8
;;;;;;			DEVICE,/HELVETICA
;;;;;;	    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
;;;;;;	    TV,IMAGE, TRUE=TRUE_COLOR
;;;;;;
;;;;;;			X = 0.06
;;;;;;			Y = 0.97
;;;;;;			IX = 0.335
;;;;;;			IY = -0.25
;;;;;;			CHARSIZE 	= 2.75
;;;;;;			COLOR     = 0
;;;;;;			CHARTHICK = 1
;;;;;;			ALIGN     = 0.5
;;;;;;			XYOUTS,X,Y,'1998', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+IX,Y,'1999', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+2*IX,Y,'2000', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X,Y+IY,'2001', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+IX,Y+IY,'2002', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+2*IX,Y+IY,'2003', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X,Y+2*IY,'2004', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+IX,Y+2*IY,'2005', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+2*IX,Y+2*IY,'2006', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;
;;;;;;			IF APROD EQ 'GRAD_DIR' THEN BEGIN
;;;;;;				CHARSIZE = 2.5
;;;;;;				LABELS_COMPASS=['N','E','S','W']
;;;;;;				IF MAP EQ 'NEC' 	 THEN BEGIN
;;;;;;					POLY_X = [0.87,0.87,1.01,1.01,0.87] & POLY_Y = [0.25,0.345,0.345,0.25,0.25]
;;;;;;					CIR_POS = [0.91,0.265,0.975,0.325]
;;;;;;					XYOUTS,0.675,0.225,TITLE,CHARSIZE=CHARSIZE,/NORMAL,FONT='HELVETICA'
;;;;;;				ENDIF
;;;;;;				IF MAP EQ 'EQ_NWA' THEN BEGIN
;;;;;;					POLY_X = [0.91,0.91,1.0,1.0,0.91] & POLY_Y = [0.325,0.435,0.435,0.325,0.325]
;;;;;;					CIR_POS = [0.93,0.345,1.0,0.415]
;;;;;;					XYOUTS,0.8,0.3,TITLE,CHARSIZE=CHARSIZE,/NORMAL,FONT='HELVETICA'
;;;;;;				ENDIF
;;;;;;				POLYFILL,POLY_X ,POLY_Y,COLOR=255,/NORMAL
;;;;;;				COLOR_CIRCLE ,LABELS_COMPASS,CHARSIZE=30,POSITION=CIR_POS,FONT='HELVETICA'
;;;;;;			ENDIF ELSE $
;;;;;;		;	LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
;;;;;;	    DEVICE,/CLOSE
;;;;;;	    SET_PLOT,olddevice
;;;;;;		ENDFOR
;;;;;;
;;;;;;		PNGFILES = [DIR_OUT + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE-1_9.PNG',$
;;;;;;								DIR_OUT + 'Figure_22-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR-MEAN-COMPOSITE-1_9.PNG',$
;;;;;;								DIR_OUT + 'Figure_chl-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-OC4-MEAN-COMPOSITE-1_9.PNG']
;;;;;;		PSFILES  = [DIR_MANU + 'Figure_21-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE-1_9.PS',$
;;;;;;								DIR_MANU + 'Figure_22-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR_RATIO-MEAN-COMPOSITE-1_9.PS',$
;;;;;;								DIR_MANU + 'Figure_chl-!Y-SEAWIFS-REPRO5-NEC-CHLOR_A-OC4-MEAN-COMPOSITE-1_9.PS']
;;;;;;		SPECIAL_SCALES = ['LOW_1','','']
;;;;;;		PRODS = ['GRAD_MAG_RATIO','GRAD_DIR','CHLOR_A']
;;;;;;		MAPS = ['NEC','NEC','NEC']
;;;;;;		FOR NTH = 0L, N_ELEMENTS(PNGFILES)-1 DO BEGIN
;;;;;;			PNGFILE = PNGFILES[NTH]
;;;;;;			PSFILE  = PSFILES[NTH]
;;;;;;			SPECIAL_SCALE = SPECIAL_SCALES[NTH]
;;;;;;			APROD = PRODS[NTH]
;;;;;;			MAP = MAPS[NTH]
;;;;;;			IF APROD EQ 'GRAD_MAG' THEN TITLE = '!Eo!NC  km!E-1!N'
;;;;;;			IF APROD EQ 'GRAD_DIR' THEN TITLE = 'Gradient Direction'
;;;;;;			IF APROD EQ 'GRAD_MAG_RATIO' THEN TITLE = 'Chlorophyll Gradient Magnitude (ratio)'
;;;;;;			IF APROD EQ 'CHLOR_A'  THEN TITLE = UNITS('CHLOROPHYLL')
;;;;;;			IF APROD EQ 'SST'      THEN TITLE = UNITS('SST')
;;;;;;
;;;;;;			IMAGE = READ_PNG(PNGFILE,R,G,B)
;;;;;;			SZ=SIZE(IMAGE,/STRUCT)
;;;;;;			TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
;;;;;;	  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
;;;;;;	  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
;;;;;;	;  	===> Postscript (idl) has 1000/cm resolution
;;;;;;	;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
;;;;;;	   	XSIZE = DOUBLE(2.54*(PX_IMAGE/300.))
;;;;;;	   	YSIZE = DOUBLE(2.54*(PY_IMAGE/300.))
;;;;;;	;		===> Dimensions of postscript page (LANDSCAPE)
;;;;;;	 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
;;;;;;			XOFFSET = -3
;;;;;;	  	YOFFSET = 26.5
;;;;;;	    SCALE = 0.67
;;;;;;	;		===> Dimensions of postscript page (PORTRAIT)
;;;;;;;	 		HEIGHT = 26.9  &   WIDTH = 20.5  ; MAX SIZE
;;;;;;;			XOFFSET = 1
;;;;;;;	  	YOFFSET = 15
;;;;;;;	    SCALE = 0.24
;;;;;;
;;;;;;			IF MAP EQ 'NEC' THEN XOFFSET = 10   & IF MAP EQ 'EQ_NWA' THEN XOFFSET = 5
;;;;;;	  	IF MAP EQ 'NEC' THEN YOFFSET = 27.5 & IF MAP EQ 'EQ_NWA' THEN YOFFSET = 29.5
;;;;;;	    IF MAP EQ 'NEC' THEN SCALE = 0.33   & IF MAP EQ 'EQ_NWA' THEN SCALE = 0.265
;;;;;;
;;;;;;	;		===> Set up the postscript device
;;;;;;	    OLDDEVICE= !D.NAME  ; Get present graphics device
;;;;;;	  	!P.FONT = 0
;;;;;;	    SET_PLOT,'ps'
;;;;;;	    DEVICE,FILENAME=psfile
;;;;;;			DEVICE, /LANDSCAPE
;;;;;;			DEVICE,/COLOR
;;;;;;	 		CALL_PROCEDURE,PAL,R,G,B
;;;;;;	 		TVLCT,R,G,B
;;;;;;	 		COLOR=1
;;;;;;			DEVICE,BITS_PER_PIXEL=8
;;;;;;			DEVICE,/HELVETICA
;;;;;;	    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
;;;;;;	    TV,IMAGE, TRUE=TRUE_COLOR
;;;;;;
;;;;;;			X = 0.017
;;;;;;			Y = 0.85
;;;;;;			IX = 0.1115
;;;;;;			CHARSIZE 	= 2.75
;;;;;;			COLOR     = 0
;;;;;;			CHARTHICK = 1
;;;;;;			ALIGN     = 0.5
;;;;;;			XYOUTS,X+0*IX,Y,'1998', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+1*IX,Y,'1999', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+2*IX,Y,'2000', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+3*IX,Y,'2001', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+4*IX,Y,'2002', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+5*IX,Y,'2003', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+6*IX,Y,'2004', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+7*IX,Y,'2005', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;			XYOUTS,X+8*IX,Y,'2006', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL,FONT='HELVETICA'
;;;;;;
;;;;;;;			IF APROD EQ 'GRAD_DIR' THEN BEGIN
;;;;;;;				CHARSIZE = 2.5
;;;;;;;				LABELS_COMPASS=['N','E','S','W']
;;;;;;;				IF MAP EQ 'NEC' 	 THEN BEGIN
;;;;;;;					POLY_X = [0.87,0.87,1.01,1.01,0.87] & POLY_Y = [0.25,0.345,0.345,0.25,0.25]
;;;;;;;					CIR_POS = [0.91,0.265,0.975,0.325]
;;;;;;;					XYOUTS,0.675,0.225,TITLE,CHARSIZE=CHARSIZE,/NORMAL,FONT='HELVETICA'
;;;;;;;				ENDIF
;;;;;;;				IF MAP EQ 'EQ_NWA' THEN BEGIN
;;;;;;;					POLY_X = [0.91,0.91,1.0,1.0,0.91] & POLY_Y = [0.325,0.435,0.435,0.325,0.325]
;;;;;;;					CIR_POS = [0.93,0.345,1.0,0.415]
;;;;;;;					XYOUTS,0.8,0.3,TITLE,CHARSIZE=CHARSIZE,/NORMAL,FONT='HELVETICA'
;;;;;;;				ENDIF
;;;;;;;				POLYFILL,POLY_X ,POLY_Y,COLOR=255,/NORMAL
;;;;;;;				COLOR_CIRCLE ,LABELS_COMPASS,CHARSIZE=30,POSITION=CIR_POS,FONT='HELVETICA'
;;;;;;;			ENDIF ELSE $
;;;;;;;			LEG=COLOR_BAR_SCALE(PROD=APROD,POSITION=POSITION,PAL='PAL_SW3',CHARSIZE=3,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE=SPECIAL_SCALE,FONT='HELVETICA')
;;;;;;	    DEVICE,/CLOSE
;;;;;;	    SET_PLOT,olddevice
;;;;;;		ENDFOR



	;	ENDFOR



;		Figure 24 SST and CHL front examples
		SAVEFILES = DIR_SAVE + ['!T_200105030701-AVHRR-N16-S3-CW_CD-NEC-SST.SAVE',$
														'!T_200105030701-AVHRR-N16-S3-CW_CD-NEC-SST-GAUSS_5_SIG_0_6-SOBEL-GRAD_MAG.SAVE',$
														'!S_20001014170917-SEAWIFS-OV2-MLAC-REPRO5-NEC-CHLOR_A.save',$
														'!S_20001014170917-SEAWIFS-OV2-MLAC-REPRO5-NEC-CHLOR_A-MF3_1D_5PT_E0_693-SOBEL-GRAD_MAG_RATIO.SAVE']
		SPECIAL_SCALES = ['','HIGH','','HIGH']
		FOR NTH = 0L, N_ELEMENTS(SAVEFILES)-1 DO BEGIN
		;	STRUCT_SD_2PNG,SAVEFILES[NTH],DIR_OUT=DIR_OUT,/ADD_LAND,/ADD_COAST,/OVERWRITE,SPECIAL_SCALE=SPECIAL_SCALES[NTH]
		ENDFOR
		PNGFILE   = DIR_OUT +   'Figure_24-!D-CHL-SST-FRONTS-COMPOSITE.PNG'
		PNGFILES  = DIR_OUT +  ['!T_200105030701-AVHRR-N16-S3-CW_CD-NEC-SST.PNG',$
														'!T_200105030701-AVHRR-N16-S3-CW_CD-NEC-SST-GAUSS_5_SIG_0_6-SOBEL-GRAD_MAG.PNG',$
														'!S_20001014170917-SEAWIFS-OV2-MLAC-REPRO5-NEC-CHLOR_A.PNG',$
														'!S_20001014170917-SEAWIFS-OV2-MLAC-REPRO5-NEC-CHLOR_A-MF3_1D_5PT_E0_693-SOBEL-GRAD_MAG_RATIO.PNG']
		ROWS = 2
		COLS = 2
	;	IMAGE_WELD_PAGE,FILES=PNGFILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=pngfile,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM
		PSFILE    = DIR_PLOTS + 'Figure_24-!D-CHL-SST-FRONTS-COMPOSITE.PS'

		IMAGE = READ_PNG(PNGFILE,R,G,B)
		SZ=SIZE(IMAGE,/STRUCT)
		TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
;  	===> Postscript (idl) has 1000/cm resolution
;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
   	XSIZE = DOUBLE(2.54*(PX_IMAGE/300.))
   	YSIZE = DOUBLE(2.54*(PY_IMAGE/300.))
;		===> Dimensions of postscript page (LANDSCAPE)
 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
		XOFFSET = -3
  	YOFFSET = 26.5
    SCALE = 0.67
;		===> Dimensions of postscript page (PORTRAIT)
 		HEIGHT = 26.9  &   WIDTH = 20.5  ; MAX SIZE
		XOFFSET = 1.5
  	YOFFSET = 5
    SCALE = 1.07

;		===> Set up the postscript device
    OLDDEVICE= !D.NAME  ; Get present graphics device
  	!P.FONT = 0
    SET_PLOT,'ps'
    DEVICE,FILENAME=psfile
		DEVICE, /PORTRAIT
		DEVICE,/COLOR
 		CALL_PROCEDURE,PAL,R,G,B
 		TVLCT,R,G,B
 		COLOR=1
		DEVICE,BITS_PER_PIXEL=8
		DEVICE,/HELVETICA
    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
    TV,IMAGE, TRUE=TRUE_COLOR

	;	XYOUTS,X+2*IX,Y+2*IY,'2006', ALIGN=ALIGN, CHARSIZE=CHARSIZE, COLOR=COLOR, CHARTHICK=CHARTHICK,/NORMAL

		CHARSIZE = 1.25
		TITLE = UNITS('SST')
		LEG=COLOR_BAR_SCALE(PROD='SST',POSITION=[0.01,0.98,0.3,0.995],PAL='PAL_SW3',CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA')
		TITLE = 'Gradient Magnitude !C(!Eo!NC  km!E-1!N)'
		LEG=COLOR_BAR_SCALE(PROD='GRAD_MAG',POSITION=[0.53,0.98,0.8,0.995],PAL='PAL_SW3',CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE='HIGH',FONT='HELVETICA')
		TITLE = UNITS('CHLOR_A')
		LEG=COLOR_BAR_SCALE(PROD='CHLOR_A',POSITION=[0.02, 0.475,0.3, 0.49],PAL='PAL_SW3',CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT,FONT='HELVETICA')
		TITLE = 'Gradient Magnitude !C(ratio)'
		LEG=COLOR_BAR_SCALE(PROD='GRAD_MAG_RATIO',POSITION=[0.52,0.475,0.79,0.49],PAL='PAL_SW3',CHARSIZE=CHARSIZE,/BOTTOM,TITLE=TITLE,/NO_UNIT, SPECIAL_SCALE='HIGH',FONT='HELVETICA')
		DEVICE,/CLOSE
    SET_PLOT,olddevice

;		FIGURE 23: Monthly Chlorophyll examples
		SAVEFILES = [DIR_SAVE  + '!M_200010-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.SAVE', $
								 DIR_SAVE  + '!M_200010-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR-MEAN.SAVE', $
								 DIR_SAVE  + '!M_199807-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.SAVE', $
								 DIR_SAVE  + '!M_200007-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.SAVE']
		PNGFILES  = [DIR_OUT   + '!M_200010-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.PNG', $
								 DIR_OUT   + '!M_200010-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_DIR-MEAN.PNG', $
								 DIR_OUT   + '!M_199807-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.PNG', $
								 DIR_OUT   + '!M_200007-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN.PNG']
		OUTFILE = DIR_OUT + 'FIGURE_23-!M-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE.PNG'
		PSFILE 	 = DIR_PLOTS + 'FIGURE_23-!M-SEAWIFS-REPRO5-NEC-CHLOR_A-GRAD_MAG_RATIO-MEAN-COMPOSITE.PS'
		STRUCT_SD_2PNG,SAVEFILES,DIR_OUT=DIR_OUT,/ADD_LAND,/ADD_COAST,MISS_COLOR=0,/OVERWRITE

		ROWS = 2
		COLS = 2
		IMAGE_WELD_PAGE,FILES=PNGFILES,ROWS=ROWS,COLS=COLS,PAL=PAL,PNGFILE=OUTFILE,SPACE=space,PX=px,py=py,BACKGROUND=BACKGROUND,/NOTRIM

		IMAGE = READ_PNG(OUTFILE,r,g,b)
		SZ=SIZE(IMAGE,/STRUCT)
		TRUE_COLOR  = SZ.N_DIMENSIONS EQ 3
  	PX_IMAGE = 1.0*SZ.DIMENSIONS(0+TRUE_COLOR)
  	PY_IMAGE = 1.0*SZ.DIMENSIONS(1+TRUE_COLOR)
;  ===> Postscript (idl) has 1000/cm resolution
;  	A 2400 pixel wide PCX or PNG file printed at 300dpi  will be 8 inches wide or 2.54cm*8
   	xsize = DOUBLE(2.54*(PX_IMAGE/300.))    &   ysize = DOUBLE(2.54*(PY_IMAGE/300.))
;		===> Dimensions of postscript page (LANDSCAPE)
 		HEIGHT = 20.5  &   WIDTH = 26.9  ; MAX SIZE
		XOFFSET = -3
  	YOFFSET = 26.5
    SCALE = 0.67
;		===> Dimensions of postscript page (PORTRAIT)
 		HEIGHT = 26.9  &   WIDTH = 20.5  ; MAX SIZE
		XOFFSET = 1.5
  	YOFFSET = 5
    SCALE = 1.07

;		===> Set up the postscript device
    OLDDEVICE= !D.NAME  ; Get present graphics device
  	!P.FONT = 0
    SET_PLOT,'ps'
    DEVICE,FILENAME=psfile
		DEVICE, /PORTRAIT
		DEVICE,/COLOR
 		CALL_PROCEDURE,PAL,R,G,B
 		TVLCT,R,G,B
 		COLOR=1
		DEVICE,BITS_PER_PIXEL=8
		DEVICE,/HELVETICA
    DEVICE, XOFFSET=xoffset, YOFFSET=yoffset, XSIZE=xsize, YSIZE=ysize, SCALE_FACTOR=scale
    TV,IMAGE, TRUE=TRUE_COLOR


    DEVICE,/CLOSE
    SET_PLOT,olddevice

		STOP
		SKIP_SEA_COMP:
	ENDIF


END; #####################  End of Routine ################################



