; $ID:	MAPS_LONLAT_GRID_DEMO.PRO,	2020-07-01-12,	USER-KJWH	$
; 
PRO MAPS_LONLAT_GRID_DEMO
; #########################################################################; 
;+
; PURPOSE:  THIS IS A DEMO FOR  MAPS_LONLAT_GRID 
;           [SHOWING HOW TO SAVE TIME BY STORING DATA IN A STRUCT]

;
; CATEGORY: MAPS;
;
; MODIFICATION HISTORY:
;     FEB 4, 2016  WRITTEN BY: J.E. O'REILLY
;     
;-
; #########################################################################

;**************************************
ROUTINE_NAME  = 'MAPS_LONLAT_GRID_DEMO'
;**************************************
; S_20091118170500-MODISA-1KM-R2015-L2.nc
;FILE = FLS(!S.FILES + 'V2016002164823.L2_NPP.GOM_MAB.nc')
FILE = FLS(!S.FILES + 'S_20091118170500-MODISA-1KM-R2015-L2.nc')
SD = READ_NC(FILE,PROD=['longitude','latitude','chlor_a','par'])

IF STRUCT_HAS(SD,'SD.CHLOR_A') THEN BEGIN
  CHL = SD.SD.CHLOR_A.IMAGE  & OK = WHERE(CHL EQ SD.SD.CHLOR_A._FILLVALUE._DATA[0], COUNT) & IF COUNT GE 1 THEN CHL[OK] = MISSINGS(0.0)
ENDIF;IF STRUCT_HAS(SD,'SD.CHLOR_A') THEN BEGIN

IF STRUCT_HAS(SD,'SD.PAR') THEN BEGIN
  PAR = SD.SD.PAR.IMAGE      & OK = WHERE(PAR EQ SD.SD.PAR._FILLVALUE._DATA[0],COUNT,COMPLEMENT=COMP)  & IF COUNT GE 1 THEN PAR[OK] = MISSINGS(0.0) & PAR(COMP) = PAR(COMP)*SD.SD.PAR.SCALE_FACTOR._DATA[0] + SD.SD.PAR.ADD_OFFSET._DATA[0]
ENDIF; IF STRUCT_HAS(SD,'SD.PAR') THEN BEGIN

IF STRUCT_HAS(SD,'SD.LONGITUDE') THEN BEGIN
  LONS   = SD.SD.LONGITUDE.IMAGE
ENDIF;IF STRUCT_HAS(SD,'SD.LONGITUDE') THEN BEGIN

IF STRUCT_HAS(SD,'SD.LATITUDE') THEN BEGIN
  LATS   = SD.SD.LATITUDE.IMAGE
ENDIF; IF STRUCT_HAS(SD,'SD.LATITUDE') THEN BEGIN

;===> REMAP THE CHL DATA
TIC
CH =  MAPS_LONLAT_GRID(CHL, MAP_OUT='NEC', LON=LONS, LAT=LATS, TRIANGLES=TRIANGLES, /INIT,STRUCT=STRUCT)
TOC
;SAVE,FILENAME = 'MAPS_LONLAT_GRID_STRUCT.SAV',STRUCT,/VERBOSE
IMGR, CH, MAP='NEC', PROD='CHLOR_A', DELAY=4 ; DISPLAY THE MAPPED CHL DATA
TIC
CH =  MAPS_LONLAT_GRID(CHL, MAP_OUT='NEC', /INIT,STRUCT=STRUCT)
TOC
IMGR, CH, MAP='NEC', PROD='CHLOR_A', DELAY=4 ; Display the mapped CHL data

TIC
PR =  MAPS_LONLAT_GRID(PAR, MAP_OUT='NEC', /INIT,STRUCT=STRUCT)
TOC
IMGR, PR, MAP='NEC', PROD='PAR', DELAY=4 ; Display the mapped PAR data









END; #####################  END OF ROUTINE ################################
