PRO MASK_COAST,FILES,THICK=THICK
FILE='D:\SEAWIFS-NEC\stats_browse\!STUDY-SEAWIFS-REPRO5-NEC-PXY_1024_1024-CLDICE-MEAN-LEG.PNG'
FN=PARSE_IT(FILE,/ALL)
IF STRUPCASE(FN.EXT) EQ 'PNG' THEN BEGIN
	IMAGE=READ_PNG(FILE,R,G,B)
	STOP



ENDIF







END