; $ID:	MORPH_GRADIENT_DEMO.PRO,	2020-06-26-15,	USER-KJWH	$
PRO MORPH_GRADIENT_DEMO
MAP='NEC'
IF MAP EQ 'NEC' THEN BEGIN
  	PX = 1024L & PY=1024L & 	LAND = READALL('D:\IDL\IMAGES\MASK_NEC.PNG') & OK_LAND = WHERE(LAND NE 255)
  ENDIF

IM=READALL('G:\SEAWIFS\BROWSE\S1997265163901_HNSG_SEAWIFS_REPRO3_NARR_NEC_CHLOR_A_LEG.PNG')
IM=IM(0:PX-1,0:PY-1)

IM(OK_LAND) = 255

;Define disc radius
r = 2

;Create a binary disc of given radius.
disc = SHIFT(DIST(2*r+1), r, r) LE r

bdisc = MORPH_GRADIENT(im, disc)


SLIDEW,bdisc
;TVSCL, bdisc, 360, 280


;Show thresholded edges
;XYOUTS, 180, 265, 'Threshold Edges', ALIGNMENT=.5, /DEVICE
;TVSCL, bdisc LT 100, 20, 20

 COPY=LAND
 OK = WHERE(LAND EQ 255)
 COPY[OK] = 255
 OK = WHERE(BDISC GT 8 AND BDISC LT 64)
 COPY[OK] = 0
 TV,COPY


STOP

END
