; $ID:	NEFSC_WEBSITE_MAIN.PRO,	2020-07-08-15,	USER-KJWH	$
;+
; This Program is an example TEMPLATE for a main routine involving several sequential processing steps


; HISTORY:
;     Oct 15, 2004  Written by: J.E. O'Reilly
;-
; *************************************************************************

PRO NEFSC_WEBSITE_MAIN
  ROUTINE_NAME='NEFSC_WEBSITE_MAIN'

	DISK = 'D:'
  DELIM=DELIMITER(/PATH)
  PATH = DISK+DELIM + 'PROJECTS\NEFSC_WEBSITE'+DELIM

	MAP = 'NEC'

 	LANDMASK = READALL('D:\IDL\IMAGES\MASK_NEC.PNG')
  OK_LAND = WHERE(LANDMASK NE 255)
  OK_COAST = WHERE(LANDMASK EQ 0)
  MASK = LANDMASK & MASK(*,*) = 0
  MASK(OK_LAND) = 1

; **************************************
; Directories
; Edit these as needed

	DIR_DATA = path+'DATA'+delim
  DIR_SAVE = path+'SAVE'+delim
  DIR_FLT  = path+'FLT'+delim
  DIR_PLOTS = path+'PLOTS'+delim
  DIR_ERRORS = path+'ERRORS'+delim
  DIR_TEMP   = path+'TEMP'+delim
  DIR_MOVIES   = path+'MOVIES'+delim

	DIR_ALL = [DIR_DATA,DIR_SAVE,DIR_PLOTS,DIR_ERRORS,DIR_FLT, DIR_TEMP, DIR_MOVIES]


; ===> FILES
	PNG_FILES = DIR_PLOTS + 'template.csv'
	SAVE_FILE  = DIR_SAVE  + '*.save'



; ****************************
; Set up color system defaults
	SETCOLOR



; ********************************************************************************
; ***** U S E R    S W I T C H E S  Controlling which Processing STEPS to do *****
; ********************************************************************************
;	0 (Do not do the step)
;	1 (Do the step)
; 2 (Do the step and OVERWRITE any output if it alread exists)

; ================>
; Switches controlling which Processing STEPS to do:
	DO_CHECK_DIRS = 1 ; GOOD IDEA TO ALWAYS KEEP THIS SWITCH ON


  DO_LATLON_MAPGEN 						= 0
  DO_SAVE2FLT									=	0
  DO_SST_PNG_EDIT 						=	0
  DO_CHL_STUDY_MEAN_EDIT			=	2
  DO_PPD_YEAR_MEAN_EDIT			  = 0

; MOVIES
 	DO_SST_DEMO_GOM_SPRING_BLOOM			  = 0
 	DO_SST_DEMO_MAB_UPWELLING           = 0
 	DO_SST_DEMO_MAB_SUMMER_BLOOM				= 0
 	DO_SST_DEMO_WCR_ADVECTION						= 0



; *********************************************
; ******** C H E C K   D I R S  ***************
; *********************************************
  IF DO_CHECK_DIRS GE 1 THEN BEGIN
    PRINT, 'S T E P:    DO_CHECK_DIRS'
    FOR N=0,N_ELEMENTS(DIR_ALL)-1 DO BEGIN
      AFILE = STRMID(DIR_ALL(N),0,STRLEN(DIR_ALL(N))-1)
      IF FILE_TEST(AFILE,/DIRECTORY) EQ 0L THEN FILE_MKDIR,AFILE
    ENDFOR
  ENDIF ; IF DO_CHECK_DIRS GE 1 THEN BEGIN
; |||||||||||||||||||||||||||||||||||||||||||||||||


; **************************************************************
 	IF DO_LATLON_MAPGEN GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_LATLON_MAPGEN GE 2
    PRINT, 'S T E P:    DO_LATLON_MAPGEN'
    LL = LATLON_MAPGEN(MAP='NEC', PX=1024,PY=1024) ; ALLOW ROUNDING
	  LON=LL.LON
	  LAT=LL.LAT
	  LATFILE = DIR_FLT + MAP+'-LAT.FLT'
	  OPENW,LUNOUT,LATFILE,/GET_LUN & WRITEU,LUNOUT,LAT & CLOSE,LUNOUT & FREE_LUN,LUNOUT

	  LONFILE = DIR_FLT + MAP+'-LON.FLT'
	  OPENW,LUNOUT,LONFILE,/GET_LUN & WRITEU,LUNOUT,LON & CLOSE,LUNOUT & FREE_LUN,LUNOUT

	ENDIF
;	|||||||||||||||||||||||||||||

; **************************************************************
 	IF DO_SAVE2FLT GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SAVE2FLT GE 2
    PRINT, 'S T E P:    DO_SAVE2FLT'
		FILES = FILELIST(DIR_SAVE+'*.SAVE')
		PRODS = 'SST'
		TARGETS = ['MEAN','MIN','MAX','SPAN']
		V=VALID_PERIOD_CODES(FILES)
		OK = WHERE(V NE MISSINGS(V))
		FILES=FILES[OK]
		FN=PARSE_IT(FILES,/ALL)
		OK=WHERE_IN(FN.STAT, TARGETS,COUNT)

		FILES=FILES[OK]
		FOR NTH=0,N_ELEMENTS(FILES)-1 DO BEGIN
			AFILE=FILES[NTH]
			FN=FILE_PARSE(AFILE)
			FLT_FILE = DIR_FLT + FN.NAME + '.FLT'
			IF FILE_TEST(FLT_FILE) EQ 0 OR OVERWRITE EQ 1 THEN STRUCT_SD_SAVE_2FLT,AFILE, DIR_OUT=DIR_FLT,MASK=MASK
 		ENDFOR
;		===> SRTM30
		FILES = DIR_SAVE+'SRTM30-NEC-PXY_1024_1024-BATHY-SMOOTH_5.SAVE'
		STRUCT_SD_SAVE_2FLT,FILES, DIR_OUT=DIR_FLT,MASK=MASK


	ENDIF
;	|||||||||||||||||||||||||||||


; **************************************************************
 	IF DO_SST_PNG_EDIT GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SST_PNG_EDIT GE 2
    PRINT, 'S T E P:    DO_SST_PNG_EDIT'
		FILES = FILELIST(DIR_PLOTS+'*SST*.PNG')
		TARGETS = ['MEAN','MIN','MAX','SPAN']
		OK=WHERE(STRPOS(FILES,'PAGE') EQ -1 AND STRPOS(FILES,'EDIT') EQ -1)
		FILES = FILES[OK]
		FN=PARSE_IT(FILES,/ALL)
		OK=WHERE_IN(FN.STAT, TARGETS,COUNT)
		FILES=FILES[OK]

;		LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
    FOR NTH=0,N_ELEMENTS(FILES)-1 DO BEGIN
    	AFILE=FILES[NTH]
    	FN = PARSE_IT(AFILE,/ALL)
    	OUTFILE = FN.DIR+FN.FIRST_NAME+'-EDIT.PNG'
    	IF FILE_TEST(OUTFILE) EQ 0 OR OVERWRITE GE 1 THEN BEGIN
 				IMAGE = READ_PNG(AFILE,R,G,B)
 				IMAGE(10:222,555:888) = IMAGE(2,550)

 				IF FN.STAT EQ 'MIN' THEN 	TXT = 'Annual Minimum'
 				IF FN.STAT EQ 'MAX' THEN 	TXT = 'Annual Maximum'
 				IF FN.STAT EQ 'MEAN' THEN TXT = 'Annual Mean'
 				IF FN.STAT EQ 'SPAN' THEN TXT = 'Annual Span!C(max-min)'
 				ZWIN,IMAGE
 			 	TV,IMAGE
 				FONT_TIMES
 				XYOUTS,0.250,0.843,TXT,CHARSIZE=5,ALIGN=0.5,COLOR=0,/NORMAL
 				NEW = TVRD()
 				ZWIN
 				WRITE_PNG,OUTFILE,NEW,R,G,B
			ENDIF
		ENDFOR
	ENDIF


; **************************************************************
 	IF DO_CHL_STUDY_MEAN_EDIT GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_CHL_STUDY_MEAN_EDIT GE 2
    PRINT, 'S T E P:    DO_CHL_STUDY_MEAN_EDIT'
		FILE = FILELIST(DIR_SAVE+'*!STUDY-SEAWIFS-REPRO4-NEC-CHLOR_A-MEAN.SAVE')
		STRUCT_SD_2PNG,FILE,DIR_OUT=DIR_PLOTS,/ADD_BATHY,BATHY_COLOR=254,OVERWRITE=1 ,/ADD_COLORBAR
    TXT ='SeaWiFS!CAnnual Mean'
		AFILE = DIR_PLOTS+ '!STUDY-SEAWIFS-REPRO4-NEC-PXY_1024_1024-CHLOR_A-MEAN-LEG.PNG'
  	FN = PARSE_IT(AFILE,/ALL)

  	OUTFILE = FN.DIR+FN.FIRST_NAME+'-EDIT.PNG'
  	IF FILE_TEST(OUTFILE) EQ 0 OR OVERWRITE GE 1 THEN BEGIN
;			IMAGE = READ_PNG(AFILE,R,G,B)
;			IMAGE(10:222,555:888) = IMAGE(2,550)
;			ZWIN,IMAGE
;		 	TV,IMAGE
;			FONT_TIMES
;			XYOUTS,0.250,0.843,TXT,CHARSIZE=5,ALIGN=0.5,COLOR=0,/NORMAL
;			NEW = TVRD()
;			ZWIN
;			WRITE_PNG,OUTFILE,NEW,R,G,B
;



		LEVELS =  [0.25,  0.5,  1.0,   2.0, 3.0,  5, 10]
		C_COLORS = [255, 255,  255,  254, 	253, 252, 251]
		C_THICK  = [1,   1,        1,     1,   1,   1,1]
		C_LABELS  = [1,   1,      1,     1,   1,   1,1]
	;	C_ANNOTATION = [1, 1,1,1]
		MIN_PTS = [200,  200, 200, 200, 200, 200,  20]
		MED = 5
		CON=STRUCT_SD_CONTOUR(FILE, LEVELS=levels,C_colors=C_colors, C_thick=C_thick,C_ANNOTATION=c_annotation,C_LABELS=C_LABELS,MIN_VALUE=MIN_VALUE, MIN_PTS=MIN_PTS,$
	    												/ADD_LAND,/ADD_COAST,/ADD_LAKES,/ADD_COLORBAR,ADD_EXTRA=ADD_EXTRA,MED=MED,C_CHARSIZE=0.9,/CONFILE )

  	PAL_SW3,R,G,B
;				ALTER 255 COLORS TO BE OFF WHITE
;				R(255)=224 & B(255) = 224 & G(255) = 224
		PNGFILE = DIR_PLOTS+FN.FIRST_NAME+'-LEG-CONTOUR.PNG'
		WRITE_PNG,PNGFILE,CON,R,G,B
;		CON=MAP_ADD_BATHY(CON,MAP='NEC',BATHS=[100],COLOR=0,LINESTYLE=1)
    CON=MAP_ADD_BATHY(CON,MAP='NEC',BATHS=[200],COLOR=0,LINESTYLE=1)
		PNGFILE = DIR_PLOTS+FN.FIRST_NAME+'-LEG-CONTOUR-BATH.PNG'
		WRITE_PNG,PNGFILE,CON,R,G,B



		ENDIF
  ENDIF ; IF DO_CHL_STUDY_MEAN_EDIT GE 1 THEN BEGIN
; |||||||||||||||||||||||||||||||||||||||||||||||||

; **************************************************************
 	IF DO_PPD_YEAR_MEAN_EDIT GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_PPD_YEAR_MEAN_EDIT GE 2
    PRINT, 'S T E P:    DO_PPD_YEAR_MEAN_EDIT'

		FILE = FILELIST(DIR_SAVE+'*!YEAR-PP-VGPM2A-NEC-PPD-MEAN.SAVE')
		FILE = FILELIST(DIR_SAVE+'!STUDY-PP-VGPM2A-NEC-PPD-MEAN.SAVE')
		FN=FILE_PARSE(FILE)
		FI=FILE_INFO(FILE)


;		STRUCT_SD_2PNG,FILE,DIR_OUT=DIR_PLOTS,/ADD_BATHY,BATHY_COLOR=254,/ADD_LAND,OVERWRITE=1 ,/ADD_COLORBAR
		LEVELS =  [0.4,0.6,    0.70, 1,   2,  3]
		C_COLORS = [254, 254,  253,  253, 252, 251]
		C_THICK  = [1,   1,        1,     1,   1,   1]
		C_LABELS  = [1,   1,      1,     1,   1,   1]
	;	C_ANNOTATION = [1, 1,1,1]
		MIN_PTS = [1000, 1000, 300, 300,400,500]
		MED = 5
		CON=STRUCT_SD_CONTOUR(FILE, LEVELS=levels,C_colors=C_colors, C_thick=C_thick,C_ANNOTATION=c_annotation,C_LABELS=C_LABELS,MIN_VALUE=MIN_VALUE, MIN_PTS=MIN_PTS,$
	    												/ADD_LAND,/ADD_COAST,/ADD_LAKES,/ADD_COLORBAR,ADD_EXTRA=ADD_EXTRA,MED=MED,C_CHARSIZE=0.9,/CONFILE )

  	PAL_SW3,R,G,B
;				ALTER 255 COLORS TO BE OFF WHITE
;				R(255)=224 & B(255) = 224 & G(255) = 224
		PNGFILE = DIR_PLOTS+FN.FIRST_NAME+'-LEG-CONTOUR.PNG'
		WRITE_PNG,PNGFILE,CON,R,G,B
;		CON=MAP_ADD_BATHY(CON,MAP='NEC',BATHS=[100],COLOR=0,LINESTYLE=1)
CON=MAP_ADD_BATHY(CON,MAP='NEC',BATHS=[200],COLOR=0,LINESTYLE=1)
		PNGFILE = DIR_PLOTS+FN.FIRST_NAME+'-LEG-CONTOUR-BATH.PNG'
		WRITE_PNG,PNGFILE,CON,R,G,B


STOP

		DATA = STRUCT_SD_READ(FILE,STRUCT=STRUCT)
	  ZWIN,   DATA
	  CALL_PROCEDURE,'MAP_'+STRUCT.MAP
	    FOR NTH=0,N_ELEMENTS(CON)-1 DO BEGIN
	    	STOP
				W=  (STR_BREAK(CON[NTH].LONLAT,';')) & LL=REFORM(STR_BREAK(W,'_'),  N_ELEMENTS(W),2)	& LL=TRANSPOSE(LL)
				PLOTS,LL(0,*),LL(1,*)
			ENDFOR
		IM=TVRD()
		ZWIN

		CON=STRUCT_SD_CONTOUR(FILE, LEVELS=levels,C_colors=C_colors, C_thick=C_thick,C_ANNOTATION=c_annotation,C_LABELS=C_LABELS,MIN_VALUE=MIN_VALUE, MIN_PTS=MIN_PTS,$
	    												/ADD_LAND,/ADD_COAST,/ADD_LAKES,/ADD_COLORBAR,ADD_EXTRA=ADD_EXTRA,MED=MED,C_CHARSIZE=0.9)

STOP
    TXT ='Annual Mean!CDaily PP';SeaWiFS + !CAVHRR + !CVGPM2a Model'
		AFILE = DIR_PLOTS+ '!YEAR-PP-VGPM2A-NEC-PXY_1024_1024-PPD-MEAN-LEG.PNG'
  	FN = PARSE_IT(AFILE,/ALL)
  	OUTFILE = FN.DIR+FN.FIRST_NAME+'-EDIT.PNG'
  	IF FILE_TEST(OUTFILE) EQ 0 OR OVERWRITE GE 1 THEN BEGIN
			IMAGE = READ_PNG(AFILE,R,G,B)
			IMAGE(10:222,555:888) = IMAGE(2,550)
			ZWIN,IMAGE
		 	TV,IMAGE
			FONT_TIMES
			XYOUTS,0.250,0.843,TXT,CHARSIZE=4.75,ALIGN=0.5,COLOR=0,/NORMAL
			NEW = TVRD()
			ZWIN
			WRITE_PNG,OUTFILE,NEW,R,G,B
		ENDIF
  ENDIF ; IF DO_PPD_YEAR_MEAN_EDIT GE 1 THEN BEGIN
; |||||||||||||||||||||||||||||||||||||||||||||||||



; **************************************************************
 	IF DO_SST_DEMO_GOM_SPRING_BLOOM GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SST_DEMO_GOM_SPRING_BLOOM GE 2
    PRINT, 'S T E P:    DO_SST_DEMO_GOM_SPRING_BLOOM'
		DRIVES=GET_DRIVE_NAMES()
		OK=WHERE(DRIVES.NAME EQ 'IOMEGA_HDD_13')
		DRIVE_IN = DRIVES[OK].DRIVE
		FOLDER = 'ts_images_save_chlor_a_nec\
	  FILES = FILE_SEARCH(DRIVE_IN+ FOLDER+'!D*.SAVE')
		DATE_RANGE = ['20020301','20020531']
		JD_RANGE = DATE_2JD(DATE_RANGE)
		FN = PARSE_IT(FILES,/ALL)
		JD = DATE_2JD(FN.DATE_START)
		OK = WHERE(JD GE JD_RANGE[0] AND JD LE JD_RANGE[1])
		FILES = FILES[OK]
		MAP_OUT = 'GOM'
		PAL = 'PAL_SW3'
		TITLE_SLIDE = 1
		DIR_OUT = DIR_TEMP

		S= STRUCT_SD_REMAP(FILES=FILES, DIR_OUT=DIR_OUT, MAP_OUT=MAP_OUT,OVERWRITE=OVERWRITE)
		STRUCT_SD_2PNG,DIR_OUT+'!D_*-SEAWIFS-REPRO5-GOM-PXY_430_400-CHLOR_A-INTERP-TS_IMAGES.SAVE',/ADD_COLORBAR,OVERWRITE=OVERWRITE,/ADD_LAND,/ADD_DATEBAR,/ADD_BATHY,BATHS=100
		FILES = FILE_SEARCH(DIR_OUT+ '!D_*-SEAWIFS-REPRO5-GOM-PXY_430_400-CHLOR_A-INTERP-TS_IMAGES-LEG.PNG')
		FA=FILE_ALL(FILES,/ALL)
		IM=READ_PNG(FILES[0]) & SZ=SIZE(IM,/STRUCT) & WIDTH = SZ.DIMENSIONS[0] & HEIGHT = SZ.DIMENSIONS[1]

 		DATE_START=FA.DATE_START & S=SORT(DATE_START) & DATE_START=DATE_START(S)
    DD='!DD_'+STRMID(FIRST(DATE_START),0,8)+'_' +STRMID(LAST(DATE_START),0,8)

    FILE_LABEL_LIST=['SENSOR','METHOD','MAP','PROD']
    _FILE_LABEL=FILE_LABEL_MAKE(FA[0].FIRST_NAME,LIST=FILE_LABEL_LIST)

    AVI_FILE  = DIR_OUT + DD +'-'+_FILE_LABEL+'-'+'PXY_'+NUM2STR(WIDTH)+'_'+NUM2STR(HEIGHT)+'.AVI'
    FA_OUT = FILE_ALL(AVI_FILE)
    STOP

    IF FA_OUT.FULLNAME NE '' THEN BEGIN
    	IF FA_OUT.MTIME LT MAX(FA.MTIME)  OR OVERWRITE EQ 1 THEN BEGIN
				MAKE_AVI,FILES=FILES,DIR_OUT=DIR_OUT,PAL=pal,TITLE_FILE_PNG=FILES[0],TITLE_SLIDE=TITLE_SLIDE,AVI_FILE=avi_file
			ENDIF
		ENDIF
	ENDIF
;	|||||||||||||||||||||||||||||||||||||||||||||



; **************************************************************
 	IF DO_SST_DEMO_MAB_UPWELLING GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SST_DEMO_MAB_UPWELLING GE 2
    PRINT, 'S T E P:    DO_SST_DEMO_MAB_UPWELLING'
		DRIVES=GET_DRIVE_NAMES()
		OK=WHERE(DRIVES.NAME EQ 'IOMEGA_HDD_13')
		DRIVE_IN = DRIVES[OK].DRIVE
		folder = '\ts_images_save_n4atg_sst_nec\
	  FILES = FILE_SEARCH(DRIVE_IN+ folder + '!D*.SAVE')

		DATE_RANGE = ['20020601','20020930']
		JD_RANGE = DATE_2JD(DATE_RANGE)
		FN = PARSE_IT(FILES,/ALL)
		JD = DATE_2JD(FN.DATE_START)
		OK = WHERE(JD GE JD_RANGE[0] AND JD LE JD_RANGE[1])
		FILES = FILES[OK]	 & 	FN=FN[OK]
		MAP_IN  = 'NEC'
		MAP_OUT = 'MAB'
		PAL = 'PAL_SW3'

		PAL = 'PAL_PETES24J2'
		TITLE_SLIDE = 1
		DIR_OUT = DIR_TEMP


;		S= STRUCT_SD_REMAP(FILES=FILES, DIR_OUT=DIR_OUT, MAP_OUT=MAP_OUT,OVERWRITE=OVERWRITE)
	  FILES = FILE_SEARCH(DIR_TEMP + '!D*N4ATG-'+MAP_OUT+'*.SAVE')
	  FN = PARSE_IT(FILES,/ALL)
		JD = DATE_2JD(FN.DATE_START)
		OK = WHERE(JD GE JD_RANGE[0] AND JD LE JD_RANGE[1])
		FILES = FILES[OK]	 & 	FN=FN[OK]

 		STRUCT_SD_2PNG,FILES,/ADD_COLORBAR,OVERWRITE=OVERWRITE,/ADD_LAND,/ADD_DATEBAR,/ADD_BATHY,BATHS=100,PAL=PAL

		FILES = REPLACE(FILES,'.SAVE','-LEG.PNG')

		FA=FILE_ALL(FILES,/ALL)
		IM=READ_PNG(FILES[0]) & SZ=SIZE(IM,/STRUCT) & WIDTH = SZ.DIMENSIONS[0] & HEIGHT = SZ.DIMENSIONS[1]

 		DATE_START=FA.DATE_START & S=SORT(DATE_START) & DATE_START=DATE_START(S)
    DD='!DD_'+STRMID(FIRST(DATE_START),0,8)+'_' +STRMID(LAST(DATE_START),0,8)

    FILE_LABEL_LIST=['SENSOR','METHOD','MAP','PROD']
    _FILE_LABEL=FILE_LABEL_MAKE(FA[0].FIRST_NAME,LIST=FILE_LABEL_LIST)

    AVI_FILE  = DIR_OUT + DD +'-'+_FILE_LABEL+'-'+'PXY_'+NUM2STR(WIDTH)+'_'+NUM2STR(HEIGHT)+'.AVI'
    FA_OUT = FILE_ALL(AVI_FILE)


    IF FA_OUT.FULLNAME NE '' THEN BEGIN
    	IF FA_OUT.MTIME LT MAX(FA.MTIME)  OR OVERWRITE EQ 1 THEN BEGIN
				MAKE_AVI,FILES=FILES,DIR_OUT=DIR_OUT,PAL=pal,TITLE_FILE_PNG=FILES[0],TITLE_SLIDE=TITLE_SLIDE,AVI_FILE=avi_file
			ENDIF
		ENDIF
	ENDIF
;	|||||||||||||||||||||||||||||||||||||||||||||



; **************************************************************
 	IF DO_SST_DEMO_MAB_SUMMER_BLOOM GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SST_DEMO_MAB_SUMMER_BLOOM GE 2
    PRINT, 'S T E P:    DO_SST_DEMO_MAB_SUMMER_BLOOM'
		DRIVES=GET_DRIVE_NAMES()
		OK=WHERE(DRIVES.NAME EQ 'IOMEGA_HDD_13')
		DRIVE_IN = DRIVES[OK].DRIVE
		FOLDER = 'ts_images_save_chlor_a_nec\
	  FILES = FILE_SEARCH(DRIVE_IN+ folder + '!D*.SAVE')

		DATE_RANGE = ['20010601','20010931']
		JD_RANGE = DATE_2JD(DATE_RANGE)
		FN = PARSE_IT(FILES,/ALL)
		JD = DATE_2JD(FN.DATE_START)
		OK = WHERE(JD GE JD_RANGE[0] AND JD LE JD_RANGE[1])
		FILES = FILES[OK]	 & 	FN=FN[OK]
		MAP_IN  = 'NEC'
		MAP_OUT = 'MAB'

		PAL = 'PAL_SW3'
		TITLE_SLIDE = 1

		STRUCT_SD_2PNG,FILES,/ADD_COLORBAR,OVERWRITE=OVERWRITE,/ADD_LAND,/ADD_DATEBAR,/ADD_BATHY,BATHS=100,PAL=PAL,MAP_OUT=MAP_OUT,DIR_OUT=DIR_TEMP

		FILES=REPLACE(FN.FIRST_NAME,'-NEC-', '-'+MAP_OUT+'-PXY*')
		FILES=REPLACE(FILES,'-TS_IMAGES', '-TS_IMAGES-LEG')
		FILES= DIR_TEMP+FILES+'.PNG'
		FILES=FILELIST(FILES)


		FA=FILE_ALL(FILES,/ALL)
		IM=READ_PNG(FILES[0]) & SZ=SIZE(IM,/STRUCT) & WIDTH = SZ.DIMENSIONS[0] & HEIGHT = SZ.DIMENSIONS[1]

 		DATE_START=FA.DATE_START & S=SORT(DATE_START) & DATE_START=DATE_START(S)
    DD='!DD_'+STRMID(FIRST(DATE_START),0,8)+'_' +STRMID(LAST(DATE_START),0,8)

    FILE_LABEL_LIST=['SENSOR','METHOD','MAP','PROD']
    _FILE_LABEL=FILE_LABEL_MAKE(FA[0].FIRST_NAME,LIST=FILE_LABEL_LIST)

    AVI_FILE  = DIR_MOVIES + DD +'-'+_FILE_LABEL+'-'+'PXY_'+NUM2STR(WIDTH)+'_'+NUM2STR(HEIGHT)+'.AVI'
    FA_OUT = FILE_ALL(AVI_FILE)

    IF FA_OUT.FULLNAME NE '' THEN BEGIN
    	IF FA_OUT.MTIME LT MAX(FA.MTIME)  OR OVERWRITE EQ 1 THEN BEGIN
				MAKE_AVI,FILES=FILES,DIR_OUT=DIR_OUT,PAL=pal,TITLE_FILE_PNG=FILES[0],TITLE_SLIDE=TITLE_SLIDE,AVI_FILE=avi_file
			ENDIF
		ENDIF
	ENDIF
;	|||||||||||||||||||||||||||||||||||||||||||||




; **************************************************************
 	IF DO_SST_DEMO_WCR_ADVECTION GE 1 THEN BEGIN
; **************************************************************
		OVERWRITE = DO_SST_DEMO_WCR_ADVECTION GE 2
    PRINT, 'S T E P:    DO_SST_DEMO_WCR_ADVECTION'
		DRIVES=GET_DRIVE_NAMES()
		OK=WHERE(DRIVES.NAME EQ 'IOMEGA_HDD_13')
		DRIVE_IN = DRIVES[OK].DRIVE
		FOLDER = 'ts_images_save_chlor_a_nec\
	  FILES = FILE_SEARCH(DRIVE_IN+ folder + '!D*.SAVE')

		DATE_RANGE = ['19990801','19991015']
		JD_RANGE = DATE_2JD(DATE_RANGE)
		FN = PARSE_IT(FILES,/ALL)
		JD = DATE_2JD(FN.DATE_START)
		OK = WHERE(JD GE JD_RANGE[0] AND JD LE JD_RANGE[1])
		FILES = FILES[OK]	 & 	FN=FN[OK]
		MAP_IN  = 'NEC'
		MAP_OUT = 'MAB'
		MAP_OUT = 'NEC'

		PAL = 'PAL_SW3'
		TITLE_SLIDE = 1

		STRUCT_SD_2PNG,FILES,/ADD_COLORBAR,OVERWRITE=OVERWRITE,/ADD_LAND,/ADD_DATEBAR,/ADD_BATHY,BATHS=100,PAL=PAL,MAP_OUT=MAP_OUT,DIR_OUT=DIR_TEMP

		FILES=REPLACE(FN.FIRST_NAME,'-NEC-', '-'+MAP_OUT+'-PXY*')
		FILES=REPLACE(FILES,'-TS_IMAGES', '-TS_IMAGES-LEG')
		FILES= DIR_TEMP+FILES+'.PNG'
		FILES=FILELIST(FILES)


		FA=FILE_ALL(FILES,/ALL)
		IM=READ_PNG(FILES[0]) & SZ=SIZE(IM,/STRUCT) & WIDTH = SZ.DIMENSIONS[0] & HEIGHT = SZ.DIMENSIONS[1]

 		DATE_START=FA.DATE_START & S=SORT(DATE_START) & DATE_START=DATE_START(S)
    DD='!DD_'+STRMID(FIRST(DATE_START),0,8)+'_' +STRMID(LAST(DATE_START),0,8)

    FILE_LABEL_LIST=['SENSOR','METHOD','MAP','PROD']
    _FILE_LABEL=FILE_LABEL_MAKE(FA[0].FIRST_NAME,LIST=FILE_LABEL_LIST)

    AVI_FILE  = DIR_MOVIES + DD +'-'+_FILE_LABEL+'-'+'PXY_'+NUM2STR(WIDTH)+'_'+NUM2STR(HEIGHT)+'.AVI'
    FA_OUT = FILE_ALL(AVI_FILE)

    IF FA_OUT.FULLNAME NE '' THEN BEGIN
    	IF FA_OUT.MTIME LT MAX(FA.MTIME)  OR OVERWRITE EQ 1 THEN BEGIN
				MAKE_AVI,FILES=FILES,DIR_OUT=DIR_OUT,PAL=pal,TITLE_FILE_PNG=FILES[0],TITLE_SLIDE=TITLE_SLIDE,AVI_FILE=avi_file
			ENDIF
		ENDIF
	ENDIF
;	|||||||||||||||||||||||||||||||||||||||||||||


PRINT,'END OF NEFSC_WEBSITE_MAIN.PRO'

END; #####################  End of Routine ################################
