; $ID:	NEFSC_ADVISORY_MAIN.PRO,	2020-06-30-17,	USER-KJWH	$
PRO NEFSC_ADVISORY_MAIN

ROUTINE_NAME='NEFSC_ADVISORY'

	DISK = 'D:'
  DELIM=DELIMITER(/PATH)
  PATH = DISK+DELIM + 'PROJECTS\'+ROUTINE_NAME+DELIM

	MAP = 'NEC'

 	LANDMASK = READALL('D:\IDL\IMAGES\MASK_NEC.PNG')
  OK_LAND = WHERE(LANDMASK NE 255)
  OK_COAST = WHERE(LANDMASK EQ 0)
  MASK = LANDMASK & MASK(*,*) = 0
  MASK(OK_LAND) = 1


	TARGET_MONTH = 10

; **************************************
; Directories
; Edit these as needed

	DIR_DATA = path+'DATA'+delim
  DIR_SAVE = path+'SAVE'+delim
  DIR_FLT  = path+'FLT'+delim
  DIR_BROWSE = path+'BROWSE'+delim
  DIR_PLOTS = path+'PLOTS'+delim
  DIR_ERRORS = path+'ERRORS'+delim
  DIR_TEMP   = path+'TEMP'+delim
  DIR_MOVIES   = path+'MOVIES'+delim

	DIR_ALL = [DIR_DATA,DIR_SAVE,DIR_PLOTS,DIR_BROWSE,DIR_ERRORS,DIR_FLT, DIR_TEMP, DIR_MOVIES]



; ================>
; Switches controlling which Processing STEPS to do:
	DO_CHECK_DIRS = 1 ; GOOD IDEA TO ALWAYS KEEP THIS SWITCH ON

	DO_SAVE_2CSV           			= 0
	DO_EXTRACT_SUBAREAS_SEASON 	= 0

	DO_BROWSE_EDIT							= 2
	DO_ADD_GFISH4_OUTLINES 			= 1

; *********************************************
; ******** C H E C K   D I R S  ***************
; *********************************************
  IF DO_CHECK_DIRS GE 1 THEN BEGIN
    PRINT, 'S T E P:    DO_CHECK_DIRS'
    FOR N=0,N_ELEMENTS(DIR_ALL)-1 DO BEGIN
      AFILE = STRMID(DIR_ALL(N),0,STRLEN(DIR_ALL(N))-1)
      IF FILE_TEST(AFILE,/DIRECTORY) EQ 0L THEN FILE_MKDIR,AFILE
    ENDFOR
  ENDIF ; IF DO_CHECK_DIRS GE 1 THEN BEGIN
; |||||||||||||||||||||||||||||||||||||||||||||||||



	IF DO_SAVE_2CSV GE 1 THEN BEGIN

		STOP
	FILES=FILELIST(DIR_SAVE+'!M-*GFISH4*CHLOR_A.SAVE')
		SAVE_2CSV,FILES

	FILES=FILELIST(DIR_SAVE+'!M-*GFISH4*N4AT-SST.SAVE')
	SAVE_2CSV,FILES

	ENDIF




	IF DO_EXTRACT_SUBAREAS_SEASON GE 1 THEN BEGIN
		FILES=FILE_SEARCH(DIR_SAVE+'!M-*GFISH4*CHLOR_A.SAVE')
		FILES=[FILES,FILE_SEARCH(DIR_SAVE+'!M-*GFISH4*N4AT-SST.SAVE')]

		LIST, FILES
		STOP

		TARGET_STAT = 'MEAN'
		TARGET_MONTH = 10

		FOR _FILE = 0,N_ELEMENTS(FILES)-1 DO BEGIN
			AFILE = FILES(_FILE)
			FA = FILE_ALL(AFILE)
				APROD = FA[0].PROD
				AMETHOD = FA[0].METHOD
			SD=READALL(AFILE)





;			===> SUBSET FOR THE TARGET MONTH

			SETS=WHERE_SETS(SD.SUBAREA_CODE)
			FOR _SET = 0,N_ELEMENTS(SETS)-1 DO BEGIN
				ASET=SETS(_SET)
				SUBS=WHERE_SETS_SUBS(ASET)
				DB  = SD(SUBS)
				FA = FILE_ALL(DB.FIRST_NAME)
				SUBAREA_CODE =  DB[0].SUBAREA_CODE
				SUBAREA_NAME =  DB[0].SUBAREA_NAME


;				===> PERIOD STATS ON !M DATA
				JD = PERIOD_2JD(DB.FIRST_NAME)
				DATA = DB.MEAN

	 			P=PERIOD_STATS_ALL( JD, DATA, PROD=Aprod, LN=LN, $
 					CRITERIA_RANGE = CRITERIA_RANGE,$
 					CRITERIA_OPER=CRITERIA_OPER, $
 					MPY_MIN=MPY_MIN, $
 					MIN_CPY=MIN_CPY,MAX_CPY=MAX_CPY,$
 					DO_LNP=DO_LNP, DO_DFT=DO_DFT, $
 					ERROR=ERROR	)

;				*** YEARLY MEANS ***
				MPY_MIN = 12
 				OK = WHERE(P.Y.N EQ MPY_MIN,COUNT)
 				_P=P.Y[OK]
 			  _P = STRUCT_COPY(_P,TAGNAMES=['PERIOD','N','MEAN'])
 			  IF APROD EQ 'CHLOR_A' THEN _P.MEAN = EXP(_P.MEAN)
 			  TXT = TARGET_STAT+'_'+ APROD
 				_P=STRUCT_RENAME(_P, 'MEAN',TXT)
 				CSV_YEAR = DIR_SAVE+SUBAREA_NAME+'-'+AMETHOD+'-'+APROD+'-'+'YEARLY-'+TARGET_STAT+'.CSV'
 				STRUCT_2CSV,CSV_YEAR,_P
 ;			|||||||||||||||||||||||||||||||||||

;				*** MEANS FOR TARGET MONTH (SEASON)
				OK=WHERE(FA.MONTH_START EQ TARGET_MONTH)
				MONTHNAME = MONTH_NAMES(TARGET_MONTH,/SHORT)
				D=DB[OK]

				PRINT
				TXT = TARGET_STAT+'_'+ APROD
				D=STRUCT_RENAME(D, 'FIRST_NAME','DATE')

				D.DATE = STRMID(JD_2DATE(JD_2JD(PERIOD_2JD(D.DATE),/MONTH,/MID)),0,8)
				D=STRUCT_COPY(D,TAGNAMES=['DATE','MASK','SUBAREA_CODE','SUBAREA_NAME','N_SUBAREA','N',TARGET_STAT])
				D=STRUCT_RENAME(D, TARGET_STAT,TXT)

				CSV_FILE_MONTH = DIR_SAVE+SUBAREA_NAME+'-'+MONTHNAME+'-'+AMETHOD+'-'+APROD+'-'+TARGET_STAT+'.CSV'
				STRUCT_2CSV,CSV_FILE_MONTH, D

			ENDFOR

		ENDFOR
		SAVE_2CSV,FILES
	ENDIF




;	**************************************
	IF DO_BROWSE_EDIT GE 1 THEN BEGIN
;	**************************************
	FILES = FILELIST(DIR_SAVE+'!M_200610*.SAVE')
	LIST, FILES


;	LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
	FOR NTH=0,N_ELEMENTS(FILES)-1 DO BEGIN
		AFILE = FILES[NTH]


		FN = PARSE_IT(AFILE,/ALL)
		IF FN.PROD EQ 'SST' THEN BEGIN
			IF FN.STAT EQ 'MEAN' AND FN.MATH EQ '' THEN BEGIN
				USE_PROD='SST'
				PAL = 'PAL_PETES24J'
				NO_NAME = 0
				NO_UNIT = 0
			ENDIF
			IF FN.MATH EQ 'DIF' THEN BEGIN
				USE_PROD='DIF_5'
				PAL = 'PAL_RATIO'
				NO_NAME = 1
			ENDIF
		ENDIF

	IF FN.PROD EQ 'CHLOR_A' THEN BEGIN
			IF FN.STAT EQ 'MEAN' AND FN.MATH EQ '' THEN BEGIN
				USE_PROD='CHLOR_A'
				PAL = 'PAL_SW3'
				NO_NAME = 0
				NO_UNIT = 0
				COLORBAR_TITLE = 'Chlorophyll a
			ENDIF

			IF FN.STAT EQ 'MEAN' AND FN.MATH EQ 'RATIO' THEN BEGIN
				USE_PROD='RATIO_5'
				PAL = 'PAL_RATIO'
				NO_NAME = 1
			ENDIF
		ENDIF

		PX_OUT = 450
		PY_OUT = 450
		STRUCT_SD_2PNG,AFILE,DIR_OUT=DIR_BROWSE, /OVERWRITE,PAL=PAL,USE_PROD=USE_PROD,$
		   /ADD_COLORBAR,/ADD_LAND,/ADD_COAST,/ADD_BATHY,BATHS=[100],BATHY_COLOR=251, NO_NAME=NO_NAME,NO_UNIT=NO_UNIT,$
		   MAP_OUT='NEC',PX_OUT=PX_OUT,PY_OUT=PY_OUT,ADD_LAKES = 0,FONT='TIMES'
  ENDFOR

ENDIF




IF DO_ADD_GFISH4_OUTLINES GE 1 THEN BEGIN

	 MASK = READALL('D:\IDL\IMAGES\MASK_SUBAREA-NEC-PXY_1024_1024-GFISH4-OUTLINE-EDIT.png')
	 STOP
	 XY = IMAGE_TRACE(MASK,1)


	; CLOUDIER,IMAGE=MASK,MASK=MASK,BOX=2,CLOUDS=1,/QUIET
  ; MASK=MAP_REMAP(MASK,MAP_IN='NEC',MAP_OUT='NEC', PX_OUT=PX_OUT,PY_OUT=PY_OUT)


;	LINES = WHERE(MASK EQ 1)

	FILES = FILE_SEARCH(DIR_BROWSE+'*NEC*'+STRTRIM(PX_OUT,2)+'*.PNG')
	stop
	FN=FILE_PARSE(FILES)
	OK=WHERE_STRING(FN.FIRST_NAME, 'OUTLINE',COUNT,NCOMPLEMENT=NCOMPLEMENT,COMPLEMENT=COMPLEMENT)
	FILES = FILES(COMPLEMENT)

	FOR NTH=0,N_ELEMENTS(FILES)-1 DO BEGIN
		AFILE = FILES[NTH]
		FN=FILE_PARSE(AFILE)
		OUTFILE = FN.DIR+FN.NAME+'-OUTLINE.PNG'
		IM=READ_PNG(AFILE,R,G,B)
		IM(XY.X*450./1024,XY.Y*450./1024) = 0
;		IM(LINES) = 0
		TVLCT,R,G,B
	;	SLIDEW, IM
		WRITE_PNG,OUTFILE,IM,R,G,B


	ENDFOR
ENDIF



END
