; $ID:	PLOT_SUBAREAS_BY_MONTH.PRO,	2020-06-30-17,	USER-KJWH	$
PRO PLOT_SUBAREAS_BY_MONTH,FILE, DIR_OUT=dir_out

  FILE = 'D:\SEAWIFS_NEC\TS_SUBAREAS\save\!M-MASK_SUBAREA-NEC-PXY_1024_1024-GFISH4-REPRO5-CHLOR_A.SAVE'
  SUBAREA_CODE = 3

  DB=READALL(FILE)

 	FN=PARSE_IT(FILE,/ALL)
	IF N_ELEMENTS(DIR_OUT) NE 1 THEN _DIR_OUT = FN.DIR ELSE _DIR_OUT = DIR_OUT


	PROD = FN.PROD
	OK=WHERE(DB.SUBAREA_CODE EQ SUBAREA_CODE AND VALIDS('PRODS',DB.FIRST_NAME) EQ PROD)


	D=DB[OK]
	JD_TODAY = DATE_2JD(DATE_NOW())
	JD=PERIOD_2JD(D.FIRST_NAME)


	YY = MINMAX(D.MEAN)
	YEAR_COLORS=[2,4,8,10,13,17,18,19,21,26]

;	===> GROUP PERIODS INTO !Y
	SETS=	PERIOD_SETS(STRMID(D.FIRST_NAME,3,6),PERIOD_CODE='!Y',/DATE)

	N_SETS=N_ELEMENTS(SETS)

	TITLE = D[0].SUBAREA_NAME
	PS_FILE =  _DIR_OUT+FN.FIRST_NAME+ '-'+ TITLE+'.PS'
	PS_FILE = REPLACE(PS_FILE,' ','_')

	JD		=	PERIOD_2JD(D.FIRST_NAME)
	STAT	=	PERIOD_STATS(JD,D.MEAN,PERIOD_CODE='!Y',/FULL)

;	===> Set up POSTSCRIPT
 	PAL_36,R,G,B
  PSPRINT,FILENAME=PS_FILE,/HALF,/COLOR


;	===> MONTH AXIS
	AX=DATE_AXIS(/FYEAR,ROOM=[0,0])

	IF PROD EQ 'CHLOR_A' THEN BPROD = 'CHLOROPHYLL' ELSE BPROD = PROD
	YTITLE = 'SeaWiFS '+ UNITS(BPROD,/NAME,/UNIT)


;	===> PLOT EACH YEARS MONTHS AS A SEPARATE LINE
	PLOT,AX.JD,YY, XTICKS=AX.TICKS,XTICKNAME=AX.TICKNAME,XTICKV=AX.TICKV,/XSTYLE, TITLE=TITLE,YTITLE=YTITLE,/NODATA
	BACKGROUND,/PLOT,COLOR=35
	GRIDS,XX=AX.TICKV,COLOR=34

  LABELS = JD_2YEAR(PERIOD_2JD(SETS.PERIOD))
  THICKS = REPLICATE(11,N_SETS)
  LSIZE  = 1.1
  LSTYLE = REPLICATE(0,N_SETS)
  LSTYLE = [0,1,2,3,4,0,1,2,3,4,0,1]


	BOX=[35, 0,  1, 0.75, 0.8]
	LEG,pos =[0.84 ,0.650,0.89,0.96], BOX=BOX,color=YEAR_COLORS,label=labels ,THICK=THICKS ,LSIZE=LSIZE

  !P.CHARTHICK=3

; LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
	FOR NTH=0,N_ELEMENTS(SETS)-1 DO BEGIN
		ASET = SETS[NTH]
		SUBS=WHERE_SETS_SUBS(ASET)
		_D=D(SUBS)
		JD	=	PERIOD_2JD(_D.FIRST_NAME)
		JD=  JD_2JD(DATE_2JD('2020'+ STRMID(JD_2DATE(JD),4)),/MONTH,/MID)
	;	LIST,JD_2DATE(JD)

		PLOTS, JD, _D.MEAN ,COLOR=YEAR_COLORS[NTH],THICK=THICKS[NTH]
		PLOTS, JD, _D.MEAN ,COLOR=0,THICK=1,LINESTYLE=0
		IF N_ELEMENTS(_D) EQ 1 THEN BEGIN
			PLOTS, [JD-4,JD+4], [_D.MEAN,_D.MEAN] ,COLOR=YEAR_COLORS[NTH],THICK=THICKS[NTH]
			PLOTS, [JD-4,JD+4], [_D.MEAN,_D.MEAN] ,COLOR=0,THICK=1,LINESTYLE=0
		ENDIF
	ENDFOR

; square km.

CAPTION,"J.O'Reilly,NMFS,NOAA",/plot



;	===> Make a plot of yearly mean values
	OK=WHERE(STAT.N EQ 12,COUNT)
	IF COUNT GE 1 THEN _STAT = STAT[OK] ELSE STOP
	JD =  PERIOD_2JD(_STAT.PERIOD)
	;	===> MONTH AXIS
	AX=DATE_AXIS(JD,/YEAR,ROOM=[1,1])

	YY = MINMAX(_STAT.MEAN)

;	===> PLOT YEARS
	PLOT,AX.JD,YY, XTICKS=AX.TICKS,XTICKNAME=AX.TICKNAME,XTICKV=AX.TICKV,/XSTYLE,/YSTYLE, TITLE=TITLE,YTITLE=YTITLE,/NODATA
	BACKGROUND,/PLOT,COLOR=35
	GRIDS,XX=AX.TICKV,COLOR=34

	PLOTS, JD, _STAT.MEAN ,COLOR=13,THICK=11
	PLOTS, JD, _STAT.MEAN ,COLOR=0,THICK=1,LINESTYLE=0
	PLOTS, JD, _STAT.MEAN ,COLOR=0,THICK=3,PSYM=1
  CAPTION,"J.O'Reilly,NMFS,NOAA",/plot
PSPRINT
!P.CHARTHICK=1
 STOP
IMAGE_TRIM, PS_FILE,DPI=600,/OVERWRITE

END ; ROUTINE
