; $ID:	PLOT_POLY.PRO,	2020-07-08-15,	USER-KJWH	$
;+
;	PLOT_POLY:	This Function returns DATE FROM A VALID PERIOD
;	NOTES:
;		THE FIRST DIMENSION OF THE 2D-ARRAY IS X, THE SECOND DIMENSION WILL BE STACKED
; HISTORY:	May 28, 2003 Written by:	J.E. O'Reilly, NOAA, 28 Tarzwell Drive, Narragansett, RI 02882
;-
; *************************************************************************

PRO PLOT_POLY,X,ARRAY,COLOR=COLOR, OUTLINE_COLOR=outline_color, GRID_COLOR=grid_color,_EXTRA=_extra
  ROUTINE_NAME='PLOT_POLY'

	IF N_PARAMS() EQ 1 THEN BEGIN
		_ARRAY=X
		X=LINDGEN(N_ELEMENTS(ARRAY(*,0)))
	ENDIF



  SZ=SIZE(ARRAY,/STRUCT)
  COLS=SZ.DIMENSIONS[0]
  ROWS=SZ.DIMENSIONS[1]
  IF N_ELEMENTS(COLOR) NE ROWS THEN COLOR=INDGEN(ROWS)*2+1
  IF N_ELEMENTS(GRID_COLOR) NE 1 THEN _GRID_COLOR = 0 ELSE _GRID_COLOR = GRID_COLOR

  PRINT,COLS,ROWS
  BASE = REPLICATE(0.0,COLS)
;	===> Compute total of columns (stacking is based on columns)
  T=TOTAL(ARRAY,2)

  PLOT,X,T,/NODATA,_EXTRA=_extra,XTICK_GET=XTICK_GET,YTICK_GET=YTICK_GET
  GRIDS,XTICK_GET,YTICK_GET,/ALL,color=grid_color
  FOR ROW=0,ROWS-1 DO BEGIN
  	XX = [X,REVERSE(X)]
  	YY = [BASE+ARRAY(*,ROW), REVERSE(BASE)]
  	POLYFILL,XX,YY,COLOR=COLOR(ROW),_EXTRA=_extra
  	IF N_ELEMENTS(OUTLINE_COLOR) EQ 1 THEN PLOTS,XX,YY,COLOR=OUTLINE_COLOR
  	BASE = BASE+ARRAY(*,ROW)
	ENDFOR

END; #####################  End of Routine ################################
