; $ID:	PLT_DATE.PRO,	2020-06-26-15,	USER-KJWH	$
;+
;#############################################################################################################
	PRO PLT_DATE,DATES,VAL,TITLE=TITLE,FILE=FILE,PROD=PROD,_EXTRA = _EXTRA

;
; PURPOSE: PLOT A TIME-SERIES FOR AN ARRAY OF DATES
;
; CATEGORY:	PLT FAMILY
;
; CALLING SEQUENCE: PLT_DATE,DATES
;
; INPUTS: STRUCTURE
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		NONE:

; OUTPUTS: 
;		
; EXAMPLES: 
;
; MODIFICATION HISTORY:
;			MAY 10,2014,  WRITTEN BY J.O'REILLY 
;			AUG 2,2014,JOR ADDED TXT = 'N= ' + ROUNDS(NUM)
;                    IF NONE(TITLE) THEN TITLE = ROUTINE_NAME

;			
;			
;			
;#################################################################################
;-
;**************************
ROUTINE_NAME  = 'PLT_DATE'
;**************************
IF NONE(PROD) THEN PROD = 'CHLOR_A'

IF ANY(_EXTRA) THEN BEGIN
  ;IF TAG_NAMES(_EXTRA)
  
ENDIF;IF ANY(_EXTRA) THEN BEGIN

IF NONE(DATES) THEN MESSAGE,'ERROR: DATES ARE REQUIRED'
IF NONE(PROD) THEN MESSAGE,'ERROR: PROD IS REQUIRED'
IF NONE(FILE) THEN FILE= !S.IDL_TEMP + ROUTINE_NAME + '.PNG'

FONT_SIZE =18
;DA=DATE_AXIS(MM(DATES),/YEAR,ROOM=[2,2],STEP_SIZE=3,MAX_LABELS=600,/ENDS)
DA=DATE_AXIS(MM(DATES),/YEAR,STEP_SIZE=2,MAX_LABELS=600)
JD = DATE_2JD(DATES)
NUM = N_ELEMENTS(DATES)
;Y = REPLICATE(0.5,NUM)
;OK = WHERE(DATE_2YEAR(DATES) EQ 2003,COUNT) 
;Y[OK] = MISSINGS(Y)
COLOR = 'MIDNIGHT BLUE'
XTITLE = 'YEAR'
YTITLE = UNITS(PROD)
IF N_ELEMENTS(JD) EQ 1 THEN BEGIN
  JD = [JD,JD]
  VAL = [VAL,VAL]
ENDIF;IF N_ELEMENTS(JD) EQ 1 THEN BEGIN
;STOP

  P = PLOT(JD,FLOAT(VAL),XTICKV=DA.TICKV,XTICKNAME = DA.TICKNAME,$
    THICK = 22,FONT_SIZE = FONT_SIZE,COLOR = COLOR,$
    TITLE = TITLE,XTITLE = XTITLE,YTITLE = YTITLE)
    
    
PLT_GRIDS,P
XX =DATE_2JD(MAX(DATES))
YY = 0.5
TXT = 'N= ' + ROUNDS(NUM)
T = TEXT(XX,YY,TXT,/OVERPLOT, /DATA,ALIGN = 0.5,VERTICAL_ALIGNMENT = 0.5,COLOR = 'RED',FONT_SIZE = 18)
P.SAVE,FILE
P.CLOSE

END; #####################  END OF ROUTINE ################################
