; $ID:	PLUN.PRO,	2018-11-14-09,	USER-KJWH	$
PRO PLUN, LUN, TXT, LINES

  IF NONE(LINES) THEN LINES = 1
  IF NONE(TXT)   THEN TXT = ''
  
  IF ~NONE(LUN) THEN IF IDLTYPE(LUN) NE 'STRING' THEN BEGIN
    FLUSH, LUN
    FOR N=0, LINES-1 DO PRINTF, LUN
    PRINTF, LUN, TXT
    FLUSH, LUN
  ENDIF
  
  FOR N=0, LINES-1 DO PRINT
  PRINT, TXT

END
