; $ID:	POF.PRO,	2019-11-08-13,	USER-KJWH	$

	PRO POF,NTH,ARRAY,TXT=TXT,QUIET=QUIET,OUTTXT=OUTTXT,NOPRO=NOPRO,LOGLUN=LOGLUN

;+
; NAME:
;		POF
;
; PURPOSE: PRINT THE NTH OF ARRAY OF ELEMENTS BEING PROCESSED
;
; CATEGORY:
;		PRINT
;
; CALLING SEQUENCE:
; POF, ARRAY
; INPUTS:
;   NTH:  THE NTH ITEM BEING PROCESSED  
;		ARRAY:	ARRAY OF DATA
;		
; OPTIONAL INPUTS:
;		NONE:	
;
; KEYWORD PARAMETERS:
;		TXT: OPTIONAL TEXT STRING TO PRINT AFTER CALLING ROUTINE
;		OUTTXT: OPTION TO OUTPUT THE TEXT STRING
;		QUIET: TO NOT PRINT THE TEXT STRING
;		NOPRO: TO NOT PRINT THE PROGRAM IN THE TEXT STRING
;		LOGLUN..... If provided, the LUN to write to a log file
;
; OUTPUTS:
;		This PROGRAM PRINTS THE NTH ITEM BEING PROCESSED [AND THE NAME OF THE PROGRAM DOING THE PROVESSING] 
;

; EXAMPLE:
;  POF,1,555
;
;
; MODIFICATION HISTORY:
;			Written NOV 26,2011 J.O'Reilly
;			DEC 16, 2011 - JEOR: ADDED 1 TO THE RESULT
;			APR 06, 2012 - JEOR: IF N_ELEMENTS(_ARRAY) EQ 1 THEN _ARRAY = BYTARR(_ARRAY)
;			APR 11, 2012 - JEOR:  IF IDLTYPE(ARRAY,/CODE) EQ 8 THEN BEGIN
;			JUL 06, 2012 - JEOR: USING STR_COMMA
;			JUL 17, 2012 - JEOR: ADDED INFO ON: +'  ' +CALLER(2)
;			JAN 24, 2013 - JEOR: ADDED KEYWORD TXT
;			MAR 26, 2014 - KJWH: ADDED QUIET AND OUTTXT KEYWORDS
;			DEC 03, 2015 - JEOR: IF HAS(C,'0') EQ 1 THEN C = 'MAIN'
;     NOV 17, 2017 - KJWH: Added + ' (' + ROUNDS((NTH+1)/FLOAT(N)*100,2) + '%)' to print the percent of files in the output string
;     MAR 12, 2019 - KJWH: Cleaned up and simplified
;     JUL 22, 2019 - KJWH: Added LOGLUN keyword and replaced PRINT with PLUN
;     NOV 04, 2019 - KJHW: Added IF N_ELEMENTS(ARRAY) EQ 1 THEN N = N_ELEMENTS(BYTARR(ARRAY)) ELSE N = N_ELEMENTS(ARRAY) for when ARRAY is a single value
;     NOV 08, 2019 - KJWH: Updated previous fix to be IF N_ELEMENTS(ARRAY) EQ 1 AND IDLTYPE(ARRAY) NE 'STRING' THEN N = N_ELEMENTS(BYTARR(ARRAY)) ELSE N = N_ELEMENTS(ARRAY)
;-
;***********************
  ROUTINE_NAME = 'POF'
;************************

  IF NONE(LOGLUN)    THEN LOG_LUN = [] ELSE LOG_LUN = LOGLUN
  IF N_ELEMENTS(TXT) NE 1 THEN _TXT = '' ELSE _TXT = TXT
	IF IDLTYPE(ARRAY,/CODE) EQ 8 THEN ARRAY = BYTARR(N_ELEMENTS(ARRAY)) ; If array is a structure
	IF N_ELEMENTS(ARRAY) EQ 1 AND IDLTYPE(ARRAY) NE 'STRING' THEN N = N_ELEMENTS(BYTARR(ARRAY)) ELSE N = N_ELEMENTS(ARRAY)
	OUTTXT = '# '+STR_COMMA(STRTRIM((NTH+1),2)) +' of '+STR_COMMA(STRTRIM(N,2)) + ' (' + ROUNDS((NTH+1)/FLOAT(N)*100,2) + '%)' 
	
	C = STRUPCASE(CALLER(2)) 
	IF HAS(C,'0') THEN C = 'MAIN'
	IF KEYWORD_SET(NOPRO) THEN OUTTXT = OUTTXT + ' ' + _TXT ELSE OUTTXT = OUTTXT +'  ' + C + '   ' + _TXT
	IF NOT KEYWORD_SET(QUIET) THEN PLUN, LOG_LUN, OUTTXT
  
END; #####################  End of Routine ################################
