; $ID:	POLY_FIT_ORTHO_DEMO.PRO,	2020-06-26-15,	USER-KJWH	$
PRO POLY_FIT_ORTHO_DEMO

!P.SYMSIZE=1.0

GOTO, SKIP
X = FINDGEN(101)
    Y = SIN(12.*!PI*X/100.) + RANDOMN(SEED, 101)
    NDEGREE = 66
    YFIT = POLY_FIT_ORTHO(X, Y, NDEGREE, /FIT)
    PLOT, X, Y, LINESTYLE = 1
    OPLOT, X, YFIT, THICK = 2





SKIP:

STOP
	NDEGREE = 5
  DIR_SAVE='D:\PROJECTS\OC_NOMAD\SAVE\'
	FILE = DIR_SAVE +'OC_NOMAD-EDIT-INTERP-TRIM.SAVE'
	DS=READALL(FILE)
	OK=WHERE(DS.USE EQ 'USE' AND DS.IRRS443 NE MISSINGS(DS.IRRS443))
	DS=DS[OK]
	MBR = (((DS.IRRS443>DS.IRRS489>DS.IRRS510)/DS.IRRS555))
	C   = DS.CHLOR_A
	XX = ALOG10(((DS.IRRS443>DS.IRRS489>DS.IRRS510)/DS.IRRS555))
	YY = ALOG10(DS.CHLOR_A)
	TYPE = 2
	A = POLY_FIT_ORTHO( XX, YY, NDEGREE,YFIT, $ ;[YFIT, POLYVAR, SIGMA, Corrm,] ,$
												TYPE=TYPE,$
                        ORPOLY=ORPOLY, XINTERP=XIN, YINTERP=YIN, INPOLY=INPOLY,$
                        C_O=C_O, C_X=C_X, C_T=C_T, XAVG=XAVG,XRANGE=XRANGE,$
                        QX=QX, QT=QT, RMS=RMS, STD=STD, FIT=FIT, DOUBLE=DOUBLE,$
                        WARNMSSG=WM )

  PRINT,A
  YFIT=10^YFIT


 	PSPRINT,FILENAME='POLY_FIT_ORTHO.PS',/COLOR,/FULL
  ; ====================>
; Make a standard 5 statistical plot of model vs data
  PLOT_OC_STATS,C,YFIT, COEFFS=a,ratio=ratio,modelx=rx,MODEL_X_TITLE=MODEL_X_TITLE,$
            MODELY=MODELY,notes=notes,PAGE_TITLE=ALG_TITLE,TITLE=ALG_TITLE,/QUIET,DECIMALS=decimals,NO_NOTES=NO_NOTES,$
            xrange=xrange,char_scale=1,LL=ll,NOTE_SIZE=0.6,binsize=binsize, SINGLE=single,$
            ALG_FORMULA=ALG_FORMULA

	PSPRINT


; COEFFS = REGRESS(X, ALOG10(C), WEIGHTS, Yfit, CONST, Sigma, FTEST,R,RMUL,CHISQ,STATUS)

	Result = POLY_FIT( XX, YY, NDEGREE , CHISQ=CHISQ, COVAR=COVAR, /DOUBLE , MEASURE_ERRORS=MEASURE_ERRORS, SIGMA=variable, STATUS=STATUS, YBAND=YBAND, YERROR=variable, YFIT=YFIT )
   YFIT=10^YFIT

	PSPRINT,FILENAME='POLY_FIT.PS',/COLOR,/FULL
  ; ====================>
; Make a standard 5 statistical plot of model vs data
  PLOT_OC_STATS,C,YFIT, COEFFS=a,ratio=ratio,modelx=rx,MODEL_X_TITLE=MODEL_X_TITLE,$
            MODELY=MODELY,notes=notes,PAGE_TITLE=ALG_TITLE,TITLE=ALG_TITLE,/QUIET,DECIMALS=decimals,NO_NOTES=NO_NOTES,$
            xrange=xrange,char_scale=1,LL=ll,NOTE_SIZE=0.6,binsize=binsize, SINGLE=single,$
            ALG_FORMULA=ALG_FORMULA

	PSPRINT


STOP


WIN
SET_PMULTI
  RX =  0.01+ double(indgen(10000)*0.01)
 ; RX =  0.001+ double(LIndgen(10000)*0.001)
  ok = WHERE(RX GE .1 AND RX LE 30)
  rx = (rx(ok))
  ONES=replicate(1.0,N_ELEMENTS(RX))

 CHL_OC4 = A_OC4_4(RX,RX,RX,ONES)
 CHL_OC5 = A_OC4_5(RX,RX,RX,ONES)

PLOTXY, MBR,C,PSYM=1,/LOGLOG,XRANGE= ([0.1,30]),YRANGE= ([0.001,100]),/XSTYLE,/YSTYLE
OPLOT, RX,CHL_OC4,COLOR=TC(20),PSYM=1
OPLOT, RX,CHL_OC5,COLOR=TC(26),PSYM=1

STOP

SETS=WHERE_SETS(DS.CRUISE)
SUBS=WHERE_SETS_SUBS(SETS(254))
D=DS(SUBS)






    END
