; $ID:	PROFILE_INTEGRATION_DEMO.PRO,	2014-12-18	$

 PRO PROFILE_INTEGRATION_DEMO, DEPTH=depth,PROFILE=profile, KD=kd,Z90=Z90,CHL=CHL, BIN=BIN, Z=Z, ERROR=error
;+
; NAME:
; 	CHL_Z90_DEMO

;		This Program Demonstrates CHL_Z90

; MODIFICATION HISTORY:
;		Written Jan 31, 2005 by J.O'Reilly, 28 Tarzwell Drive, NMFS, NOAA 02882 (Jay.O'Reilly@NOAA.GOV)
;-

ROUTINE_NAME='PROFILE_INTEGRATION_DEMO'
	ERROR = 0
	PAL_36

PSFILE = ROUTINE_NAME+'.PS'
PSPRINT, FILENAME = PSFILE, /HALF, /COLOR, /TIMES & !P.MULTI=[0,1,1]

KD_Z90 =  0.31  ; POSITIVE VALUES


;	*** VERTICALLY UNIFORM CHL
	TITLE = 'DEMO 1'
	VAR = REPLICATE(0.9,12)
 	DEPTH = FINDGEN(N_ELEMENTS(VAR))
 	MAX_DEPTH = MAX(DEPTH+2)
	STRUCT= PROFILE_INTEGRATION(DEPTH=depth,VAR=VAR,MAX_DEPTH=MAX_DEPTH, KD_Z90=KD_Z90,Z_90=Z_90, /SHOW, /Z90_CHL, XTITLE='Chlorophyll a', TITLE=TITLE, ERROR=error)
	PRINT,STRUCT.WCHL


;	*** SUBSURFACE MAX LAYER
	TITLE = 'DEMO - SUBSURFACE MAX'
 	VAR= [0.3, 0.4,0.5,0.65,0.8,1,1.2, 1.1,1,0.8, 0.6, 0.4]
 	DEPTH = FINDGEN(N_ELEMENTS(VAR))
 	MAX_DEPTH = MAX(DEPTH+2)
	STRUCT= PROFILE_INTEGRATION(DEPTH=depth,VAR=VAR,MAX_DEPTH=MAX_DEPTH, KD_Z90=KD_Z90,Z_90=Z_90, /SHOW, /Z90_CHL, XTITLE='Chlorophyll a', TITLE=TITLE, ERROR=error)
	PRINT,STRUCT.WCHL

STOP

;	*** VERY STRONG SUBSURFACE MAX LAYER
	TITLE = 'DEMO - STRONG SUBSURFACE MAX'
 	VAR= [0.3, 0.5,0.9,1.3,1.2, 1.1,1,0.8, 0.6, 0.4]
 	DEPTH = FINDGEN(N_ELEMENTS(VAR))
 	MAX_DEPTH = MAX(DEPTH+2)
	STRUCT= PROFILE_INTEGRATION(DEPTH=depth,VAR=VAR,MAX_DEPTH=MAX_DEPTH, KD_Z90=KD_Z90,Z_90=Z_90, /SHOW, /Z90_CHL, XTITLE='Chlorophyll a', TITLE=TITLE, ERROR=error)
	PRINT,STRUCT.WCHL

;	*** VERY STRONG SUBSURFACE MAX LAYER, NO ZERO DEPTH
	TITLE = 'DEMO - NO ZERO'
 	VAR= [0.3, 0.5,0.9,1.3,1.2, 1.1,1,0.8, 0.6, 0.4]
 	DEPTH = FINDGEN(N_ELEMENTS(VAR))+1
 	MAX_DEPTH = MAX(DEPTH+2)
	STRUCT= PROFILE_INTEGRATION(DEPTH=depth,VAR=VAR,MAX_DEPTH=MAX_DEPTH, KD_Z90=KD_Z90, Z_90=Z_90,/SHOW, /Z90_CHL, XTITLE='Chlorophyll a', TITLE=TITLE, ERROR=error)
	PRINT,STRUCT.WCHL

PSPRINT
STOP
END; #####################  End of Routine ################################



