; $Id:	project_lnp_main.pro,	Jan 11 2010	$
;+

;   Jan 11,2010 T.Ducas
;-
; *************************************************************************

PRO PROJECT_LNP_MAIN
  ROUTINE_NAME='PROJECT_LNP_MAIN'

 	DO_LNP_BROWSE    		= 1
 	DO_LNP_BROWSE_PAGE  = 0

; ===============>
	AS = '*' & UL ='_'& & DASH = '-' & CM =',' & COMPUTER=GET_COMPUTER() & DELIM=DELIMITER(/PATH)& NOW = LONG(STRMID(DATE_NOW(),0,8))

; *********************************************************
	IF KEYWORD_SET(DO_LNP_BROWSE) THEN BEGIN
; *********************************************************
		MAP = 'L3B'
		MAP = 'EC'

		_OVERWRITE=0
		_OVERWRITE=1


		IF MAP EQ 'L3B' THEN BEGIN
			MAP_OUT='ROBINSON'
			DIR_IN='D:\OC-SEAWIFS-9-L3B\TS_IMAGES\LNP\'
			DIR_OUT=DIR_IN


			FILES=[ $
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_MAX_YP.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_MAX.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_1CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_2CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_3CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_4CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_5CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_025CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_050CPY.SAVE',$
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_075CPY.SAVE' $
			]

			FILES=[ $
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-TREND-SLOPE.SAVE', $
			'ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-TREND-INT.SAVE' $
			]

			FILES='ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_SIGNIF.SAVE'
		;	FILES='ANNUAL-SEAWIFS-REPRO6-9-L3B-CHLOR_A-OC4-PSERIES_3638-LNP_NUM.SAVE'

		ENDIF


		IF MAP EQ 'EC' THEN BEGIN

			COVERAGE='MLAC'
			;COVERAGE='LAC'

			IF COVERAGE EQ 'MLAC' THEN BEGIN
				DIR_IN='T:\OC-SEAWIFS-MLAC-EC\TS_IMAGES\LNP\'
				DIR_OUT='T:\OC-SEAWIFS-MLAC-EC\TS_IMAGES\LNP\BROWSE\'


				FILES=[ $
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_MAX_YP.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_MAX.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_1CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_2CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_3CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_4CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_5CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_025CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_050CPY.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_075CPY.SAVE', $
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_SLOPE.SAVE', $
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_INT.SAVE', $
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_SIGNIF.SAVE',$
				'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_NUM.SAVE' $
				]

				FILES='ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3521-LNP_SIGNIF.SAVE'

			ENDIF

			IF COVERAGE EQ 'LAC' THEN BEGIN
				DIR_IN='S:\OC-SEA_AQU-LAC-EC\TS_IMAGES\LNP\'
				DIR_OUT=DIR_IN

				FILES=[ $
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_MAX_YP.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_MAX.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_1CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_2CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_3CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_4CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_5CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_025CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_050CPY.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_075CPY.SAVE', $
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_SLOPE.SAVE', $
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_INT.SAVE', $
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_SIGNIF.SAVE',$
				'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_NUM.SAVE' $
				]

			FILES='ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_MAX_YP.SAVE'


			ENDIF




		ENDIF;	IF MAP EQ 'EC' THEN BEGIN


		FOR _FILE=0,N_ELEMENTS(FILES)-1 DO BEGIN

			AFILE = DIR_IN + FILES(_FILE)
			_USE_PROD='CHLOR_A'
			_SPECIAL_SCALE=''
			_PAL='PAL_SW3'
			_ADD_LABEL=''
			BIN_TOP=''
			BIN_BOT=''
			IF STRPOS(AFILE,'LNP_MAX.SAVE') GE 0 THEN BEGIN
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' LNP Max'
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='400'
			ENDIF
			IF STRPOS(AFILE,'LNP_MAX_YP.SAVE') GE 0 THEN BEGIN
			;	_ADD_LABEL='Max Peak Cycle'
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' Cycles Per Year'
				_USE_PROD='TEN2ONE'
				_SPECIAL_SCALE=''
			ENDIF
			IF STRPOS(AFILE,'LNP_1CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='400'
				_ADD_LABEL='CPY  gt 0.85 & le 1.5  '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 1CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_2CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_ADD_LABEL='CPY  gt 1.5 & le 2.5  '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 2CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_3CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY  gt 2.5 & le 3.5  '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 3CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_4CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY  gt 3.5 & le 4.5  '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 4CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_5CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY  gt 4.5           '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 5CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_025CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY gt 0.15 & le 0.35 '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 025CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_050CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY  gt 0.35 & le .65 '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 050CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_075CPY.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNUM'
				_SPECIAL_SCALE='200'
				_SPECIAL_SCALE='100'
				_ADD_LABEL='CPY gt 0.65 & le .85 '
				_COLORBAR_TITLE =UNITS('CHLOR_A',/NO_UNIT)+' 075CPY LNP Max'
			ENDIF

			IF STRPOS(AFILE,'LNP_SLOPE.SAVE') GE 0 THEN BEGIN
				_USE_PROD='SLOPE'
				_SPECIAL_SCALE='05'
				_COLORBAR_TITLE = 'SLOPE  !8Chl !Da!X!N '+'mg y!U-1!N'
				_PAL='PAL_ANOM'
			ENDIF

			IF STRPOS(AFILE,'LNP_INT.SAVE') GE 0 THEN BEGIN
				_USE_PROD='INT'
				_SPECIAL_SCALE='75'
				_COLORBAR_TITLE =	'INTERCEPT  !8Chl !Da!X!N '+'mg y!U-1!N'
			ENDIF

			IF STRPOS(AFILE,'LNP_PROB.SAVE') GE 0 THEN BEGIN
				_USE_PROD='PROB'
				_SPECIAL_SCALE='VERY_HIGH'
				_COLORBAR_TITLE =	'lnp peak probability'
			ENDIF

			IF STRPOS(AFILE,'LNP_SIGNIF.SAVE') GE 0 THEN BEGIN
				_USE_PROD='LNP_SIGNIF'
				_COLORBAR_TITLE =	'lnp peak significance'
			;	_ADD_LABEL='lt '+'10!U-15!N'+'  are gray.'
			;	BIN_BOT=0.000000000001
			ENDIF

			IF STRPOS(AFILE,'LNP_NUM.SAVE') GE 0 THEN BEGIN
				_USE_PROD='CNUM'
				_SPECIAL_SCALE=''
				;_ADD_LABEL='Number Observations'
				_COLORBAR_TITLE =	'cumulative number'
			ENDIF


;STOP
			STRUCT_SD_2PNG,AFILE,USE_PROD=_USE_PROD,SPECIAL_SCALE=_SPECIAL_SCALE,ADD_LABEL=_ADD_LABEL,DIR_OUT=DIR_OUT,$
											COLORBAR_TITLE=_COLORBAR_TITLE,PAL=_PAL,/ADD_COLORBAR,/ADD_LAND,BACKGROUND=252B,$
											BIN_TOP=BIN_TOP,BIN_BOT=BIN_BOT,OVERWRITE=_OVERWRITE

		ENDFOR

	ENDIF;	IF KEYWORD_SET(DO_LME_BROWSE) THEN BEGIN



; *********************************************************
	IF KEYWORD_SET(DO_LNP_BROWSE_PAGE) THEN BEGIN
; *********************************************************

		MAP_OUT='EC'
		;MAP_OUT='ROBINSON'

		IF MAP_OUT EQ 'ROBINSON' THEN BEGIN
			DIR_IN='S:\OC-SEAWIFS-9-L3B\TS_IMAGES\LNP\'
			DIR_OUT=DIR_IN
			PAL='PAL_SW3'

			PNGFILE=DIR_OUT+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-CHLOR_A-OC4-PSERIES_3521-LNP_CPY_PAGE_2_5.PNG'
			ROWS=5
			COLS=2
			PX=4096
			PY=2048

			PNG_MAX_YP = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_MAX_YP.PNG'
			PNG_MAX    = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_MAX.PNG'
			PNG_1CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_1CPY.PNG'
			PNG_2CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_2CPY.PNG'
			PNG_3CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_3CPY.PNG'
			PNG_4CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_4CPY.PNG'
			PNG_5CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_5CPY.PNG'
			PNG_025CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_025CPY.PNG'
			PNG_050CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_050CPY.PNG'
			PNG_075CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_075CPY.PNG'

STOP

			FILES=[PNG_MAX_YP,PNG_MAX, PNG_1CPY, PNG_2CPY, PNG_3CPY, PNG_4CPY, PNG_5CPY, PNG_025CPY,PNG_050CPY, PNG_075CPY ]






			PNGFILE=DIR_OUT+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-CHLOR_A-OC4-PSERIES_3521-LNP_STATS_PAGE_2_3.PNG'
			ROWS=3
			COLS=2
			PX=4096
			PY=2048


			FILES=[$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_MAX_YP.PNG',$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_MAX.PNG',$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_SLOPE.PNG',$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_INT.PNG',$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_NUM.PNG',$
					DIR_IN+'ANNUAL-SEAWIFS-REPRO6-9-ROBINSON-PXY_4096_2048-CHLOR_A-OC4-PSERIES_3521-LNP_SIGNIF.PNG'$
					]


  		image_weld_page, files=FILES,rows=ROWS,cols=cols,pal=_PAL,PX=PX,PY=PY,BACKGROUND=255,SPACE=8,PNGFILE=PNGFILE,/OVERWRITE


		ENDIF; IF MAP_OUT EQ 'ROBINSON' THEN BEGIN

		IF MAP_OUT EQ 'EC' THEN BEGIN
			COVERAGE='MLAC'
			;COVERAGE='LAC'

			IF COVERAGE EQ 'MLAC' THEN BEGIN
				DIR_IN='T:\OC-SEAWIFS-MLAC-EC\TS_IMAGES\LNP\'
				DIR_OUT=DIR_IN
				PAL='PAL_SW3'

				PNGFILE=DIR_OUT+'ANNUAL-SEAWIFS-REPRO6-EC-CHLOR_A-OC4-PSERIES_3638-LNP_CPY_PAGE_2_7.PNG'
				ROWS=7
				COLS=2
				PX=1024
				PY=1024

				PNG_MAX_YP = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_MAX_YP.PNG'
				PNG_MAX    = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_MAX.PNG'
				PNG_1CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_1CPY.PNG'
				PNG_2CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_2CPY.PNG'
				PNG_3CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_3CPY.PNG'
				PNG_4CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_4CPY.PNG'
				PNG_5CPY   = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_5CPY.PNG'
				PNG_025CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_025CPY.PNG'
				PNG_050CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_050CPY.PNG'
				PNG_075CPY = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_075CPY.PNG'
				PNG_SLOPE  = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_SLOPE.PNG'
				PNG_INT    = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_INT.PNG'
				PNG_NUM    = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_NUM.PNG'
				PNG_SIGNIF = DIR_IN+'ANNUAL-SEAWIFS-REPRO6-MLAC-EC-CHLOR_A-OC4-PSERIES_3638-LNP_SIGNIF.PNG'
			ENDIF

			IF COVERAGE EQ 'LAC' THEN BEGIN
				DIR_IN='S:\OC-SEA_AQU-LAC-EC\TS_IMAGES\LNP\'
				DIR_OUT=DIR_IN
				PAL='PAL_SW3'

				PNGFILE=DIR_OUT+'ANNUAL-SEA_AQU-REPRO5-LAC-EC-CHLOR_A-PSERIES_4377-LNP_CPY_PAGE_2_7.PNG'
				ROWS=7
				COLS=2
				PX=1024
				PY=1024

				PNG_MAX_YP = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_MAX_YP.PNG'
				PNG_MAX    = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_MAX.PNG'
				PNG_1CPY   = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_1CPY.PNG'
				PNG_2CPY   = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_2CPY.PNG'
				PNG_3CPY   = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_3CPY.PNG'
				PNG_4CPY   = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_4CPY.PNG'
				PNG_5CPY   = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_5CPY.PNG'
				PNG_025CPY = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_025CPY.PNG'
				PNG_050CPY = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_050CPY.PNG'
				PNG_075CPY = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_075CPY.PNG'
				PNG_SLOPE  = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_SLOPE.PNG'
				PNG_INT    = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_INT.PNG'
				PNG_NUM    = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_NUM.PNG'
				PNG_SIGNIF = DIR_IN+'ANNUAL-SEA_AQU-LAC-EC-CHLOR_A-PSERIES_4377-LNP_SIGNIF.PNG'
			ENDIF



STOP

			FILES=[PNG_MAX_YP,PNG_MAX, PNG_025CPY,PNG_050CPY, PNG_075CPY ,PNG_1CPY, PNG_2CPY, PNG_3CPY, PNG_4CPY, PNG_5CPY,$
			        PNG_SLOPE, PNG_INT, PNG_NUM, PNG_SIGNIF]


  		image_weld_page, files=FILES,rows=ROWS,cols=cols,pal=_PAL,PX=PX,PY=PY,BACKGROUND=255,SPACE=8,PNGFILE=PNGFILE,/OVERWRITE



		ENDIF; IF MAP_OUT EQ 'ROBINSON' THEN BEGIN



	ENDIF	;	IF KEYWORD_SET(DO_LME_BROWSE_PAGE) THEN BEGIN


DONE:

END; #####################  End of Routine ################################
;;;


