; $ID:	ROUNDS.PRO,	2017-08-23-16,	USER-JEOR	$
;##############################################################
	FUNCTION ROUNDS, VALUES, DECIMAL_PLACES,DOWN=DOWN,SIG=SIG

;+
; NAME:
;		ROUNDS
;
; PURPOSE:;
;		THIS FUNCTION ROUNDS NUMBERS TO THE SPECIFIED NUMBER OF DECIMAL PLACES AND RETURNS STRING VALUES;
;
; CATEGORY:
;		NUMERIC
;
; CALLING SEQUENCE:
;		 RESULT = ROUNDS(VALUES)
;
; INPUTS:
;		VALUE: NUMERIC OR STRING
;		
; KEYWORD PARAMETERS:
;   DOWN: ROUNDS THE VALUES DOWN INSTEAD OF UP [1.5 BECOMES 1 INSTEAD OF 2]
;   SIG: MAKE DECIMAL_PLACES THE TOTAL NUMBER OF SIGNIFICANT DIGITS IN THE RESULT
;
; OUTPUTS:
;   THIS FUNCTION RETURNS A STRING WITH THE SPECIFIED DECIMAL_PLACES [OR SIGNIFICANT DIGITS]

; OPTIONAL INPUTS:
;		DECIMAL_PLACES: THE NUMBER OF DECIMAL PLACES TO USE IN ROUNDING
;										(IF DECIMAL_PLACES NOT PROVIDED THEN ZERO DECIMAL PLACES ARE ASSUMED BY THIS ROUTINE
;										AND THE VALUES ARE ROUNDED TO THE NEAREST INTEGER NUMBER)
;
; RESTRICTIONS:
;			VALUES MUST BE NUMERIC OR STRING
;
;
; PROCEDURE:
;			FLOATING-POINT AND DOUBLE-PRECISION NUMBERS ARE CONVERTED TO STRING 
;			USING IDL'S FORMAT WHICH AUTOMATICALLY ROUNDS THE VALUES TO THE 
;			NUMBER OF DECIMAL PLACES SPECIFIED IN THE FORMAT.
;
;
; EXAMPLES:
; P,ROUNDS(9998.12345)
; P,ROUNDS(9998.12345,5); NOTICE IMPRECISION OF FLOATING DATA TYPE
; P,ROUNDS(9998.12345D,5); DOUBLE IS BETTER
; P,ROUNDS(9998.12345D,4)
; P,ROUNDS(1.5)
; P,ROUNDS(1.5,/DOWN)
; P,ROUNDS(1.5,2)
; P,ROUNDS(1.5,2,/DOWN)
; P,ROUNDS(9998.12345D,3,/SIG);3 SIGNIFICANT DIGITS 
; P,ROUNDS(9998.12345D,4,/SIG);4 SIGNIFICANT DIGITS ; 
; P,ROUNDS(9998.12345D,5,/SIG);5 SIGNIFICANT DIGITS ; 
; P,ROUNDS(9998.12345D,6,/SIG);6 SIGNIFICANT DIGITS ; 
; P,ROUNDS(1E6)
; P,ROUNDS(1.12345E6,5)
; P,ROUNDS(380187134)
; 
;
;		THE FOLLOWING TWO EXAMPLES ILLUSTRATE WHY DOUBLE-PRECISION IS THE PREFERED INPUT DATA TYPE FOR VALUES,
;		PARTICULARLY WHEN THE INPUT VALUES ARE LARGE AND WHEN YOU WANT ROUNDING TO SEVERAL DECIMAL PLACES
;
;		RESULT=ROUNDS(1234567890.1234567890,5) 	& HELP, RESULT & PRINT,RESULT ; NOTE THE LOSS OF PRECISION WITH FLOATING
;		RESULT=ROUNDS(1234567890.1234567890D,5) & HELP, RESULT & PRINT,RESULT ; NOTE THE RESULT IS CORRECT
;
;		LONG STRINGS ALSO WORK:
;		RESULT=ROUNDS('1234567890.1234567890',5) & HELP, RESULT & PRINT,RESULT
;
;		NOTE THAT IN THIS EXAMPLE WE ASK FOR 10 DECIMAL_PLACES BUT THE ACCURACY FADES AT ABOUT EIGHT DECIMAL PLACES
;		WHEN THE NUMBER IS LARGE.  COMPARE THE ACCURACY OF THE RESULTS FROM THESE TWO EXAMPLES USING A SMALL AND LARGE
;		DOUBLE-PRECISION NUMBER:
;		RESULT=ROUNDS(0.12345678901234567890D,10) & HELP, RESULT & PRINT,RESULT
;		RESULT=ROUNDS(1234567890.12345678901234567890D,10) & HELP, RESULT & PRINT,RESULT
;   RESULT=ROUNDS(1234567890.1) & HELP, RESULT & PRINT,RESULT
;   USING DOWN KEYWORD:
;   RESULT=ROUNDS(1.5,0,/DOWN) & HELP, RESULT & PRINT,RESULT

; NOTES:
;		DOUBLE-PRECISION VALUES ARE THE BEST INPUTS TO THIS ROUTINE TO CONSERVE AS MANY DECIMAL PLACES AS POSSIBLE,
;		PARTICULARLY WITH LARGE VALUES
;
;		THE FOLLOWING IS FROM IDL HELP ON 'DATA TYPES, ABOUT'
;
;		FLOATING-POINT:
;			"A 32-BIT, SINGLE-PRECISION, FLOATING-POINT NUMBER IN THE RANGE OF �10^38,
;			 WITH APPROXIMATELY SIX OR SEVEN DECIMAL PLACES OF SIGNIFICANCE."

;		DOUBLE-PRECISION
;			"A 64-BIT, DOUBLE-PRECISION, FLOATING-POINT NUMBER IN THE RANGE OF �10^308
;			WITH APPROXIMATELY 14 DECIMAL PLACES OF SIGNIFICANCE."
;
; MODIFICATION HISTORY:
;			WRITTEN NOV 21, 2006 BY J.O'REILLY, 28 TARZWELL DRIVE, NMFS, NOAA 02882 (JAY.O'REILLY@NOAA.GOV)
;			AUGUST 30,2010,JOR,FIXED PROBLEM WITH STRING INPUTS,:
;			ADDED IF NUMERIC(VALUES) EQ 1
;     SEP 26,2013,JOR, ADDED KEYWORD SIG [ MAKES THE NUMBER OF DECIMAL_PLACES INTO SIGNIFICANT DIGITS 
;     NOV 21,2013,JOR  ADDED KEYWORD DOWN [ FROM KWH'S VERSION]
;     APR 06,2016,JOR: CHANGED FMT = '(G128.'+STRTRIM(_DECIMAL_PLACES,2)+')' TO
;                              FMT = '(D128.'+STRTRIM(_DECIMAL_PLACES,2)+')' TO AVOID SCIENTIFIC EXPONENTS 
;                              ADDED ADITIONAL SCIENTIFIC NOTATION EXAMPLES
;     JUL 15,2016,JOR:         REMOVED COMMENTED CODE
;     AUG 23,2017, JEOR: FIXED BUG REPORTED BY KIM, CHANGED FLOAT TO DOUBLE ADDED EXAMPLE
;                              TXT=STRTRIM(STRING(ROUND(DOUBLE(_VALUES)), FORMAT=FMT),2)

;##############################################################################################
;-
;***************
ROUTINE='ROUNDS'
;***************

  IF NUMERIC(VALUES) THEN _VALUES = VALUES ELSE _VALUES = DOUBLE(VALUES)
  IF N_ELEMENTS(DOWN) EQ 1 THEN _VALUES= FLOOR(_VALUES)
	IF N_ELEMENTS(DECIMAL_PLACES) NE 1 THEN _DECIMAL_PLACES= 0 ELSE _DECIMAL_PLACES = DECIMAL_PLACES ; ===> IF NO DECIMAL_PLACES ARE PROVIDED THEN ASSUME 0
	_DECIMAL_PLACES = 0 > _DECIMAL_PLACES ;  ===> ENSURE THAT DECIMAL_PLACES ARE NON-NEGATIVE


; ===> IF ZERO DECIMAL PLACES THEN USE THE I FORMAT ELSE USE D FORMAT
IF _DECIMAL_PLACES EQ 0 THEN BEGIN
  FMT = '(I)
  TXT=STRTRIM(STRING(ROUND(DOUBLE(_VALUES)), FORMAT=FMT),2)
ENDIF ELSE BEGIN
  FMT = '(D0.'+STRTRIM(_DECIMAL_PLACES,2)+')'
  TXT=STRTRIM(STRING(_VALUES, FORMAT=FMT),2)
ENDELSE;IF _DECIMAL_PLACES EQ 0 THEN BEGIN
IF KEYWORD_SET(SIG) THEN BEGIN
  FMT = '(D128.'+STRTRIM(_DECIMAL_PLACES,2)+')'
  TXT=STRTRIM(STRING(_VALUES, FORMAT=FMT),2)
ENDIF;IF KEYWORD_SET(SIG) THEN BEGIN
  
RETURN,TXT


END; #####################  END OF ROUTINE ################################
