pro SCALE_INTEGER_DEMO
DATA=[0.000055, .0001, .001, .01, 0.0107, .1,1,10,100,188]
N=N_ELEMENTS(DATA)


PRINT, 'OLD'
PRINT, DATA,FORMAT='('+NUM2STR(N)+'F15.6)
II = -32768 > ROUND((1000*(DATA-32.0))) < 32767
PRINT, II,FORMAT='('+NUM2STR(N)+'I15)
D= II *.001 + 32.
PRINT, D,FORMAT='('+NUM2STR(N)+'F15.6)

PRINT, 'NEW SD SCALES WITH LOG10 TRANSFORM FOR CHLOR_A, DATA2INT'
PRINT, DATA,FORMAT='('+NUM2STR(N)+'F15.6)
II=sd_scales(prod='chlor_a',DATA,/data2int)
PRINT, II,FORMAT='('+NUM2STR(N)+'I15)
D=sd_scales(prod='chlor_a',II,/INT2DATA)
PRINT, D,FORMAT='('+NUM2STR(N)+'F15.6)


DD=[1.0 +FINDGEN(1000)*1E-5]

II=sd_scales(prod='chlor_a',DD,/data2int)
D	=sd_scales(prod='chlor_a',II,/INT2DATA) & PLOT,(DD-D)/DD


PRINT
PRINT
N=N_ELEMENTS(DATA)
PRINT,'DATA'
PRINT, DATA,FORMAT='('+NUM2STR(N)+'F15.6)
PRINT
; ===> Checking transformation
PRINT,'DATA2INT'
II=sd_scales(prod='chlor_a',DATA,/data2int,SCALING=SCALING,SLOPE=SLOPE,INTERCEPT=INTERCEPT,TRANSFORMATION=TRANSFORMATION)
PRINT, SCALING,TRANSFORMATION,SLOPE,INTERCEPT
PRINT, II,FORMAT='('+NUM2STR(N)+'I15)
PRINT

PRINT,'INT2DATA'
D=sd_scales(prod='chlor_a',II,/INT2DATA,SCALING=SCALING,SLOPE=SLOPE,INTERCEPT=INTERCEPT,TRANSFORMATION=TRANSFORMATION)
PRINT,SCALING,TRANSFORMATION,SLOPE,INTERCEPT
PRINT, D,FORMAT='('+NUM2STR(N)+'F15.6)
PRINT

PRINT, 'DATA2BIN'
B=sd_scales(prod='chlor_a',DATA,/DATA2BIN,SCALING=SCALING,SLOPE=SLOPE,INTERCEPT=INTERCEPT,TRANSFORMATION=TRANSFORMATION)
PRINT, SCALING,TRANSFORMATION,SLOPE,INTERCEPT
PRINT, B,FORMAT='('+NUM2STR(N)+'I15)
PRINT

PRINT, 'BIN2DATA'
DD=sd_scales(prod='chlor_a',B,/BIN2DATA,SCALING=SCALING,SLOPE=SLOPE,INTERCEPT=INTERCEPT,TRANSFORMATION=TRANSFORMATION)
PRINT, SCALING,TRANSFORMATION,SLOPE,INTERCEPT
PRINT, DD,FORMAT='('+NUM2STR(N)+'F15.6)

END
