; $ID:	SST_MODIS_1KM_EDIT_MASK_MAIN.PRO,	2020-06-26-15,	USER-KJWH	$
PRO SST_MODIS_1KM_EDIT_MASK_MAIN

; read save file, can write out browse with l2 flags, with no l2 flags, with QUAL1 or QUAL2 masking
;
MAP='NEC'

DO_MASK_PNG         =0   ; MAKE PNG FROM MASK IMAGE IN THE SAVE FILE, COLORS SPECIFIED IN THE STEP BELOW
DO_NO_MASK_PNG			=0   ; MAKE PNG FROM DATA IMAGE, SPECIFY /NO_MASK KEYWORD IN STRUCT_SD_2IMAGE
DO_QUAL1_PNG        =0	 ; MAKE PNG FROM DATA IMAGE, MASK OUT PIXELS WHERE FLAG CODE GT 1
DO_QUAL2_PNG        =0   ; MAKE PNG FROM DATA IMAGE, MASK OUT PIXELS WHERE FLAG CODE GT 2

DO_QUAL2_DILATE_PNG =0   ; MAKE PNG FROM DATA IMAGE, DILATE PIXELS WHERE FLAG CODE EQ 3



DO_MAKE_EDIT_MASK   =0
DO_NEW_EDIT_SAVE    =1   ; APPLY CHANGES TO THE MASK ARRAY



DIR_SAVE='T:\SST-MODIS-1KM-NEC\SAVE\'


STOP
;files =file_search('t:\sst_COMPARE\browse\!S_2007*4UM.png')

FLAG_COLOR=254B
LAND_COLOR=252B

IF MAP EQ 'NEC' THEN LANDMASK_FILE='D:\IDL\IMAGES\MASK_LAND-NEC-PXY_1024_1024.PNG'
LANDMASK=READ_PNG(LANDMASK_FILE)
OK_LAND=WHERE(LANDMASK NE 0,COUNT_LAND)

IF DO_MASK_PNG GE 1 OR DO_NO_MASK_PNG GE 1 OR DO_QUAL1_PNG GE 1 OR DO_QUAL2_PNG GE 1 $
												OR DO_QUAL2_DILATE_PNG GE 1 THEN BEGIN

	FOR  _file=0,n_elements(files)-1l do begin

		FN=FILE_ALL(FILES(_FILE))
		DT= PERIOD_FORMAT(FN.PERIOD,/BELOW,/NAME,/SHORT)

	; find corresponding save file
	  SAVEFILE=STRUPCASE(DIR_SAVE+FN.NAME_EXT)
	  SAVEFILE=REPLACE(SAVEFILE,'.PNG','.SAVE')

		struct=READALL(SAVEFILE)
		QUAL_IMAGE=struct.SST.MASK

		IF DO_MASK_PNG GE 1 THEN BEGIN
		; write png for MASK
			_PAL='PAL_36'
			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-MASK.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'MASK'
			BIMAGE=QUAL_IMAGE
			BIMAGE(0:*)=0B
			OK_QUAL_0 = WHERE(QUAL_IMAGE EQ 0, COUNT_QUAL_0)
		  OK_QUAL_1 = WHERE(QUAL_IMAGE EQ 1, COUNT_QUAL_1)
		  OK_QUAL_2 = WHERE(QUAL_IMAGE EQ 2, COUNT_QUAL_2)
		  OK_QUAL_3 = WHERE(QUAL_IMAGE EQ 3, COUNT_QUAL_3)
		  OK_QUAL_4 = WHERE(QUAL_IMAGE EQ 4, COUNT_QUAL_4)
		  OK_QUAL_5 = WHERE(QUAL_IMAGE EQ 5, COUNT_QUAL_5)
		  OK_QUAL_6 = WHERE(QUAL_IMAGE EQ 6, COUNT_QUAL_6)

		;  our SST-MODIS-1KM-NEC saves contain mask image for QUAL1 where CODEs 0B 1B designate good data
		;		===> NOT_MASK (good data , 0b)
			;	CODE_NAME = 'NOT_MASK'	   ACODE = 0B
		  ; CODE_NAME = 'NOT_MASK'     ACODE = 1B
			;	CODE_NAME = 'SUSPECT_SST'  ACODE = 2B
			; CODE_NAME = 'BAD_SST'      ACODE = 3B
			;	CODE_NAME = 'SST_FAIL'     ACODE = 4B
			; CODE_NAME = 'L2_FLAGS'     ACODE = 5B
		 	; CODE_NAME = 'LAND'         ACODE = 6B
		  IF COUNT_QUAL_0 GE 1 THEN BIMAGE(OK_QUAL_0) = 3B
		  IF COUNT_QUAL_1 GE 1 THEN BIMAGE(OK_QUAL_1) = 5B
		  IF COUNT_QUAL_2 GE 1 THEN BIMAGE(OK_QUAL_2) = 15B
		  IF COUNT_QUAL_3 GE 1 THEN BIMAGE(OK_QUAL_3) = 20B
			IF COUNT_QUAL_4 GE 1 THEN BIMAGE(OK_QUAL_4) = 25B
		  IF COUNT_QUAL_5 GE 1 THEN BIMAGE(OK_QUAL_5) = 32B
		  IF COUNT_QUAL_6 GE 1 THEN BIMAGE(OK_QUAL_6) = 35B

			BIMAGE = MAP_ADD_TXT(BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
			CALL_PROCEDURE,_PAL,R,G,B
			PRINT, 'WRITING: '+PNGFILE
			WRITE_PNG,PNGFILE,BIMAGE,R,G,B
		ENDIF;		IF DO_MASK_PNG GE 1 THEN BEGIN

		IF DO_NO_MASK_PNG GE 1 THEN BEGIN
		; write png with NO MASK APPLIED
			_PAL='PAL_SW3'
			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-no_mask.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'no mask'
			BIMAGE=struct_sd_2image(struct,/no_mask)
			_BIMAGE=BIMAGE
			_BIMAGE(OK_LAND)=LAND_COLOR
			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)

			CALL_PROCEDURE,_PAL,R,G,B
			PRINT, 'WRITING: '+PNGFILE
			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
		ENDIF;		IF DO_NO_MASK_PNG GE 1 THEN BEGIN

		IF DO_QUAL1_PNG GE 1 THEN BEGIN
	; 	write png with qual1 masking mask code GT 1
			_PAL='PAL_SW3'
			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL1.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL1 mask'
			_BIMAGE=BIMAGE
			ok_qual1=where(qual_image GT 1,count)
			IF COUNT GE 1 THEN _BIMAGE(OK_QUAL1)=FLAG_COLOR
			_BIMAGE(OK_LAND)=LAND_COLOR
			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
			CALL_PROCEDURE,_PAL,R,G,B
			PRINT, 'WRITING: '+PNGFILE
			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
		ENDIF;		IF DO_QUAL1_PNG GE 1 THEN BEGIN

		IF DO_QUAL2_PNG GE 1 THEN BEGIN
	; 	write png with qual2 masking mask code GT 2
			_PAL='PAL_SW3'
			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2 mask'
			ok_qual2=where(qual_image GT 2,count)
			_BIMAGE=BIMAGE
			IF COUNT GE 1 THEN _BIMAGE(OK_QUAL2)=FLAG_COLOR
			_BIMAGE(OK_LAND)=LAND_COLOR
			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
			CALL_PROCEDURE,_PAL,R,G,B
			PRINT, 'WRITING: '+PNGFILE
			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
		ENDIF;		IF DO_QUAL2_PNG GE 1 THEN BEGIN


		IF KEYWORD_SET(DO_QUAL2_DILATE_PNG) THEN BEGIN
;	; 	write png with qual2 masking mask code 3 DILATED
			_PAL='PAL_SW3'
			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2_DILATED_3.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2_dilated_3 mask'
			BIMAGE=struct_sd_2image(struct,/no_mask)
			_BIMAGE=BIMAGE
			_QUAL_IMAGE=QUAL_IMAGE
;			ok_qual2=where(_qual_image GT 2,count)
;			_QUAL_IMAGE(OK_QUAL2)=3
;			CLOUDIER, IMAGE=_QUAL_IMAGE,CLOUDS=3,MASK=MASK,BOX=3,/QUIET
;			OK_CLOUD = WHERE(MASK EQ 1,COUNT_CLOUD)
;
;			IF COUNT_CLOUD GE 1 THEN _BIMAGE(OK_CLOUD)=FLAG_COLOR
;			_BIMAGE(OK_LAND)=LAND_COLOR
;			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
;			CALL_PROCEDURE,_PAL,R,G,B
;			PRINT, 'WRITING: '+PNGFILE
;			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
;
;
;			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2_DILATED_4.PNG'
;			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2_dilated_4 mask'
;			_BIMAGE=BIMAGE
;			_QUAL_IMAGE=QUAL_IMAGE
;			ok_qual2=where(_qual_image GT 2,count)
;			_QUAL_IMAGE(OK_QUAL2)=3
;			CLOUDIER, IMAGE=_QUAL_IMAGE,CLOUDS=3,MASK=MASK,BOX=4,/QUIET
;			OK_CLOUD = WHERE(MASK EQ 1,COUNT_CLOUD)
;
;			IF COUNT_CLOUD GE 1 THEN _BIMAGE(OK_CLOUD)=FLAG_COLOR
;			_BIMAGE(OK_LAND)=LAND_COLOR
;			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
;			CALL_PROCEDURE,_PAL,R,G,B
;			PRINT, 'WRITING: '+PNGFILE
;			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
;
;			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2_DILATED_5.PNG'
;			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2_dilated_5 mask'
;			_BIMAGE=BIMAGE
;			_QUAL_IMAGE=QUAL_IMAGE
;			ok_qual2=where(_qual_image GT 2,count)
;			_QUAL_IMAGE(OK_QUAL2)=3
;			CLOUDIER, IMAGE=_QUAL_IMAGE,CLOUDS=3,MASK=MASK,BOX=5,/QUIET
;			OK_CLOUD = WHERE(MASK EQ 1,COUNT_CLOUD)
;
;			IF COUNT_CLOUD GE 1 THEN _BIMAGE(OK_CLOUD)=FLAG_COLOR
;			_BIMAGE(OK_LAND)=LAND_COLOR
;			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
;			CALL_PROCEDURE,_PAL,R,G,B
;			PRINT, 'WRITING: '+PNGFILE
;			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B
;
;			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2_DILATED_6.PNG'
;			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2_dilated_6 mask'
;			_BIMAGE=BIMAGE
;			_QUAL_IMAGE=QUAL_IMAGE
;			ok_qual2=where(_qual_image GT 2,count)
;			_QUAL_IMAGE(OK_QUAL2)=3
;			CLOUDIER, IMAGE=_QUAL_IMAGE,CLOUDS=3,MASK=MASK,BOX=6,/QUIET
;			OK_CLOUD = WHERE(MASK EQ 1,COUNT_CLOUD)
;
;			IF COUNT_CLOUD GE 1 THEN _BIMAGE(OK_CLOUD)=FLAG_COLOR
;			_BIMAGE(OK_LAND)=LAND_COLOR
;			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
;			CALL_PROCEDURE,_PAL,R,G,B
;			PRINT, 'WRITING: '+PNGFILE
;			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B

			PNGFILE='T:\SST_COMPARE\BROWSE\'+FN.NAME+'-QUAL2_DILATED_10.PNG'
			LABEL=DT+'!C'+'MODIS-4um-1km'+'!C'+'QUAL2_dilated_10 mask'
			_BIMAGE=BIMAGE
			_QUAL_IMAGE=QUAL_IMAGE
			ok_qual2=where(_qual_image GT 2,count)
			_QUAL_IMAGE(OK_QUAL2)=3
			CLOUDIER, IMAGE=_QUAL_IMAGE,CLOUDS=3,MASK=MASK,BOX=10,/QUIET
			OK_CLOUD = WHERE(MASK EQ 1,COUNT_CLOUD)

			IF COUNT_CLOUD GE 1 THEN _BIMAGE(OK_CLOUD)=FLAG_COLOR
			_BIMAGE(OK_LAND)=LAND_COLOR
			_BIMAGE = MAP_ADD_TXT(_BIMAGE,0.01,0.75,LABEL, 	COLOR=0,charsize=(4.0*FLOAT(1024)/1024),CHARTHICK=2)
			CALL_PROCEDURE,_PAL,R,G,B
			PRINT, 'WRITING: '+PNGFILE
			WRITE_PNG,PNGFILE,_BIMAGE,R,G,B

		ENDIF;IF KEYWORD_SET(DO_QUAL2_DILATE_PNG) THEN BEGIN

		BIMAGE=''
		_BIMAGE=''
		QUAL_IMAGE=''
		struct=''
	ENDFOR
ENDIF;IF DO_MASK_PNG GE 1 OR DO_NO_MASK_PNG GE 1 OR DO_QUAL1_PNG GE 1 OR DO_QUAL2_PNG GE 1 OR DO_QUAL2_DILATE_PNG GE 1 THEN BEGIN







IF DO_MAKE_EDIT_MASK EQ 1 THEN BEGIN

	; THIS PROCESS IS NOT AUTOMATED AT THIS TIME.
	; OPEN *NO_MASK.PNG IN PAINT , WHITE OUT ALL AREAS LEAVING ONLY GOOD DATA INTACT.
	;    SAVE RESULT IN PNGFILE WITH NAME*-MASK_EDIT.PNG , Place them in \MASK_EDIT\ folder

	STOP
ENDIF

IF KEYWORD_SET(DO_NEW_EDIT_SAVE) GE 1 THEN BEGIN

STOP
	DIR_SAVE='T:\SST-MODIS-1KM-NEC\SAVE\'
	DIR_OUT_SAVE='T:\SST_COMPARE\SAVE_EDIT\'
	DIR_OUT_BROWSE='T:\SST_COMPARE\BROWSE\'
	files =file_search('t:\sst_COMPARE\MASK_EDIT\!S_2007*-MASK_EDIT.png')
	LANDMASK = READ_LANDMASK(MAP=MAP,/LAND)
	OK_LAND=WHERE(LANDMASK NE 0,COUNT_LAND)
	FOR  _file=0,n_elements(files)-1l do begin
		MASK_EDIT_PNG=FILES(_FILE)
		FN=FILE_ALL(MASK_EDIT_PNG)
	;	DT= PERIOD_FORMAT(FN.PERIOD,/BELOW,/NAME,/SHORT)
	;	LABEL=DT+'!C'+'SST' + '!C'+'some QUAL1 unmasked '
	; find corresponding save file
	  SAVEFILE=STRUPCASE(DIR_SAVE+FN.NAME_EXT)
	  SAVEFILE=REPLACE(SAVEFILE,'-MASK_EDIT.PNG','.SAVE')
	  NEW_SAVE_FILE=SAVEFILE
	  NEW_SAVE_FILE=REPLACE(NEW_SAVE_FILE,DIR_SAVE,DIR_OUT_SAVE)
	  NEW_SAVE_FILE=REPLACE(NEW_SAVE_FILE,'.SAVE','-EDIT.SAVE')
		exist=FILE_TEST(SAVEFILE)
		IF EXIST EQ 1 THEN BEGIN
			fn_out=file_all(NEW_SAVE_FILE)
			IF FN.MTIME LT FN_OUT.MTIME THEN CONTINUE
			struct=READALL(SAVEFILE)
			MASK=READALL(MASK_EDIT_PNG)
			OK=WHERE(MASK NE 255B AND (LANDMASK EQ 0B AND STRUCT.SST.MASK LT 5B),COUNT)
			IF COUNT GT 1 THEN BEGIN
				struct.SST.MASK[OK]=0B
				SAVE,FILENAME=NEW_SAVE_FILE,STRUCT,/COMPRESS
				STRUCT_SD_2PNG,NEW_SAVE_FILE,DIR_OUT=DIR_OUT_BROWSE,/ADD_LAND,/ADD_COLORBAR,/ADD_PROD,/ADDDATE
			ENDIF
		ENDIF;IF EXIST EQ 1 THEN BEGIN

	ENDFOR;FOR _FILE

ENDIF; IF KEYWORD_SET(DO_NEW_EDIT_SAVE)




DONE:
END
