; $ID:	STATS_PHENOLOGY_LME_PAGE.PRO,	2020-07-08-15,	USER-KJWH	$
;#############################################################################################################
	PRO STATS_PHENOLOGY_LME_PAGE,FILE,DIR_OUT = DIR_OUT,PAGE_TITLE=PAGE_TITLE,LABEL=LABEL
	
;  PRO STATS_PHENOLOGY_LME_PAGE
;+
; NAME:
;		STATS_PHENOLOGY_LME_PAGE
;
; PURPOSE: THIS PROGRAM PLOTS A PAGE WITH  THE MONTH  OF THE MIN AND MAX FOR THE LMES
;
; CATEGORY:
;		PLOTS
;		 
;
; CALLING SEQUENCE:STATS_PHENOLOGY_LME_PAGE
;
; INPUTS: 
; ; FILE:E.G. FILE = 'I:\SMI\CHL_STATS_PERIOD\TAG_Y-CHLOR_A.CSV'
;		
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		DIR_OUT: OUTPUT DIRECTORY
;   DIR_OUT: OUTPUT DIRECTORY
; OUTPUTS:  STRUCT_SD_WRITE,SAVEFILE [MONTH MIN, MONTH MAX]
;		
;; EXAMPLES:
;  STATS_PHENOLOGY_LME_PAGE
;	NOTES:
;	
; MODIFICATION HISTORY:
;			WRITTEN JULY 18,2013 J.O'REILLY

;#################################################################################
;-
;	*******************************************
ROUTINE_NAME='STATS_PHENOLOGY_LME_PAGE'
; *******************************************
; XYOUTS FRAME  CV CHARSIZE  ENDFOR SWITCHES  RETURN    ,
; 

IF N_ELEMENTS(FILE) NE 1 THEN MESSAGE,'ERROR:   FILE IS REQUIRED'
FA = FILE_ALL(FILE)
PROD = VALIDS('PRODS',FA.PROD)

DB = CSV_READ(FILE) & PN,DB,'RECORDS'
SETS = WHERE_SETS(DB.LME) & PN,SETS,'N SETS' & IF N_ELEMENTS(SETS) NE 63 THEN STOP

;SSS SWITCHES SSS
DO_SYM = 1
;===> CONSTANTS
YEAR_CHARSIZE = 1.5
CV_CHARSIZE    = 0.80
NAME_CHARSIZE  = 0.80
!P.CHARSIZE=1.0
;? !P.REGION = 0
!Y.OMARGIN=[6,5]
!X.OMARGIN=[22,4] 
!Y.MINOR=1
!Y.TICKLEN=0.002
SYM_THICK = 21
PAL_36,R,G,B
SETCOLOR,255
IF N_ELEMENTS(PAGE_TITLE) EQ 0 THEN PAGE_TITLE = ROUTINE_NAME
;===> IF OUTPUT DIR_OUTECTORY NOT PROVIDED, WRITE PSFILE TO IDL WORKING DIRECTOTY
IF N_ELEMENTS(DIR_OUT) LT 1 THEN DIR_OUT = GET_DIR() 
IF N_ELEMENTS(LABEL)NE 1 THEN LABEL = ROUTINE_NAME  


IF N_ELEMENTS(GRIDS_COLOR)     NE 1   THEN GRIDS_COLOR    = 0
; ===> STANDARDIZE FOR MONTH LABELS AND GRID LINES (SO VARYING TIME SERIES LENGTHS DO NOT CAUSE STAGGERING OF VERTICAL LINE AT EACH YEAR)
;XJY=DATE_AXIS(['19960101','20140101'],/YEAR,ROOM=[0,1],STEP_SIZE=3,MAX_LABELS=60,/NO_L2_TXT)
XJY=DATE_AXIS(['19960101','20114101'],/YEAR,ROOM=[0,0],STEP_SIZE=1)


PANELS =  N_ELEMENTS(SETS) 
!P.MULTI=[0,1,PANELS]
;!P.MULTI=[0,1,5]

YRANGE = [0,1.0]
Y_MID_RANGE = MEAN(YRANGE)  
TAGS  = ['JD_MIN','JD_MAX']
TAGS  = ['JD_MAX']

;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR _TAGS = 0,N_ELEMENTS(TAGS)-1 DO BEGIN 
  ATAG = TAGS(_TAGS)
  PSFILE = DIR_OUT+LABEL+'-'+ ATAG + '.PS'
  
  ;===> CHANGE PROD TO  MONTH_MAX OR MONTH_MIN FOR COLOR_BAR_SCALE
  IF ATAG EQ 'JD_MIN' THEN USE_PROD ='MONTH_MIN'
  IF ATAG EQ 'JD_MAX' THEN USE_PROD ='MONTH_MAX'
  PSFILE = REPLACE(PSFILE,' ','_')
  PSPRINT,FILENAME=PSFILE,/FULL,/COLOR  
  
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR _SET = 0,N_ELEMENTS(SETS)-1 DO BEGIN
    SET = SETS(_SET)
    LME = SET.VALUE & PFILE,LME,/U
    ANAME = LME
    SUBS = WHERE_SETS_SUBS(SET) & PN,SUBS,' YEARS'
    D = DB(SUBS)
    OK_TAG = WHERE(TAG_NAMES(D) EQ ATAG,COUNT_TAG)
    JD = FLOAT(D.(OK_TAG)) 
    XRANGE = MM(JD) & YTICKS = 1
    MONTHS = JD_2MONTH(JD) &  COLORS = (FIX(MONTHS))
    YY = REPLICATE(Y_MID_RANGE,N_ELEMENTS(JD))
    
    IF _SET EQ N_ELEMENTS(SETS)-1 THEN BEGIN
            XTICKNAME=XJY.TICKNAME
            XTITLE=' '
            ;STOP
    ENDIF ELSE BEGIN
           XTICKNAME =  REPLICATE(' ',N_ELEMENTS(XJY.TICKNAME))
           XTITLE=''
           YTITLE=' '          
    ENDELSE;IF _SET EQ N_ELEMENTS(SETS)-1 THEN BEGIN
   
   
   PLOT,JD,YY,XRANGE=XRANGE,CHARSIZE = YEAR_CHARSIZE,XSTYLE =XSTYLE,$
              XTICKS=XJY.TICKS,XTICKV=XJY.TICKV,XTICKNAME=XTICKNAME,$
              XTITLE=XTITLE,TITLE=TITLE,$
              YTITLE=YTITLE,YRANGE=YRANGE, YSTYLE=4,YTICKS=YTICKS,PSYM=1,$
              XTICK_GET=XTICK_GET,YTICK_GET=YTICK_GET,$
              COLOR = 0,/NODATA
EMPTY
    GRIDS,X=XTICK_GET,YY=YTICK_GET,COLOR=GRIDS_COLOR,THICK = 1,/NO_Y
;   PLOTS,JD,YY,COLOR = COLORS, LINESTYLE = 0,THICK = 21,PSYM = 6, SYMSIZE = 10 & EMPTY & STOP


IF DO_SYM EQ 1 THEN BEGIN
  PLOTS,JD,YY,COLOR = COLORS, THICK = SYM_THICK,PSYM = 6 
ENDIF ELSE BEGIN
   PLOTS,JD,YY,COLOR = COLORS, LINESTYLE = 0,THICK = 21
ENDELSE;IF DO_SYM EQ 1 THEN BEGIN

   XYOUTS,JD,YY,STRTRIM(COLORS,2),/DATA,COLOR = 255,ALIGN = 0.5,CHARSIZE = 0.5 & 
    XPOS_LEFT = !X.CRANGE[0] - 100 ; DAYS
    XPOS_RIGHT= !X.CRANGE[1] + 14 ; DAYS
    
    IF !Y.TYPE EQ 0 THEN BEGIN
            YPOS= 0.30*(!Y.CRANGE[1] - !Y.CRANGE[0])+ !Y.CRANGE[0]+ 0.2
    ENDIF ELSE BEGIN
      YPOS= 10^(0.5* (!Y.CRANGE[1] - !Y.CRANGE[0]) + !Y.CRANGE[0])
         ;   YPOS=  10^( !Y.CRANGE(0))
     ENDELSE
    IF _SET EQ 0 THEN XYOUTS,XPOS_RIGHT-500,YPOS+1.2,' %CV ',ALIGN = -0.90,CHARSIZE = CV_CHARSIZE
  ;       =====> WRITE THE LME NAME IN LEFT COLUMN
          XYOUTS,XPOS_LEFT,YPOS,/DATA, ANAME, CHARSIZE=NAME_CHARSIZE, ALIGN = 1.03,WIDTH=CWIDTH,COLOR=0 & EMPTY
  
  ;       =====> WRITE THE STATS_STRING IN RIGHT COLUMN FOR CV OF MONTHS
          S=STATS(FLOAT(MONTHS),DECIMALS=2,/QUIET)
  ;;         TXT = ROUNDS(_STATS.MEAN,2)
           TXT = ROUNDS(S.CV,0)
           XYOUTS,XPOS_RIGHT,YPOS,/DATA, TXT, CHARSIZE=STATS_CHARSIZE,COLOR=_STATS_COLOR
;       =====> WRITE THE LME NAME IN LEFT COLUMN
          XYOUTS,XPOS_LEFT,YPOS,/DATA, ANAME, CHARSIZE=NAME_CHARSIZE, ALIGN = 1.03,WIDTH=CWIDTH,COLOR=0
;PSPRINT  & STOP
    FRAME, COLOR=0,THICK=1,/PLOT
    EMPTY
 ;     =====> ADD LEGEND
   IF _SET EQ N_ELEMENTS(SETS)-1 THEN BEGIN
     POS = [ !X.WINDOW[0],0.970, !X.WINDOW[1], 0.980]  
     LEG=COLOR_BAR_SCALE(PROD=PROD,USE_PROD=USE_PROD,/TRIM,PY=95,/PS,POS=POS, CHARSIZE=3)
   ENDIF;IF _SET EQ N_ELEMENTS(SETS)-1 THEN BEGIN
    
  ENDFOR;FOR _SET = 0,N_ELEMENTS(SETS)-1 DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  CAPTION,"J.E. O'Reilly",CHARSIZE = 0.25
  PSPRINT & PFILE,PSFILE,/W
ENDFOR;FOR _TAGS = 0,N_ELEMENTS(TAGS)-1 DO BEGIN 
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF



DONE:          
	END; #####################  END OF ROUTINE ################################
