; $ID:	STATS_NORMAL_DEMO.PRO,	2020-07-08-15,	USER-KJWH	$
;#############################################################################################################
	PRO STATS_NORMAL_DEMO
	
;  PRO STATS_NORMAL_DEMO
;+
; NAME:
;		STATS_NORMAL_DEMO
;
; PURPOSE: DEMO FOR STATS_NORMAL
;
; CATEGORY:
;		STATS
;		 
;
; CALLING SEQUENCE: STATS_NORMAL_DEMO
;
; INPUTS: NONE
;		
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		NONE:

; OUTPUTS: 
;		
;; EXAMPLES:
;
;  STATS_NORMAL_DEMO
;
; MODIFICATION HISTORY:
;			WRITTEN SEP 11,2013 J.O'REILLY
;			SEP 23,2013,JOR ADDED STEP DO_1000_TRIALS,DO_VARY_NBINS
;     SEP 28,2013,JOR,ADDED XSQ_VERSUS_N STEP
;     SEP 30,2013,JOR, ADDED STEP DO_QUANTILES
;			
;#################################################################################
;
;-
;**********************************
ROUTINE_NAME  = 'STATS_NORMAL_DEMO'
;**********************************
;RANDOM
;
;SSSSS     SWITCHES     SSSSS
DO_IDL_EXAMPLE                = 0
DO_IDL_ALDER_ROESSLER_EXAMPLE = 0
DO_RANDOM_XSQ_CALC_VS_IDL     = 0
DO_QUANTILES                  = 0
DO_CHISQR_PDF                 = 0
DO_TEST_NORMAL                = 1
DO_1000_TRIALS                = 0
DO_VARY_NBINS                 = 0
PLOT_DO_VARY_NBINS            = 0
DO_GLOBAL                     = 0
DO_GLOBAL_LOGS                = 0
DO_BOX_COX_GLOBAL             = 0
DO_NORTHEAST                  = 0
DO_HISTPLOT_NORMAL            = 0
XSQ_VERSUS_N                  = 0
;SSSSS     SWITCHES     SSSSS

SMI_MISSING_CODE = -32767.0
IDL_MISSING_CODE = MISSINGS(0.0)



;**********************************
IF DO_IDL_EXAMPLE GE 1 THEN BEGIN
;**********************************
;
; DEFINE THE VECTORS OF OBSERVED AND EXPECTED FREQUENCIES:

OBFREQ = [2, 1, 4, 15, 10, 5, 3]
EXFREQ = [0.5, 2.1, 5.9, 10.3, 10.7, 7.0, 3.5]
; TEST THE HYPOTHESIS THAT THE GIVEN OBSERVED FREQUENCIES ARE AN
; ACCURATE APPROXIMATION TO THE EXPECTED FREQUENCY DISTRIBUTION:
RESULT = XSQ_TEST(OBFREQ, EXFREQ)
PRINT, RESULT,'SHOULD BE  3.05040       0.383920'
ENDIF;IF DO_IDL_EXAMPLE GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||

;**********************************
IF DO_IDL_ALDER_ROESSLER_EXAMPLE GE 1 THEN BEGIN
  ;**********************************
  ;ALDER_ROESSLER TABLE 13.1 PAGE 205
  OBFREQ = [13,28,16,10,32,21]
  EXFREQ = [20,20,20,20,20,20]
  PRINT,'OBFREQ-EXFREQ'
  PLIST,OBFREQ-EXFREQ
  PRINT,'(OBFREQ-EXFREQ)^2'
  PLIST,(OBFREQ-EXFREQ)^2
  PRINT,'(OBFREQ-EXFREQ)^2)/EXFREQ'
  PLIST,(1.0*(OBFREQ-EXFREQ)^2)/EXFREQ 
  
  CHISQ = TOTAL((1.0*(OBFREQ-EXFREQ)^2)/EXFREQ )
  R = XSQ_TEST(OBFREQ, EXFREQ)
  CHISQ = R[0]
  PROB = R[1]
  PRINT, '   SHOULD BE  18.70   ',ROUNDS(CHISQ,2)
  PRINT,'SIGNIFICANCE LEVEL AT 0.05P FOR 5 DF IS 11.07'
  PRINT, 'XSQ_TEST YIELDS A PROB OF ' + ROUNDS(PROB,3)
  PRINT, ' SINCE THE CHISQ VALUE OF ' +ROUNDS(CHISQ,2) + '  EXCEEDS 11.07 '
  PRINT,'THE RESULT IS SIGNIFICANT AND THE HYPOTHESIS OF AN HONEST DIE HAS TO BE REJECTED'
 ; PRINT, ROUNDS(PROB,3) +': + ROUNDS(PROB,3) + '   IS LESS THAN 0.05 THE DICE ARE NOT HONEST '
  PRINT
  STOP
ENDIF;IF DO_IDL_ALDER_ROESSLER_EXAMPLE GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||||||||||||||

;*******************************************
IF DO_RANDOM_XSQ_CALC_VS_IDL GE 1 THEN BEGIN
  ;*****************************************
  ;FOLLOWING FORMULA BY ALDER_ROESSLER TABLE 13.1 PAGE 205
  FOR N = 0,9 DO BEGIN
  NUM = 1E3
  NBINS = 10
  DATA      = RANDOMN(SEED,NUM,/DOUBLE)
  EXPECTED  = RANDOMN(SEED, NUM,/DOUBLE)
  
  EXFREQ = DOUBLE(HISTOGRAM(EXPECTED, NBINS  = NBINS))
  OBFREQ = DOUBLE(HISTOGRAM(DATA, NBINS  = NBINS))
  
  
  
  CHISQ_FORM = TOTAL((1.0*(OBFREQ-EXFREQ)^2)/EXFREQ )
  R = XSQ_TEST(OBFREQ, EXFREQ)
  CHISQ = R[0]
  PROB = R[1]
  PRINT,'CHISQ_FORMULA  ', ROUNDS(CHISQ_FORM,2),  '     CHISQ-IDL     ',ROUNDS(CHISQ,3)
  
  PRINT
  WAIT,1
  ENDFOR;
  ;FFFFFFFFFFFFFFFFFFFFFFFFFF
ENDIF;IF DO_RANDOM_XSQ_CALC_VS_IDL GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||||||||||||||

;********************************
IF DO_QUANTILES GE 1 THEN BEGIN
;********************************
  ,'DO_QUANTILES'
  NUMS = DECADES([3,4])
  PSFILE = 'DO_QUANTILES.PS'   
  PSPRINT,FILENAME = PSFILE,/COLOR
  PAL_36
; FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR _NUMS = 0,N_ELEMENTS(NUMS) -1 DO BEGIN
    N=NUMS(_NUMS)
  POF,_NUMS,NUMS
  DATA = RANDOMN(SEED,N,/DOUBLE) & PN,DATA 
  R = STATS_NORMAL(DATA,EXOB=EXOB)
  RSQ = (CORRELATE(EXOB.OBFREQ,EXOB.EXFREQ))^2
  TITLE = 'N = '+STR_COMMA(ROUNDS(R.N)) + ' ;  RSQ = ' + ROUNDS(RSQ,4)
  XTITLE = 'OBSERVED QUANTILES'
  YTITLE = 'EXPECTED QUANTILES'
  
  Q = QUANTILE(DATA,EXOB.EXPECTED,$
              ONE_COLOR=35,$
              ONE_THICK=21,$
              ONE_LINESTYLE=0,$
              GRIDS_LINESTYLE = 1,$
              GRIDS_COLOR=0,$
              GRIDS_THICK = 1,$
              Q_COLOR = 26,$
              Q_THICK = 11,$
              Q_LINESTYLE = 0,$
              XTITLE = XTITLE,YTITLE = YTITLE,TITLE = TITLE)
  ENDFOR;FOR _NUMS = 0,N_ELEMENTS(MUMS) -1 DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

  PSPRINT & PFILE,PSFILE

  ,'DO_QUANTILES'
  
ENDIF;IF DO_QUANTILES GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||


;********************************
IF DO_CHISQR_PDF GE 1 THEN BEGIN
;********************************

;USE THE FOLLOWING COMMAND TO COMPUTE THE PROBABILITY THAT A RANDOM VARIABLE X, FROM THE CHI-SQUARE DISTRIBUTION WITH THREE DEGREES OF FREEDOM, IS LESS THAN OR EQUAL TO 6.25. THE RESULT SHOULD BE 0.899939.
PRINT,'PROBABILITY THAT A RANDOM VARIABLE X, FROM THE CHI-SQUARE DISTRIBUTION WITH THREE DEGREES OF FREEDOM, IS LESS THAN OR EQUAL TO 6.25.'
PRINT, CHISQR_PDF(6.25, 3)

;IDL PRINTS:0.899939
;COMPUTE THE PROBABILITY THAT A RANDOM VARIABLE X FROM THE CHI-SQUARE DISTRIBUTION WITH THREE DEGREES OF FREEDOM, IS GREATER THAN 6.25. THE RESULT SHOULD BE 0.100061.
PRINT,'PROBABILITY THAT A RANDOM VARIABLE X FROM THE CHI-SQUARE DISTRIBUTION WITH THREE DEGREES OF FREEDOM, IS GREATER THAN 6.25.'
PRINT, 1 - CHISQR_PDF(6.25, 3)

;IDL PRINTS:0.100061

;T = 'ADLER & ROESSLER,1968,PROBABILITY AND STATISTICS TABLE 4, P 300:301'
;V= [14.95,16.31,18.49,20.60,23.36,25.51,29.34,33.53,36.25,40.26,43.77,47.96,50.89,59.70] & DF = 30 & X2=CHISQR_PDF(V, DF) & PRINT,ROUNDS(1-X2,2) & P,ROUNDS(1-LAST(X2),3)

ENDIF;IF DO_CHISQR_PDF GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||


;***************************
IF DO_GLOBAL GE 1 THEN BEGIN
;***************************
  ;===> GET THE BEST AQUA COVERAGE [2002252] 
  DATA = IDL_RESTORE('STATS_NORMAL_DEMO-GLOBAL-AQUA.SAVE') & GOTO,SKIP
  DIR = GET_DIRS()
  FILE = FILE_SEARCH(DIR.BZ2, 'A2002252*.L3m_DAY_CHL_chlor_a_9km.bz2') & PFILE,FILE,/X
  
  D=READHDF(FILE)
  
  DATA =D.L3M_DATA * D.SLOPE[0]+ D.INTERCEPT[0]
  HDF_DATA_MINIMUM = D.DATA_MINIMUM
  HDF_DATA_MAXIMUM = D.DATA_MAXIMUM
  
  OK = WHERE(DATA NE SMI_MISSING_CODE,COUNT)
  IF COUNT GE 1 THEN BEGIN
    DATA_MINIMUM = MIN(DATA[OK])
    DATA_MAXIMUM = MAX(DATA[OK])
  ENDIF;IF COUNT GE 1 THEN BEGIN
  
  OK=WHERE(DATA EQ SMI_MISSING_CODE ,COUNT)
  IF COUNT GE 1 THEN DATA[OK] = IDL_MISSING_CODE
  OK = WHERE(DATA NE MISSINGS(DATA),COUNT)
  IF COUNT GE 1 THEN DATA=DATA[OK]
  ;S=STATS(DATA)
  ;DATA = SUBSAMPLE(DATA,1000)
  ;R= STATS_NORMAL(DATA) & ST,R
  ;R= STATS_NORMAL(ALOG(DATA)) & ST,R
  ;; R=MD_TEST(DATA, MDC = mdc) & P,R
  
  
  SKIP:
  
  PAGE_TITLE = 'GLOBAL CHL  AQUA:'+ DATE_FORMAT(SATDATE_2DATE('A2002252'),/YMD) 

  SET_PMULTI,2
  ;===> PLOT DATA
  PSFILE = GET_DIR() + ROUTINE_NAME + '-DO_GLOBAL.PS'
  PAL_36
  FONT_HELVETICA
  PSPRINT,FILENAME = PSFILE,/COLOR,/FULL
  TITLE = 'DATA' &   XTITLE = TITLE
;;  SAVE,FILENAME = ROUTINE_NAME + '-GLOBAL-AQUA.SAVE',DATA,/COMPRESS


  HISTPLOT,     DATA,BINSIZE=0.1,XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=13,CUM_THICK = 7,CUM_COLOR = 6,TITLE = TITLE,XTITLE = XTITLE,STATS_CHARSIZE = 2,PARAMS = [26,0,1,3,8,14],DECIMALS = 4;,XTITLE = UNITS('CHLOR_A')
  
  S=STATS(DATA) & M=S.MEAN & ABOVE = WHERE(DATA GE M,COUNT_ABOVE)& BELOW = WHERE(DATA LT M,COUNT_BELOW) & PCT_ABOVE = ROUNDS(100.0*COUNT_ABOVE/N_ELEMENTS(DATA),2)& PCT_BELOW = ROUNDS(100.0*COUNT_BELOW/N_ELEMENTS(DATA),2)
  PCT_ABOVE = '% ABOVE MEAN:  ' + PCT_ABOVE & PCT_BELOW = '% BELOW MEAN:  ' + PCT_BELOW
  TXT = PCT_ABOVE + '!C'+ PCT_BELOW
  XY = COORD_2PLOT(0.8,0.8,/TO_DATA)
  XYOUTS,XY.X,XY.Y,/DATA,TXT,CHARSIZE = 1,ALIGN = 0.5
  XYOUTS,0.5,0.999,/NORMAL,PAGE_TITLE,CHARSIZE = 1.5,ALIGN = 0.5
  
  ;######
  ;===> PLOT ALOG (DATA)
TITLE = 'ALOG(DATA)' &   XTITLE = TITLE
  
  
  HISTPLOT,ALOG(DATA),BINSIZE=0.1,XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=13,CUM_THICK = 7,CUM_COLOR = 6,TITLE = TITLE,XTITLE = XTITLE,STATS_CHARSIZE = 2,PARAMS = [26,0,1,3,8,14],DECIMALS = 4;,XTITLE = UNITS('CHLOR_A')
  
  
  S=STATS(ALOG(DATA)) & M=S.MEAN & ABOVE = WHERE(ALOG(DATA) GE M,COUNT_ABOVE) & BELOW = WHERE(ALOG(DATA) LT M,COUNT_BELOW) & PCT_ABOVE = ROUNDS(100.0*COUNT_ABOVE/N_ELEMENTS(DATA),2)& PCT_BELOW = ROUNDS(100.0*COUNT_BELOW/N_ELEMENTS(DATA),2)
 PCT_ABOVE = '% ABOVE MEAN:  ' + PCT_ABOVE & PCT_BELOW = '% BELOW MEAN:  ' + PCT_BELOW
  TXT = PCT_ABOVE + '!C'+ PCT_BELOW
  XY = COORD_2PLOT(0.8,0.8,/TO_DATA)
  XYOUTS,XY.X,XY.Y,/DATA,TXT,CHARSIZE = 1,ALIGN = 0.5
  
  XYOUTS,0.5,0.999,/NORMAL,PAGE_TITLE,CHARSIZE = 1.5,ALIGN = 0.5
 
  PSPRINT& PFILE,PSFILE 
    


ENDIF;IF DO_GLOBAL GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||

;***************************
IF DO_GLOBAL_LOGS GE 1 THEN BEGIN
  ;***************************
  ;===> GET THE BEST AQUA COVERAGE [2002252]
  DATA = IDL_RESTORE('STATS_NORMAL_DEMO-GLOBAL-AQUA.SAVE') & GOTO,SKIP2
  DIR = GET_DIRS()
  FILE = FILE_SEARCH(DIR.BZ2, 'A2002252*.L3m_DAY_CHL_chlor_a_9km.bz2') & PFILE,FILE,/X
  
  D=READHDF(FILE)
  
  DATA =D.L3M_DATA * D.SLOPE[0]+ D.INTERCEPT[0]
  HDF_DATA_MINIMUM = D.DATA_MINIMUM
  HDF_DATA_MAXIMUM = D.DATA_MAXIMUM
  
  OK = WHERE(DATA NE SMI_MISSING_CODE,COUNT)
  IF COUNT GE 1 THEN BEGIN
    DATA_MINIMUM = MIN(DATA[OK])
    DATA_MAXIMUM = MAX(DATA[OK])
  ENDIF;IF COUNT GE 1 THEN BEGIN
  
  OK=WHERE(DATA EQ SMI_MISSING_CODE ,COUNT)
  IF COUNT GE 1 THEN DATA[OK] = IDL_MISSING_CODE
  OK = WHERE(DATA NE MISSINGS(DATA),COUNT)
  IF COUNT GE 1 THEN DATA=DATA[OK]
  ;S=STATS(DATA)
  ;DATA = SUBSAMPLE(DATA,1000)
  ;R= STATS_NORMAL(DATA) & ST,R
  ;R= STATS_NORMAL(ALOG(DATA)) & ST,R
  ;; R=MD_TEST(DATA, MDC = mdc) & P,R
  SKIP2:
  PAGE_TITLE = 'GLOBAL CHL  AQUA:'+ DATE_FORMAT(SATDATE_2DATE('A2002252'),/YMD)
  
  SET_PMULTI,2
  ;===> PLOT DATA
  PSFILE = GET_DIR() + ROUTINE_NAME + '-DO_GLOBAL_LOGS.PS'
  PAL_36
  FONT_HELVETICA
  PSPRINT,FILENAME = PSFILE,/COLOR,/FULL
  TITLE = 'DATA' &   XTITLE = TITLE
  ;;  SAVE,FILENAME = ROUTINE_NAME + '-GLOBAL-AQUA.SAVE',DATA,/COMPRESS
  
  
  HISTPLOT,     DATA,BINSIZE=0.1,XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=13,CUM_THICK = 7,CUM_COLOR = 6,TITLE = TITLE,XTITLE = XTITLE,STATS_CHARSIZE = 2,PARAMS = [26,0,1,3,8,14],DECIMALS = 4;,XTITLE = UNITS('CHLOR_A')
  
  S=STATS(DATA) & M=S.MEAN & ABOVE = WHERE(DATA GE M,COUNT_ABOVE)& BELOW = WHERE(DATA LT M,COUNT_BELOW) & PCT_ABOVE = ROUNDS(100.0*COUNT_ABOVE/N_ELEMENTS(DATA),2)& PCT_BELOW = ROUNDS(100.0*COUNT_BELOW/N_ELEMENTS(DATA),2)
  PCT_ABOVE = '% ABOVE MEAN:  ' + PCT_ABOVE & PCT_BELOW = '% BELOW MEAN:  ' + PCT_BELOW
  TXT = PCT_ABOVE + '!C'+ PCT_BELOW
  XY = COORD_2PLOT(0.8,0.8,/TO_DATA)
  XYOUTS,XY.X,XY.Y,/DATA,TXT,CHARSIZE = 1,ALIGN = 0.5
  XYOUTS,0.5,0.999,/NORMAL,PAGE_TITLE,CHARSIZE = 1.5,ALIGN = 0.5
  
  ;######
  ;===> PLOT ALOG (DATA)
  TITLE = 'ALOG(DATA)' &   XTITLE = TITLE
  
  
  HISTPLOT,ALOG(DATA),BINSIZE=0.1,XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=13,CUM_THICK = 7,CUM_COLOR = 6,TITLE = TITLE,XTITLE = XTITLE,STATS_CHARSIZE = 2,PARAMS = [26,0,1,3,8,14],DECIMALS = 4;,XTITLE = UNITS('CHLOR_A')
  
  
  S=STATS(ALOG(DATA)) & M=S.MEAN & ABOVE = WHERE(ALOG(DATA) GE M,COUNT_ABOVE) & BELOW = WHERE(ALOG(DATA) LT M,COUNT_BELOW) & PCT_ABOVE = ROUNDS(100.0*COUNT_ABOVE/N_ELEMENTS(DATA),2)& PCT_BELOW = ROUNDS(100.0*COUNT_BELOW/N_ELEMENTS(DATA),2)
  PCT_ABOVE = '% ABOVE MEAN:  ' + PCT_ABOVE & PCT_BELOW = '% BELOW MEAN:  ' + PCT_BELOW
  TXT = PCT_ABOVE + '!C'+ PCT_BELOW
  XY = COORD_2PLOT(0.8,0.8,/TO_DATA)
  XYOUTS,XY.X,XY.Y,/DATA,TXT,CHARSIZE = 1,ALIGN = 0.5
  
  XYOUTS,0.5,0.999,/NORMAL,PAGE_TITLE,CHARSIZE = 1.5,ALIGN = 0.5
  
  PSPRINT& PFILE,PSFILE
  
  
  
ENDIF;IF DO_GLOBAL_LOGS GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||
;
;************************************
IF DO_BOX_COX_GLOBAL GE 1 THEN BEGIN
;************************************
;===> PLOT BOX_COX (DATA)
 DATA = IDL_RESTORE('BOX_COX_MAIN-GLOBAL-AQUA.SAVE') & P,MM(DATA)
TITLE = 'BOX_COX(DATA)' &   XTITLE = TITLE
PAGE_TITLE = 'GLOBAL CHL  AQUA:'+ DATE_FORMAT(SATDATE_2DATE('A2002252'),/YMD)

;;B = IMSL_BOXCOXTRANS(DATA, 1, inverse=0, s=1.0, double=1)                  

;LAM =BOX_COX_AMOEBA(DATA,METHOD = 'R2',SCALE = 0.005)

LAM =BOX_COX_AMOEBA(DATA,METHOD = 'R2',SCALE = .1)


TRANSFORMED   = BOX_COX(DATA,  LAM[0]) & ST,STATS(TRANSFORMED)
SET_PMULTI,2
PSFILE = GET_DIR() + ROUTINE_NAME + '-DO_BOX_COX_GLOBAL.PS'
PAL_36
FONT_HELVETICA
PSPRINT,FILENAME = PSFILE,/COLOR,/FULL
HISTPLOT,(TRANSFORMED),BINSIZE=0.1,XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=13,CUM_THICK = 7,CUM_COLOR = 6,TITLE = TITLE,XTITLE = XTITLE,STATS_CHARSIZE = 2,PARAMS = [26,0,1,3,8,14],DECIMALS = 4;,XTITLE = UNITS('CHLOR_A')


S=STATS(TRANSFORMED) & M=S.MEAN & ABOVE = WHERE(TRANSFORMED GE M,COUNT_ABOVE) & BELOW = WHERE(TRANSFORMED LT M,COUNT_BELOW) & PCT_ABOVE = ROUNDS(100.0*COUNT_ABOVE/N_ELEMENTS(TRANSFORMED),2)& PCT_BELOW = ROUNDS(100.0*COUNT_BELOW/N_ELEMENTS(TRANSFORMED),2)
PCT_ABOVE = '% ABOVE MEAN:  ' + PCT_ABOVE & PCT_BELOW = '% BELOW MEAN:  ' + PCT_BELOW
TXT = PCT_ABOVE + '!C'+ PCT_BELOW
XY = COORD_2PLOT(0.8,0.8,/TO_DATA)
XYOUTS,XY.X,XY.Y,/DATA,TXT,CHARSIZE = 1,ALIGN = 0.5
PSPRINT & PFILE,PSFILE
  
 P,LAM[0]
 STOP
ENDIF;IF DO_BOX_COX_GLOBAL GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||

;
;********************************
IF DO_TEST_NORMAL GE 1 THEN BEGIN
;********************************
PRINT,' ===> DEFINE RANDOM DATA ONCE THEN SUBSAMPLE TO SEE THE INFLUENCE OF SAMPLE SIZE ON RESULTS'
DATA = RANDOMN(SEED,1E6,/DOUBLE) & PN,DATA & PRINT,MM(DATA)

;FFFFFFFFFFFFFFFFFFFFFFFFF
  ARR = INTERVAL([100,1E3],100)
; FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  
 FOR NTH = 0,N_ELEMENTS(ARR) -1 DO BEGIN
  POF, NTH,ARR
  N = ARR[NTH]
  DATA = RANDOMN(SEED,N,/DOUBLE) & PN,DATA & PRINT,MM(DATA)
  R= STATS_NORMAL(DATA)
  ST,R
 STOP
 NDATA=N_ELEMENTS(DATA)
  ;PRINT,'N =  ',STR_COMMA(NDATA)
  IF NTH EQ 0 THEN X = NDATA ELSE X = [X,NDATA]
  IF NTH EQ 0 THEN Y = R.XSQ ELSE Y = [Y,R.XSQ]

ENDFOR;FOR NTH = 0,N_ELEMENTS(ARR) -1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
PSFILE=GET_DIR() + ROUTINE_NAME + '.PS'
 PSPRINT,FILENAME = PSFILE,/COLOR
 PAL_36
 PLOTXY,X,Y,CHARSIZE = 1.7,XTITLE = 'N DATA',YTITLE = 'XSQ',STATS_CHARSIZE = 2,THICK = 11,PARAMS = [1,2,4,5,7],PSYM = 1,SYMSIZE = 5,SYM_COLOR = 21,YRANGE = [.1,20],/LOGLOG
 PSPRINT & PFILE,PSFILE
ENDIF;IF DO_TEST_NORMAL GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||


;********************************
IF DO_1000_TRIALS GE 1 THEN BEGIN
;********************************
  PRINT,' ===> RUN STATS_NORMAL 1000 TIMES WITH A RANDOMN(SEED,1E5,/DOUBLE)TO CHECK XSQ AND MD PROBS FOR CONSISTANCY'
  
  NUM = 1000
  
  ; FFFFFFFFFFFFFFFFFFFFFF
  FOR NTH = 0,NUM DO BEGIN
    POF, NTH,NUM
    DATA = RANDOMN(SEED,1E6,/DOUBLE) 
    R= STATS_NORMAL(DATA)
    
    IF N_ELEMENTS(DB) EQ 0 THEN DB = R ELSE DB = [DB,R]
  ENDFOR;FOR NTH = 1,NUM DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  
OK = WHERE(DB.XSQ_PROB GE 0.05,COUNT) 
PCT =   100*FLOAT(COUNT)/N_ELEMENTS(DB) & PRINT,'XSQ_PROB GE 0.05  '+ ROUNDS(PCT,2)+ '%'
OK = WHERE(DB.XSQ_NOTES EQ 'NORMAL',COUNT) 
PCT_NORMAL =   100*FLOAT(COUNT)/1000. & PRINT,'XSQ_IS NORMAL  '+ ROUNDS(PCT_NORMAL,2)+ '%'
SAVEFILE = ROUTINE_NAME +'-DO_1000_TRIALS' + '.SAVE'
SAVE,FILENAME = SAVEFILE,DB,/COMPRESS & PFILE,SAVEFILE
SETS = WHERE_SETS(DB.XSQ_NOTES) & PN,SETS
SETS = WHERE_SETS(DB.MD_NOTES) & PN,SETS
P,MM(DB.XSQ_PROB)

S=SORT(DB.XSQ) & DB = DB(S)
PLOT,DB.XSQ,DB.XSQ_PROB,LINESTYLE = 0,CHARSIZE = 2,XTITLE = 'XSQ',YTITLE = 'PROB.',/XLOG
GRIDS
  STOP
ENDIF;IF DO_1000_TRIALS GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||


;********************************
IF DO_VARY_NBINS GE 1 THEN BEGIN
  ;********************************
  PRINT,' ===> RUN STATS_NORMAL 100 TIMES WITH A RANDOMN(SEED,1E5) WITH VARIOUS NBINS TO CHECK XSQ AND MD PROBS FOR CONSISTANCY'
 
  NUM = 100 
  ;FFFFFFFFFFFFFFFFFFFFFFF
  FOR _NUM = 0,NUM DO BEGIN
    POF, _NUM,NUM
    FOR NBINS = 10,100,10 DO BEGIN
    DATA = RANDOMN(SEED,1E5,/DOUBLE)
    R= STATS_NORMAL(DATA,NBINS=NBINS)
    IF _NUM EQ 0 THEN DB = R ELSE DB = [DB,R]
    ENDFOR;FOR NBINS = 10,100,10 DO BEGIN
    
  ENDFOR;FOR _NUM = 1,NUM DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  
  SAVEFILE = ROUTINE_NAME +'-DO_VARY_NBINS' + '.SAVE'
  SAVE,FILENAME = SAVEFILE,DB,/COMPRESS & PFILE,SAVEFILE
 
  STOP
ENDIF;IF DO_VARY_NBINS GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||

;**************************************
IF PLOT_DO_VARY_NBINS GE 1 THEN BEGIN
;**************************************
SAVEFILE = ROUTINE_NAME +'-DO_VARY_NBINS' + '.SAVE'
PSFILE = '-DO_VARY_NBINS' + '.PS'
DB = IDL_RESTORE(SAVEFILE)
ST,DB
STOP
S = SORT(DB.NUM_BINS) & DB = DB(S)
SET_PMULTI,2
PSPRINT,/COLOR,FILENAME = PSFILE
PLOT,DB.NUM_BINS,DB.XSQ,/NODATA,XTITLE = 'NUM_BINS',YTITLE = 'XSQ'
PLOTS,DB.NUM_BINS,DB.XSQ,PSYM = 1,THICK =3
PLOT,DB.NUM_BINS,DB.XSQ_PROB,/NODATA,XTITLE = 'NUM_BINS',YTITLE = 'XSQ_PROB'
PLOTS,DB.NUM_BINS,DB.XSQ,PSYM = 1,THICK =3
;PLOTXY,DB.NUM_BINS,DB.XSQ,CHARSIZE = 1.6,XTITLE = 'NUM_BINS',YTITLE = 'XSQ',PSYM = 1,$
;      /STATS_NONE,SYM_COLOR = 21,SYM_THICK = 3,/LOGLOG
PSPRINT
PFILE,PSFILE
ENDIF;IF PLOT_DO_VARY_NBINS GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||||||
  

;******************************
IF DO_HISTPLOT_NORMAL GE 1 THEN BEGIN
;******************************
PSFILE = GET_DIR() + ROUTINE_NAME + '-DO_HISTPLOT_NORMAL.PS
PSPRINT,FILENAME = PSFILE,/COLOR,/HALF
HISTPLOT,RANDOMN(SEED,100000,/DOUBLE),BINSIZE=0.1,LAB_BARS=[7,1,7],XTICKS=10,XRANGE=[-5,5],BAR_THICK=1,BAR_COLOR=21,CUM_THICK = 7,CUM_COLOR = 8
PSPRINT& PFILE,PSFILE
ENDIF;IF DO_HISTPLOT_NORMAL GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||

;*******************************
IF XSQ_VERSUS_N GE 1 THEN BEGIN
;*******************************
PRINT,'THIS STEP EVALUATES XSQ AS A FUNCTION OF N'
SAMPLE =LONG64(INTERVAL([2,8],BASE = 10,0.05))
SAMPLE =LONG64(INTERVAL([2,6],BASE = 10,0.01))

;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR NTH = 0,N_ELEMENTS(SAMPLE) -1 DO BEGIN
  POF,NTH,SAMPLE
  N = SAMPLE[NTH]
  IF N LT 100 THEN NBINS = 10 ELSE NBINS = 100

  DATA = RANDOMN(SEED,N,/DOUBLE)
  R = STATS_NORMAL(DATA,NBINS=NBNS)
  IF N_ELEMENTS(DB) EQ 0 THEN DB = R ELSE DB = [DB,R]
  ;PRINT,'N   ', N,'    PROB  ',ROUNDS(R.XSQ_PROB,3)
  
ENDFOR;FOR NTH = 0,N_ELEMENTS(SAMPLE) -1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
SETS = WHERE_SETS(DB.XSQ_NOTES) & PN,SETS
SETS = WHERE_SETS(DB.MD_NOTES) & PN,SETS
OK = WHERE(DB.XSQ_PROB GE 0.05,COUNT) 
PCT =   100*FLOAT(COUNT)/N_ELEMENTS(DB) & PRINT,'XSQ_PROB GE 0.05  '+ ROUNDS(PCT,2)+ '%'
OK = WHERE(DB.XSQ_NOTES EQ 'NORMAL',COUNT) 
PCT_NORMAL =   100*FLOAT(COUNT)/N_ELEMENTS(DB) & PRINT,'XSQ_IS NORMAL  '+ ROUNDS(PCT_NORMAL,2)+ '%'
PAL_36
PSPRINT,/COLOR
 PLOTXY,DB.N,DB.XSQ,CHARSIZE = 1.7,XTITLE = 'N DATA',YTITLE = 'XSQ',STATS_CHARSIZE = 2,THICK = 11,PARAMS = [1,2,4,5,7],PSYM = 1,SYMSIZE = 5,SYM_COLOR = 21,YRANGE = [.1,20],/LOGLOG
 PSPRINT
 
 CSVFILE = ROUTINE_NAME + '-XSQ_VERSUS_N-.CSV
 STRUCT_2CSV,CSVFILE,DB
STOP
ENDIF;IF XSQ_VERSUS_N GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||


END; #####################  END OF ROUTINE ################################
