; $ID:	STR_FIND.PRO,	2020-06-30-17,	USER-KJWH	$
  FUNCTION STR_FIND, ARRAY,TXT
    IF IDLTYPE(ARRAY,/CODE) NE 7 THEN RETURN,-1

    IF N_ELEMENTS(TXT) NE 1 THEN  RETURN,-1

    ARRAY = STRUPCASE(ARRAY)
    TXT   = STRUPCASE(TXT)
    FOUND = LONARR(N_ELEMENTS(ARRAY))

    FOR NTH = 0,N_ELEMENTS(array)-1L DO BEGIN
      FOUND[NTH] = STRPOS(ARRAY[NTH],TXT)
    ENDFOR

    FOUND = FOUND/ABS(FOUND)
    RETURN, FOUND

  END
