; $ID:	STR_2LINES.PRO,	2020-06-30-17,	USER-KJWH	$
;+
;;#############################################################################################################
	FUNCTION STR_2LINES,TXT,WPL = WPL
;
; PURPOSE: THIS FUNCTION ADDS !C TO TXT TO BREAK UP TXT FOR OUTPUT ON MULTIPLE LINES 
; 
; 
; CATEGORY:	STRING;		 
;
; CALLING SEQUENCE: RESULT = STR_2LINES(TXT)
;
; INPUTS: TXT TEXT TO BREAK INTO MULTIPLE LINES 
;         BY ADDING !C TO EACH LINE OF ~10 WORDS [10 WPL = DEFAULT] 

; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;   WPL: THE NUMBER OF WORDS PER EACH OUTPUT LINE

; OUTPUTS: A TEXT ARRAY WITH EACH LINE HAVING WPL WORDS 
;          AND A '!C' AT THE END OF EACH LINE.
;		
;; EXAMPLES:
;  PLIST, STR_2LINES('NOW IS THE TIME FOR ALL GOOD MEN TO COME TO THE AID OF THEIR COUNTRY')
;  PLIST, STR_2LINES('NOW IS THE TIME FOR ALL GOOD MEN TO COME TO THE AID OF THEIR COUNTRY',WPL = 3)
;
; MODIFICATION HISTORY:
;		MAR 19, 2014	WRITTEN  J.O'REILLY
;		
;#################################################################################
;-
;****************************
ROUTINE_NAME  = 'STR_2LINES'
;****************************
IF N_ELEMENTS(TXT) EQ 0 THEN MESSAGE,'ERROR: TXT IS REQUIRED'
IF N_ELEMENTS(WPL) EQ 0 THEN WPL = 10

;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR NTH = 0,N_ELEMENTS(TXT)-1 DO BEGIN
  _TXT = TXT[NTH]

;===> DETERMINE THE NUMBER OF WORDS IN TXT
W = WORDS(_TXT,DELIM = ' ')& NUM =N_ELEMENTS(W)
IF N_ELEMENTS(W) EQ 1 THEN RETURN,TXT
START = 0
FIN = WPL

;WWWWWWWWWWWWWWWWWWWWWWWWWW
WHILE START LT NUM DO BEGIN 
  T = STRJOIN(W(START:FIN-1)+ ' ') + '!C'  
  IF N_ELEMENTS(OUT) EQ 0 THEN OUT = T ELSE OUT = [OUT,T]
  START = START+ WPL
  FIN = (FIN + WPL) <NUM
ENDWHILE;WHILE N LT NUM DO BEGIN
;WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
ENDFOR;FOR NTH = 0,N_ELEMENTS(TXT)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
RETURN,OUT
DONE:          
	END; #####################  END OF ROUTINE ################################
