; $ID:	STRUCT_ANY_MISS.PRO,	2020-07-01-12,	USER-KJWH	$
;+
;#############################################################################################################
	PRO STRUCT_ANY_MISS,STRUCT,OUT=OUT

;
; PURPOSE:  EVALUATE ALL TAGS IN A STRUCTURE
;
; CATEGORY:	STRUCT
;
; CALLING SEQUENCE: STRUCT_ANY_MISS,STRUCT
;
; INPUTS: STRUCT A STRUCTURE ARRAY
;         
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:  OUT OUTPUT FILE NAME [USUALLY  A CSV]
;		

; OUTPUTS: 
; 
; EXAMPLES: STRUCT_ANY_MISS,PRINT
; 
;
; MODIFICATION HISTORY:
;			SEP 21,2014,  WRITTEN BY J.O'REILLY 
;			
;			
;			
;#################################################################################
;-
;********************************
ROUTINE_NAME  = 'STRUCT_ANY_MISS'
;********************************

IF NONE(LABEL) THEN LABEL = ROUTINE_NAME
TAGNAMES  = TAG_NAMES(STRUCT)

;STRUCT = STRUCT_2NUM(STRUCT)
;*************************************
FOR TAG = 0,N_TAGS(STRUCT)-1 DO BEGIN
;*************************************
  IF TAG EQ N_TAGS(STRUCT)-1 THEN CLOSE = 1
  ;IF NONE(APPEND) THEN APPEND = 0 ELSE APPEND = 1
  NAME = TAGNAMES(TAG)
  PFILE,NAME,/M
  DATA = STRUCT.(TAG)
 MIN_ = STRTRIM(MIN(DATA),2)
 MAX_ = STRTRIM(MAX(DATA),2)
 ;IF MAX_ EQ 'NaN' THEN MAX_ = STRTRIM(MISSINGS(0.0),2)
 P
 IF IDLTYPE(DATA) EQ 'STRING' THEN BEGIN
   OK = WHERE(DATA NE '',COUNT,NCOMPLEMENT=NCOMPLEMENT) & P,COUNT
   D = CREATE_STRUCT('LABEL',LABEL,'TAG',NAME,'N_GOOD',COUNT,'N_MISS',NCOMPLEMENT,'MIN',MIN_,'MAX',MAX_)
 ENDIF ELSE BEGIN
 OK = WHERE(FINITE(DATA) AND DATA NE MISSINGS(DATA),COUNT,NCOMPLEMENT = NCOMPLEMENT,COMPLEMENT = COMPLEMENT)
 D = CREATE_STRUCT('LABEL',LABEL,'TAG',NAME,'N_GOOD',COUNT,'N_MISS',NCOMPLEMENT,'MIN',MIN_,'MAX',MAX_)
 ENDELSE;IF IDLTYPE(DATA) EQ 'STRING' THEN BEGIN
  IF NCOMPLEMENT GE 1 THEN BEGIN
     BAD = STRUCT(COMPLEMENT)
     FILE = !S.IDL_TEMP + LABEL + '-'+ NAME + '.CSV'
     CSV_WRITE,FILE,BAD
     PFILE,FILE
  ENDIF ;IF NCOMPLEMENT GE 1 THEN BEGIN
 
 
IF NONE(DB) THEN DB = D ELSE DB = [DB,D]
  
ENDFOR;FOR TAG = 0,N_TAGS(STRUCT)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
IF NONE(OUT) THEN OUT = !S.IDL_TEMP + ROUTINE_NAME + '.CSV'
CSV_WRITE,OUT,DB
PFILE,OUT


END; #####################  END OF ROUTINE ################################
