; $ID:	STRUCT_MINMAX.PRO,	2020-06-26-15,	USER-KJWH	$

FUNCTION STRUCT_MINMAX,STRUCT ,NAME=NAME, FIN=FIN
;+
; NAME:
;       STRUCT_MINMAX
;
; PURPOSE:
;       CHARACTERIZE MIN, MAX OF EACH TAG IN A STRUCTURE
;
; MODIFICATION HISTORY:
;       WRITTEN BY:  J.E.O'REILLY, AUG 6, 2003
;-

; ====================>
 	TAGS = TAG_NAMES(STRUCT)
 	NTAGS=N_TAGS(STRUCT)
 	IF N_ELEMENTS(NAME) NE 1 THEN _NAME = '_' ELSE _NAME = NAME
	DB= REPLICATE(CREATE_STRUCT('NAME',_NAME,'TAG','','MIN','','MAX',''),NTAGS)


; *********************************************
  FOR _TAGS = 0, (N_ELEMENTS(TAGS) -1) DO BEGIN
    DATA = STRUCT.(_TAGS)
    ATAG = TAGS(_TAGS)

    IF KEYWORD_SET(FIN) THEN BEGIN
    	OK = WHERE(DATA NE MISSINGS(DATA),COUNT)
	    IF COUNT GE 1 THEN BEGIN
	    	_MIN = NUM2STR(MIN(DATA[OK]),TRIM=2)
	    	_MAX = NUM2STR(MAX(DATA[OK]),TRIM=2)
	    ENDIF ELSE BEGIN
	    	_MIN = NUM2STR(MISSINGS(DATA),TRIM=2)
	    	_MAX = NUM2STR(MISSINGS(DATA),TRIM=2)
	    ENDELSE
	  ENDIF ELSE BEGIN
	   	_MIN = NUM2STR(MIN(DATA),TRIM=2)
	    _MAX = NUM2STR(MAX(DATA),TRIM=2)
	  ENDELSE

		 DB(_TAGS).TAG = ATAG
		 DB(_TAGS).MIN = _MIN
		 DB(_TAGS).MAX = _MAX
   ENDFOR

RETURN,DB

END ; END OF PROGRAM
