; $ID:	T_TEST_SLOPE_DEMO.PRO,	2020-07-01-12,	USER-KJWH	$
; 
PRO T_TEST_SLOPE_DEMO

; #########################################################################; 
;+
; THIS PROGRAM IS A DEMO FOR KIM'S T_TEST_SLOPE

; HISTORY:
;     JUL 28, 2014  WRITTEN BY: J.E. O'REILLY
;-
; #########################################################################

;**********************************
ROUTINE_NAME  = 'T_TEST_SLOPE_DEMO'
;**********************************

; SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
; SSSSS       S W I T C H E S      CONTROLLING WHICH PROCESSING STEPS TO DO SSSSS
;SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS;	

  DO_SPSS_EXAMPLE		    =	1
  DO_DOWDY_WEARDEN      = 1
  DO_SOKAL_ROHLF	      = 0

;SSSSS     END OF SWITCHES     SSSSS

; ********************************
IF DO_SPSS_EXAMPLE GE 1 THEN BEGIN
; ********************************
  
  , 'DO_SPSS_EXAMPLE'
  OVERWRITE = DO_SPSS_EXAMPLE EQ 2   & IF DO_SPSS_EXAMPLE EQ 3 THEN STOP 
  TITLE = 'CORVETTE PRICE VERSUS AGE IN YEARS
  XTITLE = 'AGE OF CORVETTE (YEARS)'
  YTITLE = 'PRICE'
  X = [6,6,6,4,2,5,4,5,1,2]
  Y = [125,115,130,160,219,150,190,163,260,260]*100
  DB = REPLICATE(CREATE_STRUCT('X',0.0,'Y',0.0),N_ELEMENTS(X)) &
  DB.X = X & DB.Y = Y
  CSV_WRITE,!S.DATA + 'CORVETTES.CSV',DB
   PLT_XY,X,Y,SYM_SIZE=2,SYMBOL = 'CIRCLE',/SYM_FILLED,$
     XTITLE=XTITLE,YTITLE = YTITLE,/STATS_ADD,/REG_ADD,$
     MODEL = 'LSY',TITLE=TITLE,FILE = !S.IDL_TEMP + 'DO_SPSS_EXAMPLE.PNG'
  ALPHA = 0.05
  T = T_TEST_SLOPE( X=X, Y=Y,ALPHA = ALPHA,SLOPE_P=SLOPE_P)
   
  Result = REGRESS( X, Y, /DOUBLE, FTEST=FTEST )
  PRINT,'USING AN ALPHA OF :   ',ALPHA
  PRINT,'OUR T-VALUE: ',T[0] ,'   VERSUS : -10.8873'
  PRINT,'OUR F-VALUE: ',FTEST ,'   VERSUS : 118.5330'
  ;PRINT,'SIGNIFICANCE IS 0.000004484'
  PRINT, 'OUR SIGNIFICANCE :',SLOPE_P, '  VERSUS: '
  PRINT,"AT THE =0.05 LEVEL OF SIGNIFICANCE, THERE EXISTS ENOUGH EVIDENCE" 
  PRINT,'TO CONCLUDE THAT THE SLOPE OF THE POPULATION REGRESSION LINE IS NOT ZERO' 
  PRINT,'AND, HENCE, THAT AGE IS USEFUL AS A PREDICTOR OF PRICE FOR CORVETTES'
      
  , 'DO_SPSS_EXAMPLE'
      
    ENDIF;IF DO_SPSS_EXAMPLE GE 1 THEN BEGIN
    ;|||||||||||||||||||||||||||||||

    
     

     
;**********************************
IF DO_DOWDY_WEARDEN GE 1 THEN BEGIN
;**********************************
  
  , 'DO_DOWDY_WEARDEN'
  OVERWRITE = DO_DOWDY_WEARDEN EQ 2   & IF DO_DOWDY_WEARDEN EQ 3 THEN STOP
  TITLE = 'TRAINING VERSUS PRODUCTION'
  X = [1,2,3,4,5] & Y= [5,4,6,8,7]
  DB = REPLICATE(CREATE_STRUCT('X',0.0,'Y',0.0),N_ELEMENTS(X)) & 
  DB.X = X & DB.Y = Y 
  CSV_WRITE,!S.DATA + 'DOWDY_WEARDEN.CSV',DB
  PLT_XY,X,Y,SYM_SIZE=2,SYMBOL = 'CIRCLE',/SYM_FILLED,$
    XTITLE='TRAINING -HRS',YTITLE = 'PRODUCTION',/STATS_ADD,/REG_ADD,$
    MODEL = 'LSY',TITLE=TITLE, FILE = !S.IDL_TEMP + 'DO_DOWDY_WEARDEN.PNG'
    
  ALPHA = 0.05
  T = T_TEST_SLOPE( X=X, Y=Y,ALPHA = ALPHA,SLOPE_P=SLOPE_P)  
  RESULT = REGRESS( X, Y, /DOUBLE, FTEST=FTEST )
  PRINT,'USING AN ALPHA OF :   ',ALPHA
  PRINT,'OUR T-VALUE: ',T[0] ,'   VERSUS : 2.31','  VERSUS 2.353 FOR CRITICAL VALUE'
  PRINT, 'OUR SIGNIFICANCE :',SLOPE_P, '  VERSUS: '
  PRINT,"AND THE NULL HYPOTHESIS IS NOT REJECTED"
  PRINT,'THUS THE LINE SEEMS TO BE HORIZONTAL'
  PRINT,'AND, THE EQUATION FOR THE TREND LINE '
  PRINT,'SHOULD NOT BE USED FOR PREDICTION'
  PRINT
  PRINT,'A ONE-TAIL !!! T-TEST IS USED BECAUSE ADDITIONAL '
  PRINT,'TRAINING IS EXPECTED TO INCREASE PRODUCTIVITY '
  PRINT,'IF IT IS OF ANY EFFECT AT ALL,P.220'

  , 'DO_DOWDY_WEARDEN'
 
ENDIF ; IF DO_DOWDY_WEARDEN GE 1 THEN BEGIN
; ||||||||||||||||||||||||||||||||||||


; ****************************
IF DO_SOKAL_ROHLF GE 1 THEN BEGIN
  ; ****************************
  , 'DO_SOKAL_ROHLF'
  OVERWRITE = DO_SOKAL_ROHLF EQ 2   & IF DO_SOKAL_ROHLF EQ 3 THEN STOP
  TITLE = 'WEIGHT LOSS IN TRIBOLIUM BEETLES AFTER STARVATION'
  X = DOUBLE([0,12,29.5,43,53,62.5,72.5,85,93])
  Y = DOUBLE([8.98,8.14,6.67,6.08,5.90,5.83,4.68,4.20,3.72])
  DB = REPLICATE(CREATE_STRUCT('X',0.0,'Y',0.0),N_ELEMENTS(X)) &
  DB.X = X & DB.Y = Y
  CSV_WRITE,!S.DATA + 'TRIBOLIUM_BEETLES.CSV',DB
    PLT_XY,X,Y,SYM_SIZE=2,SYMBOL = 'CIRCLE',/SYM_FILLED,$
      XTITLE='% RELATIVE HUMIDITY',YTITLE = 'WEIGHT LOSS IN MILLIGRAMS',/STATS_ADD,/REG_ADD,$
      MODEL = 'LSY',TITLE=TITLE,FILE = !S.IDL_TEMP + 'DO_SOKAL_ROHLF.PNG'

ALPHA = 0.05
T = T_TEST_SLOPE( X=X, Y=Y,ALPHA = ALPHA,SLOPE_P=SLOPE_P)

Result = REGRESS( X, Y, /DOUBLE, FTEST=FTEST )
PRINT,'USING AN ALPHA OF :   ',ALPHA
PRINT,'OUR T-VALUE: ',T[0] ,'   VERSUS : 16.345'
PRINT,'OUR F-VALUE: ',FTEST ,'   VERSUS : 267.18'
PRINT, 'OUR SIGNIFICANCE :',SLOPE_P, '  VERSUS: '
PRINT,"OUR CONCLUSIONS FOR THE WEIGHT LOSS DATA ARE THAT A HIGHLY SIGNIFICANT"
PRINT,'NEGATIVE REGRESSION IS PRESENT'
PRINT,''




  , 'DO_SOKAL_ROHLF'
ENDIF ; IF DO_SOKAL_ROHLF GE 1 THEN BEGIN
; ||||||||||||||||||||||||||||||||||||




END; #####################  END OF ROUTINE ################################
