; $ID:	XSQ_TEST_DEMO.PRO,	2020-07-08-15,	USER-KJWH	$
;#############################################################################################################
	PRO XSQ_TEST_DEMO,DATA,X=X,Y=Y,N=N
	
;  PRO XSQ_TEST_DEMO
;+
; NAME:
;		XSQ_TEST_DEMO
;
; PURPOSE: THIS PROGRAM IS A DEMO FOR IDL XSQ_TEST
;
; CATEGORY:
;		STATISTICS
;		 
;
; CALLING SEQUENCE: XSQ_TEST_DEMO
;
; INPUTS: NONE
;		
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		NONE:

; OUTPUTS: 
;		
;; EXAMPLES:
;
;  XSQ_TEST_DEMO
;
; MODIFICATION HISTORY:
;			WRITTEN MAR 18,2013 J.O'REILLY
;			
;			
;			
;#################################################################################
;
;
;-
;******************************
ROUTINE_NAME  = 'XSQ_TEST_DEMO'
;******************************
;
;
;
;SSSSS     SWITCHES     SSSSS
DO_IDL_EXAMPLE        = 0
DO_PSERIES_TESTS      = 0
DO_NORMAL_VS_NORMAL   = 1
DO_XSQ_VS_SAMPLE_SIZE = 0
;SSSSS     SWITCHES     SSSSS
;********************************
IF DO_IDL_EXAMPLE GE 1 THEN BEGIN
;********************************

PRINT,' DEFINE THE VECTORS OF OBSERVED AND EXPECTED FREQUENCIES:'
OBFREQ = [2, 1, 4, 15, 10, 5, 3]
EXFREQ = [0.5, 2.1, 5.9, 10.3, 10.7, 7.0, 3.5]

PRINT,' TEST THE HYPOTHESIS THAT THE GIVEN OBSERVED FREQUENCIES ARE AN'
PRINT,' ACCURATE APPROXIMATION TO THE EXPECTED FREQUENCY DISTRIBUTION:'
RESULT = XSQ_TEST(OBFREQ, EXFREQ)
PRINT, RESULT
PRINT,' THE COMPUTED VALUE OF 0.383920 INDICATES THAT THERE IS NO REASON TO REJECT THE PROPOSED HYPOTHESIS AT THE 0.05 SIGNIFICANCE LEVEL.'

ENDIF;IF DO_IDL_EXAMPLE GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||



;********************************
IF DO_PSERIES_TESTS GE 1 THEN BEGIN
;********************************

PRINT,' DEFINE THE VECTORS OF OBSERVED AND EXPECTED FREQUENCIES:'
OBFREQ = [2, 1, 4, 15, 10, 5, 3]
EXFREQ = HISTOGRAM(RANDOMN(SEED, NUM), BINSIZE=0.1)
PRINT,' TEST THE HYPOTHESIS THAT THE GIVEN OBSERVED FREQUENCIES ARE AN'
PRINT,' ACCURATE APPROXIMATION TO THE EXPECTED FREQUENCY DISTRIBUTION:'
RESULT = XSQ_TEST(OBFREQ, EXFREQ)
PRINT, RESULT
PRINT,' THE COMPUTED VALUE OF 0.383920 INDICATES THAT THERE IS NO REASON TO REJECT THE PROPOSED HYPOTHESIS AT THE 0.05 SIGNIFICANCE LEVEL.'

ENDIF;IF DO_PSERIES_TESTS GE 1 THEN BEGIN
;||||||||||||||||||||||||||||||||||||||

;*************************************
IF DO_NORMAL_VS_NORMAL GE 1 THEN BEGIN
;*************************************
  PRINT,'OBSERVED VERY SIMILAR TO EXPECTED:[LOW XSQ & VERY HIGH PROB OF A LARGER XSQ'
  
  EXPECTED = RANDOMN(SEED, 1000)  
  OBSERVED = EXPECTED
    EXFREQ = HISTOGRAM(EXPECTED, BINSIZE=0.1) 
    OBFREQ = HISTOGRAM(OBSERVED, BINSIZE=0.1) 
  S = XSQ_TEST(OBFREQ, EXFREQ)

  PRINT, 'XSQ =  '+STRTRIM(S[0],2)
  PRINT,'PROB OF LARGER XSQ = ' +STRTRIM(S[1],2) 
   
  PRINT
  PRINT,'OBSERVED FREQ OFFSET FROM EXPECTED FREQ:[HIGH XSQ & VERY LOW PROB OF A LARGER XSQ''
  EXFREQ = HISTOGRAM(EXPECTED, BINSIZE=0.1) 
  OBFREQ = SHIFT(HISTOGRAM(OBSERVED, BINSIZE=0.1),N_ELEMENTS(OBSERVED)/2) 
  S = XSQ_TEST(OBFREQ, EXFREQ)
  PRINT, 'XSQ =  '+STRTRIM(S[0],2)
  PRINT,'PROB OF LARGER XSQ = ' +STRTRIM(S[1],2)
  
  

ENDIF;IF DO_NORMAL_VS_NORMAL GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||||

;****************************************
IF DO_XSQ_VS_SAMPLE_SIZE GE 1 THEN BEGIN
;****************************************
NUM = [INTERVAL([5,10],1),INTERVAL([10,20],2),INTERVAL([20,100],10)]
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR NTH = 0,N_ELEMENTS(NUM)-1 DO BEGIN
  N = NUM[NTH]
  EXPECTED = RANDOMN(SEED, N)  
  OBSERVED = RANDOMN(SEED, N) 
  EXFREQ = HISTOGRAM(EXPECTED, BINSIZE=0.5) 
  OBFREQ = HISTOGRAM(OBSERVED, NBINS = N_ELEMENTS(EXFREQ)) 
  S = XSQ_TEST(OBFREQ, EXFREQ)
   PRINT,'N= '+ROUNDS(N) + ':  XSQ =  '+STRTRIM(S[0],2) + '  PROB OF LARGER XSQ = ' +STRTRIM(S[1],2)
 
  ENDFOR;  FOR NTH = 0,N_ELEMENTS(NUM)-1 DO BEGIN
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  
ENDIF;IF DO_XSQ_VS_SAMPLE_SIZE GE 1 THEN BEGIN
;|||||||||||||||||||||||||||||||||||||||||||||

END; #####################  END OF ROUTINE ################################
