; $ID:	PLT_SLOPE.PRO,	2017-03-09-09,	USER-JEOR	$
;#########################################################################
 PRO PLT_SLOPE, OBJ,STRUCT=STRUCT,$
  REG_COLOR = REG_COLOR,$
  REG_THICK = REG_THICK,$
  REG_MID_COLOR=REG_MID_COLOR,$ 
  REG_LINESTYLE=REG_LINESTYLE,$ 
  REG_MID_THICK= REG_MID_THICK,$ 
  REG_MID_LINESTYLE=REG_MID_LINESTYLE
  
;+
; NAME:
;       PLT_SLOPE
;
; PURPOSE:
;       PLOT THE REGRESSION SLOPE FROM STATS2 ATOP AN EXISTING PLOT
;
; CATEGORY:
;      PLOT
;
; CALLING SEQUENCE:
;       PLT_SLOPE,OBJ,STRUCT=STRUCT

;
; INPUTS:
;       OBJ: PLOT OBJECT
;
; KEYWORD PARAMETERS:
;        STRUCT.......... OUTPUT FROM STATS2 REGRESSION

;       _EXTRA      : MAY CONTAIN ANY IDL KEYWORDS WHICH ARE VALID FOR THE PLOT FUNCTION
;
; OUTPUTS: OVERPLOTS THE REGRESSION SLOPE LINE ATOP EXISTING PLOT
;
; SIDE EFFECTS:
;       
;
; RESTRICTIONS:
;       ASSUMES YOU HAVE ALREADY ISSUED A PLOT COMMAND.

;
; MODIFICATION HISTORY:
;       WRITTEN BY:  J.E.O'REILLY, FEB 10, 1997.
;       MAR 13,2014,JOR: COPIED FROM ONE2ONE FORMATTING
;                        ADDED KEYWORD OBJ [FOR NEW GRAPHICS]
;       APR 19,2014,JOR  ADDED NEW LOGICAL FUNCTIONS
;       APR 21,2014,JOR CHANGED NAME TO PLT_SLOPE
;       APR 22,2014,JOR ADDED KEYWORDS
;       APR 27,2014,JOR:NAME = STRUPCASE(OBJ.NAME)
;                       IF NAME EQ 'IMAGE' THEN OBJ.GETDATA, IMAGE,X, Y
;                       IF NAME EQ 'PLOT' THEN OBJ.GETDATA,X, Y
;       MAY 2,2014,JOR XX = RANGE(X) CHANGED TO XX= OBJ.XRANGE
;       NOV 15,2014,JOR, WHERE_STRING NOW RETURNS A !NULL SO :
;                        WHERE_STRING(NAME,'PLOT') NE []
;       MAR 09.2017,JOR:IF WHERE_STRING(NAME,'PLOT') NE []  THEN OBJ.GETDATA,XO, YO
;                       XX = MINMAX(XO,/FIN)
;                       YY = MINMAX(YO,/FIN)

;-

; ############################################################################
;*************************** 
ROUTINE_NAME = 'PLT_SLOPE'
;***************************
;
;##### IS PLOT OBJECT OBJECT PRESENT ? #####
IF NONE(OBJ) THEN MESSAGE,'ERROR: PLOT OBJECT IS REQUIRED'
IF IDLTYPE(OBJ) NE 'OBJREF' THEN MESSAGE,'ERROR: OBJ MUST BE A PLOT OBJECT'
;||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
  
;##### MAKE SURE THE INPUT STRUCT IS FROM STATS2 #####
NAMES = TAG_NAMES(STRUCT)
TARGETS = ['INT','SLOPE','RSQ'] 
OK = WHERE_IN(NAMES,TARGETS,COUNT) 
IF COUNT NE 3 THEN MESSAGE,'ERROR: STRUCT IS NOT FROM STATS2'
;|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
;
;##########################################################
;===> GET X AND Y DATA FOR SUBSEQUENT PLOTTING OF REGRESSION LINE
NAME = STRUPCASE(OBJ.NAME)
IF WHERE_STRING(NAME,'IMAGE') NE []  THEN OBJ.GETDATA, IMAGE,X, Y
IF WHERE_STRING(NAME,'PLOT') NE []  THEN OBJ.GETDATA,XO, YO

XX = MINMAX(XO,/FIN)
YY = MINMAX(YO,/FIN)
OBJ=PLOT(XX,YY,/OVERPLOT,COLOR = REG_COLOR,THICK = REG_THICK,LINESTYLE =REG_LINESTYLE)
OBJ=PLOT(XX,YY,/OVERPLOT,COLOR = REG_MID_COLOR,THICK = REG_MID_THICK,LINESTYLE =REG_MID_LINESTYLE)
;||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

DONE:          
  END; #####################  END OF ROUTINE ################################

