; $ID:	PLT_LME_PAGE.PRO,	2020-07-08-15,	USER-KJWH	$
;+
;#############################################################################################################
	PRO PLT_LME_PAGE,TYPE=TYPE

;
; PURPOSE: PLOTS TIME-SERIES FOR AN LME
;
; CATEGORY:	PLT FAMILY
;
; CALLING SEQUENCE: PLT_LME_PAGE,TYPE=TYPE
;
; INPUTS: STRUCTURE
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		TYPE:  'PP' = UNEP PP UPDATE ; CHL = UNEP CHL UPDATE

; OUTPUTS: 
;		
; EXAMPLES: 
;
; MODIFICATION HISTORY:
;			OCT 21,2014,  WRITTEN BY J.O'REILLY 
;		TITLE
;#################################################################################
;-
;***************************** 
ROUTINE_NAME  = 'PLT_LME_PAGE'
;*****************************
DIR = GET_SMI()
EXT = '.PNG'
;===> PLOT CHARACTERISTICS
AXES_FONT_SIZE =8
MARGIN = [0.2,0.2,0.2,0.35]
BACKGROUND_COLOR = 'WHITE_SMOKE'

;===> DATA LINE [LIN_COLOR VARIES WITH PROD]
LIN_THICK = 3
LIN_MID_THICK = 1
LIN_MID_COLOR = 'WHITE'

;===> PAGE
PAGE_POS = [0.5,0.94]

;===> REGRESSION
REG_THICK = 1
REG_MID_THICK = 1
REG_COLOR = 'BLACK'
REG_MID_COLOR= 'BLACK'

;===> LEGEND
LEG_ADD=0
LEG_POS=[0.18,0.84]
LEG_FILL_BACKGROUND = 1
LEG_BACKGROUND_COLOR = 'WHITE_SMOKE'

;===> SYMBOL
SYMBOL = 'DIAMOND'
SYM_SIZE = 2
SYM_COLOR = 'MAGENTA'
SYM_THICK = 1
SYM_FILLED = 1
SYM_FILL_COLOR = 'MAGENTA'
;===> TYPE ?
IF NONE(TYPE) THEN TYPE = 'PP'

;**************************
IF TYPE EQ 'PP' THEN BEGIN
;**************************
  DIR_OUT = DIR.PP_UPDATE
  LIN_COLORS = ['GREEN','BLUE','GREEN','BLUE']
  PRODS = ['CHLOR_A','PPD','CHLOR_A','PPD']
  PERS  = ['MONTH', 'MONTH',   'Y',    'Y']
  ;===> FOR TESTING SLOPE
 
ENDIF;IF TYPE EQ 'PP' THEN BEGIN
;|||||||||||||||||||||||||||||||

;**************************
IF TYPE EQ 'CHL' THEN BEGIN
;**************************
  DIR_OUT = DIR.CHL_UPDATE
  LIN_COLORS = ['GREEN','GREEN']
  PRODS = ['CHLOR_A','CHLOR_A']
  PERS  = ['MONTH',   'Y']
ENDIF;IF TYPE EQ 'CHL' THEN BEGIN
;|||||||||||||||||||||||||||||||


MAPS = (READ_LME_DB()).MAP & PN,MAPS
;MAPS = 'NORTHEAST_US_CONTINENTAL_SHELF'
;MAPS = 'AGULHAS_CURRENT'
MAPS = 'BALTIC_SEA'

;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FOR _MAP = 0,N_ELEMENTS(MAPS) -1 DO BEGIN
  LME = MAPS(_MAP)
  PF,LME,/M
  PAGE_TITLE = FIX_LME_NAMES(LME)
  FILE= DIR_OUT + LME + EXT
  T = ALPHABET(/INIT)
  SEQ = 0
  W = WINDOW(/BUFFER)
  ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  FOR NTH = 0,N_ELEMENTS(PRODS)-1 DO BEGIN
    PROD = PRODS[NTH]
    PER = PERS[NTH]
    LIN_COLOR = LIN_COLORS[NTH] 
    LEG_COLOR=LIN_COLORS[NTH]
    SEQ = SEQ + 1
    LAYOUT = [1,N_ELEMENTS(PRODS),SEQ]
    IF PROD EQ 'PPD' AND PER EQ 'Y' THEN BEGIN
      PPY = 1     
      LEG_TXT= 'PPY'
    ENDIF;IF PROD EQ 'PPD' AND PER EQ 'Y' THEN BEGIN
    IF PROD EQ 'PPD' AND PER EQ 'MONTH' THEN BEGIN
      PPY = 0
      LEG_TXT= 'PPD'
    ENDIF;IF PROD EQ 'PPD' AND PER EQ 'Y' THEN BEGIN       
    IF PROD EQ 'CHLOR_A' THEN BEGIN
      LEG_TXT= 'CHL'
    ENDIF;IF PROD EQ 'CHL' THEN BEGIN
    TS = GET_LME_TS(LME,PROD = PROD,PER = PER,PPY=PPY) 
    DATA = TS.MEAN
   
    IF PROD EQ 'CHLOR_A' AND PER EQ 'MONTH' THEN TITLE = 'CHL Annual Cycle'
    IF PROD EQ 'CHLOR_A' AND PER EQ 'Y' THEN TITLE = 'CHL Trend'
    
    IF PROD EQ 'PPD' AND PER EQ 'MONTH' THEN TITLE = 'PP Annual Cycle'
    IF PROD EQ 'PPD' AND PER EQ 'Y' THEN TITLE = 'PP Trend'
    
    ;===> MAKE XRANGE TO 2014 FOR COMPLETE AXIS LABELING
    IF PER EQ 'Y' THEN BEGIN
      X = DATE_2DYEAR(PERIOD_2DATE(TS.PERIOD))
      XRANGE = [1998,2014]
      XTICKNAME = SUBSAMPLE(ROUNDS(INTERVAL(XRANGE)),2)
      S = STATS_NAN(DATA)
      MIN_PER = X(S.SUB_MIN) & MIN_VAL = S.MIN
      MAX_PER = X(S.SUB_MAX) & MAX_VAL = S.MAX
      REG_ADD = 1
    ENDIF;IF PER EQ 'Y' THEN BEGIN 
    IF PER EQ 'MONTH' THEN BEGIN  
      X = INTERVAL([1,12])
      XRANGE = MM(X)
      XTICKNAME = MONTH_NAMES(X,/SHORT)
      S = STATS_NAN(DATA)
      MIN_PER = X(S.SUB_MIN) & MIN_VAL = S.MIN
      MAX_PER = X(S.SUB_MAX) & MAX_VAL = S.MAX
      REG_ADD = 0
    ENDIF;IF PER EQ 'MONTH' THEN BEGIN  TITLE
  
    YRANGE = MINMAX(DATA,/FIN)
    IF NTH EQ 0 THEN MARGIN = [0.1,0.2,0.1,0.35] ELSE MARGIN = [0.1,0.2,0.1,0.1]

    PLT_XY,X,DATA,XRANGE = XRANGE,XTICKNAME=XTICKNAME, YRANGE=YRANGE,/YSTYLE,$
    AXES_FONT_SIZE=AXES_FONT_SIZE,TITLE=TITLE,$
    /LIN_ADD,LIN_COLOR = LIN_COLOR,LIN_THICK=LIN_THICK,$
    LIN_MID_COLOR = LIN_MID_COLOR,LIN_MID_THICK =LIN_MID_THICK,$
    REG_ADD=REG_ADD,REG_COLOR = REG_COLOR,REG_MID_COLOR= REG_MID_COLOR,REG_THICK=REG_THICK,REG_MID_THICK=REG_MID_THICK,$
    LEG_ADD=LEG_ADD,LEG_TXT=LEG_TXT,LEG_POS=LEG_POS,LEG_COLOR=LEG_COLOR,$
    LEG_FILL_COLOR=LEG_FILL_COLOR,LEG_FILL_BACKGROUND=LEG_FILL_BACKGROUND,$
   XTITLE = '',YTITLE = UNITS(FIRST(TS.PROD)),$
    /GRID_ADD,OBJ=OBJ,LAYOUT=LAYOUT,MARGIN=MARGIN,$
    BACKGROUND_COLOR=BACKGROUND_COLOR,/CURRENT
    ;===> IDENTIFY MIN MAX YEARS WITH ASTERISKS
    OBJ= PLOT([MIN_PER,MAX_PER],[MIN_VAL,MAX_VAL],$
    SYMBOL = SYMBOL,SYM_SIZE = SYM_SIZE,SYM_COLOR = SYM_COLOR,SYM_THICK = SYM_THICK,SYM_FILLED=SYM_FILLED,SYM_FILL_COLOR=SYM_FILL_COLOR,$
    LINESTYLE = 6,/OVERPLOT,/CURRENT)     
    LET = ALPHABET(/NEXT)
    T = TEXT(0.025,0.70,LET,FILL_BACKGROUND=1,FILL_COLOR = 'WHITE_SMOKE',TARGET = OBJ,/RELATIVE)    
  ENDFOR;FOR NTH = 0,N_ELEMENTS(PRODS)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
;===> ADD THE LME PAGE_TITLE
T = TEXT(PAGE_POS[0],PAGE_POS[1],PAGE_TITLE,ALIGN = 0.5,/CURRENT,FONT_SIZE = 21)
 W.SAVE, FILE & PF,FILE
 
ENDFOR;FOR _MAP = 0,N_ELEMENTS(MAPS) -1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
END; #####################  END OF ROUTINE ################################
