; $ID:	PLT_SHP_POINTS_DEMO.PRO,	2020-06-30-17,	USER-KJWH	$
;+
;#############################################################################################################
	PRO PLT_SHP_POINTS_DEMO
;
; PURPOSE: MAKE A SHP FILE FOR SEVERAL LON,LAT POINTS AND USE PLT_SHP TO PLOT THEM
;
; CATEGORY:	PLT FAMILY
;
; CALLING SEQUENCE: PLT_SHP_POINTS_DEMO
;
; INPUTS: NONE
;		
; OPTIONAL INPUTS:
;		NONE:	
;		
; KEYWORD PARAMETERS:
;		NONE
;
; MODIFICATION HISTORY:
;			JUN 4, 2014  WRITTEN BY J.O'REILLY
;			JUN 11,2014, MINOR FIXES 
;			NOV 22, 2017 - KJWH: Changed PLT_SHP to READ_SHPFILE
;			
;			
;			
;#################################################################################
;-
;**********************************
ROUTINE_NAME  = 'PLT_SHP_POINTS_DEMO'
;**********************************

;===> DEFAULTS
LL = LOCATE(['BATS','GB_S_FLANK','BAY_OF_FUNDY','EASTER_ISLAND','SANDY HOOK','NEW YORK','MOBY'])
LON = LL.LON & LAT = LL.LAT & SITE = LL.SITE
SITES = ['BATS','CENTER']
SHP_FILE= !S.SUBAREAS + 'SHP\' + 'LOCATE' + '-'+'SEVERAL_POINTS' + '.SHP'
; CREATE THE NEW SHAPEFILE AND DEFINE THE ENTITY TYPE TO POINT

SHP = OBJ_NEW('IDLFFSHAPE',SHP_FILE, /UPDATE, ENTITY_TYPE=1)
;===> SET THE ATTRIBUTE DEFINITIONS FOR THE NEW SHAPEFILE
;### 'ONLY LONG(3), DOUBLE(5) OR STRING(7) TYPES ARE VALID'
SHP->ADDATTRIBUTE, 'REGION', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'SUBAREA', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'CODE', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'METHOD', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'SOURCE', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'DATE', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'SITE', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'METHOD', 7, 25, PRECISION=0
SHP->ADDATTRIBUTE, 'LON', 5, 25, PRECISION=6
SHP->ADDATTRIBUTE, 'LAT', 5, 25, PRECISION=6
;===> CREATE STRUCTURE FOR NEW ENTITY
ENTNEW = {IDL_SHAPE_ENTITY}
; DEFINE THE VALUES FOR THE NEW ENTITIES
FOR NTH = 0,N_ELEMENTS(LON)-1 DO BEGIN
  ENTNEW.SHAPE_TYPE = 1
  ENTNEW.BOUNDS[0] = LON[NTH]
  ENTNEW.BOUNDS[1] = LAT[NTH]
  ENTNEW.BOUNDS[2] = 0.00000000
  ENTNEW.BOUNDS[3] = 0.00000000
  ENTNEW.BOUNDS[4] = LON[NTH]
  ENTNEW.BOUNDS[5] = LAT[NTH]
  ENTNEW.BOUNDS[6] = 0.00000000
  ENTNEW.BOUNDS[7] = 0.00000000
  ENTNEW.N_VERTICES = 1 ; TAKE OUT OF EXAMPLE, NEED AS WORKAROUND
 
  ; CREATE STRUCTURE FOR NEW ATTRIBUTES
  ATTRNEW = SHP->GETATTRIBUTES(/ATTRIBUTE_STRUCTURE)
  ; DEFINE THE VALUES FOR THE NEW ATTRIBUTES
  ATTRNEW.ATTRIBUTE_0 = SITE[NTH]
  ATTRNEW.ATTRIBUTE_1 = 'SUBAREA'
  ATTRNEW.ATTRIBUTE_2 = 'CODE'
  ATTRNEW.ATTRIBUTE_3 = ROUTINE_NAME
  ATTRNEW.ATTRIBUTE_4 = ''
  ATTRNEW.ATTRIBUTE_5 = DATE_NOW()
  ; ADD THE NEW ENTITY TO NEW SHAPEFILE
  SHP->PUTENTITY, ENTNEW
  
  ENTITY_INDEX = NTH
  ;==> ADD THE ATTRIBUTES TO NEW SHAPEFILE.
  SHP->SETATTRIBUTES, ENTITY_INDEX, ATTRNEW
ENDFOR;FOR NTH = 0,N_ELEMENTS(LON)-1 DO BEGIN
;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
;
;===> CLOSE/DESTROY THE SHAPEFILE
OBJ_DESTROY, SHP

PFILE,SHP_FILE
MAPS_SET,'SMI'
COLOR = 21
MAP_CONTINENTS,/HIRES,/COASTS, COLOR = 0
READ_SHPFILE, SHP_FILE,COLOR=COLOR,FILL=1,THICK=4,VERBOSE=VERBOSE,$
                ;GET_RANGE=GET_RANGE,TAGNAME='SUBAREA',VALUE='BATS',AROUND=5,$
                GET_RANGE=GET_RANGE,TAGNAME='SUBAREA',VALUE='SUBAREA',AROUND=5,$
                RANGE_LON = RANGE_LON, RANGE_LAT = RANGE_LAT,NORMAL=NORMAL,$
                DO_ALL = 1, AUTO=AUTO,LONS=LONS,LATS=LATS,PSYM = 6,SYMSIZE = 11,_EXTRA=_EXTRA
                
                
                
IMG = TVRD()
ZWIN
PAL_36,R,G,B
PNGFILE = !S.IDL_TEMP+ROUTINE_NAME + '.PNG'
WRITE_PNG,PNGFILE,IMG,R,G,B    & PF,PNGFILE            
OK = WHERE(IMG EQ COLOR,COUNT) & P,COUNT



END; #####################  END OF ROUTINE ################################
